ALTER PROCEDURE PROC_DISCOUNT  
(  
@ADMINDB VARCHAR(15),  
@DBNAME VARCHAR(15),  
@FROMDATE VARCHAR(30),  
@TODATE VARCHAR(30),  
@COMPANYID VARCHAR(500),  
@TEMPTABLE VARCHAR(50),  
@COSTID VARCHAR(500),  
@METALID VARCHAR(500),            
@GROUPBY VARCHAR(1),  
@WITHEX VARCHAR(1)  
)  
AS   
BEGIN  
DECLARE @QRY VARCHAR(8000)  
SET @COSTID = REPLACE(@COSTID,',',''',''')  
SET @METALID = REPLACE(@METALID,',',''',''')  
SET @COMPANYID = ''+REPLACE(@COMPANYID,',',''',''')+''  
SELECT @QRY= 'IF  EXISTS (SELECT * FROM TEMPTABLEDB..SYSOBJECTS WHERE XTYPE = ''U'' AND NAME = '''+@TEMPTABLE+''' )DROP TABLE TEMPTABLEDB..'+@TEMPTABLE+' '  
EXEC (@QRY)  
IF @WITHEX = 'Y'  
BEGIN  
SELECT @QRY= CHAR(13) +'SELECT CONVERT(VARCHAR(20),BILLNO)BILLNO ,BILLDATE,METAL,GRSWT,NETWT,AMOUNT,SUM(DISCLIMITAMT)DISCLIMITAMT,SUM(DISCALLOWAMT)DISCALLOWAMT,DISCOUNT,OFFERDISC,FINALDISC AS FINALDISC,FINALPURDISC AS FINALPURDISC'  
SELECT @QRY= @QRY + CHAR(13) +',SUM(ISNULL(DISCOUNT,0))+SUM(ISNULL(OFFERDISC,0))+SUM(ISNULL(FINALDISC,0))TOTALDISC '  
SELECT @QRY= @QRY + CHAR(13) +',CONVERT(NUMERIC(15,2),CASE WHEN AMOUNT<>0 THEN (((SUM(ISNULL(DISCOUNT,0))+SUM(ISNULL(FINALDISC,0))+SUM(ISNULL(OFFERDISC,0)))*100)/AMOUNT)END) AS DISCPER'  
SELECT @QRY= @QRY + CHAR(13) +',SALESMAN,AUTHORIZE,REMARK,COLHEAD,RESULT'  
SELECT @QRY= @QRY + CHAR(13) +',IDENTITY (INT,1,1)SNO INTO TEMPTABLEDB..'+@TEMPTABLE+' '  
SELECT @QRY= @QRY + CHAR(13) +'FROM('  
SELECT @QRY= @QRY + CHAR(13) +'SELECT  BILLNO'  
SELECT @QRY= @QRY + CHAR(13) +',BILLDATE,METAL,SUM(GRSWT) AS GRSWT,SUM(NETWT) AS NETWT'  
SELECT @QRY= @QRY + CHAR(13) +',SUM(AMOUNT) AS AMOUNT'  
SELECT @QRY= @QRY + CHAR(13) +',CONVERT(NUMERIC(15,2),SUM(ISNULL(DISCOUNT1,0))) AS DISCOUNT'  
SELECT @QRY= @QRY + CHAR(13) +',SUM(DISCOUNT) AS OFFERDISC'  
SELECT @QRY= @QRY + CHAR(13) +',SUM(FIN_DISCOUNT) AS FINALDISC'
SELECT @QRY= @QRY + CHAR(13) +',SUM(FIN_PURDISCOUNT) AS FINALPURDISC'
SELECT @QRY= @QRY + CHAR(13) +' ,(SELECT SUM(DISCLIMITAMT) FROM DISCHISTORY D WHERE D.BATCHNO IN '  
SELECT @QRY= @QRY + CHAR(13) +' (SELECT BATCHNO FROM '+@ADMINDB+'..EXEMPTION AS EX WHERE EX.BATCHNO=X.BATCHNO '  
SELECT @QRY= @QRY + CHAR(13) +' AND EX.OPTIONID=''6'' ))DISCLIMITAMT '  
SELECT @QRY= @QRY + CHAR(13) +' ,(SELECT SUM(DISCALLOWAMT) FROM DISCHISTORY D WHERE D.BATCHNO IN '  
SELECT @QRY= @QRY + CHAR(13) +' (SELECT BATCHNO FROM '+@ADMINDB+'..EXEMPTION AS EX WHERE EX.BATCHNO=X.BATCHNO  '  
SELECT @QRY= @QRY + CHAR(13) +' AND EX.OPTIONID=''6'' ))DISCALLOWAMT '  
SELECT @QRY= @QRY + CHAR(13) +',SALESMAN,AUTHORIZE,REMARK, CONVERT(VARCHAR,'''') AS COLHEAD,''1'' AS RESULT '  
SELECT @QRY= @QRY + CHAR(13) +'FROM('  
SELECT @QRY= @QRY + CHAR(13) +'SELECT I.TRANNO AS BILLNO,I.TRANDATE AS BILLDATE,METALNAME AS METAL,I.GRSWT AS GRSWT,I.NETWT AS NETWT,'  
SELECT @QRY= @QRY + CHAR(13) +'I.AMOUNT AS AMOUNT,'  
SELECT @QRY= @QRY + CHAR(13) +'I.DISCOUNT,I.FIN_DISCOUNT,I.FIN_PURDISCOUNT'  
SELECT @QRY= @QRY + CHAR(13) +',E.EMPNAME AS SALESMAN'  
SELECT @QRY= @QRY + CHAR(13) +',E1.EMPNAME AS AUTHORIZE,I.BATCHNO'  
SELECT @QRY= @QRY + CHAR(13) +',(SELECT SUM(AMOUNT) FROM ACCTRAN WHERE BATCHNO=I.BATCHNO AND TRANMODE=''D'' AND PAYMODE=''DI'')/(SELECT CASE WHEN COUNT(*)=0 THEN 1 ELSE COUNT(*) END FROM ISSUE AS Q WHERE Q.BATCHNO=I.BATCHNO)DISCOUNT1'  
SELECT @QRY= @QRY + CHAR(13) +',(SELECT TOP 1 REMARK1 FROM '+@ADMINDB+'..CUSTOMERINFO WHERE BATCHNO=I.BATCHNO) REMARK'   
SELECT @QRY= @QRY + CHAR(13) +'FROM ISSUE AS I'  
SELECT @QRY= @QRY + CHAR(13) +'INNER JOIN '+@ADMINDB+'..METALMAST AS M ON M.METALID=I.METALID'  
SELECT @QRY= @QRY + CHAR(13) +'INNER JOIN '+@ADMINDB+'..EMPMASTER AS E ON E.EMPID=I.EMPID '  
SELECT @QRY= @QRY + CHAR(13) +'LEFT JOIN '+@ADMINDB+'..EMPMASTER AS E1 ON E1.EMPID=I.DISC_EMPID'   
SELECT @QRY= @QRY + CHAR(13) +'WHERE I.TRANDATE BETWEEN  '''+@FROMDATE+''' AND '''+@TODATE+''''  
SELECT @QRY= @QRY + CHAR(13) +'AND I.COMPANYID IN('''+@COMPANYID+''')'  
SELECT @QRY= @QRY + CHAR(13) +'AND ISNULL(I.CANCEL,'''')='''''  
IF @COSTID<>'ALL'  
BEGIN  
SELECT @QRY= @QRY + CHAR(13) +' AND I.COSTID IN('''+@COSTID+''') '  
END  
IF @METALID<>'ALL'  
BEGIN  
SELECT @QRY= @QRY + CHAR(13) +' AND I.METALID IN('''+@METALID+''') '  
END  
SELECT @QRY= @QRY + CHAR(13) +')X'  
SELECT @QRY= @QRY + CHAR(13) +'GROUP BY BILLNO,BILLDATE,METAL,SALESMAN,AUTHORIZE,BATCHNO,REMARK '  
SELECT @QRY= @QRY + CHAR(13) +')Z'  
SELECT @QRY= @QRY + CHAR(13) +'GROUP BY BILLNO,BILLDATE,METAL,GRSWT,NETWT,AMOUNT,DISCOUNT,OFFERDISC,FINALDISC,FINALPURDISC'  
SELECT @QRY= @QRY + CHAR(13) +',SALESMAN,AUTHORIZE,COLHEAD,RESULT,REMARK '  
SELECT @QRY= @QRY + CHAR(13) +'ORDER BY BILLDATE,BILLNO'  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY=  'INSERT INTO TEMPTABLEDB..'+@TEMPTABLE+'(BILLNO,GRSWT,NETWT,AMOUNT,DISCOUNT,DISCLIMITAMT,DISCALLOWAMT,OFFERDISC,FINALDISC,FINALPURDISC,TOTALDISC,COLHEAD,RESULT)'  
SELECT @QRY= @QRY + CHAR(13) +'SELECT ''GRAND TOTAL'' AS BILLNO ,SUM(GRSWT),SUM(NETWT),SUM(AMOUNT)'  
SELECT @QRY= @QRY + CHAR(13) +',SUM(DISCOUNT),SUM(DISCLIMITAMT),SUM(DISCALLOWAMT),SUM(OFFERDISC),SUM(FINALDISC),SUM(FINALPURDISC),SUM(TOTALDISC)'  
SELECT @QRY= @QRY + CHAR(13) +',''G'' AS COLHEAD,''2'' AS RESULT FROM TEMPTABLEDB..'+@TEMPTABLE+' WHERE RESULT=1 HAVING COUNT(BILLNO)>1'  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= 'UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET DISCOUNT=NULL WHERE DISCOUNT=0'  
SELECT @QRY= @QRY + CHAR(13) +' UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET OFFERDISC=NULL WHERE OFFERDISC=0'  
SELECT @QRY= @QRY + CHAR(13) +' UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET FINALDISC=NULL WHERE FINALDISC=0'  
SELECT @QRY= @QRY + CHAR(13) +' UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET FINALPURDISC=NULL WHERE FINALPURDISC=0'
SELECT @QRY= @QRY + CHAR(13) +' UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET TOTALDISC=NULL WHERE TOTALDISC=0'  
SELECT @QRY= @QRY + CHAR(13) +' UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET AMOUNT=NULL WHERE AMOUNT=0'  
SELECT @QRY= @QRY + CHAR(13) +' UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET DISCLIMITAMT=NULL WHERE DISCLIMITAMT=0'  
SELECT @QRY= @QRY + CHAR(13) +' UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET DISCALLOWAMT=NULL WHERE DISCALLOWAMT=0'  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= 'SELECT * FROM TEMPTABLEDB..'+@TEMPTABLE+' ORDER BY SNO'  
PRINT @QRY  
EXEC (@QRY)  
END  
ELSE  
BEGIN  
IF @GROUPBY='N'  
BEGIN  
SELECT @QRY= CHAR(13) +'SELECT CONVERT(VARCHAR(20),BILLNO)BILLNO ,BILLDATE,METAL,GRSWT,NETWT,AMOUNT,DISCOUNT,OFFERDISC,FINALDISC,FINALPURDISC,'  
SELECT @QRY= @QRY + CHAR(13) +'SUM(ISNULL(DISCOUNT,0))+SUM(ISNULL(OFFERDISC,0))+SUM(ISNULL(FINALDISC,0))TOTALDISC'  
SELECT @QRY= @QRY + CHAR(13) +',CONVERT(NUMERIC(15,2),CASE WHEN AMOUNT<>0 THEN (((SUM(ISNULL(DISCOUNT,0))+SUM(ISNULL(OFFERDISC,0))+SUM(ISNULL(FINALDISC,0)))*100)/AMOUNT)END) AS DISCPER'  
SELECT @QRY= @QRY + CHAR(13) +',SALESMAN,AUTHORIZE,REMARK,COLHEAD,RESULT'  
SELECT @QRY= @QRY + CHAR(13) +',IDENTITY (INT,1,1)SNO INTO TEMPTABLEDB..'+@TEMPTABLE+' '  
SELECT @QRY= @QRY + CHAR(13) +'FROM('  
SELECT @QRY= @QRY + CHAR(13) +'SELECT  BILLNO'  
SELECT @QRY= @QRY + CHAR(13) +',BILLDATE,METAL,SUM(GRSWT) AS GRSWT,SUM(NETWT) AS NETWT'  
SELECT @QRY= @QRY + CHAR(13) +',SUM(AMOUNT) AS AMOUNT'  
SELECT @QRY= @QRY + CHAR(13) +',CONVERT(NUMERIC(15,2),SUM(ISNULL(DISCOUNT1,0))) AS DISCOUNT'  
SELECT @QRY= @QRY + CHAR(13) +',SUM(DISCOUNT) AS OFFERDISC,SUM(FIN_DISCOUNT) AS FINALDISC,SUM(FIN_PURDISCOUNT) AS FINALPURDISC'  
SELECT @QRY= @QRY + CHAR(13) +',SALESMAN,AUTHORIZE,REMARK, CONVERT(VARCHAR,'''') AS COLHEAD,''1'' AS RESULT '  
SELECT @QRY= @QRY + CHAR(13) +'FROM('  
SELECT @QRY= @QRY + CHAR(13) +'SELECT I.TRANNO AS BILLNO,I.TRANDATE AS BILLDATE,METALNAME AS METAL,I.GRSWT AS GRSWT,I.NETWT AS NETWT,'  
SELECT @QRY= @QRY + CHAR(13) +'I.AMOUNT AS AMOUNT'  
SELECT @QRY= @QRY + CHAR(13) +',I.DISCOUNT,I.FIN_DISCOUNT,I.FIN_PURDISCOUNT '  
SELECT @QRY= @QRY + CHAR(13) +',E.EMPNAME AS SALESMAN'  
SELECT @QRY= @QRY + CHAR(13) +',E1.EMPNAME AS AUTHORIZE,BATCHNO'  
SELECT @QRY= @QRY + CHAR(13) +',(SELECT SUM(AMOUNT) FROM ACCTRAN WHERE BATCHNO=I.BATCHNO AND TRANMODE=''D'' AND PAYMODE=''DI'')/(SELECT CASE WHEN COUNT(*)=0 THEN 1 ELSE COUNT(*) END FROM ISSUE AS Q WHERE Q.BATCHNO=I.BATCHNO)DISCOUNT1'  
SELECT @QRY= @QRY + CHAR(13) +',(SELECT TOP 1 REMARK1 FROM '+@ADMINDB+'..CUSTOMERINFO WHERE BATCHNO=I.BATCHNO) REMARK'   
SELECT @QRY= @QRY + CHAR(13) +'FROM ISSUE AS I'  
SELECT @QRY= @QRY + CHAR(13) +'INNER JOIN '+@ADMINDB+'..METALMAST AS M ON M.METALID=I.METALID'  
SELECT @QRY= @QRY + CHAR(13) +'INNER JOIN '+@ADMINDB+'..EMPMASTER AS E ON E.EMPID=I.EMPID '  
SELECT @QRY= @QRY + CHAR(13) +'LEFT JOIN '+@ADMINDB+'..EMPMASTER AS E1 ON E1.EMPID=I.DISC_EMPID'   
SELECT @QRY= @QRY + CHAR(13) +'WHERE I.TRANDATE BETWEEN  '''+@FROMDATE+''' AND '''+@TODATE+''''  
SELECT @QRY= @QRY + CHAR(13) +'AND I.COMPANYID IN('''+@COMPANYID+''')'  
SELECT @QRY= @QRY + CHAR(13) +'AND ISNULL(I.CANCEL,'''')='''''  
IF @COSTID<>'ALL'  
BEGIN  
SELECT @QRY= @QRY + CHAR(13) +'AND I.COSTID IN('''+@COSTID+''')'  
END  
IF @METALID<>'ALL'  
BEGIN  
SELECT @QRY= @QRY + CHAR(13) +' AND I.METALID IN('''+@METALID+''') '  
END            
SELECT @QRY= @QRY + CHAR(13) +')X'  
SELECT @QRY= @QRY + CHAR(13) +'GROUP BY BILLNO,BILLDATE,METAL,SALESMAN,AUTHORIZE,BATCHNO,REMARK '  
SELECT @QRY= @QRY + CHAR(13) +')Z'  
SELECT @QRY= @QRY + CHAR(13) +'GROUP BY BILLNO,BILLDATE,METAL,GRSWT,NETWT,AMOUNT,DISCOUNT,FINALDISC,FINALPURDISC,OFFERDISC'  
SELECT @QRY= @QRY + CHAR(13) +',SALESMAN,AUTHORIZE,COLHEAD,RESULT,REMARK '  
SELECT @QRY= @QRY + CHAR(13) +'ORDER BY BILLDATE,BILLNO'  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY=  'INSERT INTO TEMPTABLEDB..'+@TEMPTABLE+'(BILLNO,GRSWT,NETWT,AMOUNT,DISCOUNT,OFFERDISC,FINALDISC,FINALPURDISC,TOTALDISC,COLHEAD,RESULT)'  
SELECT @QRY= @QRY + CHAR(13) +'SELECT ''GRAND TOTAL'' AS BILLNO ,SUM(GRSWT),SUM(NETWT),SUM(AMOUNT)'  
SELECT @QRY= @QRY + CHAR(13) +',SUM(DISCOUNT),SUM(OFFERDISC),SUM(FINALDISC),SUM(FINALPURDISC),SUM(TOTALDISC)'  
SELECT @QRY= @QRY + CHAR(13) +',''G'' AS COLHEAD,''2'' AS RESULT FROM TEMPTABLEDB..'+@TEMPTABLE+' WHERE RESULT=1 HAVING COUNT(BILLNO)>1'  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= 'UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET DISCOUNT=NULL WHERE DISCOUNT=0'  
SELECT @QRY= @QRY + CHAR(13) +' UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET OFFERDISC=NULL WHERE OFFERDISC=0'  
SELECT @QRY= @QRY + CHAR(13) +' UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET FINALDISC=NULL WHERE FINALDISC=0'
SELECT @QRY= @QRY + CHAR(13) +' UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET FINALPURDISC=NULL WHERE FINALPURDISC=0'		   
SELECT @QRY= @QRY + CHAR(13) +' UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET TOTALDISC=NULL WHERE TOTALDISC=0'  
SELECT @QRY= @QRY + CHAR(13) +' UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET AMOUNT=NULL WHERE AMOUNT=0'  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= 'SELECT * FROM TEMPTABLEDB..'+@TEMPTABLE+' ORDER BY SNO'  
PRINT @QRY  
EXEC (@QRY)  
END  
ELSE  
BEGIN  
SELECT @QRY=  CHAR(13) +'SELECT I.SNO,I.TRANNO AS BILLNO,I.TRANDATE AS BILLDATE'  
SELECT @QRY= @QRY + CHAR(13) +',I.TAGNO,I.ITEMID,I.SUBITEMID'  
SELECT @QRY= @QRY + CHAR(13) +',IM.ITEMNAME,SI.SUBITEMNAME'  
SELECT @QRY= @QRY + CHAR(13) +',METALNAME AS METAL,I.PCS,I.GRSWT AS GRSWT,I.NETWT AS NETWT'  
SELECT @QRY= @QRY + CHAR(13) +',CONVERT(NUMERIC(20,2),NULL) TAGVALUE,I.AMOUNT AS AMOUNT,NULL STNAMT'  
SELECT @QRY= @QRY + CHAR(13) +',I.DISCOUNT,I.FIN_DISCOUNT,I.FIN_PURDISCOUNT'  
SELECT @QRY= @QRY + CHAR(13) +',E.EMPNAME AS SALESMAN'  
SELECT @QRY= @QRY + CHAR(13) +',E1.EMPNAME AS AUTHORIZE,BATCHNO'  
SELECT @QRY= @QRY + CHAR(13) +',I.RATE,I.TAGDESIGNER,I.ITEMCTRID,IM.STOCKTYPE,''D''AS COLHEAD'  
SELECT @QRY= @QRY + CHAR(13) +',CONVERT(NUMERIC(20,3),NULL) MAXWASTPER '  
SELECT @QRY= @QRY + CHAR(13) +',CONVERT(NUMERIC(20,3),NULL) MAXMCGRM'  
SELECT @QRY= @QRY + CHAR(13) +',CONVERT(NUMERIC(20,3),NULL) MAXWAST'  
SELECT @QRY= @QRY + CHAR(13) +',CONVERT(NUMERIC(20,3),NULL) MC'  
SELECT @QRY= @QRY + CHAR(13) +',CONVERT(NUMERIC(20,3),NULL) MAXMC'  
SELECT @QRY= @QRY + CHAR(13) +',CONVERT(NUMERIC(20,3),NULL) WASTAGE,1 AS RESULT'  
SELECT @QRY= @QRY + CHAR(13) +',(SELECT TOP 1 REMARK1 FROM '+@ADMINDB+'..CUSTOMERINFO WHERE BATCHNO=I.BATCHNO) REMARK'   
SELECT @QRY= @QRY + CHAR(13) +'INTO TEMPTABLEDB..'+@TEMPTABLE+' FROM ISSUE AS I'  
SELECT @QRY= @QRY + CHAR(13) +'INNER JOIN '+@ADMINDB+'..ITEMMAST AS IM ON IM.ITEMID=I.ITEMID'  
SELECT @QRY= @QRY + CHAR(13) +'LEFT JOIN '+@ADMINDB+'..SUBITEMMAST AS SI ON SI.SUBITEMID=I.SUBITEMID'  
SELECT @QRY= @QRY + CHAR(13) +'INNER JOIN '+@ADMINDB+'..METALMAST AS M ON M.METALID=I.METALID'  
SELECT @QRY= @QRY + CHAR(13) +'INNER JOIN '+@ADMINDB+'..EMPMASTER AS E ON E.EMPID=I.EMPID '  
SELECT @QRY= @QRY + CHAR(13) +'LEFT JOIN '+@ADMINDB+'..EMPMASTER AS E1 ON E1.EMPID=I.DISC_EMPID'  
SELECT @QRY= @QRY + CHAR(13) +'WHERE I.TRANDATE BETWEEN  '''+@FROMDATE+''' AND '''+@TODATE+''''  
SELECT @QRY= @QRY + CHAR(13) +'AND I.COMPANYID IN('''+@COMPANYID+''')'  
SELECT @QRY= @QRY + CHAR(13) +'AND ISNULL(I.CANCEL,'''')='''''  
IF @COSTID<>'ALL'  
BEGIN  
SELECT @QRY= @QRY + CHAR(13) +'AND I.COSTID IN('''+@COSTID+''')'  
END  
IF @METALID<>'ALL'  
BEGIN  
SELECT @QRY= @QRY + CHAR(13) +' AND I.METALID IN('''+@METALID+''') '  
END            
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= CHAR(13) +'UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET MAXWASTPER =W.MAXWASTPER,MAXMCGRM=W.MAXMCGRM , MAXWAST =W.MAXWAST, MAXMC =W.MAXMC '  
SELECT @QRY= @QRY + CHAR(13) +'FROM '+@ADMINDB+'..ITEMTAG  W,TEMPTABLEDB..'+@TEMPTABLE+' T'  
SELECT @QRY= @QRY + CHAR(13) +'WHERE W.TAGNO = T.TAGNO AND T.STOCKTYPE =''T'' AND  T.MAXWASTPER IS NULL'  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= CHAR(13) +'UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET MAXWASTPER =W.WASTPER,MAXMCGRM=W.MCPERGRM , MAXWAST =W.WASTAGE , MAXMC =W.MC  '  
SELECT @QRY= @QRY + CHAR(13) +'FROM '+@ADMINDB+'..ITEMNONTAG  W,TEMPTABLEDB..'+@TEMPTABLE+' T'  
SELECT @QRY= @QRY + CHAR(13) +'WHERE W.ITEMID  = T.ITEMID  AND T.STOCKTYPE =''N'' '  
SELECT @QRY= @QRY + CHAR(13) +'AND T.SUBITEMID = W.SUBITEMID AND T.TAGDESIGNER =W.DESIGNERID '  
SELECT @QRY= @QRY + CHAR(13) +'AND T.ITEMCTRID = W.ITEMCTRID AND W.RECISS =''R'''  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= CHAR(13) +'UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET WASTAGE = GRSWT * MAXWASTPER / 100 WHERE ISNULL(MAXWASTPER,0)>0'  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= CHAR(13) +'UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET WASTAGE = MAXWAST WHERE ISNULL(MAXWAST,0)>0 AND ISNULL(WASTAGE,0)=0'  
PRINT @QRY  
EXEC (@QRY)  
DECLARE @MCWITHWASTAGE VARCHAR(1);   
SELECT @MCWITHWASTAGE=CASE WHEN ISNULL(CTLTEXT,'N') <>'' THEN ISNULL(CTLTEXT,'N')  ELSE 'N' END  FROM BMGADMINDB..SOFTCONTROL WHERE CTLID = 'MCWITHWASTAGE'  
IF  @MCWITHWASTAGE='Y'   
BEGIN  
SELECT @QRY= CHAR(13) +'UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET MC = (GRSWT +WASTAGE) * MAXMCGRM * PCS  WHERE ISNULL(MAXMCGRM,0)>0'  
EXEC (@QRY)  
END  
ELSE  
BEGIN  
SELECT @QRY= CHAR(13) +'UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET MC = GRSWT  * MAXMCGRM * PCS  WHERE ISNULL(MAXMCGRM,0)>0'  
EXEC (@QRY)  
END  
SELECT @QRY= CHAR(13) +'UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET MC = MAXMC * PCS  WHERE ISNULL(MAXMC,0)>0 AND ISNULL(MC,0)=0'  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= CHAR(13) +'UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET WASTAGE =0 WHERE MAXWASTPER=0 AND MAXWAST=0 AND WASTAGE IS NULL'  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= CHAR(13) +'UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET MC =0 WHERE MAXMCGRM=0 AND MAXMC=0 AND MC IS NULL'  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= CHAR(13) +'UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET STNAMT = I.STNAMT FROM '  
SELECT @QRY= @QRY + CHAR(13) +'(SELECT SUM(STNAMT)STNAMT,ISSSNO  FROM ISSSTONE GROUP BY ISSSNO) I'  
SELECT @QRY= @QRY + CHAR(13) +',TEMPTABLEDB..'+@TEMPTABLE+' T WHERE I.ISSSNO =T.SNO '  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= CHAR(13) +'UPDATE TEMPTABLEDB..'+@TEMPTABLE+' SET TAGVALUE = (ISNULL(GRSWT,0)+ISNULL(WASTAGE,0))*ISNULL(RATE,0) + ISNULL(MC ,0) +ISNULL(STNAMT,0) '  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= CHAR(13) +'ALTER TABLE TEMPTABLEDB..'+@TEMPTABLE+' DROP COLUMN RATE'  
SELECT @QRY= @QRY + CHAR(13) +'ALTER TABLE TEMPTABLEDB..'+@TEMPTABLE+' DROP COLUMN ITEMID'  
SELECT @QRY= @QRY + CHAR(13) +'ALTER TABLE TEMPTABLEDB..'+@TEMPTABLE+' DROP COLUMN SUBITEMID'  
SELECT @QRY= @QRY + CHAR(13) +'ALTER TABLE TEMPTABLEDB..'+@TEMPTABLE+' DROP COLUMN METAL'  
SELECT @QRY= @QRY + CHAR(13) +'ALTER TABLE TEMPTABLEDB..'+@TEMPTABLE+' DROP COLUMN STNAMT'  
SELECT @QRY= @QRY + CHAR(13) +'ALTER TABLE TEMPTABLEDB..'+@TEMPTABLE+' DROP COLUMN TAGDESIGNER'  
SELECT @QRY= @QRY + CHAR(13) +'ALTER TABLE TEMPTABLEDB..'+@TEMPTABLE+' DROP COLUMN ITEMCTRID'  
SELECT @QRY= @QRY + CHAR(13) +'ALTER TABLE TEMPTABLEDB..'+@TEMPTABLE+' DROP COLUMN STOCKTYPE'  
SELECT @QRY= @QRY + CHAR(13) +'ALTER TABLE TEMPTABLEDB..'+@TEMPTABLE+' DROP COLUMN MAXWAST'  
SELECT @QRY= @QRY + CHAR(13) +'ALTER TABLE TEMPTABLEDB..'+@TEMPTABLE+' DROP COLUMN MC'  
SELECT @QRY= @QRY + CHAR(13) +'ALTER TABLE TEMPTABLEDB..'+@TEMPTABLE+' DROP COLUMN WASTAGE'  
SELECT @QRY= @QRY + CHAR(13) +'ALTER TABLE TEMPTABLEDB..'+@TEMPTABLE+' DROP COLUMN MAXWASTPER'  
SELECT @QRY= @QRY + CHAR(13) +'ALTER TABLE TEMPTABLEDB..'+@TEMPTABLE+' DROP COLUMN MAXMCGRM'  
SELECT @QRY= @QRY + CHAR(13) +'ALTER TABLE TEMPTABLEDB..'+@TEMPTABLE+' DROP COLUMN MAXMC'  
SELECT @QRY= @QRY + CHAR(13) +'ALTER TABLE TEMPTABLEDB..'+@TEMPTABLE+' DROP COLUMN SNO'  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= 'IF  EXISTS (SELECT * FROM TEMPTABLEDB..SYSOBJECTS WHERE XTYPE = ''U'' AND NAME = ''TEMP'+@TEMPTABLE+''' )DROP TABLE TEMPTABLEDB..TEMP'+@TEMPTABLE+' '  
EXEC (@QRY)  
SELECT @QRY= CHAR(13) +'SELECT BILLNO,BILLDATE,TAGNO,ITEMNAME,SUBITEMNAME'  
SELECT @QRY= @QRY + CHAR(13) +' ,SUM(PCS)PCS,SUM(GRSWT)GRSWT,SUM(NETWT)NETWT,SUM(TAGVALUE)TAGVALUE'  
SELECT @QRY= @QRY + CHAR(13) +' ,SUM(AMOUNT)AMOUNT'  
SELECT @QRY= @QRY + CHAR(13) +' ,CONVERT(NUMERIC(20,2),((SELECT SUM(AMOUNT) FROM ACCTRAN WHERE BATCHNO=I.BATCHNO '  
SELECT @QRY= @QRY + CHAR(13) +' AND PAYMODE=''DI'' AND TRANMODE=''D'')'  
SELECT @QRY= @QRY + CHAR(13) +' /(SELECT CASE WHEN COUNT(*)=0 THEN 1 ELSE COUNT(*) END '  
SELECT @QRY= @QRY + CHAR(13) +' FROM ISSUE WHERE BATCHNO=I.BATCHNO))) DISCOUNT'  
SELECT @QRY= @QRY + CHAR(13) +' ,SUM(DISCOUNT) AS OFFERDISC,SUM(FIN_DISCOUNT) AS FINALDISC,SUM(FIN_PURDISCOUNT) AS FINALPURDISC,CONVERT(NUMERIC(20,2),NULL)TOTALDISC'  
SELECT @QRY= @QRY + CHAR(13) +' ,CONVERT(NUMERIC(20,2),NULL)DISCPER'  
SELECT @QRY= @QRY + CHAR(13) +' ,SALESMAN,AUTHORIZE,REMARK,BATCHNO,COLHEAD,RESULT'  
SELECT @QRY= @QRY + CHAR(13) +' INTO TEMPTABLEDB..TEMP'+@TEMPTABLE+''  
SELECT @QRY= @QRY + CHAR(13) +' FROM TEMPTABLEDB..'+@TEMPTABLE+' I '  
SELECT @QRY= @QRY + CHAR(13) +' GROUP BY BILLNO,BILLDATE,TAGNO,ITEMNAME,SUBITEMNAME,SALESMAN'  
SELECT @QRY= @QRY + CHAR(13) +' ,AUTHORIZE,COLHEAD,RESULT,BATCHNO,REMARK'  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= CHAR(13) +'INSERT INTO TEMPTABLEDB..TEMP'+@TEMPTABLE+''  
SELECT @QRY= @QRY + CHAR(13) +'(TAGNO,PCS,GRSWT,NETWT,TAGVALUE,AMOUNT,DISCOUNT,OFFERDISC,FINALDISC,FINALPURDISC,RESULT,COLHEAD,BATCHNO)'  
SELECT @QRY= @QRY + CHAR(13) +'SELECT '' '''  
SELECT @QRY= @QRY + CHAR(13) +',SUM(PCS),SUM(GRSWT),SUM(NETWT),SUM(TAGVALUE),SUM(AMOUNT),SUM(DISCOUNT),SUM(OFFERDISC),SUM(FINALDISC),SUM(FINALPURDISC)'  
SELECT @QRY= @QRY + CHAR(13) +',2,''S'',BATCHNO'  
SELECT @QRY= @QRY + CHAR(13) +'FROM TEMPTABLEDB..TEMP'+@TEMPTABLE+' GROUP BY BATCHNO /*HAVING COUNT(BATCHNO)>1*/'  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= CHAR(13) +'INSERT INTO TEMPTABLEDB..TEMP'+@TEMPTABLE+''  
SELECT @QRY= @QRY + CHAR(13) +'(TAGNO,PCS,GRSWT,NETWT,TAGVALUE,AMOUNT,DISCOUNT,OFFERDISC,FINALDISC,FINALPURDISC,RESULT,COLHEAD,BATCHNO)'  
SELECT @QRY= @QRY + CHAR(13) +'SELECT ''TOTAL'''  
SELECT @QRY= @QRY + CHAR(13) +',SUM(PCS),SUM(GRSWT),SUM(NETWT),SUM(TAGVALUE),SUM(AMOUNT),SUM(DISCOUNT),SUM(OFFERDISC),SUM(FINALDISC),SUM(FINALPURDISC)'  
SELECT @QRY= @QRY + CHAR(13) +',3,''G'',''ZZZZZ99999999'''  
SELECT @QRY= @QRY + CHAR(13) +'FROM TEMPTABLEDB..TEMP'+@TEMPTABLE+' WHERE RESULT=1'  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= CHAR(13) +'UPDATE  TEMPTABLEDB..TEMP'+@TEMPTABLE+' SET TOTALDISC=(ISNULL(OFFERDISC,0)+ISNULL(FINALDISC,0)+ISNULL(DISCOUNT,0))'  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= CHAR(13) +'UPDATE  TEMPTABLEDB..TEMP'+@TEMPTABLE+' SET DISCPER=(TOTALDISC*100)/CASE WHEN AMOUNT=0 THEN 1 ELSE AMOUNT END'  
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= CHAR(13) +'UPDATE  TEMPTABLEDB..TEMP'+@TEMPTABLE+' SET TOTALDISC=NULL WHERE TOTALDISC=0'  
SELECT @QRY= @QRY+CHAR(13) +'UPDATE  TEMPTABLEDB..TEMP'+@TEMPTABLE+' SET DISCPER=NULL WHERE DISCPER=0'  
SELECT @QRY= @QRY+CHAR(13) +'UPDATE  TEMPTABLEDB..TEMP'+@TEMPTABLE+' SET DISCOUNT=NULL WHERE DISCOUNT=0'  
SELECT @QRY= @QRY+CHAR(13) +'UPDATE  TEMPTABLEDB..TEMP'+@TEMPTABLE+' SET FINALDISC=NULL WHERE FINALDISC=0'
SELECT @QRY= @QRY+CHAR(13) +'UPDATE  TEMPTABLEDB..TEMP'+@TEMPTABLE+' SET FINALPURDISC=NULL WHERE FINALPURDISC=0'		   
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY= CHAR(13) +'SELECT * FROM  TEMPTABLEDB..TEMP'+@TEMPTABLE+' ORDER BY CONVERT(INT,SUBSTRING(BATCHNO,6,20)),RESULT '  
PRINT @QRY  
EXEC (@QRY)  
END  
END  
END