 /*=============================================
 Author:		<>
 Create Date:   <11-08-2022>
 Description:	<TRANSFER REPORT, ITEMTAG, DATA Get FROM BASE TABLE [ITEMTAG , ITEMNONTAG ,TRANSIT_AUDIT ]> 
 ============================================= */
  ALTER PROCEDURE PROC_TRANSFERSUMMARYCOSTCENTREWISE
     (
	 @DBNAME VARCHAR(20)
	,@ADMINDB VARCHAR(20)
	,@FROMDATE VARCHAR(15)
	,@TODATE VARCHAR(15)
	,@MCOSTNAME VARCHAR(30)
	,@MCOSTID VARCHAR(4)
	,@CCOSTID VARCHAR(50)
	)
AS
BEGIN
	    SET NOCOUNT ON;
        DECLARE @QRY VARCHAR(MAX) 
        DECLARE @QRY1 VARCHAR(MAX) 
        DECLARE @COSTID VARCHAR(50)
        DECLARE @COSTNAME VARCHAR(50)
       /* GET ALL THEN RECORD TO INSERT TEMPTABLE ==>  TABLE NAME [TEMP_SYNCISSREC_TR_OT] [BASE TABLE [ITEMTAG , ITEMNONTAG ,TRANSIT_AUDIT]*/
       SELECT @QRY =CHAR(13)+''
       SELECT @QRY=@QRY+CHAR(13)+' IF OBJECT_ID(''TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT'',''U'')IS NOT NULL DROP TABLE TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT'
       SELECT @QRY=@QRY+CHAR(13)+' SELECT CONVERT(VARCHAR(200),NULL)PARTICULAR'
       SELECT @QRY=@QRY+CHAR(13)+',IFC.COSTNAME [ISSUED FROM]'
       SELECT @QRY=@QRY+CHAR(13)+',ITC.COSTNAME [ISSUED TO]'
       SELECT @QRY=@QRY+CHAR(13)+',IM.ITEMNAME,SM.SUBITEMNAME,TAG.TAGNO,TAG.PCS,TAG.GRSWT,TAG.NETWT'
       SELECT @QRY=@QRY+CHAR(13)+',(SELECT SUM(STNPCS) FROM '+ @ADMINDB +'..ITEMTAGSTONE WHERE TAGSNO = TAG.SNO AND STNITEMID IN (SELECT ITEMID FROM '+ @ADMINDB +'..ITEMMAST WHERE DIASTONE = ''D'')) AS DIAPCS'
       SELECT @QRY=@QRY+CHAR(13)+',(SELECT SUM(STNWT) FROM '+ @ADMINDB +'..ITEMTAGSTONE WHERE TAGSNO = TAG.SNO AND STNITEMID IN (SELECT ITEMID FROM '+ @ADMINDB +'..ITEMMAST WHERE DIASTONE = ''D'')) AS DIAWT'
       SELECT @QRY=@QRY+CHAR(13)+',(SELECT SUM(STNPCS) FROM '+ @ADMINDB +'..ITEMTAGSTONE WHERE TAGSNO = TAG.SNO AND STNITEMID IN (SELECT ITEMID FROM '+ @ADMINDB +'..ITEMMAST WHERE DIASTONE = ''S'')) AS STNPCS'
	   SELECT @QRY=@QRY+CHAR(13)+',(SELECT SUM(STNWT) FROM '+ @ADMINDB +'..ITEMTAGSTONE WHERE TAGSNO = TAG.SNO AND STNITEMID IN (SELECT ITEMID FROM '+ @ADMINDB +'..ITEMMAST WHERE DIASTONE = ''S'')) AS STNWT'
	   SELECT @QRY=@QRY+CHAR(13)+' ,(SELECT TOP 1 STONEUNIT  FROM '+ @ADMINDB +'..ITEMTAGSTONE WHERE TAGSNO = TAG.SNO AND STNITEMID IN (SELECT ITEMID FROM '+ @ADMINDB +'..ITEMMAST WHERE DIASTONE = ''S'')) AS STONEUNIT'
	   SELECT @QRY=@QRY+CHAR(13)+',CASE WHEN TAG.MAXWASTPER=0 THEN NULL ELSE TAG.MAXWASTPER END AS WASTPER '
	   SELECT @QRY=@QRY+CHAR(13)+',CASE WHEN TAG.MAXWAST=0 THEN NULL ELSE TAG.MAXWAST END AS WASTAGE'
	   SELECT @QRY=@QRY+CHAR(13)+',CASE WHEN TAG.MAXMCGRM=0 THEN NULL ELSE TAG.MAXMCGRM END AS MCGRM '
	   SELECT @QRY=@QRY+CHAR(13)+',CASE WHEN TAG.MAXMC=0 THEN NULL ELSE TAG.MAXMC END AS MC'
	   SELECT @QRY=@QRY+CHAR(13)+',TAG.RATE,TAG.SALVALUE'
	   SELECT @QRY=@QRY+CHAR(13)+',TAG.TABLECODE'
	   SELECT @QRY=@QRY+CHAR(13)+',(SELECT TOP 1 LOTNO FROM '+ @ADMINDB +'..ITEMLOT L WHERE L.SNO=TAG.LOTSNO)LOTNO'
	   SELECT @QRY=@QRY+CHAR(13)+',(SELECT NAME FROM '+ @ADMINDB +'..ITEMTYPE WHERE ITEMTYPEID=TAG.ITEMTYPEID)ITEMTYPE'
	   SELECT @QRY=@QRY+CHAR(13)+' ,(SELECT TOP 1 SHORTNAME FROM '+ @ADMINDB +'..ITEMMAST WHERE ITEMID IN ((SELECT STNITEMID FROM '+ @ADMINDB +'..ITEMTAGSTONE S WHERE ' 
	   SELECT @QRY=@QRY+CHAR(13)+'S.ITEMID = TAG.ITEMID AND S.TAGNO = TAG.TAGNO  AND STNITEMID IN (SELECT ITEMID FROM '+ @ADMINDB +'..ITEMMAST WHERE DIASTONE = ''D'')))) [CLARITY]'
	   SELECT @QRY=@QRY+CHAR(13)+',CASE WHEN STKTYPE=''M'' THEN ''MANUFACTURING'' WHEN STKTYPE=''E'' THEN ''EXEMPTED'' ELSE ''TRADING'' END AS STOCKTYPE'
	   SELECT @QRY=@QRY+CHAR(13)+',(SELECT DESIGNERNAME FROM '+ @ADMINDB +'..DESIGNER WHERE DESIGNERID = TAG.DESIGNERID) DESIGNERNAME'
	   SELECT @QRY=@QRY+CHAR(13)+',TAG.TAGVAL/*,TAG.TRANINVNO REFNO*/,CASE WHEN ISNULL(T.REFNO,'''') <>'''' THEN T.REFNO ELSE TAG.TRANINVNO END REFNO '
	   SELECT @QRY=@QRY+CHAR(13)+',CONVERT(VARCHAR(200),NULL)GROUP1'
	   SELECT @QRY=@QRY+CHAR(13)+',CONVERT(VARCHAR(200),NULL)GROUP2'
	   SELECT @QRY=@QRY+CHAR(13)+',CONVERT(VARCHAR(3),NULL)COLHEAD'
	   SELECT @QRY=@QRY+CHAR(13)+',CONVERT(INT,1)RESULT'
	   SELECT @QRY=@QRY+CHAR(13)+',T.TRANDATE AS [ISSUED DATE]'
	   SELECT @QRY=@QRY+CHAR(13)+',CONVERT(VARCHAR(100),(CASE WHEN ISNULL((SELECT ENTORDER FROM '+ @ADMINDB +'..CTRANSFER WHERE TAGSNO=T.TAGSNO AND TRFNO=T.REFNO AND COSTID=T.FROMID) ,0)=1 THEN ''LOT'' ELSE ''TRANSFER'' END)) FLAG'
	   SELECT @QRY=@QRY+CHAR(13)+', CNT.ITEMCTRNAME AS COUNTERNAME  '
	   SELECT @QRY=@QRY+CHAR(13)+'INTO TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT'
	   SELECT @QRY=@QRY+CHAR(13)+'FROM '+ @DBNAME +'..TRANSIT_AUDIT T'
	   SELECT @QRY=@QRY+CHAR(13)+'INNER JOIN '+ @ADMINDB +'..ITEMTAG AS TAG ON TAG.SNO = T.TAGSNO'
	   SELECT @QRY=@QRY+CHAR(13)+'INNER JOIN '+ @ADMINDB +'..ITEMMAST AS IM ON IM.ITEMID = TAG.ITEMID'
	   SELECT @QRY=@QRY+CHAR(13)+'INNER JOIN '+ @ADMINDB +'..COSTCENTRE AS IFC ON IFC.COSTID = T.FROMID '
	   SELECT @QRY=@QRY+CHAR(13)+'LEFT JOIN '+ @ADMINDB +'..SUBITEMMAST AS SM ON SM.SUBITEMID = TAG.SUBITEMID AND SM.ITEMID=TAG.ITEMID'
	   SELECT @QRY=@QRY+CHAR(13)+' AND IFC.COSTNAME IN ('''+@MCOSTNAME+''')'
	   SELECT @QRY=@QRY+CHAR(13)+'INNER JOIN '+ @ADMINDB +'..COSTCENTRE AS ITC ON ITC.COSTID = T.TOID '
	   SELECT @QRY=@QRY+CHAR(13)+'INNER JOIN '+ @ADMINDB +'..ITEMCOUNTER AS CNT ON CNT.ITEMCTRID = TAG.ITEMCTRID '
	   SELECT @QRY=@QRY+CHAR(13)+'WHERE 1=1 '
	   SELECT @QRY=@QRY+CHAR(13)+'AND T.TRANDATE BETWEEN '''+@FROMDATE+''' AND '''+@TODATE+''' '
	   SELECT @QRY=@QRY+CHAR(13)+'AND T.ISSREC = ''I'''
	   SELECT @QRY=@QRY+CHAR(13)+'AND T.TOID IN('+ @CCOSTID +')'
       SELECT @QRY=@QRY+CHAR(13)+'UNION ALL '
	   SELECT @QRY=@QRY+CHAR(13)+'SELECT '
	   SELECT @QRY=@QRY+CHAR(13)+'CONVERT(VARCHAR(200),NULL)PARTICULAR'
	   SELECT @QRY=@QRY+CHAR(13)+',IFC.COSTNAME [ISSUED FROM]'
	   SELECT @QRY=@QRY+CHAR(13)+',ITC.COSTNAME [ISSUED TO]'
	   SELECT @QRY=@QRY+CHAR(13)+',IM.ITEMNAME,SM.SUBITEMNAME,NULL TAGNO,T.PCS,T.GRSWT,T.NETWT'
	   SELECT @QRY=@QRY+CHAR(13)+',(SELECT SUM(STNPCS) FROM '+ @ADMINDB +'..ITEMNONTAGSTONE WHERE TAGSNO = T.SNO AND STNITEMID IN (SELECT ITEMID FROM '+ @ADMINDB +'..ITEMMAST WHERE DIASTONE = ''D'')) AS DIAPCS'
	   SELECT @QRY=@QRY+CHAR(13)+',(SELECT SUM(STNWT) FROM '+ @ADMINDB +'..ITEMNONTAGSTONE WHERE TAGSNO = T.SNO AND STNITEMID IN (SELECT ITEMID FROM '+ @ADMINDB +'..ITEMMAST WHERE DIASTONE = ''D'')) AS DIAWT'
	   SELECT @QRY=@QRY+CHAR(13)+',(SELECT SUM(STNPCS) FROM '+ @ADMINDB +'..ITEMNONTAGSTONE WHERE TAGSNO = T.SNO AND STNITEMID IN (SELECT ITEMID FROM '+ @ADMINDB +'..ITEMMAST WHERE DIASTONE = ''S'')) AS STNPCS'
	   SELECT @QRY=@QRY+CHAR(13)+',(SELECT SUM(STNWT) FROM '+ @ADMINDB +'..ITEMNONTAGSTONE WHERE TAGSNO = T.SNO AND STNITEMID IN (SELECT ITEMID FROM '+ @ADMINDB +'..ITEMMAST WHERE DIASTONE = ''S'')) AS STNWT'
	   SELECT @QRY=@QRY+CHAR(13)+' ,(SELECT TOP 1 STONEUNIT  FROM '+ @ADMINDB +'..ITEMNONTAGSTONE WHERE TAGSNO = T.SNO AND STNITEMID IN (SELECT ITEMID FROM '+ @ADMINDB +'..ITEMMAST WHERE DIASTONE = ''S'')) AS STONEUNIT'
	   SELECT @QRY=@QRY+CHAR(13)+',CASE WHEN T.WASTPER=0 THEN NULL ELSE T.WASTPER END AS WASTPER ' 
	   SELECT @QRY=@QRY+CHAR(13)+',CASE WHEN T.WASTAGE=0 THEN NULL ELSE T.WASTAGE END AS WASTAGE'
	   SELECT @QRY=@QRY+CHAR(13)+',0  MCGRM '
	   SELECT @QRY=@QRY+CHAR(13)+',CASE WHEN T.MC=0 THEN NULL ELSE T.MC END AS MC'
	   SELECT @QRY=@QRY+CHAR(13)+',T.RATE,NULL SALVALUE'
	   SELECT @QRY=@QRY+CHAR(13)+',NULL TABLECODE'
	   SELECT @QRY=@QRY+CHAR(13)+',(SELECT TOP 1 LOTNO FROM '+ @ADMINDB +'..ITEMLOT L WHERE L.SNO=T.LOTSNO)LOTNO'
	   SELECT @QRY=@QRY+CHAR(13)+',(SELECT NAME FROM '+ @ADMINDB +'..ITEMTYPE WHERE ITEMTYPEID=T.ITEMTYPEID)ITEMTYPE,'
	   SELECT @QRY=@QRY+CHAR(13)+'NULL [CLARITY]'
	   SELECT @QRY=@QRY+CHAR(13)+',CASE WHEN STKTYPE=''M'' THEN ''MANUFACTURING'' WHEN STKTYPE=''E'' THEN ''EXEMPTED'' ELSE ''TRADING'' END AS STOCKTYPE'
	   SELECT @QRY=@QRY+CHAR(13)+',(SELECT DESIGNERNAME FROM '+ @ADMINDB +'..DESIGNER WHERE DESIGNERID = T.DESIGNERID) DESIGNERNAME'
	   SELECT @QRY=@QRY+CHAR(13)+', NULL TAGVAL/*,TAG.TRANINVNO REFNO*/,CASE WHEN ISNULL(T.REFNO,'''') <>'''' THEN T.REFNO ELSE NULL END REFNO '
	   SELECT @QRY=@QRY+CHAR(13)+',CONVERT(VARCHAR(200),NULL)GROUP1'
	   SELECT @QRY=@QRY+CHAR(13)+',CONVERT(VARCHAR(200),NULL)GROUP2'
	   SELECT @QRY=@QRY+CHAR(13)+',CONVERT(VARCHAR(3),NULL)COLHEAD'
	   SELECT @QRY=@QRY+CHAR(13)+',CONVERT(INT,1)RESULT'
	   SELECT @QRY=@QRY+CHAR(13)+',T.RECDATE AS [ISSUED DATE]'
	   SELECT @QRY=@QRY+CHAR(13)+',''TRANSFER'' FLAG'
	   SELECT @QRY=@QRY+CHAR(13)+', CNT.ITEMCTRNAME AS COUNTERNAME '
	   SELECT @QRY=@QRY+CHAR(13)+'FROM '+ @ADMINDB +'..ITEMNONTAG T'
	   SELECT @QRY=@QRY+CHAR(13)+'INNER JOIN '+ @ADMINDB +'..ITEMMAST AS IM ON IM.ITEMID = T.ITEMID'
	   SELECT @QRY=@QRY+CHAR(13)+'INNER JOIN '+ @ADMINDB +'..COSTCENTRE AS IFC ON IFC.COSTID = '''+@MCOSTID+''' '
	   SELECT @QRY=@QRY+CHAR(13)+'INNER JOIN '+ @ADMINDB +'..COSTCENTRE AS ITC ON ITC.COSTID = T.TCOSTID '
	   SELECT @QRY=@QRY+CHAR(13)+'LEFT JOIN '+ @ADMINDB +'..SUBITEMMAST AS SM ON SM.SUBITEMID = T.SUBITEMID AND SM.ITEMID=T.ITEMID'
	   SELECT @QRY=@QRY+CHAR(13)+'INNER JOIN '+ @ADMINDB +'..ITEMCOUNTER AS CNT ON CNT.ITEMCTRID = T.ITEMCTRID '
	   SELECT @QRY=@QRY+CHAR(13)+'WHERE 1=1 '
	   SELECT @QRY=@QRY+CHAR(13)+'AND T.RECDATE BETWEEN '''+@FROMDATE+''' AND '''+@TODATE+''' '
	   SELECT @QRY=@QRY+CHAR(13)+'AND T.RECISS = ''I''  '
	   SELECT @QRY=@QRY+CHAR(13)+'AND T.ISSTYPE =''TR'''
	   SELECT @QRY=@QRY+CHAR(13)+'AND T.COSTID IN('''+@MCOSTID+''')'
	   SELECT @QRY=@QRY+CHAR(13)+'AND T.TCOSTID IN('+ @CCOSTID +')'
       SELECT @QRY=@QRY+CHAR(13)+' UNION ALL '
       SELECT @QRY=@QRY+CHAR(13)+' SELECT '
	   SELECT @QRY=@QRY+CHAR(13)+' CONVERT(VARCHAR(200),NULL)PARTICULAR'
	   SELECT @QRY=@QRY+CHAR(13)+' ,IFC.COSTNAME [ISSUED FROM]'
	   SELECT @QRY=@QRY+CHAR(13)+' ,ITC.COSTNAME [ISSUED TO]'
	   SELECT @QRY=@QRY+CHAR(13)+' ,IM.ITEMNAME,SM.SUBITEMNAME,T.TAGNO  TAGNO,T.PCS,T.GRSWT,T.NETWT'
	   SELECT @QRY=@QRY+CHAR(13)+',(SELECT SUM(STNPCS) FROM '+ @ADMINDB +'..ITEMTAGSTONE WHERE TAGSNO = T.SNO AND STNITEMID IN (SELECT ITEMID FROM '+ @ADMINDB +'..ITEMMAST WHERE DIASTONE = ''D'')) AS DIAPCS'
	   SELECT @QRY=@QRY+CHAR(13)+',(SELECT SUM(STNWT) FROM '+ @ADMINDB +'..ITEMTAGSTONE WHERE TAGSNO = T.SNO AND STNITEMID IN (SELECT ITEMID FROM '+ @ADMINDB +'..ITEMMAST WHERE DIASTONE = ''D'')) AS DIAWT'
	   SELECT @QRY=@QRY+CHAR(13)+',(SELECT SUM(STNPCS) FROM '+ @ADMINDB +'..ITEMTAGSTONE WHERE TAGSNO = T.SNO AND STNITEMID IN (SELECT ITEMID FROM '+ @ADMINDB +'..ITEMMAST WHERE DIASTONE = ''S'')) AS STNPCS'
	   SELECT @QRY=@QRY+CHAR(13)+',(SELECT SUM(STNWT) FROM '+ @ADMINDB +'..ITEMTAGSTONE WHERE TAGSNO = T.SNO AND STNITEMID IN (SELECT ITEMID FROM '+ @ADMINDB +'..ITEMMAST WHERE DIASTONE = ''S'')) AS STNWT'
       SELECT @QRY=@QRY+CHAR(13)+' ,(SELECT TOP 1 STONEUNIT  FROM '+ @ADMINDB +'..ITEMTAGSTONE WHERE TAGSNO = T.SNO AND STNITEMID IN (SELECT ITEMID FROM '+ @ADMINDB +'..ITEMMAST WHERE DIASTONE = ''S'')) AS STONEUNIT'
	   SELECT @QRY=@QRY+CHAR(13)+' ,0 AS WASTPER  '
	   SELECT @QRY=@QRY+CHAR(13)+' ,0 AS WASTAGE'
	   SELECT @QRY=@QRY+CHAR(13)+' ,0  MCGRM '
	   SELECT @QRY=@QRY+CHAR(13)+' ,0 AS MC'
	   SELECT @QRY=@QRY+CHAR(13)+' ,T.RATE,NULL SALVALUE'
	   SELECT @QRY=@QRY+CHAR(13)+' ,NULL TABLECODE'
	   SELECT @QRY=@QRY+CHAR(13)+' ,(SELECT TOP 1 LOTNO FROM '+ @ADMINDB +'..ITEMLOT L WHERE L.SNO=T.LOTSNO)LOTNO'
	   SELECT @QRY=@QRY+CHAR(13)+' ,(SELECT NAME FROM '+ @ADMINDB +'..ITEMTYPE WHERE ITEMTYPEID=T.ITEMTYPEID)ITEMTYPE,'
	   SELECT @QRY=@QRY+CHAR(13)+' NULL [CLARITY]'
	   SELECT @QRY=@QRY+CHAR(13)+',CASE WHEN STKTYPE=''M'' THEN ''MANUFACTURING'' WHEN STKTYPE=''E'' THEN ''EXEMPTED'' ELSE ''TRADING'' END AS STOCKTYPE'
	   SELECT @QRY=@QRY+CHAR(13)+' ,(SELECT DESIGNERNAME FROM '+ @ADMINDB +'..DESIGNER WHERE DESIGNERID = T.DESIGNERID) DESIGNERNAME'
	   SELECT @QRY=@QRY+CHAR(13)+' , NULL TAGVAL/*,TAG.TRANINVNO REFNO*/,CASE WHEN ISNULL(T.REFNO,'''') <>'''' THEN T.REFNO ELSE NULL END REFNO '
	   SELECT @QRY=@QRY+CHAR(13)+' ,CONVERT(VARCHAR(200),NULL)GROUP1'
	   SELECT @QRY=@QRY+CHAR(13)+' ,CONVERT(VARCHAR(200),NULL)GROUP2'
	   SELECT @QRY=@QRY+CHAR(13)+' ,CONVERT(VARCHAR(3),NULL)COLHEAD'
	   SELECT @QRY=@QRY+CHAR(13)+' ,CONVERT(INT,1)RESULT'
	   SELECT @QRY=@QRY+CHAR(13)+' ,T.RECDATE AS [ISSUED DATE]'
	   SELECT @QRY=@QRY+CHAR(13)+' ,''TRANSFER'' FLAG'
	   SELECT @QRY=@QRY+CHAR(13)+' , CNT.ITEMCTRNAME AS COUNTERNAME '
	   SELECT @QRY=@QRY+CHAR(13)+' FROM '+ @ADMINDB +'..ITEMTAG T'
	   SELECT @QRY=@QRY+CHAR(13)+' INNER JOIN '+ @ADMINDB +'..ITEMMAST AS IM ON IM.ITEMID = T.ITEMID'
	   SELECT @QRY=@QRY+CHAR(13)+' INNER JOIN '+ @ADMINDB +'..COSTCENTRE AS IFC ON IFC.COSTID = '''+@MCOSTID+''' '
	   SELECT @QRY=@QRY+CHAR(13)+' INNER JOIN '+ @ADMINDB +'..COSTCENTRE AS ITC ON ITC.COSTID = '''+@MCOSTID+''' '
	   SELECT @QRY=@QRY+CHAR(13)+' LEFT JOIN '+ @ADMINDB +'..SUBITEMMAST AS SM ON SM.SUBITEMID = T.SUBITEMID AND SM.ITEMID=T.ITEMID'
       SELECT @QRY=@QRY+CHAR(13)+' INNER JOIN '+ @ADMINDB +'..ITEMCOUNTER AS CNT ON CNT.ITEMCTRID = T.ITEMCTRID '
       SELECT @QRY=@QRY+CHAR(13)+' WHERE 1=1 '
       SELECT @QRY=@QRY+CHAR(13)+' AND T.ISSDATE  BETWEEN '''+@FROMDATE+''' AND '''+@TODATE+'''  '
       SELECT @QRY=@QRY+CHAR(13)+' AND T.TOFLAG  =''MI'''
       SELECT @QRY=@QRY+CHAR(13)+' AND T.COSTID IN('''+@MCOSTID+''')'
       SELECT @QRY=@QRY+CHAR(13)+' AND T.TCOSTID IN('''+@MCOSTID+''')'
 		PRINT (@QRY)
		EXEC (@QRY)
        /* CREATE TABLE IN TEMPTABLE DB  TABLE NAME  TEMP_SYNCISSREC_NEW_SUM */ 
        SET @QRY = ''
        SET @QRY1= ''
        SELECT @QRY =CHAR(13)+''
        SELECT @QRY=@QRY+CHAR(13)+' IF OBJECT_ID(''TEMPTABLEDB..TEMP_SYNCISSREC_NEW_SUM'',''U'')IS NOT NULL DROP TABLE TEMPTABLEDB..TEMP_SYNCISSREC_NEW_SUM ' 
        SELECT @QRY=@QRY+CHAR(13)+' CREATE TABLE TEMPTABLEDB.. TEMP_SYNCISSREC_NEW_SUM(  [PARTICULAR] [VARCHAR](200) NULL,[COUNTERNAME] [VARCHAR](30) NULL,[DETAILS] [VARCHAR](40)  NULL'
        DECLARE RUNCUR_OID CURSOR
        FOR SELECT DISTINCT [ISSUED TO] COSTNAME,(SELECT  COSTID FROM  COSTCENTRE CT WHERE CT.COSTNAME = TEM.[ISSUED TO] ) COSTID FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT TEM ORDER BY [ISSUED TO]
        OPEN RUNCUR_OID
        FETCH NEXT FROM RUNCUR_OID INTO @COSTNAME,@COSTID
        WHILE @@FETCH_STATUS=0
        BEGIN 
        IF     @COSTID = @MCOSTID
        BEGIN              
        SELECT @QRY1=@QRY1+CHAR(13)+','+@COSTID+'OTPCS [int] NULL,'+@COSTID+'OTGRSWT [numeric](38, 3) NULL,'+@COSTID+'OTNETWT [numeric](38, 3) NULL'
        END
        ELSE
        BEGIN
        SELECT @QRY1=@QRY1+CHAR(13)+','+@COSTID+'PCS [int] NULL,'+@COSTID+'GRSWT [numeric](38, 3) NULL,'+@COSTID+'NETWT [numeric](38, 3) NULL'
        END
		FETCH NEXT FROM RUNCUR_OID INTO @COSTNAME,@COSTID
		END
        CLOSE RUNCUR_OID
        DEALLOCATE RUNCUR_OID
        SELECT @QRY=@QRY+@QRY1+CHAR(13)+' ,[TOTPCS] [int] NULL,[RESULT] [int] NULL,[ISSUED TO] [varchar](20) NULL,[TENTRY] [int]  NULL,[GROUP1] [varchar](200) NULL,[GROUP2] [varchar](200) NULL,[COLHEAD] [varchar](3) NULL)  ON [PRIMARY]'
 		PRINT (@QRY)
		EXEC (@QRY)
        /* INSERT TRANSFER TAGGED DETAILS*/
        SET @QRY = ''
        SET @QRY1= ''
        SELECT @QRY=CHAR(13)+'INSERT INTO [TEMPTABLEDB].[dbo].[TEMP_SYNCISSREC_NEW_SUM] ' 
        SELECT @QRY=@QRY+CHAR(13)+' SELECT PARTICULAR,COUNTERNAME ,''TAGGED ITEM'' DETAILS'
        DECLARE RUNCUR_TAGGED CURSOR
        FOR SELECT DISTINCT [ISSUED TO] COSTNAME,(SELECT  COSTID FROM  COSTCENTRE CT WHERE CT.COSTNAME = TEM.[ISSUED TO] ) COSTID FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT TEM ORDER BY [ISSUED TO]
        OPEN RUNCUR_TAGGED
        FETCH NEXT FROM RUNCUR_TAGGED INTO @COSTNAME,@COSTID
        WHILE @@FETCH_STATUS=0
        BEGIN  
        IF     @COSTID = @MCOSTID
        BEGIN
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(PCS) ELSE NULL END) '+@COSTID+'OTPCS '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(GRSWT) ELSE NULL END) '+@COSTID+'OTGRSWT '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(NETWT) ELSE NULL END) '+@COSTID+'OTNETWT '
        END
        ELSE
        BEGIN
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(PCS) ELSE NULL END) '+@COSTID+'PCS '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(GRSWT) ELSE NULL END) '+@COSTID+'GRSWT '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(NETWT) ELSE NULL END) '+@COSTID+'NETWT '
        END
		FETCH NEXT FROM RUNCUR_TAGGED INTO @COSTNAME,@COSTID
		END
        CLOSE RUNCUR_TAGGED
        DEALLOCATE RUNCUR_TAGGED
        SELECT @QRY=@QRY+@QRY1+CHAR(13)+'  , SUM(PCS) TOTPCS, RESULT,[ISSUED TO] ,1  TENTRY,GROUP1,GROUP2,COLHEAD FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT  WHERE ISNULL(TAGNO,'''') <> '''''
        SELECT @QRY=@QRY+CHAR(13)+' GROUP BY COUNTERNAME,RESULT,[ISSUED TO],GROUP1,GROUP2,COLHEAD,PARTICULAR'
 		PRINT (@QRY)
		EXEC (@QRY)
		/* INSERT TRANSFER NON TAGGED DETAILS*/
		SET @QRY = ''
        SET @QRY1= ''
        SELECT @QRY=CHAR(13)+'INSERT INTO [TEMPTABLEDB].[dbo].[TEMP_SYNCISSREC_NEW_SUM] ' 
        SELECT @QRY=@QRY+CHAR(13)+' SELECT PARTICULAR,COUNTERNAME ,''NON TAGGED ITEM'' DETAILS'
        DECLARE RUNCUR_NTAGGED CURSOR
        FOR SELECT DISTINCT [ISSUED TO] COSTNAME,(SELECT  COSTID FROM  COSTCENTRE CT WHERE CT.COSTNAME = TEM.[ISSUED TO] ) COSTID FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT TEM ORDER BY [ISSUED TO]
        OPEN RUNCUR_NTAGGED
        FETCH NEXT FROM RUNCUR_NTAGGED INTO @COSTNAME,@COSTID
        WHILE @@FETCH_STATUS=0
        BEGIN     
        IF     @COSTID = @MCOSTID
        BEGIN
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(PCS) ELSE NULL END) '+@COSTID+'OTPCS '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(GRSWT) ELSE NULL END) '+@COSTID+'OTGRSWT '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(NETWT) ELSE NULL END) '+@COSTID+'OTNETWT '
        END
        ELSE
        BEGIN
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(PCS) ELSE NULL END) '+@COSTID+'PCS '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(GRSWT) ELSE NULL END) '+@COSTID+'GRSWT '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(NETWT) ELSE NULL END) '+@COSTID+'NETWT '
        END
		FETCH NEXT FROM RUNCUR_NTAGGED INTO @COSTNAME,@COSTID
		END
        CLOSE RUNCUR_NTAGGED
        DEALLOCATE RUNCUR_NTAGGED
        SELECT @QRY=@QRY+@QRY1+CHAR(13)+'  , SUM(PCS) TOTPCS, RESULT,[ISSUED TO] ,4  TENTRY,GROUP1,GROUP2,COLHEAD FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT  WHERE ISNULL(TAGNO,'''') = '''''
        SELECT @QRY=@QRY+CHAR(13)+' GROUP BY COUNTERNAME,RESULT,[ISSUED TO],GROUP1,GROUP2,COLHEAD,PARTICULAR'
 		PRINT (@QRY)
		EXEC (@QRY)
		/* INSERT TRANSFER TAGGED STONE DETAILS*/
		SET @QRY = ''
        SET @QRY1= ''
        SELECT @QRY=CHAR(13)+'INSERT INTO [TEMPTABLEDB].[dbo].[TEMP_SYNCISSREC_NEW_SUM] ' 
        SELECT @QRY=@QRY+CHAR(13)+' SELECT PARTICULAR,COUNTERNAME ,''TAGGED STONE'' DETAILS'
        DECLARE RUNCUR_STAGGED CURSOR
        FOR SELECT DISTINCT [ISSUED TO] COSTNAME,(SELECT  COSTID FROM  COSTCENTRE CT WHERE CT.COSTNAME = TEM.[ISSUED TO] ) COSTID FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT TEM ORDER BY [ISSUED TO]
        OPEN RUNCUR_STAGGED
        FETCH NEXT FROM RUNCUR_STAGGED INTO @COSTNAME,@COSTID
        WHILE @@FETCH_STATUS=0
        BEGIN               
        IF     @COSTID = @MCOSTID
        BEGIN
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(STNPCS) ELSE NULL END) '+@COSTID+'OTPCS '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(STNWT)  ELSE NULL END) '+@COSTID+'OTGRSWT '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,NULL  '+@COSTID+'OTNETWT '
        END
        ELSE
        BEGIN
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(STNPCS) ELSE NULL END) '+@COSTID+'PCS '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(STNWT) ELSE NULL END) '+@COSTID+'GRSWT '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,NULL '+@COSTID+'NETWT '
        END
		FETCH NEXT FROM RUNCUR_STAGGED INTO @COSTNAME,@COSTID
		END
        CLOSE RUNCUR_STAGGED
        DEALLOCATE RUNCUR_STAGGED
        SELECT @QRY=@QRY+@QRY1+CHAR(13)+'  , SUM(STNPCS) TOTPCS, RESULT,[ISSUED TO] ,2  TENTRY,GROUP1,GROUP2,COLHEAD FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT  WHERE ISNULL(TAGNO,'''') <> '''''
        SELECT @QRY=@QRY+CHAR(13)+' GROUP BY COUNTERNAME,RESULT,[ISSUED TO],GROUP1,GROUP2,COLHEAD,PARTICULAR'
 		PRINT (@QRY)
		EXEC (@QRY)
		/* INSERT TRANSFER NON TAGGED STONE DETAILS*/
		SET @QRY = ''
        SET @QRY1= ''
        SELECT @QRY=CHAR(13)+'INSERT INTO [TEMPTABLEDB].[dbo].[TEMP_SYNCISSREC_NEW_SUM] ' 
        SELECT @QRY=@QRY+CHAR(13)+' SELECT PARTICULAR,COUNTERNAME ,''NON TAGGED STONE'' DETAILS'
        DECLARE RUNCUR_NSTAGGED CURSOR
        FOR SELECT DISTINCT [ISSUED TO] COSTNAME,(SELECT  COSTID FROM  COSTCENTRE CT WHERE CT.COSTNAME = TEM.[ISSUED TO] ) COSTID FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT TEM ORDER BY [ISSUED TO]
        OPEN RUNCUR_NSTAGGED
        FETCH NEXT FROM RUNCUR_NSTAGGED INTO @COSTNAME,@COSTID
        WHILE @@FETCH_STATUS=0
        BEGIN               
        IF     @COSTID = @MCOSTID
        BEGIN
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(STNPCS) ELSE NULL END) '+@COSTID+'OTPCS '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(STNWT) ELSE NULL END) '+@COSTID+'OTGRSWT '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,NULL  '+@COSTID+'OTNETWT '
        END
        ELSE
        BEGIN
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(STNPCS) ELSE NULL END) '+@COSTID+'PCS '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(STNWT) ELSE NULL END) '+@COSTID+'GRSWT '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,NULL '+@COSTID+'NETWT '
        END
		FETCH NEXT FROM RUNCUR_NSTAGGED INTO @COSTNAME,@COSTID
		END
        CLOSE RUNCUR_NSTAGGED
        DEALLOCATE RUNCUR_NSTAGGED
        SELECT @QRY=@QRY+@QRY1+CHAR(13)+'  , SUM(STNPCS) TOTPCS, RESULT,[ISSUED TO] ,5  TENTRY,GROUP1,GROUP2,COLHEAD FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT  WHERE ISNULL(TAGNO,'''') = '''''
        SELECT @QRY=@QRY+CHAR(13)+' GROUP BY COUNTERNAME,RESULT,[ISSUED TO],GROUP1,GROUP2,COLHEAD,PARTICULAR'
 		PRINT (@QRY)
		EXEC (@QRY)
		/* INSERT TRANSFER TAGGED DIAMOND DETAILS*/
		SET @QRY = ''
        SET @QRY1= ''
        SELECT @QRY=CHAR(13)+'INSERT INTO [TEMPTABLEDB].[dbo].[TEMP_SYNCISSREC_NEW_SUM] ' 
        SELECT @QRY=@QRY+CHAR(13)+' SELECT PARTICULAR,COUNTERNAME ,''TAGGED DIAMOND'' DETAILS'
        DECLARE RUNCUR_STAGGED CURSOR
        FOR SELECT DISTINCT [ISSUED TO] COSTNAME,(SELECT  COSTID FROM  COSTCENTRE CT WHERE CT.COSTNAME = TEM.[ISSUED TO] ) COSTID FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT TEM ORDER BY [ISSUED TO]
        OPEN RUNCUR_STAGGED
        FETCH NEXT FROM RUNCUR_STAGGED INTO @COSTNAME,@COSTID
        WHILE @@FETCH_STATUS=0
        BEGIN               
        IF     @COSTID = @MCOSTID
        BEGIN
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(DIAPCS) ELSE NULL END) '+@COSTID+'OTPCS '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(DIAWT)  ELSE NULL END) '+@COSTID+'OTGRSWT '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,NULL  '+@COSTID+'OTNETWT '
        END
        ELSE
        BEGIN
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(DIAPCS) ELSE NULL END) '+@COSTID+'PCS '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(DIAWT) ELSE NULL END) '+@COSTID+'GRSWT '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,NULL '+@COSTID+'NETWT '
        END
		FETCH NEXT FROM RUNCUR_STAGGED INTO @COSTNAME,@COSTID
		END
        CLOSE RUNCUR_STAGGED
        DEALLOCATE RUNCUR_STAGGED
        SELECT @QRY=@QRY+@QRY1+CHAR(13)+'  , SUM(DIAPCS) TOTPCS, RESULT,[ISSUED TO] ,3  TENTRY,GROUP1,GROUP2,COLHEAD FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT  WHERE ISNULL(TAGNO,'''') <> '''''
        SELECT @QRY=@QRY+CHAR(13)+' GROUP BY COUNTERNAME,RESULT,[ISSUED TO],GROUP1,GROUP2,COLHEAD,PARTICULAR'
 		PRINT (@QRY)
		EXEC (@QRY)
		/* INSERT TRANSFER NON TAGGED DIAMOND DETAILS*/
		SET @QRY = ''
        SET @QRY1= ''
        SELECT @QRY=CHAR(13)+'INSERT INTO [TEMPTABLEDB].[dbo].[TEMP_SYNCISSREC_NEW_SUM] ' 
        SELECT @QRY=@QRY+CHAR(13)+' SELECT PARTICULAR,COUNTERNAME ,''NON TAGGED DIAMOND'' DETAILS'
        DECLARE RUNCUR_NSTAGGED CURSOR
        FOR SELECT DISTINCT [ISSUED TO] COSTNAME,(SELECT  COSTID FROM  COSTCENTRE CT WHERE CT.COSTNAME = TEM.[ISSUED TO] ) COSTID FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT TEM ORDER BY [ISSUED TO]
        OPEN RUNCUR_NSTAGGED
        FETCH NEXT FROM RUNCUR_NSTAGGED INTO @COSTNAME,@COSTID
        WHILE @@FETCH_STATUS=0
        BEGIN               
        IF     @COSTID = @MCOSTID
        BEGIN
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(DIAPCS) ELSE NULL END) '+@COSTID+'OTPCS '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(DIAWT) ELSE NULL END) '+@COSTID+'OTGRSWT '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,NULL  '+@COSTID+'OTNETWT '
        END
        ELSE
        BEGIN
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(DIAPCS) ELSE NULL END) '+@COSTID+'PCS '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,(CASE WHEN [ISSUED TO] = '''+@COSTNAME+''' THEN SUM(DIAWT) ELSE NULL END) '+@COSTID+'GRSWT '
        SELECT @QRY1=@QRY1+CHAR(13)+' ,NULL '+@COSTID+'NETWT '
        END
		FETCH NEXT FROM RUNCUR_NSTAGGED INTO @COSTNAME,@COSTID
		END
        CLOSE RUNCUR_NSTAGGED
        DEALLOCATE RUNCUR_NSTAGGED
        SELECT @QRY=@QRY+@QRY1+CHAR(13)+'  , SUM(DIAPCS) TOTPCS, RESULT,[ISSUED TO] ,6  TENTRY,GROUP1,GROUP2,COLHEAD FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT  WHERE ISNULL(TAGNO,'''') = '''''
        SELECT @QRY=@QRY+CHAR(13)+' GROUP BY COUNTERNAME,RESULT,[ISSUED TO],GROUP1,GROUP2,COLHEAD,PARTICULAR'
 		PRINT (@QRY)
		EXEC (@QRY)
           /* CREATE TABLE [TEMP_SYNCISSREC_COUNTER_NON_SUM]  SELECTED TABLE  [TEMP_SYNCISSREC_NEW_SUM]*/
 		SET @QRY = ''
        SET @QRY1= ''
        SELECT @QRY =CHAR(13)+''
        SELECT @QRY=@QRY+CHAR(13)+' IF OBJECT_ID(''TEMPTABLEDB..TEMP_SYNCISSREC_COUNTER_NON_SUM'',''U'')IS NOT NULL DROP TABLE TEMPTABLEDB..TEMP_SYNCISSREC_COUNTER_NON_SUM ' 
        SELECT @QRY=@QRY+CHAR(13)+' SELECT PARTICULAR,COUNTERNAME , DETAILS'
        DECLARE RUNCUR_NSTAGGED CURSOR
        FOR SELECT DISTINCT [ISSUED TO] COSTNAME,(SELECT  COSTID FROM  COSTCENTRE CT WHERE CT.COSTNAME = TEM.[ISSUED TO] ) COSTID FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT TEM ORDER BY [ISSUED TO]
        OPEN RUNCUR_NSTAGGED
        FETCH NEXT FROM RUNCUR_NSTAGGED INTO @COSTNAME,@COSTID
        WHILE @@FETCH_STATUS=0
        BEGIN  
        IF  @COSTID = @MCOSTID
        BEGIN
        SELECT @QRY1=@QRY1+CHAR(13)+' , SUM('+@COSTID+'OTPCS)  '+@COSTID+'OTPCS , SUM('+@COSTID+'OTGRSWT)  '+@COSTID+'OTGRSWT , SUM('+@COSTID+'OTNETWT)  '+@COSTID+'OTNETWT'
        END
        ELSE
        BEGIN 
        SELECT @QRY1=@QRY1+CHAR(13)+' , SUM('+@COSTID+'PCS)  '+@COSTID+'PCS , SUM('+@COSTID+'GRSWT)  '+@COSTID+'GRSWT , SUM('+@COSTID+'NETWT)  '+@COSTID+'NETWT'
        END
        FETCH NEXT FROM RUNCUR_NSTAGGED INTO @COSTNAME,@COSTID
		END
        CLOSE RUNCUR_NSTAGGED
        DEALLOCATE RUNCUR_NSTAGGED
        SELECT @QRY=@QRY+@QRY1+CHAR(13)+'  ,SUM(TOTPCS) TOTPCS ,GROUP1,GROUP2,COLHEAD,1 RESULT   '
        SELECT @QRY=@QRY+CHAR(13)+' INTO TEMPTABLEDB..[TEMP_SYNCISSREC_COUNTER_NON_SUM] FROM TEMPTABLEDB..TEMP_SYNCISSREC_NEW_SUM ' 
        SELECT @QRY=@QRY+CHAR(13)+' GROUP BY COUNTERNAME,RESULT,TENTRY,DETAILS ,GROUP1,GROUP2,COLHEAD,PARTICULAR'
        /* UPDATE PARTICULAR ,GROUP1 ,GROUP2 COLUMNS IN [TEMP_SYNCISSREC_COUNTER_NON_SUM] TABLES*/
        SELECT @QRY=@QRY+CHAR(13)+' UPDATE TEMPTABLEDB..TEMP_SYNCISSREC_COUNTER_NON_SUM SET PARTICULAR = '''',GROUP1 = '''' ,GROUP2 = '' ''+COUNTERNAME '
 		PRINT (@QRY)
		EXEC (@QRY)
      IF (SELECT COUNT(*) FROM TEMPTABLEDB..TEMP_SYNCISSREC_COUNTER_NON_SUM)>0
      BEGIN
        SELECT @QRY=CHAR(13)+'INSERT INTO TEMPTABLEDB..TEMP_SYNCISSREC_COUNTER_NON_SUM(PARTICULAR,GROUP1,COLHEAD,RESULT,DETAILS)'
        SELECT @QRY=@QRY+CHAR(13)+'SELECT DISTINCT GROUP1,GROUP1,''T'',0,'''' RESULT FROM TEMPTABLEDB..TEMP_SYNCISSREC_COUNTER_NON_SUM WHERE RESULT = 1'
        SELECT @QRY=@QRY+CHAR(13)+'INSERT INTO TEMPTABLEDB..TEMP_SYNCISSREC_COUNTER_NON_SUM(PARTICULAR,GROUP1,GROUP2,COLHEAD,RESULT,DETAILS)'
        SELECT @QRY=@QRY+CHAR(13)+'SELECT DISTINCT GROUP2,GROUP1,GROUP2,''T1'',0,'''' RESULT FROM TEMPTABLEDB..TEMP_SYNCISSREC_COUNTER_NON_SUM WHERE RESULT = 1'  
        PRINT (@QRY)
		EXEC (@QRY)    
        SET @QRY = ''
        SET @QRY1= ''
        SELECT @QRY=CHAR(13)+'INSERT INTO TEMPTABLEDB..TEMP_SYNCISSREC_COUNTER_NON_SUM(PARTICULAR,GROUP1,GROUP2,COLHEAD,RESULT ' 
        DECLARE RUNCUR_TAGGED CURSOR
        FOR SELECT DISTINCT [ISSUED TO] COSTNAME,(SELECT  COSTID FROM  COSTCENTRE CT WHERE CT.COSTNAME = TEM.[ISSUED TO] ) COSTID FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT TEM ORDER BY [ISSUED TO]
        OPEN RUNCUR_TAGGED
        FETCH NEXT FROM RUNCUR_TAGGED INTO @COSTNAME,@COSTID
        WHILE @@FETCH_STATUS=0
        BEGIN 
        IF  @COSTID = @MCOSTID    
        SELECT @QRY1=@QRY1+CHAR(13)+' , '+@COSTID+'OTPCS , '+@COSTID+'OTGRSWT  ,'+@COSTID+'OTNETWT '
        ELSE
        SELECT @QRY1=@QRY1+CHAR(13)+' , '+@COSTID+'PCS , '+@COSTID+'GRSWT  ,'+@COSTID+'NETWT '
		FETCH NEXT FROM RUNCUR_TAGGED INTO @COSTNAME,@COSTID
		END
        CLOSE RUNCUR_TAGGED
        DEALLOCATE RUNCUR_TAGGED
        SELECT @QRY=@QRY+@QRY1+CHAR(13)+' ,DETAILS,TOTPCS)'
        SET @QRY1 =''
        SELECT @QRY=@QRY+CHAR(13)+'SELECT GROUP2 + '' TOTAL'',GROUP1,GROUP2,''S1'',2 RESULT'
        DECLARE RUNCUR_TAGGED CURSOR
        FOR SELECT DISTINCT [ISSUED TO] COSTNAME,(SELECT  COSTID FROM  COSTCENTRE CT WHERE CT.COSTNAME = TEM.[ISSUED TO] ) COSTID FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT TEM ORDER BY [ISSUED TO]
        OPEN RUNCUR_TAGGED
        FETCH NEXT FROM RUNCUR_TAGGED INTO @COSTNAME,@COSTID
        WHILE @@FETCH_STATUS=0
        BEGIN  
        IF  @COSTID = @MCOSTID            
        SELECT @QRY1=@QRY1+CHAR(13)+' , SUM('+@COSTID+'OTPCS)  '+@COSTID+'OTPCS , SUM('+@COSTID+'OTGRSWT)  '+@COSTID+'OTGRSWT , SUM('+@COSTID+'OTNETWT)  '+@COSTID+'OTNETWT'
        ELSE
        SELECT @QRY1=@QRY1+CHAR(13)+' , SUM('+@COSTID+'PCS)  '+@COSTID+'PCS , SUM('+@COSTID+'GRSWT)  '+@COSTID+'GRSWT , SUM('+@COSTID+'NETWT)  '+@COSTID+'NETWT'
		FETCH NEXT FROM RUNCUR_TAGGED INTO @COSTNAME,@COSTID
		END
        CLOSE RUNCUR_TAGGED
        DEALLOCATE RUNCUR_TAGGED
        SELECT @QRY=@QRY+@QRY1+CHAR(13)+' ,'''',SUM(TOTPCS) FROM TEMPTABLEDB..TEMP_SYNCISSREC_COUNTER_NON_SUM WHERE RESULT = 1 AND DETAILS NOT IN (''TAGGED STONE'',''NON TAGGED STONE'',''TAGGED DIAMOND'',''NON TAGGED DIAMOND'') GROUP BY GROUP2,GROUP1 '
 		PRINT (@QRY)
 		EXEC (@QRY)
        SET @QRY = ''
        SET @QRY1= ''
        SELECT @QRY=CHAR(13)+'INSERT INTO TEMPTABLEDB..TEMP_SYNCISSREC_COUNTER_NON_SUM(PARTICULAR,GROUP1,GROUP2,COLHEAD,RESULT ' 
        DECLARE RUNCUR_TAGGED CURSOR
        FOR SELECT DISTINCT [ISSUED TO] COSTNAME,(SELECT  COSTID FROM COSTCENTRE CT WHERE CT.COSTNAME = TEM.[ISSUED TO] ) COSTID FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT TEM ORDER BY [ISSUED TO]
        OPEN RUNCUR_TAGGED
        FETCH NEXT FROM RUNCUR_TAGGED INTO @COSTNAME,@COSTID
        WHILE @@FETCH_STATUS=0
        BEGIN               
        IF  @COSTID = @MCOSTID    
        SELECT @QRY1=@QRY1+CHAR(13)+' , '+@COSTID+'OTPCS , '+@COSTID+'OTGRSWT  ,'+@COSTID+'OTNETWT '
        ELSE
        SELECT @QRY1=@QRY1+CHAR(13)+' , '+@COSTID+'PCS , '+@COSTID+'GRSWT  ,'+@COSTID+'NETWT '
		FETCH NEXT FROM RUNCUR_TAGGED INTO @COSTNAME,@COSTID
		END
        CLOSE RUNCUR_TAGGED
        DEALLOCATE RUNCUR_TAGGED
        SELECT @QRY=@QRY+@QRY1+CHAR(13)+' ,DETAILS,TOTPCS)'
        SELECT @QRY=@QRY+CHAR(13)+'SELECT ''GRAND TOTAL'',''ZZZZ''GROUP1,''ZZZ''GROUP2,''G'',3 RESULT'
        SET @QRY1 =''
        DECLARE RUNCUR_TAGGED CURSOR
        FOR SELECT DISTINCT [ISSUED TO] COSTNAME,(SELECT  COSTID FROM  COSTCENTRE CT WHERE CT.COSTNAME = TEM.[ISSUED TO] ) COSTID FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT TEM ORDER BY [ISSUED TO]
        OPEN RUNCUR_TAGGED
        FETCH NEXT FROM RUNCUR_TAGGED INTO @COSTNAME,@COSTID
        WHILE @@FETCH_STATUS=0
        BEGIN         
        IF  @COSTID = @MCOSTID            
        SELECT @QRY1=@QRY1+CHAR(13)+' , SUM('+@COSTID+'OTPCS)  '+@COSTID+'OTPCS , SUM('+@COSTID+'OTGRSWT)  '+@COSTID+'OTGRSWT , SUM('+@COSTID+'OTNETWT)  '+@COSTID+'OTNETWT'
        ELSE
        SELECT @QRY1=@QRY1+CHAR(13)+' , SUM('+@COSTID+'PCS)  '+@COSTID+'PCS , SUM('+@COSTID+'GRSWT)  '+@COSTID+'GRSWT , SUM('+@COSTID+'NETWT)  '+@COSTID+'NETWT'
		FETCH NEXT FROM RUNCUR_TAGGED INTO @COSTNAME,@COSTID
		END
        CLOSE RUNCUR_TAGGED
        DEALLOCATE RUNCUR_TAGGED
        SELECT @QRY=@QRY+@QRY1+CHAR(13)+' ,'''',SUM(TOTPCS) FROM TEMPTABLEDB..TEMP_SYNCISSREC_COUNTER_NON_SUM WHERE RESULT = 1 AND DETAILS NOT IN (''TAGGED STONE'',''NON TAGGED STONE'',''TAGGED DIAMOND'',''NON TAGGED DIAMOND'') '
        PRINT (@QRY)
		EXEC (@QRY)
        SET @QRY = ''
        SET @QRY1= ''
        SELECT @QRY=CHAR(13)+'INSERT INTO TEMPTABLEDB..TEMP_SYNCISSREC_COUNTER_NON_SUM(PARTICULAR,GROUP1,GROUP2,COLHEAD,RESULT ' 
        DECLARE RUNCUR_TAGGED CURSOR
        FOR SELECT DISTINCT [ISSUED TO] COSTNAME,(SELECT  COSTID FROM COSTCENTRE CT WHERE CT.COSTNAME = TEM.[ISSUED TO] ) COSTID FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT TEM ORDER BY [ISSUED TO]
        OPEN RUNCUR_TAGGED
        FETCH NEXT FROM RUNCUR_TAGGED INTO @COSTNAME,@COSTID
        WHILE @@FETCH_STATUS=0
        BEGIN               
        IF  @COSTID = @MCOSTID    
        SELECT @QRY1=@QRY1+CHAR(13)+' , '+@COSTID+'OTPCS , '+@COSTID+'OTGRSWT  ,'+@COSTID+'OTNETWT '
        ELSE
        SELECT @QRY1=@QRY1+CHAR(13)+' , '+@COSTID+'PCS , '+@COSTID+'GRSWT  ,'+@COSTID+'NETWT '
		FETCH NEXT FROM RUNCUR_TAGGED INTO @COSTNAME,@COSTID
		END
        CLOSE RUNCUR_TAGGED
        DEALLOCATE RUNCUR_TAGGED
        SELECT @QRY=@QRY+@QRY1+CHAR(13)+' ,DETAILS,TOTPCS)'
        SELECT @QRY=@QRY+CHAR(13)+'SELECT ''GRAND TOTAL [STONE]'',''ZZZZ''GROUP1,''ZZZ''GROUP2,''G'',4 RESULT'
        SET @QRY1 =''
        DECLARE RUNCUR_TAGGED CURSOR
        FOR SELECT DISTINCT [ISSUED TO] COSTNAME,(SELECT  COSTID FROM  COSTCENTRE CT WHERE CT.COSTNAME = TEM.[ISSUED TO] ) COSTID FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT TEM ORDER BY [ISSUED TO]
        OPEN RUNCUR_TAGGED
        FETCH NEXT FROM RUNCUR_TAGGED INTO @COSTNAME,@COSTID
        WHILE @@FETCH_STATUS=0
        BEGIN         
        IF  @COSTID = @MCOSTID            
        SELECT @QRY1=@QRY1+CHAR(13)+' , SUM('+@COSTID+'OTPCS)  '+@COSTID+'OTPCS , SUM('+@COSTID+'OTGRSWT)  '+@COSTID+'OTGRSWT , SUM('+@COSTID+'OTNETWT)  '+@COSTID+'OTNETWT'
        ELSE
        SELECT @QRY1=@QRY1+CHAR(13)+' , SUM('+@COSTID+'PCS)  '+@COSTID+'PCS , SUM('+@COSTID+'GRSWT)  '+@COSTID+'GRSWT , SUM('+@COSTID+'NETWT)  '+@COSTID+'NETWT'
		FETCH NEXT FROM RUNCUR_TAGGED INTO @COSTNAME,@COSTID
		END
        CLOSE RUNCUR_TAGGED
        DEALLOCATE RUNCUR_TAGGED
        SELECT @QRY=@QRY+@QRY1+CHAR(13)+' ,'''',SUM(TOTPCS) FROM TEMPTABLEDB..TEMP_SYNCISSREC_COUNTER_NON_SUM WHERE RESULT = 1 AND DETAILS  IN (''TAGGED STONE'',''NON TAGGED STONE'') '
        PRINT (@QRY)
		EXEC (@QRY)
        SET @QRY = ''
        SET @QRY1= ''
        SELECT @QRY=CHAR(13)+'INSERT INTO TEMPTABLEDB..TEMP_SYNCISSREC_COUNTER_NON_SUM(PARTICULAR,GROUP1,GROUP2,COLHEAD,RESULT ' 
        DECLARE RUNCUR_TAGGED CURSOR
        FOR SELECT DISTINCT [ISSUED TO] COSTNAME,(SELECT  COSTID FROM COSTCENTRE CT WHERE CT.COSTNAME = TEM.[ISSUED TO] ) COSTID FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT TEM ORDER BY [ISSUED TO]
        OPEN RUNCUR_TAGGED
        FETCH NEXT FROM RUNCUR_TAGGED INTO @COSTNAME,@COSTID
        WHILE @@FETCH_STATUS=0
        BEGIN               
        IF  @COSTID = @MCOSTID    
        SELECT @QRY1=@QRY1+CHAR(13)+' , '+@COSTID+'OTPCS , '+@COSTID+'OTGRSWT  ,'+@COSTID+'OTNETWT '
        ELSE
        SELECT @QRY1=@QRY1+CHAR(13)+' , '+@COSTID+'PCS , '+@COSTID+'GRSWT  ,'+@COSTID+'NETWT '
		FETCH NEXT FROM RUNCUR_TAGGED INTO @COSTNAME,@COSTID
		END
        CLOSE RUNCUR_TAGGED
        DEALLOCATE RUNCUR_TAGGED
        SELECT @QRY=@QRY+@QRY1+CHAR(13)+' ,DETAILS,TOTPCS)'
        SELECT @QRY=@QRY+CHAR(13)+'SELECT ''GRAND TOTAL [DIAMOND]'',''ZZZZ''GROUP1,''ZZZ''GROUP2,''G'',5 RESULT'
        SET @QRY1 =''
        DECLARE RUNCUR_TAGGED CURSOR
        FOR SELECT DISTINCT [ISSUED TO] COSTNAME,(SELECT  COSTID FROM  COSTCENTRE CT WHERE CT.COSTNAME = TEM.[ISSUED TO] ) COSTID FROM TEMPTABLEDB..TEMP_SYNCISSREC_TR_OT TEM ORDER BY [ISSUED TO]
        OPEN RUNCUR_TAGGED
        FETCH NEXT FROM RUNCUR_TAGGED INTO @COSTNAME,@COSTID
        WHILE @@FETCH_STATUS=0
        BEGIN         
        IF  @COSTID = @MCOSTID            
        SELECT @QRY1=@QRY1+CHAR(13)+' , SUM('+@COSTID+'OTPCS)  '+@COSTID+'OTPCS , SUM('+@COSTID+'OTGRSWT)  '+@COSTID+'OTGRSWT , SUM('+@COSTID+'OTNETWT)  '+@COSTID+'OTNETWT'
        ELSE
        SELECT @QRY1=@QRY1+CHAR(13)+' , SUM('+@COSTID+'PCS)  '+@COSTID+'PCS , SUM('+@COSTID+'GRSWT)  '+@COSTID+'GRSWT , SUM('+@COSTID+'NETWT)  '+@COSTID+'NETWT'
		FETCH NEXT FROM RUNCUR_TAGGED INTO @COSTNAME,@COSTID
		END
        CLOSE RUNCUR_TAGGED
        DEALLOCATE RUNCUR_TAGGED
        SELECT @QRY=@QRY+@QRY1+CHAR(13)+' ,'''',SUM(TOTPCS) FROM TEMPTABLEDB..TEMP_SYNCISSREC_COUNTER_NON_SUM WHERE RESULT = 1 AND DETAILS  IN (''TAGGED DIAMOND'',''NON TAGGED DIAMOND'') '       
        PRINT (@QRY)
		EXEC (@QRY)
 END
END
