CREATE TABLE PURCHASEORDER (
	ITEMID INT
	,SUBITEMID INT
	,PARTICULAR NVARCHAR(100)
	,PO_PIECES INT
	,TAGCOMPLETE BIT
	,POFROMDATE DATE
	,POTODATE DATE
	,USERID INT
	,PONUMBER NVARCHAR(100)
	,PODATE DATE
	,TRANFLAG BIT
	,TRANDATE DATE
	)

CREATE TYPE PurchaseOrderTableType AS TABLE (
	PARTICULAR NVARCHAR(100)
	,ITEM NVARCHAR(100)
	,PO_PIECES INT
	,RESULT INT
	)

Create PROCEDURE UpdatePurchaseOrder @USERID INT
	,@POFromDate DATE
	,@POToDate DATE
	,@PurchaseOrderData PurchaseOrderTableType READONLY
AS
BEGIN
	UPDATE c
	SET PO_PIECES = a.PO_PIECES
	FROM @PurchaseOrderData a
	JOIN ITEMMAST b ON b.ITEMNAME = a.ITEM
	JOIN PURCHASEORDER c ON c.ITEMID = b.ITEMID
		AND c.PARTICULAR = a.PARTICULAR
	WHERE 1 = 1
		AND c.POFROMDATE = @POFromDate
		AND c.POTODATE = @POToDate

	INSERT INTO PURCHASEORDER (
		ITEMID
		,PARTICULAR
		,PO_PIECES
		,POFROMDATE
		,POTODATE
		,USERID
		,SUBITEMID
		)
	SELECT b.ITEMID
		,a.PARTICULAR
		,a.PO_PIECES
		,@POFromDate
		,@POToDate
		,@USERID
		,D.SUBITEMID
	FROM @PurchaseOrderData a
	JOIN ITEMMAST b ON b.ITEMNAME = a.ITEM
	LEFT JOIN SUBITEMMAST D ON D.SUBITEMNAME = RIGHT(A.PARTICULAR, CHARINDEX('-', REVERSE(A.PARTICULAR)) - 1)
	LEFT JOIN PURCHASEORDER c ON c.ITEMID = b.ITEMID
		AND c.PARTICULAR = a.PARTICULAR
		AND c.POFROMDATE = @POFromDate
		AND c.POTODATE = @POToDate
	WHERE 1 = 1
		AND isnull(c.PARTICULAR, '') = ''
END

CREATE TYPE MergePurchaseOrderTableType AS TABLE (
	MARK BIT
	,ITEM NVARCHAR(100)
	,PARTICULAR NVARCHAR(100)
	,PO_PIECES INT
	,POSTINGFROM DATE
	,POSTINGTO DATE
	,PONUMBER NVARCHAR(100)
	,PODATE DATE
	,[TRANS DATE] DATE
	)

CREATE PROCEDURE MergePurchaseOrder @USERID INT
	,@MergePurchaseOrderData MergePurchaseOrderTableType READONLY
AS
BEGIN
	IF OBJECT_ID('TEMPDB..#MERGEPO') IS NOT NULL
		DROP TABLE #MERGEPO

	SELECT rank() OVER (
			ORDER BY particular
			) cnt
		,*
	INTO #MERGEPO
	FROM @MergePurchaseOrderData

	INSERT INTO PURCHASEORDER (
		ITEMID
		,PARTICULAR
		,PO_PIECES
		,POFROMDATE
		,POTODATE
		,PONUMBER
		,USERID
		,SUBITEMID
		)
	SELECT LEFT(CAST(ITEM AS NVARCHAR(100)), CHARINDEX('-', CAST(ITEM AS NVARCHAR(100))) - 1) AS ITEM
		,PARTICULAR
		,sum(po_pieces) po_pieces
		,min(postingfrom) postingfrom
		,max(postingto) postingto
		,'RTM'
		,@USERID
		,B.SUBITEMID
	FROM #MERGEPO A
	LEFT JOIN SUBITEMMAST B ON B.SUBITEMNAME = RIGHT(A.PARTICULAR, CHARINDEX('-', REVERSE(A.PARTICULAR)) - 1)
	GROUP BY A.ITEM
		,A.PARTICULAR
		,B.SUBITEMID
	HAVING count(cnt) > 1

	DELETE c
	FROM #MERGEPO a
	JOIN (
		SELECT cnt
		FROM #MERGEPO
		GROUP BY cnt
		HAVING count(cnt) > 1
		) b ON a.cnt = b.cnt
	JOIN PURCHASEORDER c ON c.ITEMID = LEFT(CAST(a.ITEM AS NVARCHAR(100)), CHARINDEX('-', CAST(a.ITEM AS NVARCHAR(100))) - 1)
		AND c.PARTICULAR = a.PARTICULAR
		AND c.POFROMDATE = a.POSTINGFROM
		AND c.POTODATE = a.POSTINGTO
		AND c.PONUMBER = a.PONUMBER
END

create TYPE PurchaseOrderTransferTableType AS TABLE (
	ITEMID INT
	,PARTICULAR NVARCHAR(100)
	,PO_PIECES INT
	,POFROMDATE DATE
	,POTODATE DATE
	,USERID INT
	,PONUMBER NVARCHAR(100)
	,PODATE DATE
	,SUBITEMID INT
	)

Create PROCEDURE TransferPurchaseOrder @TranFlag BIT
	,@Trandate DATE
	,@PurchaseOrderTransferData PurchaseOrderTransferTableType READONLY
AS
BEGIN
	INSERT INTO PURCHASEORDER (
		ITEMID
		,PARTICULAR
		,PO_PIECES
		,POFROMDATE
		,POTODATE
		,USERID
		,PONUMBER
		,PODATE
		,TRANFLAG
		,TRANDATE
		,SUBITEMID
		)
	SELECT ITEMID
		,PARTICULAR
		,PO_PIECES
		,POFROMDATE
		,POTODATE
		,USERID
		,PONUMBER
		,PODATE
		,@TranFlag
		,@Trandate
		,SUBITEMID
	FROM @PurchaseOrderTransferData
END

alter table ITEMLOT add PONUMBER nvarchar(200)
