CREATE TABLE [dbo].[QCRECEIPT](
	[SNO] [varchar](15) NULL,
	[TRANNO] [int] NULL,
	[TRANDATE] [smalldatetime] NULL,
	[TRANTYPE] [varchar](3) NULL,
	[PCS] [int] NULL,
	[GRSWT] [numeric](12, 3) NULL,
	[NETWT] [numeric](12, 3) NULL,
	[LESSWT] [numeric](12, 3) NULL,
	[PUREWT] [numeric](12, 3) NULL,
	[ITEMID] [int] NULL,
	[SUBITEMID] [int] NULL,
	[AMOUNT] [numeric](15, 2) NULL,
	[RATE] [numeric](15, 4) NULL,
	[BOARDRATE] [numeric](15, 2) NULL,
	[RETURNSTATUS] [varchar](1) NULL,
	[COSTID] [varchar](2) NULL,
	[COMPANYID] [varchar](3) NULL,
	[FLAG] [varchar](1) NULL,
	[EMPID] [int] NULL,
	[PURITY] [numeric](15, 2) NULL,
	[CATCODE] [varchar](5) NULL,
	[OCATCODE] [varchar](5) NULL,
	[ACCODE] [varchar](7) NULL,
	[BATCHNO] [varchar](15) NULL,
	[REMARK1] [varchar](50) NULL,
	[REMARK2] [varchar](50) NULL,
	[USERID] [int] NULL,
	[UPDATED] [smalldatetime] NULL,
	[UPTIME] [smalldatetime] NULL,
	[SYSTEMID] [varchar](3) NULL,
	[CANCEL] [varchar](1) NULL,
	[CASHID] [varchar](6) NULL,
	[METALID] [varchar](1) NULL,
	[HALLMARKID] [int] NULL,
	[HMEMPID] [int] NULL
)

CREATE TABLE [dbo].[QCISSUE](
	[SNO] [varchar](15) NULL,
	[TRANNO] [int] NULL,
	[TRANDATE] [smalldatetime] NULL,
	[TRANTYPE] [varchar](3) NULL,
	[PCS] [int] NULL,
	[GRSWT] [numeric](12, 3) NULL,
	[NETWT] [numeric](12, 3) NULL,
	[LESSWT] [numeric](12, 3) NULL,
	[PUREWT] [numeric](12, 3) NULL,
	[ITEMID] [int] NULL,
	[SUBITEMID] [int] NULL,
	[AMOUNT] [numeric](15, 2) NULL,
	[RATE] [numeric](15, 4) NULL,
	[BOARDRATE] [numeric](15, 2) NULL,
	[RETURNSTATUS] [varchar](1) NULL,
	[COSTID] [varchar](2) NULL,
	[COMPANYID] [varchar](3) NULL,
	[FLAG] [varchar](1) NULL,
	[EMPID] [int] NULL,
	[PURITY] [numeric](15, 2) NULL,
	[CATCODE] [varchar](5) NULL,
	[OCATCODE] [varchar](5) NULL,
	[ACCODE] [varchar](7) NULL,
	[BATCHNO] [varchar](15) NULL,
	[REMARK1] [varchar](50) NULL,
	[REMARK2] [varchar](50) NULL,
	[USERID] [int] NULL,
	[UPDATED] [smalldatetime] NULL,
	[UPTIME] [smalldatetime] NULL,
	[SYSTEMID] [varchar](3) NULL,
	[CANCEL] [varchar](1) NULL,
	[CASHID] [varchar](6) NULL,
	[METALID] [varchar](1) NULL,
	[HALLMARKID] [int] NULL,
	[HMEMPID] [int] NULL
)

CREATE TABLE [dbo].[HALLMARK](
	[HALLMARKID] [int] NULL,
	[HALLMARKNAME] [varchar](30) NOT NULL,
	[SEAL] [varchar](15) NULL,
	[ACTIVE] [varchar](1) NULL,
	[USERID] [int] NULL,
	[UPDATED] [smalldatetime] NULL,
	[UPTIME] [smalldatetime] NULL,
	[ACCODE] [varchar](7) NULL
	)

--ALTER TABLE [QCRECEIPT] ADD [HALLMARKID] [int] NULL,[HMEMPID] [int] NULL
--ALTER TABLE [QCISSUE] ADD [HALLMARKID] [int] NULL,[HMEMPID] [int] NULL
