--sp_helptext RPT_ITEMWISE_NEW

 ALTER PROCEDURE RPT_ITEMWISE_NEW
 (
 @DBNAME VARCHAR(20)
 ,@FROMDATE VARCHAR(20)
 ,@TODATE VARCHAR(20)
 ,@COSTID VARCHAR(100)
 ,@COMPANYID VARCHAR(100)
 ,@SUMMARY VARCHAR(1)
 ,@METALID VARCHAR(10)
 )
 AS
 BEGIN
 	DECLARE @QRY VARCHAR(8000)
 	IF @COSTID<>'ALL'SET @COSTID= REPLACE(@COSTID,',',''',''')    
 	IF @COMPANYID<>'ALL'SET @COMPANYID= REPLACE(@COMPANYID,',',''',''')    
 	SELECT @QRY='IF OBJECT_ID(''TEMPTABLEDB..TEMPISSUE'',''U'')IS NOT NULL DROP TABLE TEMPTABLEDB..TEMPISSUE'
 	EXEC(@QRY)
 	IF @SUMMARY='N'
 	BEGIN
 		SELECT @QRY='SELECT '
 		SELECT @QRY=@QRY+CHAR(13)+' CONVERT(VARCHAR(400),CASE WHEN SM.SUBITEMNAME IS NOT NULL THEN SM.SUBITEMNAME ELSE IM.ITEMNAME END) AS PARTICULAR '
 		SELECT @QRY=@QRY+CHAR(13)+' ,I.TRANNO,I.TRANDATE,I.TAGNO'
 		SELECT @QRY=@QRY+CHAR(13)+' ,I.PCS,I.GRSWT'
 		SELECT @QRY=@QRY+CHAR(13)+' ,I.NETWT'
 		SELECT @QRY=@QRY+CHAR(13)+' ,CASE WHEN I.TRANTYPE=''MI'' THEN 0 ELSE I.AMOUNT END AMOUNT '
 		SELECT @QRY=@QRY+CHAR(13)+' ,CASE WHEN ISNULL(CO.ITEMCTRNAME,'''')='''' THEN ''NO COUNTER'' ELSE CONVERT(VARCHAR(100),CO.ITEMCTRNAME) END AS COUNTER '
 		SELECT @QRY=@QRY+CHAR(13)+' ,CONVERT(VARCHAR,(SELECT EMPNAME FROM  EMPMASTER WHERE EMPID = I.EMPID))AS EMPNAME'
		SELECT @QRY=@QRY+CHAR(13)+' ,DESIGNER.DESIGNERNAME'
 		SELECT @QRY=@QRY+CHAR(13)+' ,IM.ITEMNAME'
 		SELECT @QRY=@QRY+CHAR(13)+' ,''SALES''AS TYPE'
 		SELECT @QRY=@QRY+CHAR(13)+' ,3 AS RESULT'
 		SELECT @QRY=@QRY+CHAR(13)+' ,''  '' AS COLHEAD'
 		SELECT @QRY=@QRY+CHAR(13)+' INTO TEMPTABLEDB..TEMPISSUE'
 		SELECT @QRY=@QRY+CHAR(13)+' FROM '+@DBNAME+'..ISSUE AS I '
 		SELECT @QRY=@QRY+CHAR(13)+' INNER JOIN  ITEMMAST IM ON IM.ITEMID = I.ITEMID '
 		SELECT @QRY=@QRY+CHAR(13)+' LEFT OUTER JOIN  SUBITEMMAST AS SM ON SM.ITEMID = I.ITEMID AND SM.SUBITEMID = I.SUBITEMID '
 		SELECT @QRY=@QRY+CHAR(13)+' LEFT OUTER JOIN  ITEMCOUNTER AS CO ON CO.ITEMCTRID = I.ITEMCTRID '
 		SELECT @QRY=@QRY+CHAR(13)+' LEFT OUTER JOIN  ITEMTAG AS T ON T.TAGNO = I.TAGNO AND T.ITEMID = I.ITEMID AND T.BATCHNO = I.BATCHNO '
		SELECT @QRY=@QRY+CHAR(13)+' LEFT OUTER JOIN  DESIGNER ON T.DESIGNERID = DESIGNER.DESIGNERID '
 		SELECT @QRY=@QRY+CHAR(13)+' WHERE I.TRANDATE BETWEEN '''+@FROMDATE+''' AND '''+@TODATE+''' '
 		SELECT @QRY=@QRY+CHAR(13)+' AND I.TRANTYPE IN (''SA'',''OD'') '
 		IF @COSTID<>'ALL' SELECT  @QRY=@QRY+' AND I.COSTID IN('''+ @COSTID +''')'    
 		IF @COMPANYID<>'ALL' SELECT  @QRY=@QRY+' AND I.COMPANYID IN('''+ @COMPANYID +''')'    
 		SELECT @QRY=@QRY+CHAR(13)+' AND ISNULL(I.CANCEL,'''') = '''' '
		SELECT @QRY=@QRY+CHAR(13)+ 'AND (''' + @METALID + ''' = ''ALL'' OR IM.METALID = ''' + @METALID + ''')'
 		SELECT @QRY=@QRY+CHAR(13)+' UNION ALL'
 		SELECT @QRY=@QRY+CHAR(13)+' SELECT '
 		SELECT @QRY=@QRY+CHAR(13)+' CONVERT(VARCHAR(400),CASE WHEN SM.SUBITEMNAME IS NOT NULL THEN SM.SUBITEMNAME ELSE IM.ITEMNAME END) AS PARTICULAR '
 		SELECT @QRY=@QRY+CHAR(13)+' ,NULL TRANNO,I.TRANDATE'
 		SELECT @QRY=@QRY+CHAR(13)+' ,(SELECT TAGNO FROM ITEMTAG WHERE SNO=I.TAGSNO)TAGNO'
 		SELECT @QRY=@QRY+CHAR(13)+' ,(SELECT SUM(PCS) FROM ITEMTAG WHERE SNO=I.TAGSNO)PCS'
 		SELECT @QRY=@QRY+CHAR(13)+' ,(SELECT SUM(GRSWT) FROM ITEMTAG WHERE SNO=I.TAGSNO)GRSWT'
 		SELECT @QRY=@QRY+CHAR(13)+' ,(SELECT SUM(NETWT) FROM ITEMTAG WHERE SNO=I.TAGSNO)NETWT'
 		SELECT @QRY=@QRY+CHAR(13)+' ,NULL AMOUNT '
 		SELECT @QRY=@QRY+CHAR(13)+' ,CASE WHEN ISNULL(CO.ITEMCTRNAME,'''')='''' THEN ''NO COUNTER'' ELSE CONVERT(VARCHAR(100),CO.ITEMCTRNAME) END AS COUNTER '
 		SELECT @QRY=@QRY+CHAR(13)+' ,NULL AS EMPNAME'
		SELECT @QRY=@QRY+CHAR(13)+' ,NULL AS DESIGNERNAME'
 		SELECT @QRY=@QRY+CHAR(13)+' ,IM.ITEMNAME'
 		SELECT @QRY=@QRY+CHAR(13)+' ,''TRANSFER''AS TYPE'
 		SELECT @QRY=@QRY+CHAR(13)+' ,3 AS RESULT'
 		SELECT @QRY=@QRY+CHAR(13)+' ,''  '' AS COLHEAD'
 		SELECT @QRY=@QRY+CHAR(13)+' FROM '+@DBNAME+'..TRANSIT_AUDIT AS I '
 		SELECT @QRY=@QRY+CHAR(13)+' LEFT JOIN ITEMTAG T ON T.SNO=I.TAGSNO'
 		SELECT @QRY=@QRY+CHAR(13)+' INNER JOIN  ITEMMAST IM ON IM.ITEMID = T.ITEMID '
 		SELECT @QRY=@QRY+CHAR(13)+' LEFT OUTER JOIN  SUBITEMMAST AS SM ON SM.ITEMID = T.ITEMID AND SM.SUBITEMID = T.SUBITEMID '
 		SELECT @QRY=@QRY+CHAR(13)+' LEFT OUTER JOIN  ITEMCOUNTER AS CO ON CO.ITEMCTRID = T.ITEMCTRID '
 		SELECT @QRY=@QRY+CHAR(13)+' WHERE I.TRANDATE BETWEEN '''+@FROMDATE+''' AND '''+@TODATE+''' '
 		SELECT @QRY=@QRY+CHAR(13)+' AND I.ISSREC=''I'''
 		IF @COSTID<>'ALL' SELECT  @QRY=@QRY+' AND I.FROMID IN('''+ @COSTID +''')'    
		SELECT @QRY=@QRY+CHAR(13)+ 'AND (''' + @METALID + ''' = ''ALL'' OR IM.METALID = ''' + @METALID + ''')'
 		PRINT(@QRY)
 		EXEC(@QRY)
 		SELECT @QRY=CHAR(13)+' INSERT INTO TEMPTABLEDB..TEMPISSUE(PARTICULAR,TYPE,RESULT,COLHEAD)'
 		SELECT @QRY=@QRY+CHAR(13)+' SELECT DISTINCT TYPE,TYPE,0,''T'' FROM TEMPTABLEDB..TEMPISSUE'
 		EXEC(@QRY)
 		SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPISSUE(PARTICULAR,COUNTER,TYPE,RESULT,COLHEAD)'
 		SELECT @QRY=@QRY+CHAR(13)+' SELECT DISTINCT COUNTER,COUNTER,TYPE,1,''T1'' FROM TEMPTABLEDB..TEMPISSUE  WHERE COUNTER<>'''''
 		EXEC(@QRY)
 		SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPISSUE(PARTICULAR,ITEMNAME,COUNTER,TYPE,RESULT,COLHEAD)'
 		SELECT @QRY=@QRY+CHAR(13)+' SELECT DISTINCT ITEMNAME,ITEMNAME,COUNTER,TYPE,2,''T2'' FROM TEMPTABLEDB..TEMPISSUE  WHERE ITEMNAME<>'''''
 		EXEC(@QRY)
 		SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPISSUE(PARTICULAR,ITEMNAME,COUNTER,TYPE,RESULT,COLHEAD,PCS,GRSWT,NETWT,AMOUNT)'
 		SELECT @QRY=@QRY+CHAR(13)+' SELECT ''ITEM TOTAL'',ITEMNAME,COUNTER,TYPE,4,''S'' '
 		SELECT @QRY=@QRY+CHAR(13)+' ,SUM(PCS)PCS,SUM(GRSWT)GRSWT,SUM(NETWT)NETWT,SUM(AMOUNT)AMOUNT'
 		SELECT @QRY=@QRY+CHAR(13)+' FROM TEMPTABLEDB..TEMPISSUE   WHERE ITEMNAME<>'''' AND RESULT=3  GROUP BY ITEMNAME,COUNTER,TYPE'
 		PRINT(@QRY)
 		EXEC(@QRY)
 		SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPISSUE(PARTICULAR,COUNTER,TYPE,RESULT,COLHEAD,PCS,GRSWT,NETWT,AMOUNT,ITEMNAME)'
 		SELECT @QRY=@QRY+CHAR(13)+' SELECT ''COUNTER TOTAL'',COUNTER,TYPE,5,''S1'' '
 		SELECT @QRY=@QRY+CHAR(13)+' ,SUM(PCS)PCS,SUM(GRSWT)GRSWT,SUM(NETWT)NETWT,SUM(AMOUNT)AMOUNT,''ZZZ'''
 		SELECT @QRY=@QRY+CHAR(13)+' FROM TEMPTABLEDB..TEMPISSUE  WHERE COUNTER<>'''' AND RESULT=3 GROUP BY COUNTER,TYPE'
 		PRINT(@QRY)
 		EXEC(@QRY)
 		SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPISSUE(PARTICULAR,TYPE,RESULT,COLHEAD,PCS,GRSWT,NETWT,AMOUNT,ITEMNAME,COUNTER)'
 		SELECT @QRY=@QRY+CHAR(13)+' SELECT ''GRAND TOTAL'',TYPE,6,''G'' '
 		SELECT @QRY=@QRY+CHAR(13)+' ,SUM(PCS)PCS,SUM(GRSWT)GRSWT,SUM(NETWT)NETWT,SUM(AMOUNT)AMOUNT,''ZZZZ'',''ZZZZZ'''
 		SELECT @QRY=@QRY+CHAR(13)+' FROM TEMPTABLEDB..TEMPISSUE  WHERE TYPE<>'''' AND RESULT=3 GROUP BY TYPE'
 		EXEC(@QRY)
 		SELECT @QRY=' SELECT *  FROM TEMPTABLEDB..TEMPISSUE ORDER BY TYPE,COUNTER,ITEMNAME,RESULT'
 		EXEC(@QRY)
 	END
 	ELSE
 	BEGIN
 		SELECT @QRY='SELECT '
 		SELECT @QRY=@QRY+CHAR(13)+' IM.ITEMNAME  PARTICULAR '
 		SELECT @QRY=@QRY+CHAR(13)+' ,SUM(I.PCS)PCS,SUM(I.GRSWT)GRSWT'
 		SELECT @QRY=@QRY+CHAR(13)+' ,SUM(I.NETWT)NETWT'
 		SELECT @QRY=@QRY+CHAR(13)+' ,SUM(CASE WHEN I.TRANTYPE=''MI'' THEN 0 ELSE I.AMOUNT END) AMOUNT '
 		SELECT @QRY=@QRY+CHAR(13)+' ,CASE WHEN ISNULL(CO.ITEMCTRNAME,'''')='''' THEN ''NO COUNTER'' ELSE CONVERT(VARCHAR(100),CO.ITEMCTRNAME) END AS COUNTER '
 		SELECT @QRY=@QRY+CHAR(13)+' ,''SALES''AS TYPE'
 		SELECT @QRY=@QRY+CHAR(13)+' ,3 AS RESULT'
 		SELECT @QRY=@QRY+CHAR(13)+' ,''  '' AS COLHEAD'
 		SELECT @QRY=@QRY+CHAR(13)+' INTO TEMPTABLEDB..TEMPISSUE'
 		SELECT @QRY=@QRY+CHAR(13)+' FROM '+@DBNAME+'..ISSUE AS I '
 		SELECT @QRY=@QRY+CHAR(13)+' INNER JOIN  ITEMMAST IM ON IM.ITEMID = I.ITEMID '
 		SELECT @QRY=@QRY+CHAR(13)+' LEFT OUTER JOIN  SUBITEMMAST AS SM ON SM.ITEMID = I.ITEMID AND SM.SUBITEMID = I.SUBITEMID '
 		SELECT @QRY=@QRY+CHAR(13)+' LEFT OUTER JOIN  ITEMCOUNTER AS CO ON CO.ITEMCTRID = I.ITEMCTRID '
 		SELECT @QRY=@QRY+CHAR(13)+' LEFT OUTER JOIN  ITEMTAG AS T ON T.TAGNO = I.TAGNO AND T.ITEMID = I.ITEMID AND T.BATCHNO = I.BATCHNO '
 		SELECT @QRY=@QRY+CHAR(13)+' WHERE I.TRANDATE BETWEEN '''+@FROMDATE+''' AND '''+@TODATE+''' '
 		SELECT @QRY=@QRY+CHAR(13)+' AND I.TRANTYPE IN (''SA'',''OD'') '
 		IF @COSTID<>'ALL' SELECT  @QRY=@QRY+' AND I.COSTID IN('''+ @COSTID +''')'    
 		IF @COMPANYID<>'ALL' SELECT  @QRY=@QRY+' AND I.COMPANYID IN('''+ @COMPANYID +''')'    
		SELECT @QRY=@QRY+CHAR(13)+ 'AND (''' + @METALID + ''' = ''ALL'' OR IM.METALID = ''' + @METALID + ''')'
 		SELECT @QRY=@QRY+CHAR(13)+' AND ISNULL(I.CANCEL,'''') = '''' GROUP BY IM.ITEMNAME,CO.ITEMCTRNAME'
 		SELECT @QRY=@QRY+CHAR(13)+' UNION ALL'
 		SELECT @QRY=@QRY+CHAR(13)+' SELECT PARTICULAR,SUM(PCS)PCS,SUM(GRSWT)GRSWT,SUM(NETWT)NETWT,NULL AMOUNT,COUNTER '
 		SELECT @QRY=@QRY+CHAR(13)+' ,TYPE,RESULT,COLHEAD FROM ('
 		SELECT @QRY=@QRY+CHAR(13)+' SELECT '
 		SELECT @QRY=@QRY+CHAR(13)+' IM.ITEMNAME PARTICULAR '
 		SELECT @QRY=@QRY+CHAR(13)+' ,(SELECT SUM(PCS) FROM ITEMTAG WHERE SNO=I.TAGSNO)PCS'
 		SELECT @QRY=@QRY+CHAR(13)+' ,(SELECT SUM(GRSWT) FROM ITEMTAG WHERE SNO=I.TAGSNO)GRSWT'
 		SELECT @QRY=@QRY+CHAR(13)+' ,(SELECT SUM(NETWT) FROM ITEMTAG WHERE SNO=I.TAGSNO)NETWT'
 		SELECT @QRY=@QRY+CHAR(13)+' ,NULL AMOUNT '
 		SELECT @QRY=@QRY+CHAR(13)+' ,CASE WHEN ISNULL(CO.ITEMCTRNAME,'''')='''' THEN ''NO COUNTER'' ELSE CONVERT(VARCHAR(100),CO.ITEMCTRNAME) END AS COUNTER '
 		SELECT @QRY=@QRY+CHAR(13)+' ,''TRANSFER''AS TYPE'
 		SELECT @QRY=@QRY+CHAR(13)+' ,3 AS RESULT'
 		SELECT @QRY=@QRY+CHAR(13)+' ,''  '' AS COLHEAD'
 		SELECT @QRY=@QRY+CHAR(13)+' FROM '+@DBNAME+'..TRANSIT_AUDIT AS I '
 		SELECT @QRY=@QRY+CHAR(13)+' LEFT JOIN ITEMTAG T ON T.SNO=I.TAGSNO'
 		SELECT @QRY=@QRY+CHAR(13)+' INNER JOIN  ITEMMAST IM ON IM.ITEMID = T.ITEMID '
 		SELECT @QRY=@QRY+CHAR(13)+' LEFT OUTER JOIN  SUBITEMMAST AS SM ON SM.ITEMID = T.ITEMID AND SM.SUBITEMID = T.SUBITEMID '
 		SELECT @QRY=@QRY+CHAR(13)+' LEFT OUTER JOIN  ITEMCOUNTER AS CO ON CO.ITEMCTRID = T.ITEMCTRID '
 		SELECT @QRY=@QRY+CHAR(13)+' WHERE I.TRANDATE BETWEEN '''+@FROMDATE+''' AND '''+@TODATE+''' '
 		SELECT @QRY=@QRY+CHAR(13)+' AND I.ISSREC=''I'''
 		IF @COSTID<>'ALL' SELECT  @QRY=@QRY+' AND I.FROMID IN('''+ @COSTID +''')'   
		SELECT @QRY=@QRY+CHAR(13)+ 'AND (''' + @METALID + ''' = ''ALL'' OR IM.METALID = ''' + @METALID + ''')' 
 		SELECT @QRY=@QRY+CHAR(13)+' )X GROUP BY PARTICULAR,COUNTER,TYPE,RESULT,COLHEAD'
 		PRINT(@QRY)
 		EXEC(@QRY)
 		SELECT @QRY=CHAR(13)+' INSERT INTO TEMPTABLEDB..TEMPISSUE(PARTICULAR,TYPE,RESULT,COLHEAD)'
 		SELECT @QRY=@QRY+CHAR(13)+' SELECT DISTINCT TYPE,TYPE,0,''T'' FROM TEMPTABLEDB..TEMPISSUE'
 		EXEC(@QRY)
 		SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPISSUE(PARTICULAR,COUNTER,TYPE,RESULT,COLHEAD)'
 		SELECT @QRY=@QRY+CHAR(13)+' SELECT DISTINCT COUNTER,COUNTER,TYPE,1,''T1'' FROM TEMPTABLEDB..TEMPISSUE  WHERE COUNTER<>'''''
 		EXEC(@QRY)
 		SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPISSUE(PARTICULAR,COUNTER,TYPE,RESULT,COLHEAD,PCS,GRSWT,NETWT,AMOUNT)'
 		SELECT @QRY=@QRY+CHAR(13)+' SELECT ''COUNTER TOTAL'',COUNTER,TYPE,5,''S1'' '
 		SELECT @QRY=@QRY+CHAR(13)+' ,SUM(PCS)PCS,SUM(GRSWT)GRSWT,SUM(NETWT)NETWT,SUM(AMOUNT)AMOUNT'
 		SELECT @QRY=@QRY+CHAR(13)+' FROM TEMPTABLEDB..TEMPISSUE  WHERE COUNTER<>'''' AND RESULT=3 GROUP BY COUNTER,TYPE'
 		PRINT(@QRY)
 		EXEC(@QRY)
 		SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPISSUE(PARTICULAR,TYPE,RESULT,COLHEAD,PCS,GRSWT,NETWT,AMOUNT,COUNTER)'
 		SELECT @QRY=@QRY+CHAR(13)+' SELECT ''GRAND TOTAL'',TYPE,6,''G'' '
 		SELECT @QRY=@QRY+CHAR(13)+' ,SUM(PCS)PCS,SUM(GRSWT)GRSWT,SUM(NETWT)NETWT,SUM(AMOUNT)AMOUNT,''ZZZZ'''
 		SELECT @QRY=@QRY+CHAR(13)+' FROM TEMPTABLEDB..TEMPISSUE  WHERE TYPE<>'''' AND RESULT=3 GROUP BY TYPE'
 		EXEC(@QRY)
 		SELECT @QRY=' SELECT *  FROM TEMPTABLEDB..TEMPISSUE ORDER BY TYPE,COUNTER,RESULT'
 		EXEC(@QRY)
 	END
 	/*EXEC RPT_ITEMWISE_NEW 'TNGT1617','2016-04-01','2016-11-05','TN','NPL','Y'*/
 END