ALTER PROCEDURE SP_RPT_SALESABSTRACT_SALESBILLWISE  
(      
@DBNAME VARCHAR(30)        
,@FRMDATE VARCHAR(12)        
,@TODATE VARCHAR(12)        
,@COSTID VARCHAR(200)        
,@COMPANYID VARCHAR(200)  
,@CASHNAME VARCHAR(800)  
,@EMPNAME VARCHAR(800)  
,@UID VARCHAR(4)     
,@ITEMNAME VARCHAR(800)  
,@METALNAME VARCHAR(1000)  
,@BILLSUMM VARCHAR(1)
,@DAYWISE VARCHAR(1) = 'N'
)        
AS        
BEGIN /** PROC STARTS **/     
DECLARE @QRY VARCHAR(8000)      
DECLARE @TEMPISSUE VARCHAR(50)      
DECLARE @TEMPACCTRANN VARCHAR(50)      
DECLARE @TEMPADDRESS VARCHAR(50)      
DECLARE @TEMPSALEABSTRACT VARCHAR(50)      
DECLARE @TEMPSALEABSTRACT_RES VARCHAR(50)         
DECLARE @TEMPCASH VARCHAR(50)      
DECLARE @TEMPEMP VARCHAR(50)      
DECLARE @TEMPITEM VARCHAR(50)      
SELECT @TEMPCASH='TEMPTABLEDB.DBO.TEMPCASH'      
SELECT @TEMPITEM='TEMPTABLEDB.DBO.TEMPITEM'      
SELECT @TEMPEMP='TEMPTABLEDB.DBO.TEMPEMP'      
SELECT @TEMPISSUE='TEMPTABLEDB.DBO.TEMP'+@UID+'ISSUE'      
SELECT @TEMPACCTRANN='TEMPTABLEDB.DBO.TEMP'+@UID+'ACCTRANN'      
SELECT @TEMPADDRESS='TEMPTABLEDB.DBO.TEMP'+@UID+'ADDRESS'      
SELECT @TEMPSALEABSTRACT='TEMPTABLEDB.DBO.TEMP'+@UID+'SALEABSTRACT'      
SELECT @TEMPSALEABSTRACT_RES='TEMPTABLEDB.DBO.TEMP'+@UID+'SALEABSTRACT_RES'      
IF OBJECT_ID('TEMPTABLEDB.DBO.TEMPCASH', 'U') IS NOT NULL DROP TABLE TEMPTABLEDB.DBO.TEMPCASH    
DECLARE @BANKPAYPROID VARCHAR(5)  
SET @BANKPAYPROID = '-1'  
SELECT @BANKPAYPROID = CASE WHEN ISNULL(CTLTEXT,'')  = '' THEN '-1' ELSE CTLTEXT END FROM SFHADMINDB..SOFTCONTROL WHERE ISNULL(CTLID,'') = 'BANKPAYPROID'  
CREATE TABLE TEMPTABLEDB.DBO.TEMPCASH (CASHID VARCHAR(5))   
IF (SELECT COUNT(*) WHERE @CASHNAME LIKE '%ALL%')>0        
INSERT INTO TEMPTABLEDB.DBO.TEMPCASH (CASHID) SELECT ISNULL(CASHID,0) FROM SFHADMINDB..CASHCOUNTER UNION ALL SELECT ''        
ELSE        
BEGIN        
DECLARE @TCASHNAME VARCHAR(20)   
IF CHARINDEX(',',@CASHNAME)=0   
INSERT INTO TEMPTABLEDB.DBO.TEMPCASH (CASHID) SELECT ISNULL(CASHID,0) FROM SFHADMINDB..CASHCOUNTER WHERE CASHNAME = @CASHNAME   
WHILE CHARINDEX(',',@CASHNAME)>0   
BEGIN   
SET @TCASHNAME=LEFT(@CASHNAME,CHARINDEX(',',@CASHNAME)-1)   
SET @CASHNAME=RIGHT(@CASHNAME,LEN(@CASHNAME)-CHARINDEX(',',@CASHNAME))   
IF @CASHNAME <>'' AND CHARINDEX(',',@CASHNAME)=0   
SET @CASHNAME= @CASHNAME + ','   
INSERT INTO TEMPTABLEDB.DBO.TEMPCASH (CASHID) SELECT ISNULL(CASHID,0) FROM SFHADMINDB..CASHCOUNTER WHERE CASHNAME = @TCASHNAME   
END    
END   
IF OBJECT_ID('TEMPTABLEDB.DBO.TEMPITEM', 'U') IS NOT NULL DROP TABLE TEMPTABLEDB.DBO.TEMPITEM    
CREATE TABLE TEMPTABLEDB.DBO.TEMPITEM (ITEMID VARCHAR(5))   
IF (SELECT COUNT(*) WHERE @ITEMNAME LIKE '%ALL%')>0        
BEGIN   
IF @METALNAME <>'ALL'  
BEGIN   
PRINT REPLACE(@METALNAME,',',''',''')  
INSERT INTO TEMPTABLEDB.DBO.TEMPITEM (ITEMID) SELECT ISNULL(ITEMID,0) FROM SFHADMINDB..ITEMMAST  
WHERE METALID IN (SELECT METALID FROM SFHADMINDB..METALMAST WHERE METALNAME in(''+ @METALNAME +''))  
END  
IF @METALNAME ='ALL'  
BEGIN   
INSERT INTO TEMPTABLEDB.DBO.TEMPITEM (ITEMID) SELECT ISNULL(ITEMID,0) FROM SFHADMINDB..ITEMMAST UNION ALL SELECT ''        
END  
END  
ELSE        
BEGIN        
DECLARE @TITEMNAME VARCHAR(20)   
IF CHARINDEX(',',@ITEMNAME)=0   
IF @METALNAME <>'ALL'  
BEGIN   
INSERT INTO TEMPTABLEDB.DBO.TEMPITEM (ITEMID) SELECT ISNULL(ITEMID,0) FROM SFHADMINDB..ITEMMAST WHERE ITEMNAME = @ITEMNAME  
AND METALID IN (SELECT METALID FROM SFHADMINDB..METALMAST where METALNAME in(''+ @METALNAME +''))  
END  
IF @METALNAME = 'ALL'  
BEGIN   
INSERT INTO TEMPTABLEDB.DBO.TEMPITEM (ITEMID) SELECT ISNULL(ITEMID,0) FROM SFHADMINDB..ITEMMAST WHERE ITEMNAME = @ITEMNAME  
END  
WHILE CHARINDEX(',',@ITEMNAME)>0   
BEGIN   
SET @TITEMNAME=LEFT(@ITEMNAME,CHARINDEX(',',@ITEMNAME)-1)   
SET @ITEMNAME=RIGHT(@ITEMNAME,LEN(@ITEMNAME)-CHARINDEX(',',@ITEMNAME))   
IF @ITEMNAME <>'' AND CHARINDEX(',',@ITEMNAME)=0   
SET @ITEMNAME= @ITEMNAME + ','   
IF @METALNAME <>'ALL'  
BEGIN   
INSERT INTO TEMPTABLEDB.DBO.TEMPITEM (ITEMID) SELECT ISNULL(ITEMID,0) FROM SFHADMINDB..ITEMMAST WHERE ITEMNAME = @TITEMNAME   
AND METALID IN (SELECT METALID FROM SFHADMINDB..METALMAST where METALNAME in(''+ @METALNAME +''))  
END  
IF @METALNAME = 'ALL'  
BEGIN   
INSERT INTO TEMPTABLEDB.DBO.TEMPITEM (ITEMID) SELECT ISNULL(ITEMID,0) FROM SFHADMINDB..ITEMMAST WHERE ITEMNAME = @TITEMNAME   
END  
END    
END   
IF OBJECT_ID('TEMPTABLEDB.DBO.TEMPEMP', 'U') IS NOT NULL DROP TABLE TEMPTABLEDB.DBO.TEMPEMP   
CREATE TABLE TEMPTABLEDB.DBO.TEMPEMP (EMPID VARCHAR(5))   
IF (SELECT COUNT(*) WHERE @EMPNAME LIKE '%ALL%')>0        
INSERT INTO TEMPTABLEDB.DBO.TEMPEMP (EMPID) SELECT ISNULL(EMPID,0) FROM SFHADMINDB..EMPMASTER UNION ALL SELECT ''        
ELSE        
BEGIN        
DECLARE @TEMPNAME VARCHAR(20)   
IF CHARINDEX(',',@EMPNAME)=0   
INSERT INTO TEMPTABLEDB.DBO.TEMPEMP (EMPID) SELECT ISNULL(EMPID,0) FROM SFHADMINDB..EMPMASTER WHERE EMPNAME = @EMPNAME   
WHILE CHARINDEX(',',@EMPNAME)>0   
BEGIN   
SET @TEMPNAME=LEFT(@EMPNAME,CHARINDEX(',',@EMPNAME)-1)   
SET @EMPNAME=RIGHT(@EMPNAME,LEN(@EMPNAME)-CHARINDEX(',',@EMPNAME))   
IF @EMPNAME <>'' AND CHARINDEX(',',@EMPNAME)=0   
SET @EMPNAME= @EMPNAME + ','   
INSERT INTO TEMPTABLEDB.DBO.TEMPEMP (EMPID) SELECT ISNULL(EMPID,0) FROM SFHADMINDB..EMPMASTER WHERE EMPNAME = @TEMPNAME   
END    
END   
SET NOCOUNT ON      
IF @COSTID<>'ALL'SET @COSTID= REPLACE(@COSTID,',',''',''')      
IF @COMPANYID<>'ALL'SET @COMPANYID= REPLACE(@COMPANYID,',',''',''')      
SELECT @QRY='IF OBJECT_ID('''+@TEMPISSUE+''') IS NOT NULL DROP TABLE '+ @TEMPISSUE +''       
SELECT @QRY=@QRY + CHAR(13) +' IF OBJECT_ID('''+@TEMPISSUE+''') IS NOT NULL DROP TABLE '+ @TEMPISSUE +''       
SELECT @QRY=@QRY + CHAR(13) +' IF OBJECT_ID('''+@TEMPACCTRANN+''') IS NOT NULL DROP TABLE '+ @TEMPACCTRANN +''       
SELECT @QRY=@QRY + CHAR(13) +' IF OBJECT_ID('''+@TEMPADDRESS+''') IS NOT NULL DROP TABLE '+ @TEMPADDRESS +''       
SELECT @QRY=@QRY + CHAR(13) +' IF OBJECT_ID('''+@TEMPSALEABSTRACT+''') IS NOT NULL DROP TABLE '+ @TEMPSALEABSTRACT +''       
SELECT @QRY=@QRY + CHAR(13) +' IF OBJECT_ID('''+@TEMPSALEABSTRACT_RES+''') IS NOT NULL DROP TABLE '+ @TEMPSALEABSTRACT_RES +''       
SELECT @QRY=@QRY + CHAR(13) +' IF OBJECT_ID(''TEMPTABLEDB..TEMPTRANDET_RECEIPT'') IS NOT NULL DROP TABLE TEMPTABLEDB..TEMPTRANDET_RECEIPT'  
SELECT @QRY=@QRY + CHAR(13) +' IF OBJECT_ID(''TEMPTABLEDB..TEMPTRANDET_PAYMENT'') IS NOT NULL DROP TABLE TEMPTABLEDB..TEMPTRANDET_PAYMENT'  
PRINT @QRY      
EXEC(@QRY)      
/** GET FROM ISSUE TABLE **/      
SELECT @QRY=' SELECT * INTO '+@TEMPISSUE+' FROM('      
SELECT @QRY=@QRY + CHAR(13) +' SELECT I.CATCODE,I.TRANNO IBILLNO,I.TRANDATE IBILLDATE,CONVERT(VARCHAR(13),NULL)DISPDATE,CONVERT(VARCHAR(75),NULL)CUSTOMER'      
SELECT @QRY=@QRY + CHAR(13) +' ,I.ITEMID IITEMID,CONVERT(VARCHAR(100),NULL)ITEMNAME,I.PCS IPCS,I.GRSWT IGRSWT,I.NETWT INETWT'      
SELECT @QRY=@QRY + CHAR(13) +' ,(SELECT SUM(ISNULL(STNWT,0)) FROM ISSSTONE WHERE ISSSNO=I.SNO AND STNITEMID IN(SELECT ITEMID FROM '+@DBNAME+'..ITEMMAST WHERE DIASTONE=''S'')) ISTNWT'      
SELECT @QRY=@QRY + CHAR(13) +' ,(SELECT SUM(ISNULL(STNWT,0)) FROM ISSSTONE WHERE ISSSNO=I.SNO AND STNITEMID IN(SELECT ITEMID FROM '+@DBNAME+'..ITEMMAST WHERE DIASTONE=''D'')) IDIAWT'      
SELECT @QRY=@QRY + CHAR(13) +' ,I.RATE IRATE,I.MCHARGE IMCHARGE'      
SELECT @QRY=@QRY + CHAR(13) +' ,I.WASTAGE IWASTVAL,(I.WASTAGE*I.RATE) IWASTAGE,I.TAX ITAX,SUM(ISNULL(I.AMOUNT,0)+ISNULL(I.TAX,0))ITOTAL,CONVERT(VARCHAR(15),ISNULL(I.TAGNO,'''')) ITAGNO,NULL PBILLNO,NULL PITEMID'      
SELECT @QRY=@QRY + CHAR(13) +' ,CONVERT(NUMERIC(15,3),NULL) PPCS,CONVERT(NUMERIC(15,3),NULL) PGRSWT,CONVERT(NUMERIC(15,3),NULL) PNETWT,CONVERT(NUMERIC(15,3),NULL) PSTNWT,CONVERT(NUMERIC(15,3),NULL) PDIAWT,CONVERT(NUMERIC(15,2),NULL) PAMOUNT,NULL SRBILLNO,NULL SRITEMID'  
SELECT @QRY=@QRY + CHAR(13) +' ,CONVERT(NUMERIC(15,3),NULL) SRPCS,CONVERT(NUMERIC(15,3),NULL) SRGRSWT,CONVERT(NUMERIC(15,3),NULL) SRNETWT,CONVERT(NUMERIC(15,3),NULL) SRSTNWT,CONVERT(NUMERIC(15,3),NULL) SRDIAWT,CONVERT(NUMERIC(15,3),NULL) SRRATE'  
SELECT @QRY=@QRY + CHAR(13) +' , CONVERT(NUMERIC(15,3),NULL) SRMCHARGE,CONVERT(NUMERIC(15,3),NULL) SRWASTVAL,CONVERT(NUMERIC(15,3),NULL) SRWASTAGE,CONVERT(NUMERIC(15,3),NULL) SRTAX'      
SELECT @QRY=@QRY + CHAR(13) +' ,CONVERT(NUMERIC(15,3),NULL) SRTOTAL,CONVERT(NUMERIC(15,2),NULL) SRBALANCE,CONVERT(NUMERIC(15,3),NULL) CASH,CONVERT(NUMERIC(15,3),NULL) CRCARD'  
SELECT @QRY=@QRY + CHAR(13) +' ,CONVERT(NUMERIC(15,3),NULL) CHEQUE,CONVERT(NUMERIC(15,3),NULL) CHIT,CONVERT(NUMERIC(15,3),NULL) ADVANCE,CONVERT(NUMERIC(15,3),NULL) GV,CONVERT(NUMERIC(15,3),NULL) HC'  
SELECT @QRY=@QRY + CHAR(13) +' ,CONVERT(NUMERIC(15,3),NULL) DISCOUNT,CONVERT(NUMERIC(15,3),NULL) CRBALANCE,CONVERT(NUMERIC(15,3),NULL) ACTOTAL,I.CASHID,CONVERT(VARCHAR(150),I.BATCHNO)BATCHNO,''I'' COLHEAD'      
SELECT @QRY=@QRY + CHAR(13) +' ,METALID FROM ISSUE AS I '      
SELECT @QRY=@QRY + CHAR(13) +' WHERE I.TRANDATE BETWEEN '''+ @FRMDATE +''' AND ''' + @TODATE + ''' AND I.TRANTYPE IN(''SA'',''OD'') AND ISNULL(I.CANCEL,'''')='''' '      
IF @COSTID<>'ALL' SELECT  @QRY=@QRY+' AND I.COSTID IN('''+ @COSTID +''')'      
IF @COMPANYID<>'ALL' SELECT  @QRY=@QRY+' AND I.COMPANYID IN('''+ @COMPANYID +''')'      
IF @CASHNAME <>'ALL' SELECT  @QRY=@QRY+' AND ISNULL(I.CASHID,0) IN (SELECT CASHID FROM TEMPTABLEDB.DBO.TEMPCASH) '  
SELECT  @QRY=@QRY+' AND ISNULL(I.ITEMID,0) IN (SELECT ITEMID FROM TEMPTABLEDB.DBO.TEMPITEM) '  
IF @EMPNAME <>'ALL' SELECT  @QRY=@QRY+' AND ISNULL(I.EMPID,0) IN (SELECT EMPID FROM TEMPTABLEDB.DBO.TEMPEMP) '  
SELECT @QRY=@QRY + CHAR(13) +' GROUP BY I.CATCODE,I.TRANNO,I.TRANDATE,I.ITEMID,'      
SELECT @QRY=@QRY + CHAR(13) +' I.PCS,I.GRSWT,I.NETWT,I.RATE,I.MCHARGE,I.WASTAGE,I.TAX,I.CASHID,I.BATCHNO,I.RATE,I.SNO,I.TAGNO,METALID '      
SELECT @QRY=@QRY + CHAR(13) +' UNION ALL'      
PRINT '/** GET FROM RECEIPT TABLE **/    '  
SELECT @QRY=@QRY + CHAR(13) +' SELECT  R.CATCODE,R.TRANNO IBILLNO, R.TRANDATE IBILLDATE,NULL DISPDATE,CONVERT(VARCHAR(75),NULL)CUSTOMER'      
SELECT @QRY=@QRY + CHAR(13) +' ,NULL IITEMID,NULL ITEMNAME,0 IPCS,0 IGRSWT,0 INETWT ,0 ISTNWT,0 IDIAWT, 0 IRATE,0 IMCHARGE,0 IWASTVAL,0 IWASTAGE,0 ITAX,0 ITOTAL,ISNULL(NULL,'''') ITAGNO'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''PU'' THEN R.TRANNO ELSE NULL END  PBILLNO'  
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''PU'' THEN R.ITEMID ELSE NULL END  PITEMID'  
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''PU'' THEN R.PCS ELSE 0 END PPCS'  
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''PU'' THEN R.GRSWT ELSE 0 END PGRSWT'  
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''PU'' THEN R.NETWT ELSE 0 END PNETWT'  
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''PU'' THEN (SELECT SUM(ISNULL(STNWT,0)) FROM RECEIPTSTONE WHERE ISSSNO=R.SNO AND STNITEMID IN(SELECT ITEMID FROM '+@DBNAME+'..ITEMMAST WHERE DIASTONE=''S'')) ELSE 0 END PSTNWT'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''PU'' THEN (SELECT SUM(ISNULL(STNWT,0)) FROM RECEIPTSTONE WHERE ISSSNO=R.SNO AND STNITEMID IN(SELECT ITEMID FROM '+@DBNAME+'..ITEMMAST WHERE DIASTONE=''D'')) ELSE 0 END PDIAWT'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''PU'' THEN SUM(ISNULL(R.AMOUNT,0)) ELSE 0 END PAMOUNT'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''SR'' THEN R.TRANNO ELSE NULL END  SRBILLNO'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''SR'' THEN R.ITEMID ELSE NULL END  SRITEMID'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''SR'' THEN R.PCS ELSE 0 END SRPCS'  
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''SR'' THEN R.GRSWT ELSE 0 END SRGRSWT'  
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''SR'' THEN R.NETWT ELSE 0 END SRNETWT'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''SR'' THEN (SELECT SUM(ISNULL(STNWT,0)) FROM RECEIPTSTONE WHERE ISSSNO=R.SNO AND STNITEMID IN(SELECT ITEMID FROM '+@DBNAME+'..ITEMMAST WHERE DIASTONE=''S'')) ELSE 0 END SRSTNWT'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''SR'' THEN (SELECT SUM(ISNULL(STNWT,0)) FROM RECEIPTSTONE WHERE ISSSNO=R.SNO AND STNITEMID IN(SELECT ITEMID FROM '+@DBNAME+'..ITEMMAST WHERE DIASTONE=''D'')) ELSE 0 END SRDIAWT'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''SR'' THEN R.RATE ELSE 0 END SRRATE'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''SR'' THEN R.MCHARGE ELSE 0 END SRMCHARGE'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''SR'' THEN R.WASTAGE ELSE 0 END SRWASTVAL'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''SR'' THEN (R.WASTAGE*R.RATE) ELSE 0 END SRWASTAGE'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''SR'' THEN R.TAX ELSE 0 END SRTAX'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''SR'' THEN SUM(ISNULL(R.AMOUNT,0)+ISNULL(R.TAX,0)) ELSE 0 END SRTOTAL'      
SELECT @QRY=@QRY + CHAR(13) +' ,0 SRBALANCE,0 CASH,0 CRCARD,0 CHEQUE,0 CHIT,0 ADVANCE,0 GV,0 HC,0 DISCOUNT, 0 CRBALANCE,0 ACTOTAL'      
SELECT @QRY=@QRY + CHAR(13) +' ,R.CASHID,CONVERT(VARCHAR(150),R.BATCHNO)BATCHNO '  
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN TRANTYPE=''SR'' THEN ''A'' WHEN TRANTYPE=''PU'' THEN ''P'' END COLHEAD'      
SELECT @QRY=@QRY + CHAR(13) +' ,METALID FROM RECEIPT R'      
SELECT @QRY=@QRY + CHAR(13) +' WHERE R.TRANDATE BETWEEN '''+ @FRMDATE +''' AND ''' + @TODATE + ''' AND R.TRANTYPE IN(''SR'',''PU'') AND ISNULL(R.CANCEL,'''')='''''      
IF @COSTID<>'ALL' SELECT  @QRY=@QRY+' AND R.COSTID IN('''+ @COSTID +''')'      
IF @COMPANYID<>'ALL' SELECT  @QRY=@QRY+' AND R.COMPANYID IN('''+ @COMPANYID +''')'      
IF @CASHNAME <>'ALL' SELECT  @QRY=@QRY+' AND ISNULL(R.CASHID,0) IN (SELECT CASHID FROM TEMPTABLEDB.DBO.TEMPCASH) '  
SELECT  @QRY=@QRY+' AND ISNULL(R.ITEMID,0) IN (SELECT ITEMID FROM TEMPTABLEDB.DBO.TEMPITEM) '  
IF @EMPNAME <>'ALL' SELECT  @QRY=@QRY+' AND ISNULL(R.EMPID,0) IN (SELECT EMPID FROM TEMPTABLEDB.DBO.TEMPEMP) '  
SELECT @QRY=@QRY + CHAR(13) +' AND EXISTS (SELECT 1 FROM ISSUE WHERE BATCHNO=R.BATCHNO)'  
SELECT @QRY=@QRY + CHAR(13) +' GROUP BY R.CATCODE,R.TRANNO,R.TRANDATE,R.TRANTYPE,R.ITEMID,'      
SELECT @QRY=@QRY + CHAR(13) +' R.PCS,R.GRSWT,R.NETWT,R.RATE,R.MCHARGE,R.WASTAGE,R.TAX,R.CASHID,R.BATCHNO,R.RATE,R.SNO,METALID '      
SELECT @QRY=@QRY + CHAR(13) +' )X'  
PRINT @QRY      
EXEC(@QRY)   
/** GET FROM ACCTRAN TABLE **/      
SELECT @QRY=' SELECT IBILLNO,IBILLDATE,BATCHNO,SUM(CASH)CASH,SUM(CRCARD)CRCARD,SUM(CHEQUE)CHEQUE,SUM(CHIT)CHIT'      
SELECT @QRY=@QRY + CHAR(13) +' ,SUM(ADVANCE)ADVANCE,SUM(GV)GV,SUM(HC)HC,SUM(DISCOUNT)DISCOUNT,SUM(CRBALANCE)CRBALANCE ,SUM(ACTOTAL)ACTOTAL,CONVERT(NUMERIC(15,2),NULL) SRBALANCE,CUSTOMER INTO '+@TEMPACCTRANN+' FROM ('      
SELECT @QRY=@QRY + CHAR(13) +' SELECT A.TRANNO IBILLNO,A.TRANDATE IBILLDATE,A.BATCHNO'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN A.PAYMODE IN(''CA'') THEN SUM(CASE WHEN TRANMODE IN(''D'') THEN ISNULL(A.AMOUNT,0)ELSE ISNULL(A.AMOUNT,0)*-1 END) ELSE 0 END CASH'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN A.PAYMODE IN(''CC'') THEN SUM(CASE WHEN TRANMODE IN(''D'') THEN ISNULL(A.AMOUNT,0)ELSE ISNULL(A.AMOUNT,0)*-1 END) ELSE 0 END CRCARD'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN A.PAYMODE IN(''CH'') THEN SUM(CASE WHEN TRANMODE IN(''D'') THEN ISNULL(A.AMOUNT,0)ELSE ISNULL(A.AMOUNT,0)*-1 END) ELSE 0 END CHEQUE'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN A.PAYMODE IN(''CZ'',''CG'',''CD'',''CB'',''SS'')THEN SUM(CASE WHEN TRANMODE IN(''D'') THEN ISNULL(A.AMOUNT,0)ELSE ISNULL(A.AMOUNT,0)*-1 END) ELSE 0 END CHIT'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN A.PAYMODE IN(''AR'',''AA'') THEN SUM(CASE WHEN TRANMODE IN(''D'') THEN ISNULL(A.AMOUNT,0)ELSE ISNULL(A.AMOUNT,0)*-1 END) ELSE 0 END ADVANCE'    
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN A.PAYMODE IN(''GV'') THEN SUM(CASE WHEN TRANMODE IN(''D'') THEN ISNULL(A.AMOUNT,0)ELSE ISNULL(A.AMOUNT,0)*-1 END) ELSE 0 END GV'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN A.PAYMODE IN(''HC'') THEN SUM(CASE WHEN TRANMODE IN(''C'') THEN ISNULL(A.AMOUNT,0)ELSE ISNULL(A.AMOUNT,0)*-1 END) ELSE 0 END HC'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN A.PAYMODE IN(''DI'') THEN SUM(CASE WHEN TRANMODE IN(''D'') THEN ISNULL(A.AMOUNT,0)ELSE ISNULL(A.AMOUNT,0)*-1 END) ELSE 0 END DISCOUNT'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN A.PAYMODE IN(''DU'') THEN SUM(CASE WHEN TRANMODE IN(''D'') THEN ISNULL(A.AMOUNT,0)ELSE ISNULL(A.AMOUNT,0)*-1 END) ELSE 0 END CRBALANCE'      
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN A.PAYMODE IN(''CA'',''CC'',''CH'',''AA'',''AR'',''GV'',''DU'',''CZ'',''CG'',''CD'',''CB'',''SS'') '  
SELECT @QRY=@QRY + CHAR(13) +' THEN SUM(CASE WHEN TRANMODE IN(''D'') THEN ISNULL(A.AMOUNT,0)ELSE ISNULL(A.AMOUNT,0)*-1 END) ELSE 0 END ACTOTAL'      
SELECT @QRY=@QRY + CHAR(13) +' ,(SELECT TOP 1 PNAME FROM '+@DBNAME+'..PERSONALINFO WHERE SNO IN'  
SELECT @QRY=@QRY + CHAR(13) +' (SELECT TOP 1 PSNO FROM '+@DBNAME+'..CUSTOMERINFO WHERE BATCHNO=A.BATCHNO))CUSTOMER'  
SELECT @QRY=@QRY + CHAR(13) +' FROM ACCTRAN A  WHERE A.BATCHNO IN (SELECT DISTINCT BATCHNO FROM '+@TEMPISSUE+')AND ISNULL(A.CANCEL,'''')='''' '      
IF @COSTID<>'ALL' SELECT  @QRY=@QRY+' AND A.COSTID IN('''+ @COSTID +''')'      
IF @COMPANYID<>'ALL' SELECT  @QRY=@QRY+' AND A.COMPANYID IN('''+ @COMPANYID +''')'      
SELECT @QRY=@QRY + CHAR(13) +' GROUP BY A.TRANNO,A.TRANDATE,A.BATCHNO,A.PAYMODE,A.TRANMODE'      
SELECT @QRY=@QRY + CHAR(13) +' )Y GROUP BY IBILLNO,IBILLDATE,BATCHNO,CUSTOMER HAVING SUM(ISNULL(ACTOTAL,0))<>0'      
PRINT @QRY      
EXEC(@QRY)      
SELECT @QRY=' ALTER TABLE '+@TEMPISSUE+' ADD  PITEMNAME VARCHAR(100),SRITEMNAME VARCHAR(100)'      
PRINT @QRY      
EXEC(@QRY)  
SELECT @QRY=' UPDATE T SET ITEMNAME=(SELECT ''(''+ CONVERT(VARCHAR(10),ITEMID) +'') '' + ITEMNAME  FROM '+ @DBNAME +'..ITEMMAST WHERE ITEMID=T.IITEMID) FROM '+@TEMPISSUE+' T'      
SELECT @QRY=@QRY + CHAR(13) +' UPDATE T SET PITEMNAME=(SELECT ITEMNAME FROM '+ @DBNAME +'..ITEMMAST WHERE ITEMID=T.PITEMID) FROM '+@TEMPISSUE+' T'      
SELECT @QRY=@QRY + CHAR(13) +' UPDATE T SET SRITEMNAME=(SELECT ITEMNAME FROM '+ @DBNAME +'..ITEMMAST WHERE ITEMID=T.SRITEMID) FROM '+@TEMPISSUE+' T'      
PRINT @QRY      
EXEC(@QRY)      
SELECT @QRY='DECLARE @BILLNO NVARCHAR(20)'      
SELECT @QRY=@QRY + CHAR(13) +' DECLARE CUR CURSOR FOR SELECT DISTINCT IBILLNO FROM '+@TEMPACCTRANN+' '       
SELECT @QRY=@QRY + CHAR(13) +' OPEN CUR'      
SELECT @QRY=@QRY + CHAR(13) +' FETCH NEXT FROM CUR INTO @BILLNO'      
SELECT @QRY=@QRY + CHAR(13) +' WHILE @@FETCH_STATUS=0'      
SELECT @QRY=@QRY + CHAR(13) +' BEGIN'      
SELECT @QRY=@QRY + CHAR(13) +' SET ROWCOUNT 1'      
SELECT @QRY=@QRY + CHAR(13) +' UPDATE '+@TEMPISSUE+' SET CASH=A.CASH,CRCARD=A.CRCARD,CHEQUE=A.CHEQUE,CHIT=A.CHIT'  
SELECT @QRY=@QRY + CHAR(13) +' ,ADVANCE=A.ADVANCE,GV=A.GV,HC=A.HC,DISCOUNT=A.DISCOUNT,CRBALANCE=A.CRBALANCE'  
SELECT @QRY=@QRY + CHAR(13) +' ,ACTOTAL=A.ACTOTAL,CUSTOMER=A.CUSTOMER FROM '+@TEMPISSUE+' T,'+@TEMPACCTRANN+' A'      
SELECT @QRY=@QRY + CHAR(13) +' WHERE T.BATCHNO=A.BATCHNO AND T.IBILLNO=@BILLNO'      
SELECT @QRY=@QRY + CHAR(13) +' SET ROWCOUNT 0'      
SELECT @QRY=@QRY + CHAR(13) +' FETCH NEXT FROM CUR INTO @BILLNO'      
SELECT @QRY=@QRY + CHAR(13) +' END'      
SELECT @QRY=@QRY + CHAR(13) +' CLOSE CUR'      
SELECT @QRY=@QRY + CHAR(13) +' DEALLOCATE CUR'      
PRINT @QRY      
EXEC(@QRY)         
SELECT @QRY='SELECT *,CONVERT(VARCHAR(20),NULL)DBILLNO,CONVERT(VARCHAR(20),NULL)PDBILLNO,CONVERT(VARCHAR(20),NULL)SDBILLNO'  
SELECT @QRY=@QRY + CHAR(13) +' ,1 RESULT INTO '+@TEMPSALEABSTRACT+' FROM ('      
SELECT @QRY=@QRY+'SELECT *,(SELECT CASHNAME FROM '+ @DBNAME +'..CASHCOUNTER WHERE CASHID=I.CASHID)COUNTERNAME'      
SELECT @QRY=@QRY + CHAR(13) +' FROM '+@TEMPISSUE+' I)X ORDER BY IBILLDATE,BATCHNO,COLHEAD'      
PRINT @QRY  
EXEC(@QRY)        
SELECT @QRY='INSERT INTO '  
SELECT @QRY=@QRY + CHAR(13) +' '+@TEMPSALEABSTRACT+' (CUSTOMER,COUNTERNAME,RESULT)'      
SELECT @QRY=@QRY+'SELECT DISTINCT ''SALES'''  
SELECT @QRY=@QRY+',(SELECT CASHNAME FROM '+ @DBNAME +'..CASHCOUNTER WHERE CASHID=I.CASHID),0 AS RESULT'      
SELECT @QRY=@QRY + CHAR(13) +' FROM '+@TEMPISSUE+' I'      
PRINT @QRY  
EXEC(@QRY)  
IF @BILLSUMM='Y'  
BEGIN  
SELECT @QRY='INSERT INTO '+@TEMPSALEABSTRACT+' '  
SELECT @QRY=@QRY + CHAR(13) +' (CUSTOMER,COUNTERNAME,BATCHNO,IBILLDATE,RESULT,IPCS,IGRSWT,INETWT,ITOTAL,SRPCS,SRGRSWT,SRNETWT,PPCS,PGRSWT,PNETWT,PAMOUNT)'  
SELECT @QRY=@QRY + CHAR(13) +' SELECT ''SUB TOTAL'' CUSTOMER'  
SELECT @QRY=@QRY + CHAR(13) +' ,(SELECT CASHNAME FROM '+ @DBNAME +'..CASHCOUNTER WHERE CASHID=I.CASHID)COUNTERNAME,BATCHNO,IBILLDATE,2 AS RESULT,'  
SELECT @QRY=@QRY + CHAR(13) +' SUM(IPCS)IPCS,SUM(IGRSWT)IGRSWT,SUM(INETWT)INETWT,SUM(ITOTAL)ITOTAL,SUM(SRPCS)SRPCS,SUM(SRGRSWT)SRGRSWT,SUM(SRNETWT)SRNETWT,'  
SELECT @QRY=@QRY + CHAR(13) +' SUM(PPCS)PPCS,SUM(PGRSWT)PGRSWT,SUM(PNETWT)PNETWT,SUM(PAMOUNT)PAMOUNT '  
SELECT @QRY=@QRY + CHAR(13) +' FROM '+@TEMPISSUE+' I GROUP BY I.CASHID,I.BATCHNO,I.IBILLDATE '  
PRINT @QRY  
EXEC(@QRY)     
END  
SELECT @QRY='INSERT INTO '+@TEMPSALEABSTRACT+' '  
SELECT @QRY=@QRY + CHAR(13) +' (CUSTOMER,COUNTERNAME,BATCHNO,IBILLDATE,RESULT,IBILLNO,IPCS,IGRSWT,INETWT,ITOTAL,SRPCS,SRGRSWT,SRNETWT,PPCS,PGRSWT,PNETWT,PAMOUNT)'  
SELECT @QRY=@QRY + CHAR(13) +' SELECT DISTINCT (SELECT CASHNAME FROM '+ @DBNAME +'..CASHCOUNTER WHERE CASHID=I.CASHID)CUSTOMER'  
SELECT @QRY=@QRY + CHAR(13) +' ,(SELECT CASHNAME FROM '+ @DBNAME +'..CASHCOUNTER WHERE CASHID=I.CASHID)COUNTERNAME,''ZZZZZ'',MAX(IBILLDATE),3 AS RESULT,'  
SELECT @QRY=@QRY + CHAR(13) +' (SELECT COUNT(DISTINCT IBILLNO) FROM '+@TEMPISSUE+' WHERE CASHID=I.CASHID AND COLHEAD=''I'' GROUP BY CASHID)BILLNO,'   
SELECT @QRY=@QRY + CHAR(13) +' SUM(IPCS)IPCS,SUM(IGRSWT)IGRSWT,SUM(INETWT)INETWT,SUM(ITOTAL)ITOTAL,SUM(SRPCS)SRPCS,SUM(SRGRSWT)SRGRSWT,SUM(SRNETWT)SRNETWT,'  
SELECT @QRY=@QRY + CHAR(13) +' SUM(PPCS)PPCS,SUM(PGRSWT)PGRSWT,SUM(PNETWT)PNETWT,SUM(PAMOUNT)PAMOUNT '  
SELECT @QRY=@QRY + CHAR(13) +' FROM '+@TEMPISSUE+' I GROUP BY I.CASHID '  
PRINT @QRY  
EXEC(@QRY)                
SELECT @QRY='IF (SELECT COUNT(*) FROM  '+@TEMPSALEABSTRACT+') > 0 '  
SELECT @QRY=@QRY + CHAR(13) +' BEGIN'  
SELECT @QRY=@QRY + CHAR(13) +' INSERT INTO '+@TEMPSALEABSTRACT+' '  
SELECT @QRY=@QRY + CHAR(13) +' (CUSTOMER,COUNTERNAME,RESULT,IBILLNO,IPCS,IGRSWT,INETWT,ITOTAL,SRPCS,SRGRSWT,SRNETWT,PPCS,PGRSWT,PNETWT,PAMOUNT,'  
SELECT @QRY=@QRY + CHAR(13) +' CASH,CRCARD,CHIT,CHEQUE,ADVANCE,CRBALANCE,ACTOTAL)'  
SELECT @QRY=@QRY + CHAR(13) +' SELECT ''GRAND TOTAL'' CUSTOMER'  
SELECT @QRY=@QRY + CHAR(13) +' ,''ZZZZZZZZ''COUNTERNAME,4 AS RESULT,'  
SELECT @QRY=@QRY + CHAR(13) +' (SELECT COUNT(DISTINCT IBILLNO) FROM '+@TEMPISSUE+' WHERE COLHEAD=''I'')BILLNO,'   
SELECT @QRY=@QRY + CHAR(13) +' SUM(IPCS)IPCS,SUM(IGRSWT)IGRSWT,SUM(INETWT)INETWT,SUM(ITOTAL)ITOTAL,SUM(SRPCS)SRPCS,SUM(SRGRSWT)SRGRSWT,SUM(SRNETWT)SRNETWT,'  
SELECT @QRY=@QRY + CHAR(13) +' SUM(PPCS)PPCS,SUM(PGRSWT)PGRSWT,SUM(PNETWT)PNETWT,SUM(PAMOUNT)PAMOUNT, '  
SELECT @QRY=@QRY + CHAR(13) +' SUM(CASH)CASH,SUM(CRCARD)CRCARD,SUM(CHIT)CHIT,SUM(CHEQUE)CHEQUE,SUM(ADVANCE)ADVANCE,SUM(CRBALANCE)CRBALANCE,SUM(ACTOTAL)ACTOTAL '  
SELECT @QRY=@QRY + CHAR(13) +' FROM '+@TEMPISSUE+' I  '  
SELECT @QRY=@QRY + CHAR(13) +' END'  
PRINT @QRY  
EXEC(@QRY)           
PRINT '/*GET CASH PURCHASE*/'         
SELECT @QRY='INSERT INTO '+@TEMPSALEABSTRACT+' '  
SELECT @QRY=@QRY + CHAR(13) +' (CUSTOMER,COUNTERNAME,RESULT,IPCS,IGRSWT,INETWT,ITOTAL,PBILLNO,PPCS,PGRSWT,PNETWT,PAMOUNT)'         
SELECT @QRY=@QRY+ CHAR(13) +' SELECT  '  
SELECT @QRY=@QRY+ CHAR(13) +' (SELECT TOP 1 CATNAME FROM SFHADMINDB..CATEGORY WHERE CATCODE=R.CATCODE) CUSTOMER,''ZZZZZZZZ'' COUNTERNAME,'  
SELECT @QRY=@QRY+ CHAR(13) +' 6 RESULT,0 IPCS,0 IGRSWT,0 INETWT ,0 ITOTAL '  
SELECT @QRY=@QRY+ CHAR(13) +' ,TRANNO,CASE WHEN TRANTYPE=''PU'' THEN R.PCS ELSE 0 END PPCS'  
SELECT @QRY=@QRY+ CHAR(13) +' ,CASE WHEN TRANTYPE=''PU'' THEN R.GRSWT ELSE 0 END PGRSWT'  
SELECT @QRY=@QRY+ CHAR(13) +' ,CASE WHEN TRANTYPE=''PU'' THEN R.NETWT ELSE 0 END PNETWT'  
SELECT @QRY=@QRY+ CHAR(13) +' ,CASE WHEN TRANTYPE=''PU'' THEN R.AMOUNT ELSE 0 END PAMOUNT'  
SELECT @QRY=@QRY+ CHAR(13) +' FROM RECEIPT R'  
SELECT @QRY=@QRY+ CHAR(13) +' WHERE R.TRANDATE BETWEEN '''+ @FRMDATE +''' AND ''' + @TODATE + ''' AND R.TRANTYPE IN(''PU'') AND ISNULL(R.CANCEL,'''')='''''      
SELECT @QRY=@QRY+ CHAR(13) +' AND NOT EXISTS (SELECT 1 FROM ISSUE WHERE BATCHNO=R.BATCHNO)'  
IF @COSTID<>'ALL' SELECT  @QRY=@QRY+' AND R.COSTID IN('''+ @COSTID +''')'      
IF @COMPANYID<>'ALL' SELECT  @QRY=@QRY+' AND R.COMPANYID IN('''+ @COMPANYID +''')'      
IF @CASHNAME <>'ALL' SELECT  @QRY=@QRY+' AND ISNULL(R.CASHID,0) IN (SELECT CASHID FROM TEMPTABLEDB.DBO.TEMPCASH) '  
SELECT  @QRY=@QRY+' AND ISNULL(R.ITEMID,0) IN (SELECT ITEMID FROM TEMPTABLEDB.DBO.TEMPITEM) '  
IF @EMPNAME <>'ALL' SELECT  @QRY=@QRY+' AND ISNULL(R.EMPID,0) IN (SELECT EMPID FROM TEMPTABLEDB.DBO.TEMPEMP) '  
SELECT @QRY=@QRY+ CHAR(13) +' AND PUREXCH=''P'' ORDER BY TRANNO'  
PRINT @QRY   
EXEC(@QRY)  
SELECT @QRY='IF (SELECT COUNT(*) FROM  '+@TEMPSALEABSTRACT+' WHERE RESULT=6) > 0 '  
SELECT @QRY=@QRY + CHAR(13) +' BEGIN'  
SELECT @QRY=@QRY + CHAR(13) +' INSERT INTO '  
SELECT @QRY=@QRY + CHAR(13) +' '+@TEMPSALEABSTRACT+' (CUSTOMER,COUNTERNAME,RESULT,COLHEAD)'      
SELECT @QRY=@QRY+'SELECT ''CASH PURCHASE'''  
SELECT @QRY=@QRY+',''ZZZZZZZZ'',5 AS RESULT,''S'' COLHEAD'  
SELECT @QRY=@QRY + CHAR(13) +' END'  
PRINT @QRY  
EXEC(@QRY)   
SELECT @QRY='IF (SELECT COUNT(*) FROM  '+@TEMPSALEABSTRACT+' WHERE RESULT=6) > 0 '  
SELECT @QRY=@QRY + CHAR(13) +' BEGIN'  
SELECT @QRY=@QRY + CHAR(13) +' INSERT INTO '+@TEMPSALEABSTRACT+' '  
SELECT @QRY=@QRY + CHAR(13) +' (CUSTOMER,COUNTERNAME,RESULT,COLHEAD,IPCS,IGRSWT,INETWT,ITOTAL,SRPCS,SRGRSWT,SRNETWT,PPCS,PGRSWT,PNETWT,PAMOUNT,'  
SELECT @QRY=@QRY + CHAR(13) +' CASH,CRCARD,CHIT,ADVANCE,CRBALANCE,ACTOTAL)'  
SELECT @QRY=@QRY + CHAR(13) +' SELECT ''CASH PURCHASE TOTAL'' CUSTOMER'  
SELECT @QRY=@QRY + CHAR(13) +' ,''ZZZZZZZZ''COUNTERNAME,7 AS RESULT,''T'' COLHEAD,'  
SELECT @QRY=@QRY + CHAR(13) +' SUM(IPCS)IPCS,SUM(IGRSWT)IGRSWT,SUM(INETWT)INETWT,SUM(ITOTAL)ITOTAL,SUM(SRPCS)SRPCS,SUM(SRGRSWT)SRGRSWT,SUM(SRNETWT)SRNETWT,'  
SELECT @QRY=@QRY + CHAR(13) +' SUM(PPCS)PPCS,SUM(PGRSWT)PGRSWT,SUM(PNETWT)PNETWT,SUM(PAMOUNT)PAMOUNT, '  
SELECT @QRY=@QRY + CHAR(13) +' SUM(CASH)CASH,SUM(CRCARD)CRCARD,SUM(CHIT)CHIT,SUM(ADVANCE)ADVANCE,SUM(CRBALANCE)CRBALANCE,SUM(ACTOTAL)ACTOTAL '  
SELECT @QRY=@QRY + CHAR(13) +' FROM '+@TEMPSALEABSTRACT+' I  WHERE RESULT=''6'' '  
SELECT @QRY=@QRY + CHAR(13) +' END'  
PRINT @QRY  
EXEC(@QRY)  
/*SELECT @QRY='INSERT INTO '+@TEMPSALEABSTRACT+' '  
SELECT @QRY=@QRY + CHAR(13) +' (CUSTOMER,COUNTERNAME,RESULT,IPCS,IGRSWT,INETWT,ITOTAL,PBILLNO,PPCS,PGRSWT,PNETWT,PAMOUNT)'         
SELECT @QRY=@QRY+ CHAR(13) +' SELECT  '  
SELECT @QRY=@QRY+ CHAR(13) +' (SELECT TOP 1 CATNAME FROM SFHADMINDB..CATEGORY WHERE CATCODE=R.CATCODE) CUSTOMER,''ZZZZZZZZ'' COUNTERNAME,'  
SELECT @QRY=@QRY+ CHAR(13) +' 9 RESULT,0 IPCS,0 IGRSWT,0 INETWT ,0 ITOTAL '  
SELECT @QRY=@QRY+ CHAR(13) +' ,TRANNO,CASE WHEN TRANTYPE=''PU'' THEN R.PCS ELSE 0 END PPCS'  
SELECT @QRY=@QRY+ CHAR(13) +' ,CASE WHEN TRANTYPE=''PU'' THEN R.GRSWT ELSE 0 END PGRSWT'  
SELECT @QRY=@QRY+ CHAR(13) +' ,CASE WHEN TRANTYPE=''PU'' THEN R.NETWT ELSE 0 END PNETWT'  
SELECT @QRY=@QRY+ CHAR(13) +' ,CASE WHEN TRANTYPE=''PU'' THEN R.AMOUNT ELSE 0 END PAMOUNT'  
SELECT @QRY=@QRY+ CHAR(13) +' FROM RECEIPT R'  
SELECT @QRY=@QRY+ CHAR(13) +' WHERE R.TRANDATE BETWEEN '''+ @FRMDATE +''' AND ''' + @TODATE + ''' AND R.TRANTYPE IN(''PU'') AND ISNULL(R.CANCEL,'''')='''''      
SELECT @QRY=@QRY+ CHAR(13) +' AND NOT EXISTS (SELECT 1 FROM ISSUE WHERE BATCHNO=R.BATCHNO)'  
IF @COSTID<>'ALL' SELECT  @QRY=@QRY+' AND R.COSTID IN('''+ @COSTID +''')'      
IF @COMPANYID<>'ALL' SELECT  @QRY=@QRY+' AND R.COMPANYID IN('''+ @COMPANYID +''')'      
IF @CASHNAME <>'ALL' SELECT  @QRY=@QRY+' AND ISNULL(R.CASHID,0) IN (SELECT CASHID FROM TEMPTABLEDB.DBO.TEMPCASH) '  
IF @EMPNAME <>'ALL' SELECT  @QRY=@QRY+' AND ISNULL(R.EMPID,0) IN (SELECT EMPID FROM TEMPTABLEDB.DBO.TEMPEMP) '  
SELECT @QRY=@QRY+ CHAR(13) +' AND PUREXCH<>''P'' ORDER BY TRANNO'      
PRINT @QRY   
EXEC(@QRY)  
SELECT @QRY='IF (SELECT COUNT(*) FROM  '+@TEMPSALEABSTRACT+' WHERE RESULT=9) > 0 '  
SELECT @QRY=@QRY + CHAR(13) +' BEGIN'  
SELECT @QRY=@QRY + CHAR(13) +' INSERT INTO '  
SELECT @QRY=@QRY + CHAR(13) +' '+@TEMPSALEABSTRACT+' (CUSTOMER,COUNTERNAME,RESULT,COLHEAD)'      
SELECT @QRY=@QRY+'SELECT ''EXCHANGE'''  
SELECT @QRY=@QRY+',''ZZZZZZZZ'',8 AS RESULT,''S'' COLHEAD'  
SELECT @QRY=@QRY + CHAR(13) +' END'  
PRINT @QRY  
EXEC(@QRY)   
SELECT @QRY='IF (SELECT COUNT(*) FROM  '+@TEMPSALEABSTRACT+' WHERE RESULT=9) > 0 '  
SELECT @QRY=@QRY + CHAR(13) +' BEGIN'  
SELECT @QRY=@QRY + CHAR(13) +' INSERT INTO '+@TEMPSALEABSTRACT+' '  
SELECT @QRY=@QRY + CHAR(13) +' (CUSTOMER,COUNTERNAME,RESULT,COLHEAD,IPCS,IGRSWT,INETWT,ITOTAL,SRPCS,SRGRSWT,SRNETWT,PPCS,PGRSWT,PNETWT,PAMOUNT,'  
SELECT @QRY=@QRY + CHAR(13) +' CASH,CRCARD,CHIT,ADVANCE,CRBALANCE,ACTOTAL)'  
SELECT @QRY=@QRY + CHAR(13) +' SELECT ''EXCHANGE TOTAL'' CUSTOMER'  
SELECT @QRY=@QRY + CHAR(13) +' ,''ZZZZZZZZ''COUNTERNAME,10 AS RESULT,''T'' COLHEAD,'  
SELECT @QRY=@QRY + CHAR(13) +' SUM(IPCS)IPCS,SUM(IGRSWT)IGRSWT,SUM(INETWT)INETWT,SUM(ITOTAL)ITOTAL,SUM(SRPCS)SRPCS,SUM(SRGRSWT)SRGRSWT,SUM(SRNETWT)SRNETWT,'  
SELECT @QRY=@QRY + CHAR(13) +' SUM(PPCS)PPCS,SUM(PGRSWT)PGRSWT,SUM(PNETWT)PNETWT,SUM(PAMOUNT)PAMOUNT, '  
SELECT @QRY=@QRY + CHAR(13) +' SUM(CASH)CASH,SUM(CRCARD)CRCARD,SUM(CHIT)CHIT,SUM(ADVANCE)ADVANCE,SUM(CRBALANCE)CRBALANCE,SUM(ACTOTAL)ACTOTAL '  
SELECT @QRY=@QRY + CHAR(13) +' FROM '+@TEMPSALEABSTRACT+' I  WHERE RESULT=''9'' '  
SELECT @QRY=@QRY + CHAR(13) +' END'  
PRINT @QRY  
EXEC(@QRY)*/  
SELECT @QRY='IF (SELECT COUNT(*) FROM  '+@TEMPSALEABSTRACT+' WHERE RESULT=6) > 0 '  
SELECT @QRY=@QRY + CHAR(13) +' BEGIN'  
SELECT @QRY=@QRY + CHAR(13) +' INSERT INTO '+@TEMPSALEABSTRACT+' '  
SELECT @QRY=@QRY + CHAR(13) +' (CUSTOMER,COUNTERNAME,RESULT,COLHEAD,IPCS,IGRSWT,INETWT,ITOTAL,SRPCS,SRGRSWT,SRNETWT,PPCS,PGRSWT,PNETWT,PAMOUNT,'  
SELECT @QRY=@QRY + CHAR(13) +' CASH,CRCARD,CHIT,CHEQUE,ADVANCE,CRBALANCE,ACTOTAL)'  
SELECT @QRY=@QRY + CHAR(13) +'SELECT ''GRAND TOTAL'' CUSTOMER'  
SELECT @QRY=@QRY + CHAR(13) +',''ZZZZZZZZ''COUNTERNAME,11 AS RESULT,''G'' COLHEAD,'  
SELECT @QRY=@QRY + CHAR(13) +' SUM(IPCS)IPCS,SUM(IGRSWT)IGRSWT,SUM(INETWT)INETWT,SUM(ITOTAL)ITOTAL,SUM(SRPCS)SRPCS,SUM(SRGRSWT)SRGRSWT,SUM(SRNETWT)SRNETWT,'  
SELECT @QRY=@QRY + CHAR(13) +' SUM(PPCS)PPCS,SUM(PGRSWT)PGRSWT,SUM(PNETWT)PNETWT,SUM(PAMOUNT)PAMOUNT, '  
SELECT @QRY=@QRY + CHAR(13) +' SUM(CASH)CASH,SUM(CRCARD)CRCARD,SUM(CHIT)CHIT,SUM(CHEQUE)CHEQUE,SUM(ADVANCE)ADVANCE,SUM(CRBALANCE)CRBALANCE,SUM(ACTOTAL)ACTOTAL '  
SELECT @QRY=@QRY + CHAR(13) +' FROM '+@TEMPISSUE+' I  '  
SELECT @QRY=@QRY + CHAR(13) +' END'  
PRINT @QRY  
EXEC(@QRY)  
SELECT @QRY='IF (SELECT COUNT(*) FROM  '+@TEMPSALEABSTRACT+') > 0 '  
SELECT @QRY=@QRY + CHAR(13) +' BEGIN'  
SELECT @QRY=@QRY + CHAR(13) +' INSERT INTO '+@TEMPSALEABSTRACT+' '  
SELECT @QRY=@QRY + CHAR(13) +' (CUSTOMER,COUNTERNAME,RESULT,COLHEAD)'  
SELECT @QRY=@QRY + CHAR(13) +' SELECT ''CH:'' + CONVERT(VARCHAR,CONVERT(NUMERIC(15,2),SUM(CHIT))) + '' ADV:'' + '  
SELECT @QRY=@QRY + CHAR(13) +' CONVERT(VARCHAR,CONVERT(NUMERIC(15,2),SUM(ADVANCE))) + '' CHQ:'' + CONVERT(VARCHAR,CONVERT(NUMERIC(15,2),SUM(CHEQUE))) '      
SELECT @QRY=@QRY + CHAR(13) +' ,''ZZZZZZZZ''COUNTERNAME,12 AS RESULT,''T'' COLHEAD FROM '+@TEMPISSUE+' I  '  
SELECT @QRY=@QRY + CHAR(13) +' END'  
PRINT @QRY  
EXEC(@QRY)  
SELECT @QRY = ' IF OBJECT_ID(''TEMPTABLEDB..TEMPOUTSTANDING'') IS NOT NULL DROP TABLE TEMPTABLEDB..TEMPOUTSTANDING '  
SELECT @QRY = @QRY + CHAR(13) +' SELECT * INTO TEMPTABLEDB..TEMPOUTSTANDING FROM SFHADMINDB..OUTSTANDING WHERE TRANDATE BETWEEN '''+ @FRMDATE +''' AND ''' + @TODATE + ''' '  
SELECT @QRY = @QRY + CHAR(13) +' AND ISNULL(CANCEL,'''') = '''''  
IF @COSTID<>'ALL' SELECT  @QRY=@QRY+' AND COSTID IN('''+ @COSTID +''')'      
IF @COMPANYID<>'ALL' SELECT  @QRY=@QRY+' AND COMPANYID IN('''+ @COMPANYID +''')'      
IF @CASHNAME <>'ALL' SELECT  @QRY=@QRY+' AND ISNULL(CASHID,0) IN (SELECT CASHID FROM TEMPTABLEDB.DBO.TEMPCASH) '  
IF @EMPNAME <>'ALL' SELECT  @QRY=@QRY+' AND ISNULL(EMPID,0) IN (SELECT EMPID FROM TEMPTABLEDB.DBO.TEMPEMP) '      
SELECT @QRY = @QRY + CHAR(13) +' AND FROMFLAG NOT IN ('''',''S'',''O'',''A'') AND (TRANFLAG NOT IN(''W'') OR AMOUNT<>0)'      
PRINT @QRY  
EXEC (@QRY)  
SELECT @QRY='IF (SELECT COUNT(*) FROM TEMPTABLEDB..TEMPOUTSTANDING ) > 0 '  
SELECT @QRY=@QRY + CHAR(13) +' BEGIN'  
SELECT @QRY=@QRY + CHAR(13) +' INSERT INTO '+@TEMPSALEABSTRACT+' '  
SELECT @QRY=@QRY + CHAR(13) +' (CUSTOMER,COUNTERNAME,RESULT,COLHEAD,BATCHNO,ITEMNAME,ITAGNO)'  
SELECT @QRY=@QRY + CHAR(13) +' SELECT ''RECEIPT & PAYMENTS'' '  
SELECT @QRY=@QRY + CHAR(13) +' ,''ZZZZZZZZ''COUNTERNAME,13 AS RESULT,''G'' COLHEAD,''TRAN-TYPE'' AS BATCHNO'  
SELECT @QRY=@QRY + CHAR(13) +' ,''DEBIT'' AS ITEMNAME,''CREDIT'' AS ITEMNAME '  
SELECT @QRY=@QRY + CHAR(13) +' END'  
PRINT @QRY  
EXEC(@QRY)  
/** GETTING RECEIPT PART **/  
SELECT @QRY='IF (SELECT COUNT(*) FROM TEMPTABLEDB..TEMPOUTSTANDING ) > 0 '  
SELECT @QRY=@QRY + CHAR(13) +' BEGIN'  
SELECT @QRY=@QRY + CHAR(13) +' INSERT INTO '+@TEMPSALEABSTRACT+' '  
SELECT @QRY=@QRY + CHAR(13) +' (CUSTOMER,COUNTERNAME,RESULT,COLHEAD,BATCHNO,IBILLNO,ITAGNO)'  
SELECT @QRY=@QRY + CHAR(13) +' SELECT P.PNAME AS CUSTOMER,''ZZZZZZZZ''COUNTERNAME,14 RESULT,''D'' COLHEAD'  
SELECT @QRY = @QRY + CHAR(13) +' ,CASE WHEN O.PAYMODE IN (''DR'',''DU'') THEN ''CREDIT RECEIPT'''  
SELECT @QRY = @QRY + CHAR(13) +' WHEN O.PAYMODE = ''MR'' THEN ''MISCELLANEOUS RECEIPT'''  
SELECT @QRY = @QRY + CHAR(13) +' WHEN O.PAYMODE = ''OR'' AND SUBSTRING(O.RUNNO,6,1) <> ''R'' THEN ''ORDER RECEIPT'''  
SELECT @QRY = @QRY + CHAR(13) +' WHEN O.PAYMODE = ''OR'' AND SUBSTRING(O.RUNNO,6,1) = ''R'' THEN ''REPAIR RECEIPT'''  
SELECT @QRY = @QRY + CHAR(13) +' ELSE ''ADVANCE RECEIPT'' END AS BATCHNO '  
SELECT @QRY = @QRY + CHAR(13) +' ,O.TRANNO'      
SELECT @QRY = @QRY + CHAR(13) +' ,AMOUNT'  
SELECT @QRY = @QRY + CHAR(13) +' FROM TEMPTABLEDB..TEMPOUTSTANDING AS O LEFT OUTER JOIN SFHADMINDB..CUSTOMERINFO AS C ON C.BATCHNO = O.BATCHNO'  
SELECT @QRY = @QRY + CHAR(13) +' LEFT OUTER JOIN SFHADMINDB..PERSONALINFO AS P ON P.SNO = C.PSNO'  
SELECT @QRY = @QRY + CHAR(13) +' WHERE O.TRANDATE BETWEEN '''+@FRMDATE+''' AND '''+@TODATE+''' AND O.RECPAY = ''R'' AND AMOUNT <> 0'  
SELECT @QRY = @QRY + CHAR(13) +' AND ISNULL(CTRANCODE,0) != ISNULL('''+@BANKPAYPROID+''','''')'  
SELECT @QRY=@QRY + CHAR(13) +' END'  
PRINT @QRY  
EXEC (@QRY)  
/** GETTING PAYMENT PART **/      
SELECT @QRY='IF (SELECT COUNT(*) FROM TEMPTABLEDB..TEMPOUTSTANDING ) > 0 '  
SELECT @QRY=@QRY + CHAR(13) +' BEGIN'  
SELECT @QRY=@QRY + CHAR(13) +' INSERT INTO '+@TEMPSALEABSTRACT+' '  
SELECT @QRY=@QRY + CHAR(13) +' (CUSTOMER,COUNTERNAME,RESULT,COLHEAD,BATCHNO,IBILLNO,ITEMNAME)'  
SELECT @QRY=@QRY + CHAR(13) +' SELECT P.PNAME AS CUSTOMER,''ZZZZZZZZ''COUNTERNAME,15 RESULT,''D'' COLHEAD'  
SELECT @QRY = @QRY + CHAR(13) +' ,CASE '  
SELECT @QRY = @QRY + CHAR(13) +' WHEN O.PAYMODE = ''DP'' THEN ''PURCHASE/SALES RETURN'''  
SELECT @QRY = @QRY + CHAR(13) +' WHEN O.PAYMODE = ''DU'' THEN ''CREDIT SALES'''  
SELECT @QRY = @QRY + CHAR(13) +' WHEN O.PAYMODE = ''MP'' THEN ''MISCELLANEOUS PAYMENT'''  
SELECT @QRY = @QRY + CHAR(13) +' WHEN O.PAYMODE = ''AP'' AND SUBSTRING(O.RUNNO,6,1) = ''R'' THEN ''REPAIR REPAY'''  
SELECT @QRY = @QRY + CHAR(13) +' WHEN O.PAYMODE = ''AP'' AND SUBSTRING(O.RUNNO,6,1) = ''O'' THEN ''ORDER REPAY'''  
SELECT @QRY = @QRY + CHAR(13) +' WHEN O.PAYMODE = ''AP'' AND SUBSTRING(O.RUNNO,6,1) NOT IN (''O'',''R'') THEN ''ADVANCE REPAY'''  
SELECT @QRY = @QRY + CHAR(13) +' WHEN O.PAYMODE = ''GV'' THEN ''GIFT VOUCHER ADJ'''  
SELECT @QRY = @QRY + CHAR(13) +' ELSE ''ADVANCE ADJUSTED'' END AS BATCHNO'  
SELECT @QRY = @QRY + CHAR(13) +' ,O.TRANNO'  
SELECT @QRY = @QRY + CHAR(13) +' ,AMOUNT'  
SELECT @QRY = @QRY + CHAR(13) +' FROM TEMPTABLEDB..TEMPOUTSTANDING AS O'  
SELECT @QRY = @QRY + CHAR(13) +' LEFT OUTER JOIN SFHADMINDB..CUSTOMERINFO AS C ON C.BATCHNO = O.BATCHNO'  
SELECT @QRY = @QRY + CHAR(13) +' LEFT OUTER JOIN SFHADMINDB..PERSONALINFO AS P ON P.SNO = C.PSNO'  
SELECT @QRY = @QRY + CHAR(13) +' WHERE O.TRANDATE BETWEEN '''+@FRMDATE+''' AND '''+@TODATE+''' AND O.RECPAY = ''P'' AND O.AMOUNT <> 0'      
SELECT @QRY=@QRY + CHAR(13) +' END'  
PRINT @QRY  
EXEC(@QRY)  
SELECT @QRY='IF (SELECT COUNT(*) FROM TEMPTABLEDB..TEMPOUTSTANDING ) > 0 '  
SELECT @QRY=@QRY + CHAR(13) +' BEGIN'  
SELECT @QRY=@QRY + CHAR(13) +' INSERT INTO '+@TEMPSALEABSTRACT+' '  
SELECT @QRY=@QRY + CHAR(13) +' (CUSTOMER,COUNTERNAME,RESULT,COLHEAD,ITEMNAME,ITAGNO)'  
SELECT @QRY=@QRY + CHAR(13) +' SELECT ''DAY-S TOTAL'' CUSTOMER'  
SELECT @QRY=@QRY + CHAR(13)+',''ZZZZZZZZ''COUNTERNAME,16 AS RESULT,''T'' COLHEAD,'  
SELECT @QRY=@QRY + CHAR(13) +' SUM(CONVERT(NUMERIC(15,2),ITEMNAME))ITEMNAME,SUM(CONVERT(NUMERIC(15,2),ITAGNO))ITAGNO '  
SELECT @QRY=@QRY + CHAR(13) +' FROM '+@TEMPSALEABSTRACT+' I  WHERE RESULT IN (''14'',''15'') '  
SELECT @QRY=@QRY + CHAR(13) +' END'  
PRINT @QRY  
EXEC(@QRY)  
SELECT @QRY='IF (SELECT COUNT(*) FROM TEMPTABLEDB..TEMPOUTSTANDING ) > 0 '  
SELECT @QRY=@QRY + CHAR(13) +' BEGIN'  
SELECT @QRY=@QRY + CHAR(13) +' INSERT INTO '+@TEMPSALEABSTRACT+' '  
SELECT @QRY=@QRY + CHAR(13) +' (CUSTOMER,COUNTERNAME,RESULT,COLHEAD,ITEMNAME,ITAGNO)'  
SELECT @QRY=@QRY + CHAR(13) +' SELECT ''CLOSING AMOUNT'' CUSTOMER'  
SELECT @QRY=@QRY + CHAR(13) +' ,''ZZZZZZZZ''COUNTERNAME,17 AS RESULT,''G'' COLHEAD'  
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN SUM(CONVERT(NUMERIC(15,2),ITEMNAME)) > SUM(CONVERT(NUMERIC(15,2),ITAGNO)) '  
SELECT @QRY=@QRY + CHAR(13) +' THEN SUM(CONVERT(NUMERIC(15,2),ITEMNAME))-SUM(CONVERT(NUMERIC(15,2),ITAGNO)) END ITEMNAME'  
SELECT @QRY=@QRY + CHAR(13) +' ,CASE WHEN SUM(CONVERT(NUMERIC(15,2),ITAGNO)) > SUM(CONVERT(NUMERIC(15,2),ITEMNAME)) '  
SELECT @QRY=@QRY + CHAR(13) +' THEN SUM(CONVERT(NUMERIC(15,2),ITAGNO))-SUM(CONVERT(NUMERIC(15,2),ITEMNAME)) END ITEMNAME'         
SELECT @QRY=@QRY + CHAR(13) +' FROM '+@TEMPSALEABSTRACT+' I  WHERE RESULT IN (''16'') '  
SELECT @QRY=@QRY + CHAR(13) +' END'  
PRINT @QRY  
EXEC(@QRY)  
SELECT @QRY=' UPDATE '+@TEMPSALEABSTRACT+' SET IPCS=NULL WHERE IPCS=''0'''      
SELECT @QRY=@QRY+ CHAR(13) +' UPDATE '+@TEMPSALEABSTRACT+' SET IGRSWT=NULL WHERE IGRSWT=''0'''      
SELECT @QRY=@QRY+ CHAR(13) +' UPDATE '+@TEMPSALEABSTRACT+' SET INETWT=NULL WHERE INETWT=''0'''      
SELECT @QRY=@QRY+ CHAR(13) +' UPDATE '+@TEMPSALEABSTRACT+' SET ITOTAL=NULL WHERE ITOTAL=''0'''      
SELECT @QRY=@QRY+ CHAR(13) +' UPDATE '+@TEMPSALEABSTRACT+' SET PPCS=NULL WHERE PPCS=0'          
SELECT @QRY=@QRY+ CHAR(13) +' UPDATE '+@TEMPSALEABSTRACT+' SET PGRSWT=NULL WHERE PGRSWT=0'      
SELECT @QRY=@QRY+ CHAR(13) +' UPDATE '+@TEMPSALEABSTRACT+' SET PNETWT=NULL WHERE PNETWT=0'      
SELECT @QRY=@QRY+ CHAR(13) +' UPDATE '+@TEMPSALEABSTRACT+' SET PAMOUNT=NULL WHERE PAMOUNT=0'          
SELECT @QRY=@QRY+ CHAR(13) +' UPDATE '+@TEMPSALEABSTRACT+' SET SRPCS=NULL WHERE SRPCS=0'      
SELECT @QRY=@QRY+ CHAR(13) +' UPDATE '+@TEMPSALEABSTRACT+' SET SRGRSWT=NULL WHERE SRGRSWT=0'         
SELECT @QRY=@QRY+ CHAR(13) +' UPDATE '+@TEMPSALEABSTRACT+' SET SRNETWT=NULL WHERE SRNETWT=0'   
SELECT @QRY=@QRY+ CHAR(13) +' UPDATE '+@TEMPSALEABSTRACT+' SET SRTOTAL=NULL WHERE SRTOTAL=0'       
SELECT @QRY=@QRY+ CHAR(13) +' UPDATE '+@TEMPSALEABSTRACT+' SET CASH=NULL WHERE CASH=0'   
SELECT @QRY=@QRY+ CHAR(13) +' UPDATE '+@TEMPSALEABSTRACT+' SET CRCARD=NULL WHERE CRCARD=0'   
SELECT @QRY=@QRY+ CHAR(13) +' UPDATE '+@TEMPSALEABSTRACT+' SET CHIT=NULL WHERE CHIT=0'   
SELECT @QRY=@QRY+ CHAR(13) +' UPDATE '+@TEMPSALEABSTRACT+' SET ADVANCE=NULL WHERE ADVANCE=0'   
SELECT @QRY=@QRY+ CHAR(13) +' UPDATE '+@TEMPSALEABSTRACT+' SET CRBALANCE=NULL WHERE CRBALANCE=0'       
SELECT @QRY=@QRY+ CHAR(13) +' UPDATE '+@TEMPSALEABSTRACT+' SET ACTOTAL=NULL WHERE ACTOTAL=0'   
SELECT @QRY=@QRY+ CHAR(13) +' UPDATE '+@TEMPSALEABSTRACT+' SET CHEQUE=NULL WHERE CHEQUE=0'   
PRINT @QRY      
EXEC(@QRY)   

IF @DAYWISE='Y'  
BEGIN  
SELECT @QRY='SELECT CONVERT(VARCHAR(MAX),IBILLDATE,105)IBILLDATE,'  
SELECT @QRY=@QRY + CHAR(13) +' SUM(ISNULL(IPCS,0))IPCS,SUM(ISNULL(IGRSWT,0))IGRSWT,SUM(ISNULL(INETWT,0))INETWT,CAST(SUM(ISNULL(ITAX,0))/2 As DECIMAL(10,2)) ICGST,CAST(SUM(ISNULL(ITAX,0))/2 As DECIMAL(10,2)) ISGST,SUM(ISNULL(ITOTAL,0))-SUM(ISNULL(ITAX,0)) ITOTAL,'  
SELECT @QRY=@QRY + CHAR(13) +' SUM(ISNULL(PPCS,0))PPCS,SUM(ISNULL(PGRSWT,0))PGRSWT,SUM(ISNULL(PNETWT,0))PNETWT,SUM(ISNULL(PAMOUNT,0))PAMOUNT,'  
SELECT @QRY=@QRY + CHAR(13) +' SUM(ISNULL(SRPCS,0))SRPCS,SUM(ISNULL(SRGRSWT,0))SRGRSWT,SUM(ISNULL(SRNETWT,0))SRNETWT,SUM(ISNULL(SRTOTAL,0))SRTOTAL,'  
SELECT @QRY=@QRY + CHAR(13) +' SUM(ISNULL(CASH,0))CASH,SUM(ISNULL(CRCARD,0))CRCARD,SUM(ISNULL(CHIT,0))CHIT,SUM(ISNULL(CHEQUE,0))CHEQUE,SUM(ISNULL(ADVANCE,0))ADVANCE,SUM(ISNULL(CRBALANCE,0))CRBALANCE,SUM(ISNULL(ACTOTAL,0))ACTOTAL'  
SELECT @QRY=@QRY + CHAR(13) +' FROM '+@TEMPSALEABSTRACT+''  
SELECT @QRY=@QRY + CHAR(13) +' WHERE RESULT = 1'
SELECT @QRY=@QRY + CHAR(13) +' GROUP BY IBILLDATE'
SELECT @QRY=@QRY + CHAR(13) +' UNION'
SELECT @QRY=@QRY + CHAR(13) +' SELECT ''TOTAL'','
SELECT @QRY=@QRY + CHAR(13) +' SUM(ISNULL(IPCS,0))IPCS,SUM(ISNULL(IGRSWT,0))IGRSWT,SUM(ISNULL(INETWT,0))INETWT,CAST(SUM(ISNULL(ITAX,0))/2 As DECIMAL(10,2)) ICGST,CAST(SUM(ISNULL(ITAX,0))/2 As DECIMAL(10,2)) ISGST,SUM(ISNULL(ITOTAL,0))-SUM(ISNULL(ITAX,0)) ITOTAL,'  
SELECT @QRY=@QRY + CHAR(13) +' SUM(ISNULL(PPCS,0))PPCS,SUM(ISNULL(PGRSWT,0))PGRSWT,SUM(ISNULL(PNETWT,0))PNETWT,SUM(ISNULL(PAMOUNT,0))PAMOUNT,'  
SELECT @QRY=@QRY + CHAR(13) +' SUM(ISNULL(SRPCS,0))SRPCS,SUM(ISNULL(SRGRSWT,0))SRGRSWT,SUM(ISNULL(SRNETWT,0))SRNETWT,SUM(ISNULL(SRTOTAL,0))SRTOTAL,'  
SELECT @QRY=@QRY + CHAR(13) +' SUM(ISNULL(CASH,0))CASH,SUM(ISNULL(CRCARD,0))CRCARD,SUM(ISNULL(CHIT,0))CHIT,SUM(ISNULL(CHEQUE,0))CHEQUE,SUM(ISNULL(ADVANCE,0))ADVANCE,SUM(ISNULL(CRBALANCE,0))CRBALANCE,SUM(ISNULL(ACTOTAL,0))ACTOTAL'  
SELECT @QRY=@QRY + CHAR(13) +' FROM '+@TEMPSALEABSTRACT+''  
SELECT @QRY=@QRY + CHAR(13) +' WHERE RESULT = 1'
SELECT @QRY=@QRY + CHAR(13) +' ORDER BY IBILLDATE'
END 
ELSE
BEGIN
SELECT @QRY='SELECT '  
SELECT @QRY=@QRY + CHAR(13) +' CUSTOMER AS PARTICULAR'  
SELECT @QRY=@QRY + CHAR(13) +' ,BATCHNO,IBILLDATE,IBILLNO,IITEMID,ITEMNAME,ITAGNO,IPCS,IGRSWT,INETWT,ITOTAL'  
SELECT @QRY=@QRY + CHAR(13) +' ,PBILLNO,PITEMID,PPCS,PGRSWT,PNETWT,PAMOUNT'  
SELECT @QRY=@QRY + CHAR(13) +' ,SRBILLNO,SRITEMID,SRPCS,SRGRSWT,SRNETWT,SRTOTAL'  
SELECT @QRY=@QRY + CHAR(13) +' ,CASH,CRCARD,CHIT,CHEQUE,ADVANCE,CRBALANCE,ACTOTAL,COLHEAD,RESULT'  
SELECT @QRY=@QRY + CHAR(13) +' FROM '+@TEMPSALEABSTRACT+''  
SELECT @QRY=@QRY + CHAR(13) +' ORDER BY COUNTERNAME,IBILLDATE,BATCHNO,RESULT,COLHEAD,ACTOTAL DESC'  
END
PRINT @QRY  
EXEC(@QRY)  
END
