ALTER PROCEDURE SP_RPT_TAGWISEPROFITLOSS  
(      
@FROMDATE SMALLDATETIME      
,@TODATE SMALLDATETIME      
,@COMPANYID VARCHAR(50)      
,@COSTNAME VARCHAR(500)      
,@METALNAME VARCHAR(500)     
,@GROUPBY VARCHAR(1) /** (N)ONE,(I)ITEMWISE **/      
)      
AS      
BEGIN     
IF OBJECT_ID('TEMPDB..#COMPANY', 'U') IS NOT NULL DROP TABLE #COMPANY      
CREATE TABLE #COMPANY (COMPANYID VARCHAR(3))      
DECLARE @TCOMPANY VARCHAR(50)    
IF CHARINDEX(',',@COMPANYID)=0      
 BEGIN      
 INSERT INTO #COMPANY (COMPANYID) SELECT @COMPANYID      
 END      
WHILE CHARINDEX(',',@COMPANYID)>0      
 BEGIN      
 SET @TCOMPANY=LEFT(@COMPANYID,CHARINDEX(',',@COMPANYID)-1)      
 SET @COMPANYID=RIGHT(@COMPANYID,LEN(@COMPANYID)-CHARINDEX(',',@COMPANYID))      
 IF @COMPANYID <>'' AND CHARINDEX(',',@COMPANYID)=0      
  BEGIN      
  SET @COMPANYID= @COMPANYID + ','      
  END      
 INSERT INTO #COMPANY (COMPANYID) SELECT @TCOMPANY      
 END      
  IF OBJECT_ID('TEMPDB..#METAL', 'U') IS NOT NULL DROP TABLE #METAL      
CREATE TABLE #METAL (METALID VARCHAR(1))      
DECLARE @TMETAL VARCHAR(50)      
IF @METALNAME = 'ALL' OR @METALNAME = ''    
BEGIN    
INSERT INTO #METAL(METALID) SELECT METALID FROM BMPADMINDB..METALMAST    
END    
ELSE    
  BEGIN    
 IF CHARINDEX(',',@METALNAME)=0      
  BEGIN      
  INSERT INTO #METAL (METALID) SELECT  (SELECT METALID FROM BMPADMINDB..METALMAST WHERE METALNAME = @METALNAME)      
  END      
 WHILE CHARINDEX(',',@METALNAME)>0      
  BEGIN      
  SET @TMETAL=LEFT(@METALNAME,CHARINDEX(',',@METALNAME)-1)      
  SET @METALNAME=RIGHT(@METALNAME,LEN(@METALNAME)-CHARINDEX(',',@METALNAME))      
  IF @METALNAME <>'' AND CHARINDEX(',',@METALNAME)=0      
   BEGIN      
   SET @METALNAME= @METALNAME + ','      
   END      
  INSERT INTO #METAL (METALID) SELECT  (SELECT METALID FROM BMPADMINDB..METALMAST WHERE METALNAME = @TMETAL)      
  END    
  END    
IF OBJECT_ID('TEMPDB..#COSTCENTRE', 'U') IS NOT NULL DROP TABLE #COSTCENTRE  
CREATE TABLE #COSTCENTRE (COSTID VARCHAR(3))      
IF (SELECT COUNT(*) FROM BMPADMINDB..COSTCENTRE) > 0      
 BEGIN      
 DECLARE @TEMPNAME VARCHAR(20)  
 IF CHARINDEX(',',@COSTNAME)=0  
  BEGIN  
  INSERT INTO #COSTCENTRE (COSTID) SELECT (SELECT COSTID FROM BMPADMINDB..COSTCENTRE WHERE COSTNAME = @COSTNAME)      
  END  
 WHILE CHARINDEX(',',@COSTNAME)>0  
  BEGIN  
  SET @TEMPNAME=LEFT(@COSTNAME,CHARINDEX(',',@COSTNAME)-1)  
  SET @COSTNAME=RIGHT(@COSTNAME,LEN(@COSTNAME)-CHARINDEX(',',@COSTNAME))  
  IF @COSTNAME <>'' AND CHARINDEX(',',@COSTNAME)=0  
   BEGIN  
   SET @COSTNAME= @COSTNAME + ','  
   END  
  INSERT INTO #COSTCENTRE (COSTID) SELECT (SELECT COSTID FROM BMPADMINDB..COSTCENTRE WHERE COSTNAME = @TEMPNAME)      
  END      
 END      
ELSE      
 INSERT INTO #COSTCENTRE(COSTID) SELECT '' COSTID      
IF OBJECT_ID('TEMPDB..#TAGWISEPROFITLOSS', 'U') IS NOT NULL DROP TABLE #TAGWISEPROFITLOSS      
SELECT       
CONVERT(VARCHAR(50),NULL)AS PARTICULAR      
,(SELECT SUBITEMNAME FROM BMPADMINDB..SUBITEMMAST WHERE SUBITEMID = T.SUBITEMID AND ITEMID=T.ITEMID)AS SUBITEM      
,I.TRANDATE AS TRANDATE,I.TRANNO AS TRANNO      
,T.TAGNO,I.PCS,I.GRSWT,I.NETWT      
,(SELECT SUM(STNPCS) FROM ISSSTONE WHERE ISSSNO = I.SNO AND STNITEMID IN (SELECT ITEMID FROM BMPADMINDB..ITEMMAST WHERE DIASTONE = 'D')) AS DIAPCS  
,(SELECT SUM(STNWT) FROM ISSSTONE WHERE ISSSNO = I.SNO AND STNITEMID IN (SELECT ITEMID FROM BMPADMINDB..ITEMMAST WHERE DIASTONE = 'D')) AS DIAWT  
,(SELECT SUM(STNAMT) FROM ISSSTONE WHERE ISSSNO = I.SNO AND STNITEMID IN (SELECT ITEMID FROM BMPADMINDB..ITEMMAST WHERE DIASTONE = 'D')) AS DIAAMT  
,I.TAGSVALUE AS TAGVALUE,I.FIN_DISCOUNT AS DISCOUNT,CONVERT(DECIMAL(15,2),CASE WHEN ISNULL(I.TAGSVALUE,0)<>0 THEN (I.FIN_DISCOUNT/(I.TAGSVALUE/100)) ELSE 0 END)AS [DISC%]      
,I.TAX AS GST,CONVERT(DECIMAL(15,2),CASE WHEN ISNULL(I.AMOUNT,0)<>0 THEN (I.TAX/(I.AMOUNT/100)) ELSE 0 END) AS [GST%]      
,I.AMOUNT AS SALVALUE,(I.TAX + I.AMOUNT)TOT_SALVAL,CONVERT(VARCHAR(50),D.DESIGNERNAME) AS SUPPLIER    
/*,(P.PURVALUE-P.PURTAX ) AS PURVALUE      
,I.AMOUNT-(P.PURVALUE -P.PURTAX) AS DIFFVALUE*/      
,P.PURTAX PURGST
,CASE WHEN I.TAGGRSWT>I.GRSWT THEN (CASE WHEN I.GRSNET='G' THEN ((I.GRSWT+P.PURWASTAGE)*P.PURRATE)+PURMC ELSE ((I.NETWT+P.PURWASTAGE)*P.PURRATE)+PURMC END)       
ELSE (P.PURVALUE-P.PURTAX ) END AS PURVALUE
,(P.PURTAX+(CASE WHEN I.TAGGRSWT>I.GRSWT THEN (CASE WHEN I.GRSNET='G' THEN ((I.GRSWT+P.PURWASTAGE)*P.PURRATE)+PURMC ELSE ((I.NETWT+P.PURWASTAGE)*P.PURRATE)+PURMC END)ELSE (P.PURVALUE-P.PURTAX)END))TOT_PURVAL
,I.AMOUNT-CASE WHEN I.TAGGRSWT>I.GRSWT THEN  (CASE WHEN I.GRSNET='G' THEN ((I.GRSWT+P.PURWASTAGE)*P.PURRATE)+PURMC ELSE ((I.NETWT+P.PURWASTAGE)*P.PURRATE)+PURMC END)       
ELSE (P.PURVALUE-P.PURTAX ) END AS DIFFVALUE
,((I.TAX + I.AMOUNT)-(P.PURTAX+(CASE WHEN I.TAGGRSWT>I.GRSWT THEN (CASE WHEN I.GRSNET='G' THEN ((I.GRSWT+P.PURWASTAGE)*P.PURRATE)+PURMC ELSE ((I.NETWT+P.PURWASTAGE)*P.PURRATE)+PURMC END)ELSE (P.PURVALUE-P.PURTAX)END))) TOT_DIFF
,CONVERT(DECIMAL(15,2),CASE WHEN ISNULL(I.AMOUNT,0)<>0 THEN ((I.AMOUNT-(P.PURVALUE -P.PURTAX))/(I.AMOUNT/100)) ELSE 0 END) AS [DIFF%]      
,CONVERT(INT,1)AS RESULT      
,CONVERT(VARCHAR(1),'')COLHEAD      
,(SELECT ITEMNAME FROM BMPADMINDB..ITEMMAST WHERE ITEMID = T.ITEMID)AS ITEM      
INTO #TAGWISEPROFITLOSS      
FROM ISSUE I      
INNER JOIN BMPADMINDB..ITEMTAG T ON T.TAGNO=I.TAGNO AND T.ITEMID=I.ITEMID AND T.BATCHNO = I.BATCHNO      
LEFT OUTER JOIN BMPADMINDB..PURITEMTAG P ON P.TAGSNO = T.SNO      
INNER JOIN BMPADMINDB..DESIGNER D ON D.DESIGNERID=I.TAGDESIGNER      
WHERE I.TRANDATE BETWEEN @FROMDATE AND @TODATE AND I.TRANTYPE='SA'      
AND I.COMPANYID IN (SELECT COMPANYID FROM #COMPANY)      
AND ISNULL(I.COSTID,'') IN (SELECT COSTID FROM #COSTCENTRE)     
AND ISNULL(I.METALID,'') IN (SELECT METALID FROM #METAL)     
IF (SELECT COUNT(*) FROM #TAGWISEPROFITLOSS WHERE RESULT = 1) > 0      
BEGIN      
INSERT INTO #TAGWISEPROFITLOSS(PARTICULAR,ITEM,PCS,GRSWT,NETWT,TAGVALUE,DISCOUNT,GST,SALVALUE,TOT_SALVAL,PURGST,PURVALUE,TOT_PURVAL,DIFFVALUE,TOT_DIFF,RESULT,COLHEAD)      
SELECT 'GRAND TOTAL' AS PARTICULAR,'ZZZZZ'ITEM,SUM(PCS),SUM(GRSWT),SUM(NETWT),SUM(TAGVALUE),SUM(DISCOUNT),SUM(GST),SUM(SALVALUE),SUM(TOT_SALVAL),SUM(PURGST),SUM(PURVALUE),SUM(TOT_PURVAL),SUM(DIFFVALUE),SUM(TOT_DIFF)      
,3 RESULT,'G'COLHEAD      
FROM #TAGWISEPROFITLOSS WHERE RESULT = 1      
END      
IF @GROUPBY = 'I' /** ITEM WISE GROUPING **/      
 BEGIN      
 IF (SELECT COUNT(*) FROM #TAGWISEPROFITLOSS WHERE RESULT = 1) > 0      
  BEGIN      
  /**INSERTING TITLE **/      
  INSERT INTO #TAGWISEPROFITLOSS(PARTICULAR,ITEM,RESULT,COLHEAD)      
  SELECT DISTINCT ITEM,ITEM,0 RESULT,'T' COLHEAD FROM #TAGWISEPROFITLOSS WHERE RESULT = 1      
  /**INSERTING ITEMWISE SUBTOTAL **/      
  INSERT INTO #TAGWISEPROFITLOSS(PARTICULAR,ITEM,RESULT,COLHEAD,PCS,GRSWT,NETWT,TAGVALUE,DISCOUNT,GST,SALVALUE,TOT_SALVAL,PURGST,PURVALUE,TOT_PURVAL,DIFFVALUE,TOT_DIFF)      
  SELECT '-> SUB TOTAL' AS PARTICULAR,ITEM,2 RESULT,'S'COLHEAD,SUM(PCS),SUM(GRSWT),SUM(NETWT),SUM(TAGVALUE),SUM(DISCOUNT),SUM(GST),SUM(SALVALUE),SUM(TOT_SALVAL),SUM(PURGST),SUM(PURVALUE),SUM(TOT_PURVAL),SUM(DIFFVALUE),SUM(TOT_DIFF)      
  FROM #TAGWISEPROFITLOSS WHERE RESULT = 1 GROUP BY ITEM      
  UPDATE #TAGWISEPROFITLOSS SET PARTICULAR = CASE WHEN ISNULL(SUBITEM,'') <> '' THEN '  ' + SUBITEM ELSE ITEM END WHERE RESULT = 1      
  END      
 END      
ELSE IF @GROUPBY = 'N' /** GROUP BY NONE **/      
 BEGIN      
 UPDATE #TAGWISEPROFITLOSS SET PARTICULAR = ITEM WHERE RESULT = 1      
 END      
UPDATE #TAGWISEPROFITLOSS SET PURVALUE = NULL WHERE PURVALUE = 0      
UPDATE #TAGWISEPROFITLOSS SET DIFFVALUE = NULL WHERE DIFFVALUE = 0      
IF (SELECT TOP 1 1 FROM MASTER..SYSOBJECTS WHERE NAME = 'TEMP_TAGWISEPROFITLOSS')>0 DROP TABLE MASTER..TEMP_TAGWISEPROFITLOSS      
IF @GROUPBY = 'I'      
 SELECT *,IDENTITY(INT,0,1)AS KEYNO INTO MASTER..TEMP_TAGWISEPROFITLOSS FROM #TAGWISEPROFITLOSS ORDER BY ITEM,RESULT,TRANDATE,TRANNO      
ELSE IF @GROUPBY = 'N'      
 SELECT *,IDENTITY(INT,0,1)AS KEYNO INTO MASTER..TEMP_TAGWISEPROFITLOSS FROM #TAGWISEPROFITLOSS ORDER BY RESULT,TRANDATE,TRANNO      
SELECT * FROM MASTER..TEMP_TAGWISEPROFITLOSS ORDER BY KEYNO      
END