 
  alter PROCEDURE [dbo].[SP_RPT_RANGEWISESTOCK]  
 (  
 @TEMPTABLE VARCHAR(30)  
 ,@ASONDATE VARCHAR(15)  
 ,@COMPANYID VARCHAR(1000)  
 ,@COSTID VARCHAR(1000)  
 ,@METALID VARCHAR(1000)  
 ,@ITEMID VARCHAR(1000)  
 ,@SUBITEMID VARCHAR(1000)  
 ,@DESIGNERID VARCHAR(1000)  
 ,@WITHCUM VARCHAR(1)  
 ,@STKTYPE VARCHAR(1)  
 ,@BASEDON VARCHAR(1)  
 ,@DISPTYPE VARCHAR(1)  
 ,@COUNTERIDS VARCHAR(1000)  
 ,@RPTTYPE VARCHAR(1)  
 ,@WITHOUTESTK VARCHAR(1)  
 )  
 AS  
 BEGIN  
  SET NOCOUNT ON  
  DECLARE @QRY AS VARCHAR(7000)  
  DECLARE @DATEFILTER AS VARCHAR(1000)  
  DECLARE @METALFILTER AS VARCHAR(1000)  
  DECLARE @COMFILTER AS VARCHAR(1000)  
  DECLARE @COSTFILTER AS VARCHAR(1000)  
  DECLARE @ITEMFILTER AS VARCHAR(1000)  
  DECLARE @ITEMFILTER1 AS VARCHAR(1000)  
  DECLARE @SUBITEMFILTER AS VARCHAR(1000)  
  DECLARE @DESIGNFILTER AS VARCHAR(1000)  
  DECLARE @COUNTERFILTER AS VARCHAR(1000)  
  DECLARE @BASECOL AS VARCHAR(500)  
  DECLARE @BASENAME AS VARCHAR(500)  
  SET @QRY =''  
  SET @DATEFILTER =''    
  SET @METALFILTER =''    
  SET @COMFILTER =''    
  SET @COSTFILTER =''    
  SET @ITEMFILTER =''   
  SET @ITEMFILTER1 =''    
  SET @SUBITEMFILTER =''       
  SET @DESIGNFILTER =''    
  SET @COUNTERFILTER =''    
  SET @BASECOL =''    
  SET @BASENAME =''    
    DECLARE @SPECIFICFORMAT AS VARCHAR(5)  
    SET @SPECIFICFORMAT ='0'  
    SELECT @SPECIFICFORMAT = ISNULL(CTLTEXT,0) FROM SOFTCONTROL WHERE CTLID ='SPECIFICFORMAT'   
  IF @BASEDON='I'  
  BEGIN  
   SET @BASECOL ='ITEMID'    
   SET @BASENAME ='ITEMNAME'    
  END  
  IF @BASEDON='D'  
  BEGIN  
   SET @BASECOL ='DESIGNERID'    
   SET @BASENAME ='DESIGNERNAME'    
  END      
    SET @ITEMFILTER ='AND A.ITEMID IN(SELECT ITEMID FROM ITEMMAST WHERE ISNULL(STOCKREPORT,'''')=''Y'' AND ISNULL(ACTIVE,'''')=''Y'' '    
    SET @ITEMFILTER1 ='AND A.SUBITEMID IN(SELECT SUBITEMID FROM ITEMMAST WHERE ISNULL(STOCKREPORT,'''')=''Y'' AND ISNULL(ACTIVE,'''')=''Y'' '    
  IF @SUBITEMID <>'ALL'  SELECT @SUBITEMFILTER =@SUBITEMFILTER+ ' AND A.SUBITEMID IN (' + @SUBITEMID + ')'   
  SELECT @ITEMFILTER = @ITEMFILTER +' )'    
  SELECT @ITEMFILTER1 = @ITEMFILTER1 +' )'    
  IF @ITEMID <>'ALL'SET @ITEMFILTER = @ITEMFILTER+' AND A.ITEMID IN (' + @ITEMID + ')'   
  IF @ITEMID <>'ALL'SET @ITEMFILTER1 = @ITEMFILTER1+' AND A.ITEMID IN (' + @ITEMID + ')'   
  IF @COSTID <>'ALL' SET @COSTFILTER = ' AND A.COSTID IN (' + @COSTID+ ')'   
  IF @METALID <>'ALL' SET @METALFILTER = ' AND I.METALID IN (' + @METALID+ ')'              
  IF @COMPANYID<>'ALL' SELECT @COMFILTER = ' AND A.COMPANYID IN (' + @COMPANYID + ')'       
  IF @DESIGNERID <>'ALL' SELECT @DESIGNFILTER = ' AND A.DESIGNERID IN (' + @DESIGNERID + ')'   
  IF @COUNTERIDS <>'ALL'SET @COUNTERFILTER = @COUNTERFILTER+' AND A.ITEMCTRID IN (' + @COUNTERIDS + ')'   
  SELECT @QRY=' IF OBJECT_ID('''+ @TEMPTABLE+''',''U'')IS NOT NULL DROP TABLE '+ @TEMPTABLE    
  SELECT @QRY= @QRY+ ' IF OBJECT_ID('''+ @TEMPTABLE+'_RES'',''U'')IS NOT NULL DROP TABLE '+ @TEMPTABLE+'_RES'    
    PRINT (@QRY)  
  EXEC(@QRY)        
  SELECT @QRY = ' SELECT * INTO '+@TEMPTABLE +' FROM ('   
  IF @STKTYPE='B' OR @STKTYPE='T'    
  BEGIN    
   SELECT @QRY = @QRY + ' SELECT  CONVERT(DECIMAL(15,3),0.000) FROMWEIGHT ,CONVERT(DECIMAL(15,3),0.000) TOWEIGHT,CONVERT(VARCHAR(20),NULL) CAPTION,A.COSTID,I.METALID,A.'+@BASECOL+',A.SUBITEMID,A.TAGNO,A.PCS,A.GRSWT'  
   IF @BASEDON='D' SELECT @QRY=@QRY+ ' ,A.ITEMID'  
   SELECT @QRY=@QRY+ ' FROM ITEMTAG AS A'    
   SELECT @QRY = @QRY + ' LEFT JOIN ITEMMAST AS I ON I.ITEMID = A.ITEMID  '      
   SELECT @QRY = @QRY + ' WHERE RECDATE < '''+@ASONDATE +''' AND (ISSDATE IS NULL OR ISSDATE >= ''' +@ASONDATE+''') '  
   SELECT @QRY = @QRY + @COMFILTER +' '+ @COSTFILTER +' '+@METALFILTER+ ' '+@ITEMFILTER  +' '+@SUBITEMFILTER +' '+ @COUNTERFILTER   
   IF @WITHCUM ='Y'    
   BEGIN    
    SELECT @QRY = @QRY + ' UNION ALL '   
    SELECT @QRY = @QRY + ' SELECT CONVERT(DECIMAL(15,3),0.000) FROMWEIGHT ,CONVERT(DECIMAL(15,3),0.000) TOWEIGHT,CONVERT(VARCHAR(20),NULL) CAPTION,A.COSTID,I.METALID,A.'+@BASECOL+',A.SUBITEMID,A.TAGNO,A.PCS,A.GRSWT'  
    IF @BASEDON='D' SELECT @QRY=@QRY+ ' ,A.ITEMID'  
       SELECT @QRY=@QRY+ ' FROM ITEMTAG AS A'     
    SELECT @QRY = @QRY + ' LEFT JOIN ITEMMAST AS I ON I.ITEMID = A.ITEMID  '     
    SELECT @QRY = @QRY + ' WHERE RECDATE < '''+@ASONDATE +''' AND (ISSDATE IS NULL OR ISSDATE >= ''' +@ASONDATE+''')'  
    SELECT @QRY = @QRY + ' AND A.TAGNO NOT IN(SELECT TAGNO FROM ITEMTAG)'    
    SELECT @QRY = @QRY + @COMFILTER +' '+ @COSTFILTER +' '+@METALFILTER+ ' '+@ITEMFILTER +' '+@SUBITEMFILTER +' '+ @COUNTERFILTER   
   END    
  END        
  IF @STKTYPE='B' OR @STKTYPE='N'    
  BEGIN    
   IF @STKTYPE='B' SELECT @QRY = @QRY + ' UNION ALL '   
   SELECT @QRY = @QRY + ' SELECT CONVERT(DECIMAL(15,3),0.000) FROMWEIGHT ,CONVERT(DECIMAL(15,3),0.000) TOWEIGHT,CONVERT(VARCHAR(20),NULL) CAPTION,A.COSTID,I.METALID,A.'+@BASECOL+',A.SUBITEMID,''''TAGNO,CASE WHEN RECISS=''I'' THEN A.PCS*(-1)ELSE A.PCS END 
PCS'      
   SELECT @QRY = @QRY + ' ,CASE WHEN RECISS=''I'' THEN A.GRSWT *(-1) ELSE A.GRSWT END GRSWT'  
   IF @BASEDON='D' SELECT @QRY=@QRY+ ' ,A.ITEMID'  
   SELECT @QRY=@QRY+ ' FROM ITEMNONTAG AS A'    
   SELECT @QRY = @QRY + ' LEFT JOIN ITEMMAST AS I ON I.ITEMID = A.ITEMID  '    
   SELECT @QRY = @QRY + ' WHERE RECDATE < '''+@ASONDATE +''''  
   SELECT @QRY = @QRY + @COMFILTER +' '+ @COSTFILTER +' '+@METALFILTER+ ' '+@ITEMFILTER  +' '+@SUBITEMFILTER +' '+ @COUNTERFILTER   
  END    
  SELECT @QRY = @QRY +' )X'       
  PRINT (@QRY)  
  EXEC(@QRY)       
  IF @BASEDON='I'  
    BEGIN   
       SELECT @QRY = ' IF (SELECT COUNT(*) FROM TEMPTABLEDB..SYSOBJECTS WHERE NAME = ''TEMPRANGEFILTER'') > 0 DROP TABLE TEMPTABLEDB..TEMPRANGEFILTER'    
          EXEC(@QRY)   
    PRINT '###########1'      
    PRINT @QRY  
            SELECT @QRY = 'SELECT * INTO TEMPTABLEDB..TEMPRANGEFILTER FROM'    
            SELECT @QRY = @QRY + ' TEMPTABLEDB..TEMPRANGEWISE'  
            SELECT @QRY = @QRY + ' WHERE ITEMID IN(SELECT ITEMID FROM RANGEMAST)'   
            SELECT @QRY = @QRY + ' AND SUBITEMID IN (SELECT SUBITEMID FROM RANGEMAST)'  
    PRINT '###########2'      
    PRINT @QRY  
            EXEC(@QRY)  
    SELECT @QRY = ' IF (SELECT COUNT(*) FROM TEMPTABLEDB..SYSOBJECTS WHERE NAME = ''TEMPRANGEWISE'') > 0 DROP TABLE TEMPTABLEDB..TEMPRANGEWISE'   
    PRINT '###########3'      
    PRINT @QRY  
    EXEC(@QRY)   
    SELECT @QRY = 'SELECT * INTO TEMPTABLEDB..TEMPRANGEWISE FROM TEMPTABLEDB..TEMPRANGEFILTER'  
            PRINT '###########4'    
    PRINT @QRY  
    EXEC(@QRY)  
    SELECT @QRY = ' UPDATE TT SET TT.FROMWEIGHT=T.FROMWEIGHT,TT.TOWEIGHT=T.TOWEIGHT,TT.CAPTION=R.CAPTION FROM TEMPTABLEDB..TEMPRANGEWISE TT,TEMPTABLEDB..TEMPSELECTRANGE T,RANGEMAST R  '   
    SELECT @QRY = @QRY+ ' WHERE TT.GRSWT BETWEEN T.FROMWEIGHT AND T.TOWEIGHT'  
    SELECT @QRY = @QRY+ ' AND TT.GRSWT BETWEEN R.FROMWEIGHT AND R.TOWEIGHT'  
    SELECT @QRY = @QRY+ ' AND T.FROMWEIGHT=R.FROMWEIGHT  AND T.TOWEIGHT =R.TOWEIGHT'  
    IF @BASEDON='I' SELECT @QRY = @QRY+ ' AND TT.ITEMID=R.ITEMID AND TT.SUBITEMID=R.SUBITEMID '  
    IF @BASEDON='I' SELECT @QRY = @QRY+ ' AND TT.'+@BASECOL+'=R.'+@BASECOL  
    SELECT @QRY = @QRY+ ' AND TT.COSTID=R.COSTID'   
    PRINT '###########5'      
    PRINT @QRY   
    EXEC(@QRY)    
    SELECT @QRY='UPDATE TT SET TT.CAPTION=''OTHERE'' FROM TEMPTABLEDB..TEMPRANGEWISE TT WHERE ISNULL(TT.CAPTION,'''')='''''  
    PRINT @QRY   
    EXEC(@QRY)  
    SELECT @QRY = ' IF (SELECT COUNT(*) FROM TEMPTABLEDB..SYSOBJECTS WHERE NAME = ''TEMPRANGEFILTER'') > 0 DROP TABLE TEMPTABLEDB..TEMPRANGEFILTER'   
    PRINT '###########6'      
    PRINT @QRY  
    EXEC(@QRY)   
    SELECT @QRY = 'SELECT * INTO TEMPTABLEDB..TEMPRANGEFILTER FROM TEMPTABLEDB..TEMPRANGEWISE WHERE ISNULL(CAPTION,'''')=CAPTION'  
            PRINT '###########7'    
    PRINT @QRY  
    EXEC(@QRY)  
    SELECT @QRY = ' IF (SELECT COUNT(*) FROM TEMPTABLEDB..SYSOBJECTS WHERE NAME = ''TEMPRANGEWISE'') > 0 DROP TABLE TEMPTABLEDB..TEMPRANGEWISE'   
    PRINT '###########8'      
    PRINT @QRY  
    EXEC(@QRY)   
    SELECT @QRY = 'SELECT * INTO TEMPTABLEDB..TEMPRANGEWISE FROM TEMPTABLEDB..TEMPRANGEFILTER'  
            PRINT '###########9'    
    PRINT @QRY  
    EXEC(@QRY)  
   IF @ITEMID='ALL' AND @SUBITEMID='ALL' AND @METALID='ALL'   
   BEGIN  
    SELECT @QRY = ' INSERT INTO  TEMPTABLEDB..TEMPRANGEWISE(FROMWEIGHT,TOWEIGHT,CAPTION,METALID,ITEMID,SUBITEMID,TAGNO,PCS,GRSWT,COSTID)'  
    SELECT @QRY = @QRY+ ' SELECT CONVERT(DECIMAL(15,3),0.000) FROMWEIGHT,CONVERT(DECIMAL(15,3),0.000) TOWEIGHT,CAPTION,'  
            SELECT @QRY = @QRY+ ' (SELECT METALID FROM ITEMMAST WHERE ITEMID=T.ITEMID)AS METALID,'  
            SELECT @QRY = @QRY+ ' ITEMID,SUBITEMID,''0'' TAGNO,0 PCS,0 GRSWT,COSTID FROM RANGEMAST T'  
            SELECT @QRY = @QRY+ ' WHERE NOT EXISTS(SELECT 1 FROM TEMPTABLEDB..TEMPRANGEWISE '  
            SELECT @QRY = @QRY+ ' WHERE CAPTION=T.CAPTION AND ITEMID=T.ITEMID AND SUBITEMID=T.SUBITEMID)'  
    PRINT @QRY   
    EXEC(@QRY)     
   END  
   PRINT 'ITEMID'+@ITEMID   
   IF @ITEMID<>'ALL'   
   /*PRINT 'ITEMIDCHECK'+@ITEMID+'  '+@ITEMFILTER1+' 1244 '+@SUBITEMFILTER*/  
   BEGIN       
    SELECT @QRY = ' INSERT INTO  TEMPTABLEDB..TEMPRANGEWISE(FROMWEIGHT,TOWEIGHT,CAPTION,METALID,ITEMID,SUBITEMID,TAGNO,PCS,GRSWT,COSTID)'  
    SELECT @QRY = @QRY+ ' SELECT CONVERT(DECIMAL(15,3),0.000) FROMWEIGHT,CONVERT(DECIMAL(15,3),0.000) TOWEIGHT,CAPTION,'  
          SELECT @QRY = @QRY+ ' (SELECT METALID FROM ITEMMAST WHERE ITEMID=A.ITEMID)AS METALID,'  
          SELECT @QRY = @QRY+ ' ITEMID,SUBITEMID,''0'' TAGNO,0 PCS,0 GRSWT,COSTID FROM RANGEMAST A'  
          SELECT @QRY = @QRY+ ' WHERE NOT EXISTS(SELECT 1 FROM TEMPTABLEDB..TEMPRANGEWISE '  
          SELECT @QRY = @QRY+ ' WHERE CAPTION=A.CAPTION ' +@ITEMFILTER1  +')'  
          IF  @ITEMID<>'ALL' SELECT @QRY = @QRY+  ' AND A.ITEMID IN (' + @ITEMID + ')' +@SUBITEMFILTER +''  
    PRINT @QRY   
    EXEC(@QRY)    
   END  
   END  
   IF @BASEDON='D'  
     BEGIN   
       SELECT @QRY = ' IF (SELECT COUNT(*) FROM TEMPTABLEDB..SYSOBJECTS WHERE NAME = ''TEMPRANGEFILTER'') > 0 DROP TABLE TEMPTABLEDB..TEMPRANGEFILTER'    
          EXEC(@QRY)   
    PRINT '###########D1'      
    PRINT @QRY  
            SELECT @QRY = 'SELECT * INTO TEMPTABLEDB..TEMPRANGEFILTER FROM'    
            SELECT @QRY = @QRY + ' TEMPTABLEDB..TEMPRANGEWISE'  
            SELECT @QRY = @QRY + ' WHERE SUBITEMID IN (SELECT SUBITEMID FROM RANGEMAST)'  
    PRINT '###########2'      
    PRINT @QRY  
            EXEC(@QRY)  
    SELECT @QRY = ' IF (SELECT COUNT(*) FROM TEMPTABLEDB..SYSOBJECTS WHERE NAME = ''TEMPRANGEWISE'') > 0 DROP TABLE TEMPTABLEDB..TEMPRANGEWISE'   
    PRINT '###########3'      
    PRINT @QRY  
    EXEC(@QRY)   
    SELECT @QRY = 'SELECT * INTO TEMPTABLEDB..TEMPRANGEWISE FROM TEMPTABLEDB..TEMPRANGEFILTER'  
            PRINT '###########4'    
    PRINT @QRY  
    EXEC(@QRY)  
    SELECT @QRY = ' UPDATE TT SET TT.FROMWEIGHT=T.FROMWEIGHT,TT.TOWEIGHT=T.TOWEIGHT,TT.CAPTION=R.CAPTION FROM TEMPTABLEDB..TEMPRANGEWISE TT,TEMPTABLEDB..TEMPSELECTRANGE T,RANGEMAST R  '   
    SELECT @QRY = @QRY+ ' WHERE TT.GRSWT BETWEEN T.FROMWEIGHT AND T.TOWEIGHT'  
    SELECT @QRY = @QRY+ ' AND TT.GRSWT BETWEEN R.FROMWEIGHT AND R.TOWEIGHT'  
    SELECT @QRY = @QRY+ ' AND T.FROMWEIGHT=R.FROMWEIGHT  AND T.TOWEIGHT =R.TOWEIGHT'  
    IF @BASEDON='I' SELECT @QRY = @QRY+ ' AND  TT.SUBITEMID=R.SUBITEMID '  
    IF @BASEDON='I' SELECT @QRY = @QRY+ ' AND TT.'+@BASECOL+'=R.'+@BASECOL  
    SELECT @QRY = @QRY+ ' AND TT.COSTID=R.COSTID'   
    PRINT '###########5'      
    PRINT @QRY   
    EXEC(@QRY)  
    SELECT @QRY='UPDATE TT SET TT.CAPTION=''OTHERE'' FROM TEMPTABLEDB..TEMPRANGEWISE TT WHERE ISNULL(TT.CAPTION,'''')='''''  
    PRINT @QRY   
    EXEC(@QRY)  
    SELECT @QRY = ' IF (SELECT COUNT(*) FROM TEMPTABLEDB..SYSOBJECTS WHERE NAME = ''TEMPRANGEFILTER'') > 0 DROP TABLE TEMPTABLEDB..TEMPRANGEFILTER'   
    PRINT '###########5'      
    PRINT @QRY  
    EXEC(@QRY)   
    SELECT @QRY = 'SELECT * INTO TEMPTABLEDB..TEMPRANGEFILTER FROM TEMPTABLEDB..TEMPRANGEWISE'  
            PRINT '###########6'    
    PRINT @QRY  
    EXEC(@QRY)  
    SELECT @QRY = ' IF (SELECT COUNT(*) FROM TEMPTABLEDB..SYSOBJECTS WHERE NAME = ''TEMPRANGEWISE'') > 0 DROP TABLE TEMPTABLEDB..TEMPRANGEWISE'   
    PRINT '###########7'      
    PRINT @QRY  
    EXEC(@QRY)   
    SELECT @QRY = 'SELECT * INTO TEMPTABLEDB..TEMPRANGEWISE FROM TEMPTABLEDB..TEMPRANGEFILTER'  
            PRINT '###########'    
    PRINT @QRY  
    EXEC(@QRY)  
   IF @ITEMID='ALL' AND @SUBITEMID='ALL'    
   BEGIN  
    SELECT @QRY = ' INSERT INTO  TEMPTABLEDB..TEMPRANGEWISE(FROMWEIGHT,TOWEIGHT,CAPTION,METALID,DESIGNERID,SUBITEMID,TAGNO,PCS,GRSWT,COSTID)'  
    SELECT @QRY = @QRY+ ' SELECT CONVERT(DECIMAL(15,3),0.000) FROMWEIGHT,CONVERT(DECIMAL(15,3),0.000) TOWEIGHT,CAPTION,'  
            SELECT @QRY = @QRY+ ' (SELECT METALID FROM ITEMMAST WHERE ITEMID=T.ITEMID)AS METALID,'  
            SELECT @QRY = @QRY+ ' 0 DESINGERID,SUBITEMID,''0'' TAGNO,0 PCS,0 GRSWT,COSTID FROM RANGEMAST T'  
            SELECT @QRY = @QRY+ ' WHERE NOT EXISTS(SELECT 1 FROM TEMPTABLEDB..TEMPRANGEWISE '  
            SELECT @QRY = @QRY+ ' WHERE CAPTION=T.CAPTION  AND SUBITEMID=T.SUBITEMID)'  
    PRINT @QRY   
    EXEC(@QRY)     
   END  
  ELSE IF @ITEMID='ALL'  
  BEGIN  
   SELECT @QRY = ' INSERT INTO  TEMPTABLEDB..TEMPRANGEWISE(FROMWEIGHT,TOWEIGHT,CAPTION,METALID,DESIGNERID,SUBITEMID,TAGNO,PCS,GRSWT,COSTID)'  
   SELECT @QRY = @QRY+ ' SELECT CONVERT(DECIMAL(15,3),0.000) FROMWEIGHT,CONVERT(DECIMAL(15,3),0.000) TOWEIGHT,CAPTION,'  
        SELECT @QRY = @QRY+ ' (SELECT METALID FROM ITEMMAST WHERE ITEMID=T.ITEMID)AS METALID,'  
        SELECT @QRY = @QRY+ ' 0 DESINGERID,SUBITEMID,''0'' TAGNO,0 PCS,0 GRSWT,COSTID FROM RANGEMAST T'  
        SELECT @QRY = @QRY+ ' WHERE NOT EXISTS(SELECT 1 FROM TEMPTABLEDB..TEMPRANGEWISE '  
        SELECT @QRY = @QRY+ ' WHERE CAPTION=T.CAPTION  AND SUBITEMID=T.SUBITEMID)'  
   PRINT @QRY   
   EXEC(@QRY)     
  END  
  IF @SUBITEMID='ALL'  
  BEGIN  
        SELECT @QRY = ' INSERT INTO  TEMPTABLEDB..TEMPRANGEWISE(FROMWEIGHT,TOWEIGHT,CAPTION,METALID,DESIGNERID,SUBITEMID,TAGNO,PCS,GRSWT,COSTID)'  
   SELECT @QRY = @QRY+ ' SELECT CONVERT(DECIMAL(15,3),0.000) FROMWEIGHT,CONVERT(DECIMAL(15,3),0.000) TOWEIGHT,CAPTION,'  
        SELECT @QRY = @QRY+ ' (SELECT METALID FROM ITEMMAST WHERE ITEMID=T.ITEMID)AS METALID,'  
        SELECT @QRY = @QRY+ ' 0 DESINGERID,SUBITEMID,''0'' TAGNO,0 PCS,0 GRSWT,COSTID FROM RANGEMAST T'  
        SELECT @QRY = @QRY+ ' WHERE NOT EXISTS(SELECT 1 FROM TEMPTABLEDB..TEMPRANGEWISE '  
        SELECT @QRY = @QRY+ ' WHERE CAPTION=T.CAPTION  AND SUBITEMID=T.SUBITEMID)'  
      PRINT @QRY   
      EXEC(@QRY)     
  END          
 END  
  IF @DISPTYPE='H'  
  BEGIN   
   print '!!!!!!!!!!!START'+@DISPTYPE  
   SELECT @QRY = ' ALTER TABLE '+@TEMPTABLE +' ADD IITEMID INT'  
   PRINT @QRY  
   EXEC(@QRY)  
   SELECT @QRY = ' UPDATE '+@TEMPTABLE +' SET IITEMID='+ @BASECOL +''  
   PRINT @QRY  
   EXEC(@QRY)  
   SELECT @QRY = ' IF OBJECT_ID('''+@TEMPTABLE +'_1'',''U'')IS NOT NULL DROP TABLE '+@TEMPTABLE +'_1'  
   SELECT @QRY = @QRY + ' SELECT COUNT(IITEMID) CNT,IITEMID INTO '+@TEMPTABLE +'_1  FROM ( SELECT DISTINCT FROMWEIGHT,TOWEIGHT,IITEMID FROM '+@TEMPTABLE +' WHERE ISNULL(FROMWEIGHT,0)<>0 AND ISNULL(TOWEIGHT,0)<>0'  
   SELECT @QRY = @QRY + ' )X GROUP BY IITEMID'  
   PRINT @QRY  
   EXEC(@QRY)  
   SELECT @QRY = ' SELECT CONVERT(VARCHAR(50),SUBITEMNAME) PARTICULAR,'+@BASENAME+',SUBITEMNAME,METALNAME,A.METALID,A.'+@BASECOL+',A.SUBITEMID,C.COSTNAME,C.COSTID'  
   SELECT @QRY =@QRY+',''DD''COLHEAD,3 RESULT INTO '+@TEMPTABLE+'_RES FROM '+@TEMPTABLE +' A'     
   IF @BASEDON='I' SELECT @QRY = @QRY+ ' LEFT JOIN ITEMMAST I ON I.ITEMID=A.ITEMID  '    
   IF @BASEDON='D' SELECT @QRY = @QRY+ ' LEFT JOIN DESIGNER I ON I.DESIGNERID=A.DESIGNERID  '    
   SELECT @QRY = @QRY+ ' LEFT JOIN SUBITEMMAST SI ON SI.SUBITEMID=A.SUBITEMID  '    
   SELECT @QRY = @QRY+ ' LEFT JOIN METALMAST M ON M.METALID=A.METALID  '    
   SELECT @QRY = @QRY+ ' LEFT JOIN COSTCENTRE C ON C.COSTID=A.COSTID  '  
      SELECT @QRY = @QRY + ' WHERE 1=1 '  
  SELECT @QRY = @QRY + @COMFILTER +' '+ @COSTFILTER +' '+@METALFILTER+ ' '+@ITEMFILTER  +' '+@SUBITEMFILTER   
   SELECT @QRY = @QRY+ ' GROUP BY '+@BASENAME+',SUBITEMNAME,METALNAME,A.METALID,C.COSTNAME,C.COSTID,A.SUBITEMID,A.'+@BASECOL    
   IF @BASEDON='D' SELECT @QRY=@QRY+ ' ,A.ITEMID'  
   PRINT @QRY  
   EXEC(@QRY)  
   SELECT @QRY = 'INSERT INTO  '+@TEMPTABLE+'_RES(PARTICULAR,'+@BASENAME+','+ @BASECOL +',METALNAME,COLHEAD,RESULT)'  
   SELECT @QRY = @QRY+ ' SELECT DISTINCT '+@BASENAME+','+@BASENAME+','+ @BASECOL +',METALNAME,''T2'',1 FROM '+@TEMPTABLE +'_RES WHERE RESULT=3 GROUP BY '+@BASENAME+','+@BASECOL+',METALNAME'   
   PRINT @QRY  
   EXEC(@QRY)    
   /*SELECT @QRY = 'INSERT INTO '+@TEMPTABLE+'_RES(PARTICULAR,'+@BASENAME+','+ @BASECOL +',METALNAME,COLHEAD,RESULT) SELECT '+ @BASENAME +'+''-SUBTOTAL'','+@BASENAME+','+ @BASECOL +',METALNAME,''S'',4 FROM '+@TEMPTABLE +'_RES WHERE RESULT=3 GROUP BY '+@BA
SENAME+','+ @BASECOL +',METALNAME' EXEC(@QRY)PRINT @QRY*/  
   SELECT @QRY = 'INSERT INTO '+@TEMPTABLE+'_RES(PARTICULAR,METALNAME,'+@BASENAME+','+ @BASECOL +',COSTNAME,COLHEAD,RESULT) SELECT COSTNAME+''-SUBTOTAL'',METALNAME,'+@BASENAME+','+ @BASECOL +',COSTNAME,''S2'',4 FROM '+@TEMPTABLE +'_RES WHERE RESULT=3 GROU
P BY METALNAME,'+@BASENAME+','+ @BASECOL +',COSTNAME' EXEC(@QRY)PRINT @QRY  
   SELECT @QRY = 'INSERT INTO '+@TEMPTABLE+'_RES(PARTICULAR,METALNAME,COLHEAD,RESULT) SELECT DISTINCT METALNAME,METALNAME,''T1'',0 FROM '+@TEMPTABLE +'_RES WHERE RESULT=3 GROUP BY METALNAME' EXEC(@QRY)        PRINT @QRY  
   SELECT @QRY = 'INSERT INTO '+@TEMPTABLE+'_RES(PARTICULAR,METALNAME,'+@BASENAME+',COLHEAD,RESULT) SELECT METALNAME+''-SUBTOTAL'',METALNAME,''ZZZZ'',''S2'',5 FROM '+@TEMPTABLE +'_RES WHERE RESULT=3 GROUP BY METALNAME' EXEC(@QRY)PRINT @QRY       
   SELECT @QRY = 'INSERT INTO '+@TEMPTABLE+'_RES(PARTICULAR,METALNAME,'+@BASENAME+',COLHEAD,RESULT) SELECT ''GRAND TOTAL'',''ZZZZ'',''ZZZZZ'',''G'',6 ' EXEC(@QRY) PRINT @QRY  
   SELECT @QRY=' ALTER TABLE '+ @TEMPTABLE +'_RES ADD [TOTAL~PCS] INT ' EXEC(@QRY)        PRINT @QRY  
   SELECT @QRY=' ALTER TABLE '+ @TEMPTABLE +'_RES ADD [TOTAL~GRSWT] DECIMAL(15,3) ' EXEC(@QRY)      PRINT @QRY    
   SELECT @QRY=' UPDATE A SET [TOTAL~PCS]=(SELECT SUM(PCS) FROM '+ @TEMPTABLE +' WHERE '+@BASECOL+'=A.'+@BASECOL    
   SELECT @QRY= @QRY+' AND SUBITEMID=A.SUBITEMID AND ITEMID=A.ITEMID AND METALID=A.METALID AND ISNULL(CAPTION,'''')=CAPTION AND COSTID=A.COSTID)'    
   SELECT @QRY=@QRY+CHAR(13)+' FROM '+ @TEMPTABLE +'_RES A'  
   PRINT @QRY  
   EXEC(@QRY)    
   SELECT @QRY=' UPDATE A SET [TOTAL~GRSWT]=(SELECT SUM(GRSWT) FROM '+ @TEMPTABLE +' WHERE '+@BASECOL+'=A.'+@BASECOL  
   SELECT @QRY= @QRY+' AND SUBITEMID=A.SUBITEMID AND ITEMID=A.ITEMID AND METALID=A.METALID AND ISNULL(CAPTION,'''')=CAPTION AND COSTID=A.COSTID)  '      
   SELECT @QRY=@QRY+CHAR(13)+' FROM '+ @TEMPTABLE +'_RES A'  
   PRINT @QRY  
   EXEC(@QRY)    
   DECLARE @FRMWT AS VARCHAR(10)  
   DECLARE @TOWT AS VARCHAR(10)  
   DECLARE @IITEMID AS INT  
   DECLARE @OLDID AS INT  
   DECLARE @NEWID AS INT  
   SET @FRMWT=''  
   SET @TOWT=''  
   SET @IITEMID=0  
   SET @OLDID=0  
   SET @NEWID=0  
   DECLARE @COLNO AS INT  
   SET @COLNO=0  
   DECLARE CUR CURSOR FOR SELECT DISTINCT FROMWEIGHT,TOWEIGHT,IITEMID FROM TEMPTABLEDB..TEMPRANGEWISE WHERE ISNULL(FROMWEIGHT,0)<>0 AND ISNULL(TOWEIGHT,0)<>0   ORDER BY IITEMID,TOWEIGHT  
   OPEN CUR  
   BEGIN  
    WHILE 1=1  
    BEGIN  
     FETCH NEXT FROM CUR INTO @FRMWT,@TOWT,@IITEMID  
     IF @@FETCH_STATUS=-1 BREAK    
     SET @OLDID=@IITEMID  
     IF @OLDID<>@NEWID SET @COLNO=0   
     SET @COLNO=@COLNO +1   
     SET @NEWID=@IITEMID  
     SELECT @QRY=' IF(SELECT COUNT(*) FROM TEMPTABLEDB..SYSCOLUMNS WHERE NAME='''+ CONVERT(VARCHAR(10),@COLNO) +'~PCS'' AND ID=OBJECT_ID('''+ @TEMPTABLE +'_RES''))=0 ALTER TABLE '+ @TEMPTABLE +'_RES ADD ['+ CONVERT(VARCHAR(10),@COLNO) +'~PCS] INT 'EXEC(@QRY)  
     PRINT @QRY  
     SELECT @QRY=' IF(SELECT COUNT(*) FROM TEMPTABLEDB..SYSCOLUMNS WHERE NAME='''+ CONVERT(VARCHAR(10),@COLNO) +'~GRSWT'' AND ID=OBJECT_ID('''+ @TEMPTABLE +'_RES''))=0 ALTER TABLE '+ @TEMPTABLE +'_RES ADD ['+ CONVERT(VARCHAR(10),@COLNO) +'~GRSWT] DECIMAL(
15,3)'EXEC(@QRY)    
     PRINT @QRY  
     SELECT @QRY=' UPDATE A SET ['+ CONVERT(VARCHAR(10),@COLNO) +'~PCS]=(SELECT SUM(PCS) FROM '+ @TEMPTABLE +' WHERE '+@BASECOL+'=A.'+@BASECOL  
     SELECT @QRY= @QRY+' AND SUBITEMID=A.SUBITEMID  AND FROMWEIGHT = '+ @FRMWT +' AND TOWEIGHT='+ @TOWT +'  AND METALID=A.METALID AND COSTID=A.COSTID)'  
     SELECT @QRY= @QRY+' FROM '+ @TEMPTABLE +'_RES A WHERE  '+@BASECOL+'= '+CONVERT(VARCHAR(10),@IITEMID)+''  
     SELECT @QRY= @QRY+' AND ITEMID=A.ITEMID'  
     PRINT @QRY  
     EXEC(@QRY)    
     SELECT @QRY=' UPDATE A SET ['+ CONVERT(VARCHAR(10),@COLNO) +'~GRSWT]=(SELECT SUM(GRSWT) FROM '+ @TEMPTABLE +' WHERE '+@BASECOL+'=A.'+@BASECOL  
     SELECT @QRY= @QRY+' AND SUBITEMID=A.SUBITEMID   AND FROMWEIGHT = '+ @FRMWT +' AND TOWEIGHT='+ @TOWT +' AND METALID=A.METALID AND COSTID=A.COSTID)  '      
     SELECT @QRY= @QRY+' FROM '+ @TEMPTABLE +'_RES A WHERE  '+@BASECOL+'= '+CONVERT(VARCHAR(10),@IITEMID)+''  
     SELECT @QRY= @QRY+' AND ITEMID=A.ITEMID'  
     PRINT @QRY  
     EXEC(@QRY)      
    END    
   END   
   print '!!!!!!!!!!!END'+@DISPTYPE    
   CLOSE CUR    
   DEALLOCATE CUR   
   SELECT @QRY = ' IF OBJECT_ID('''+@TEMPTABLE +'_2'',''U'')IS NOT NULL DROP TABLE '+@TEMPTABLE +'_2'  
   SELECT @QRY = @QRY + ' SELECT * INTO '+@TEMPTABLE +'_2  FROM '+@TEMPTABLE +'_RES'  
   print 'CUR START'  
   print @QRY  
   EXEC(@QRY)  
   SET @COLNO =0  
   DECLARE CUR CURSOR FOR SELECT DISTINCT FROMWEIGHT,TOWEIGHT,IITEMID FROM TEMPTABLEDB..TEMPRANGEWISE WHERE ISNULL(FROMWEIGHT,0)<>0 AND ISNULL(TOWEIGHT,0)<>0  AND IITEMID =(SELECT TOP 1 IITEMID FROM TEMPTABLEDB..TEMPRANGEWISE_1 ORDER BY CNT  DESC ) ORDER 
BY IITEMID,TOWEIGHT  
   OPEN CUR  
   BEGIN  
    WHILE 1=1  
    BEGIN  
     FETCH NEXT FROM CUR INTO @FRMWT,@TOWT,@IITEMID  
     IF @@FETCH_STATUS=-1 BREAK    
     SET @COLNO =@COLNO +1  
     DECLARE @CMETAL VARCHAR(2)    
     DECLARE @CMETALNAME VARCHAR(30)    
     DECLARE CUR1 CURSOR FOR SELECT METALID,METALNAME FROM TEMPTABLEDB..TEMPRANGEWISE_RES WHERE RESULT=3 GROUP BY METALID,METALNAME    
     OPEN CUR1    
     BEGIN    
      WHILE 1=1    
      BEGIN    
       FETCH NEXT FROM CUR1 INTO @CMETAL,@CMETALNAME    
       IF @@FETCH_STATUS=-1 BREAK  
       SELECT @QRY=' UPDATE TT SET ['+ CONVERT(VARCHAR(10),@COLNO) +'~PCS]=(SELECT SUM(ISNULL(['+ CONVERT(VARCHAR(10),@COLNO) +'~PCS],0)) FROM '+ @TEMPTABLE +'_2 WHERE   '    
      SELECT @QRY= @QRY+' METALID='''+@CMETAL +''' AND RESULT=3)'  
      SELECT @QRY=@QRY+CHAR(13)+' FROM '+ @TEMPTABLE +'_RES TT WHERE RESULT=5 AND METALNAME='''+@CMETALNAME +''''    
      print 'CUR START '  
       print @QRY  
      EXEC(@QRY)    
      SELECT @QRY=' UPDATE TT SET ['+ CONVERT(VARCHAR(10),@COLNO) +'~GRSWT]=(SELECT SUM(ISNULL(['+ CONVERT(VARCHAR(10),@COLNO) +'~GRSWT],0)) FROM '+ @TEMPTABLE +'_2 WHERE   '    
      SELECT @QRY= @QRY+' METALID='''+@CMETAL +''' AND RESULT=3)'  
      SELECT @QRY=@QRY+CHAR(13)+' FROM '+ @TEMPTABLE +'_RES TT WHERE RESULT=5 AND METALNAME='''+@CMETALNAME +''''    
      print 'CUR START '  
       print @QRY  
      EXEC(@QRY)  
       SELECT @QRY=' UPDATE TT SET [TOTAL~PCS]=(SELECT SUM(PCS) FROM '+ @TEMPTABLE +' WHERE'    
       SELECT @QRY= @QRY+'  METALID='''+@CMETAL +''' AND ISNULL(CAPTION,'''')=CAPTION)  '    
       SELECT @QRY=@QRY+CHAR(13)+' FROM '+ @TEMPTABLE +'_RES TT WHERE RESULT=5 AND METALNAME='''+@CMETALNAME +''''  
       print 'CUR START '  
       print @QRY  
       EXEC(@QRY)    
       SELECT @QRY=' UPDATE TT SET [TOTAL~GRSWT]=(SELECT SUM(GRSWT) FROM '+ @TEMPTABLE +' WHERE'  
       SELECT @QRY= @QRY+'  METALID='''+@CMETAL +''' AND ISNULL(CAPTION,'''')=CAPTION)'  
       SELECT @QRY=@QRY+CHAR(13)+' FROM '+ @TEMPTABLE +'_RES TT WHERE RESULT=5 AND METALNAME='''+@CMETALNAME +''''  
       print 'CUR START '  
       print @QRY  
       EXEC(@QRY)  
      END    
     END    
     CLOSE CUR1    
     DEALLOCATE CUR1   
     DECLARE @CCOST VARCHAR(4)    
     DECLARE @CCOSTNAME VARCHAR(200)    
     IF @BASEDON='I'      
     BEGIN      
      DECLARE CUR1 CURSOR FOR  SELECT COSTID,COSTNAME FROM TEMPTABLEDB..TEMPRANGEWISE_RES WHERE RESULT=3 GROUP BY COSTID,COSTNAME  
      OPEN CUR1    
      BEGIN    
       WHILE 1=1    
       BEGIN    
        FETCH NEXT FROM CUR1 INTO @CCOST,@CCOSTNAME    
        IF @@FETCH_STATUS=-1 BREAK    
        SELECT @QRY=' UPDATE TT SET ['+ CONVERT(VARCHAR(10),@COLNO) +'~PCS]=(SELECT SUM(ISNULL(['+ CONVERT(VARCHAR(10),@COLNO) +'~PCS],0)) FROM '+ @TEMPTABLE +'_2 WHERE   '    
        SELECT @QRY= @QRY+' COSTID='''+@CCOST +''' AND RESULT=3 AND '+@BASECOL+'=TT.'+@BASECOL+') '    
        SELECT @QRY=@QRY+CHAR(13)+' FROM '+ @TEMPTABLE +'_RES TT WHERE RESULT=4 AND COSTNAME='''+@CCOSTNAME +''''   
        print 'CUR START '  
        print @QRY  
        EXEC(@QRY)    
        SELECT @QRY=' UPDATE TT SET ['+ CONVERT(VARCHAR(10),@COLNO) +'~GRSWT]=(SELECT SUM(ISNULL(['+ CONVERT(VARCHAR(10),@COLNO) +'~GRSWT],0)) FROM '+ @TEMPTABLE +'_2 WHERE'  
        SELECT @QRY= @QRY+' COSTID='''+@CCOST +''' AND '+@BASECOL+'=TT.'+@BASECOL+')  '     
        SELECT @QRY=@QRY+CHAR(13)+' FROM '+ @TEMPTABLE +'_RES TT WHERE RESULT=4 AND COSTNAME='''+@CCOSTNAME +''''  
        print 'CUR START '  
           print @QRY  
        EXEC(@QRY)       
        SELECT @QRY=' UPDATE TT SET [TOTAL~PCS]=(SELECT SUM(PCS) FROM '+ @TEMPTABLE +' WHERE '    
        SELECT @QRY= @QRY+' 1=1 AND COSTID='''+@CCOST +''' AND ISNULL(CAPTION,'''')=CAPTION  AND '+@BASECOL+'=TT.'+@BASECOL+')  '     
        SELECT @QRY=@QRY+CHAR(13)+' FROM '+ @TEMPTABLE +'_RES TT WHERE RESULT=4 AND COSTNAME='''+@CCOSTNAME +''''    
        print 'CUR START '  
           print @QRY  
        EXEC(@QRY)    
        SELECT @QRY=' UPDATE TT SET [TOTAL~GRSWT]=(SELECT SUM(GRSWT) FROM '+ @TEMPTABLE +' WHERE   '    
        SELECT @QRY= @QRY+' 1=1 AND  COSTID='''+@CCOST +''' AND ISNULL(CAPTION,'''')=CAPTION AND '+@BASECOL+'=TT.'+@BASECOL+')  '    
        SELECT @QRY=@QRY+CHAR(13)+' FROM '+ @TEMPTABLE +'_RES TT WHERE RESULT=4 AND COSTNAME='''+@CCOSTNAME +''''    
        print 'CUR START '  
           print @QRY  
        EXEC(@QRY)             
       END    
      END    
      CLOSE CUR1    
      DEALLOCATE CUR1    
     END      
     IF @BASEDON='D'      
     BEGIN      
       DECLARE @QRY1 AS VARCHAR(8000)   
       SET @QRY1 =''   
    SET @QRY1 =' SELECT DESIGNERID,DESIGNERNAME FROM TEMPTABLEDB..TEMPRANGEWISE_RES WHERE RESULT=3 GROUP BY DESIGNERID,DESIGNERNAME '  
      DECLARE CUR1 CURSOR FOR  SELECT @QRY1  
      OPEN CUR1    
      BEGIN    
       WHILE 1=1    
       BEGIN    
        FETCH NEXT FROM CUR1 INTO @CCOST,@CCOSTNAME    
        IF @@FETCH_STATUS=-1 BREAK    
        SELECT @QRY1=' UPDATE TT SET ['+ CONVERT(VARCHAR(10),@COLNO) +'~PCS]=(SELECT SUM(ISNULL(['+ CONVERT(VARCHAR(10),@COLNO) +'~PCS],0)) FROM '+ @TEMPTABLE +'_2 WHERE'  
        SELECT @QRY1= @QRY1+' '+ @BASECOL +'='''+@CCOST +''')  '    
        SELECT @QRY1=@QRY1+CHAR(13)+' FROM '+ @TEMPTABLE +'_RES TT WHERE RESULT=4 AND '+@BASENAME+'='''+@CCOSTNAME +''''    
        EXEC(@QRY1)    
        SELECT @QRY1=' UPDATE TT SET ['+ CONVERT(VARCHAR(10),@COLNO) +'~GRSWT]=(SELECT SUM(ISNULL(['+ CONVERT(VARCHAR(10),@COLNO) +'~GRSWT],0)) FROM '+ @TEMPTABLE +'_2 WHERE'  
        SELECT @QRY1= @QRY1+' '+ @BASECOL +'='''+@CCOST +''')'  
        SELECT @QRY1=@QRY1+CHAR(13)+' FROM '+ @TEMPTABLE +'_RES TT WHERE RESULT=4 AND '+@BASENAME+'='''+@CCOSTNAME +''''  
        EXEC(@QRY1)       
        SELECT @QRY1=' UPDATE TT SET [TOTAL~PCS]=(SELECT SUM(PCS) FROM '+ @TEMPTABLE +' WHERE   '    
        SELECT @QRY1= @QRY1+'  1=1 AND '+ @BASECOL +'='''+@CCOST +''' AND ISNULL(CAPTION,'''')=CAPTION) '    
        SELECT @QRY1=@QRY1+CHAR(13)+' FROM '+ @TEMPTABLE +'_RES TT WHERE RESULT=4 AND '+@BASENAME+'='''+@CCOSTNAME +''''    
        EXEC(@QRY1)    
        SELECT @QRY1=' UPDATE TT SET [TOTAL~GRSWT]=(SELECT SUM(GRSWT) FROM '+ @TEMPTABLE +' WHERE   '    
        SELECT @QRY1= @QRY1+' 1=1 AND  '+ @BASECOL +'='''+@CCOST +''' AND ISNULL(CAPTION,'''')=CAPTION)  '    
        SELECT @QRY1=@QRY1+CHAR(13)+' FROM '+ @TEMPTABLE +'_RES TT WHERE RESULT=4 AND '+@BASENAME+'='''+@CCOSTNAME +''''    
        EXEC(@QRY1)       
       END    
      END            
      CLOSE CUR1    
      DEALLOCATE CUR1    
     END   
     SELECT @QRY=' UPDATE TT SET ['+ CONVERT(VARCHAR(10),@COLNO) +'~PCS]=(SELECT SUM(ISNULL(['+ CONVERT(VARCHAR(10),@COLNO) +'~PCS],0)) FROM '+ @TEMPTABLE +'_2 WHERE RESULT=3)'  
     SELECT @QRY= @QRY+' FROM '+ @TEMPTABLE +'_RES TT WHERE RESULT=6 '  
     print 'SUBTOT START '  
     print @QRY  
     EXEC(@QRY)    
     SELECT @QRY=' UPDATE TT SET ['+ CONVERT(VARCHAR(10),@COLNO) +'~GRSWT]=(SELECT SUM(ISNULL(['+ CONVERT(VARCHAR(10),@COLNO) +'~GRSWT],0)) FROM '+ @TEMPTABLE +'_2 WHERE RESULT=3)'  
     SELECT @QRY= @QRY+' FROM '+ @TEMPTABLE +'_RES TT WHERE RESULT=6'  
     print 'SUBTOT START '  
     print @QRY  
     EXEC(@QRY)  
     SELECT @QRY=' UPDATE '+ @TEMPTABLE +'_RES  SET ['+ CONVERT(VARCHAR(10),@COLNO) +'~PCS]=NULL WHERE ISNULL(['+ CONVERT(VARCHAR(10),@COLNO) +'~PCS],0)=0'  
     print 'SUBTOT START '  
     print @QRY  
     EXEC(@QRY)    
     SELECT @QRY=' UPDATE '+ @TEMPTABLE +'_RES SET ['+ CONVERT(VARCHAR(10),@COLNO) +'~GRSWT]= NULL WHERE ISNULL(['+ CONVERT(VARCHAR(10),@COLNO) +'~GRSWT],0)=0'  
     print 'SUBTOT START '  
     print @QRY  
     EXEC(@QRY)  
    END    
   END  
   CLOSE CUR    
   DEALLOCATE CUR          
   SELECT @QRY=' UPDATE TT SET [TOTAL~PCS]=(SELECT SUM(PCS) FROM '+ @TEMPTABLE +' WHERE 1=1 AND ISNULL(CAPTION,'''')=CAPTION AND '+@BASECOL+'=TT.'+@BASECOL+')  '    
   SELECT @QRY=@QRY+CHAR(13)+' FROM '+ @TEMPTABLE +'_RES TT WHERE RESULT=6 '    
   print 'TOT PCS '  
     print @QRY  
   EXEC(@QRY)    
   SELECT @QRY=' UPDATE TT SET [TOTAL~GRSWT]=(SELECT SUM(GRSWT) FROM '+ @TEMPTABLE +' WHERE 1=1 AND ISNULL(CAPTION,'''')=CAPTION AND '+@BASECOL+'=TT.'+@BASECOL+')  '    
   SELECT @QRY=@QRY+CHAR(13)+' FROM '+ @TEMPTABLE +'_RES TT WHERE RESULT=6 '    
   print 'TOT PCS '  
     print @QRY  
   EXEC(@QRY)               
   SELECT @QRY=' DECLARE @SQLQRY AS NVARCHAR(4000)'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' DECLARE @COLNO AS INT'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' DECLARE @OLDID AS INT'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' DECLARE @NEWID AS INT'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' DECLARE @CAPTION AS VARCHAR(10)'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' DECLARE @FWT AS VARCHAR(10)'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' DECLARE @TWT AS VARCHAR(10)'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' DECLARE @ITID AS VARCHAR(10)'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' DECLARE @COLNAME AS VARCHAR(8000)'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' DECLARE @COLVAL AS VARCHAR(8000)'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' SET @COLNO=0'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' SET @OLDID=0'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' SET @NEWID=0'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' SET @ITID='''''  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' SET @CAPTION='''''  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' SET @COLNAME='''''  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' SET @COLVAL='''''  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' DECLARE CURI CURSOR FOR SELECT DISTINCT FROMWEIGHT,TOWEIGHT,CAPTION,IITEMID AS ITID FROM TEMPTABLEDB..TEMPRANGEWISE WHERE ISNULL(FROMWEIGHT,0)<>0 AND ISNULL(TOWEIGHT,0)<>0 ORDER BY IITEMID,TOWEIGHT'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' OPEN CURI'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' BEGIN'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +'  WHILE 1=1'    
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +'  BEGIN'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +'   FETCH NEXT FROM CURI INTO @FWT,@TWT,@CAPTION,@ITID'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +'   IF @@FETCH_STATUS=-1 BREAK'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +'   SET @OLDID=@ITID'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +'   IF @OLDID<>@NEWID SET @COLNO=0'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +'   SET @COLNO=@COLNO+1'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +'   SET @NEWID=@ITID'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +'   SELECT @SQLQRY='' ALTER TABLE '+ @TEMPTABLE +'_RES ALTER COLUMN [''+ CONVERT(VARCHAR(10),@COLNO) +''~PCS] VARCHAR(30)'''  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +'   SELECT @SQLQRY=@SQLQRY+'' ALTER TABLE '+ @TEMPTABLE +'_RES ALTER COLUMN [''+ CONVERT(VARCHAR(10),@COLNO) +''~GRSWT] VARCHAR(30)'''   
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +'   EXECUTE SP_EXECUTESQL @SQLQRY'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +'   SELECT @SQLQRY=''UPDATE '+ @TEMPTABLE +'_RES SET [''+ CONVERT(VARCHAR(10),@COLNO) +''~PCS]=(''''''+ @CAPTION +'''''')'''  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +'   SELECT @SQLQRY=@SQLQRY+'',[''+ CONVERT(VARCHAR(10),@COLNO) +''~GRSWT]=(''''''+ @CAPTION +'''''')'''  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +'   SELECT @SQLQRY=@SQLQRY+'' WHERE '+ @BASECOL +'=''+@ITID+'' AND RESULT=1'''  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +'   EXECUTE SP_EXECUTESQL @SQLQRY'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +'  END'   
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' END'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' CLOSE CURI'  
   SELECT @QRY=@QRY+CHAR(13)+ CHAR(13) +' DEALLOCATE CURI'  
   EXEC(@QRY)   
   SELECT @QRY=' UPDATE TEMPTABLEDB..TEMPRANGEWISE_RES SET [TOTAL~PCS]=NULL WHERE [TOTAL~PCS]=0 '  
   PRINT '#########################'  
   PRINT @QRY  
   EXEC(@QRY)  
   SELECT @QRY=' UPDATE TEMPTABLEDB..TEMPRANGEWISE_RES SET [TOTAL~GRSWT]=NULL WHERE [TOTAL~GRSWT]=0.000 '  
   print '#########################'  
   PRINT @QRY  
   EXEC(@QRY)  
  IF @SPECIFICFORMAT = '1'  
  BEGIN  
    SELECT @QRY=' SELECT * FROM '+ @TEMPTABLE +'_RES WHERE RESULT<>4  ORDER BY METALNAME,'+ @BASENAME +',SUBITEMNAME,COSTNAME,RESULT    '    
  END  
   IF @SPECIFICFORMAT <> '1'  
  BEGIN  
    SELECT @QRY=' SELECT * FROM '+ @TEMPTABLE +'_RES  ORDER BY METALNAME,'+ @BASENAME +',COSTNAME,RESULT    '    
  END  
   PRINT @QRY  
   EXEC(@QRY)   
  END  
  IF @DISPTYPE='V'  
  BEGIN  
   PRINT '@@@@@@@@@@'+@DISPTYPE  
     SELECT @QRY = ' ALTER TABLE '+@TEMPTABLE +' ADD IITEMID INT'  
   PRINT @QRY  
   EXEC(@QRY)  
   SELECT @QRY = ' UPDATE '+@TEMPTABLE +' SET IITEMID='+ @BASECOL +''  
   PRINT @QRY  
   EXEC(@QRY)  
     IF @RPTTYPE ='D'  
     BEGIN  
   IF OBJECT_ID('TEMPTABLEDB..TEMPRANGEWISE_RES ') IS NOT NULL DROP TABLE TEMPTABLEDB..TEMPRANGEWISE_RES   
   SELECT @QRY = ' SELECT PARTICULAR,'+@BASENAME+',SUBITEMNAME,COSTNAME,COSTID,'+@BASECOL+',SUBITEMID,METALNAME,METALID,PCS,GRSWT,FROMWEIGHT,TOWEIGHT,RESULT,COLHEAD,RANGE,DISPORDER INTO TEMPTABLEDB..TEMPRANGEWISE_RES FROM ( '  
   SELECT @QRY=@QRY+CHAR(13)+' SELECT CONVERT(VARCHAR,T.CAPTION)+''        '' as PARTICULAR,'+@BASENAME+',SUBITEMNAME,C.COSTNAME,C.COSTID,A.'+@BASECOL+',A.SUBITEMID,METALNAME,M.METALID'  
   SELECT @QRY=@QRY+CHAR(13)+' ,SUM(CASE WHEN A.GRSWT BETWEEN T.FROMWEIGHT AND T.TOWEIGHT THEN A.PCS ELSE 0 END)PCS,SUM(CASE WHEN A.GRSWT BETWEEN T.FROMWEIGHT AND T.TOWEIGHT THEN A.GRSWT ELSE 0 END)GRSWT,T.FROMWEIGHT,T.TOWEIGHT,3 RESULT,''DD''COLHEAD'  
   SELECT @QRY=@QRY + ' ,CONVERT(VARCHAR(12),CASE WHEN (SUM(CASE WHEN A.GRSWT BETWEEN T.FROMWEIGHT AND T.TOWEIGHT THEN A.GRSWT ELSE 0 END))>0 THEN ''RANGE-IN'' ELSE ''0'' END) AS  RANGE '  
   SELECT @QRY=@QRY+CHAR(13)+' ,CONVERT(INT,CASE WHEN T.FROMWEIGHT=0.001 AND T.TOWEIGHT=0.001 THEN 1 ELSE 0 END) DISPORDER'  
   SELECT @QRY=@QRY+CHAR(13)+' FROM TEMPTABLEDB..TEMPRANGEWISE A'       
   IF @BASEDON='I' SELECT @QRY = @QRY+ ' LEFT JOIN ITEMMAST I ON I.'+@BASECOL+'=A.'+@BASECOL+'  '    
   IF @BASEDON='D' SELECT @QRY = @QRY+ ' LEFT JOIN DESIGNER I ON I.DESIGNERID=A.DESIGNERID  '    
   SELECT @QRY=@QRY+CHAR(13)+' LEFT JOIN SUBITEMMAST S ON S.SUBITEMID=A.SUBITEMID'  
   SELECT @QRY=@QRY+CHAR(13)+' LEFT JOIN METALMAST M ON M.METALID=A.METALID'  
   SELECT @QRY=@QRY+CHAR(13)+' LEFT JOIN COSTCENTRE C ON C.COSTID=A.COSTID'  
   IF @BASEDON='I' SELECT @QRY=@QRY+CHAR(13)+' INNER JOIN TEMPTABLEDB..TEMPSELECTRANGE AS T ON T.'+@BASECOL+'=A.'+@BASECOL+'  '  
   IF @BASEDON='I' SELECT @QRY=@QRY+CHAR(13)+' WHERE T.SUBITEMID=A.SUBITEMID AND T.COSTID=A.COSTID '  
   IF @BASEDON='D' SELECT @QRY=@QRY+CHAR(13)+' INNER JOIN TEMPTABLEDB..TEMPSELECTRANGE AS T ON T.SUBITEMID=A.SUBITEMID '  
   SELECT @QRY=@QRY+CHAR(13)+' GROUP BY T.CAPTION,T.FROMWEIGHT,T.TOWEIGHT,'+@BASENAME+',SUBITEMNAME,A.'+@BASECOL+',A.SUBITEMID,METALNAME,M.METALID,C.COSTNAME,C.COSTID'  
   SELECT @QRY=@QRY+CHAR(13)+' UNION ALL '  
   SELECT @QRY=@QRY+CHAR(13)+ ' SELECT CONVERT(VARCHAR,A.CAPTION)+''         '' as PARTICULAR,'+@BASENAME+',SUBITEMNAME,C.COSTNAME,C.COSTID,A.'+@BASECOL+',A.SUBITEMID,METALNAME,M.METALID'  
   SELECT @QRY=@QRY+CHAR(13)+' ,SUM(A.PCS)PCS,SUM(A.GRSWT)GRSWT,A.FROMWEIGHT,A.TOWEIGHT,3 RESULT,''DD''COLHEAD'  
   SELECT @QRY=@QRY + ' ,CONVERT(VARCHAR(12),CASE WHEN (SUM(CASE WHEN A.GRSWT BETWEEN A.FROMWEIGHT AND A.TOWEIGHT THEN A.GRSWT ELSE 0 END))>0 THEN ''RANGE-IN'' ELSE ''0'' END) AS  RANGE '  
   SELECT @QRY=@QRY+CHAR(13)+' ,CONVERT(INT,CASE WHEN A.FROMWEIGHT=0.001 AND A.TOWEIGHT=0.001 THEN 1 ELSE 0 END) DISPORDER'  
   SELECT @QRY=@QRY+CHAR(13)+' FROM TEMPTABLEDB..TEMPRANGEWISE A'  
   IF @BASEDON='I' SELECT @QRY = @QRY+ ' LEFT JOIN ITEMMAST I ON I.'+@BASECOL+'=A.'+@BASECOL+'  '    
   IF @BASEDON='D' SELECT @QRY = @QRY+ ' LEFT JOIN DESIGNER I ON I.DESIGNERID=A.DESIGNERID  '    
   SELECT @QRY=@QRY+CHAR(13)+' LEFT JOIN SUBITEMMAST S ON S.SUBITEMID=A.SUBITEMID'  
   SELECT @QRY=@QRY+CHAR(13)+' LEFT JOIN METALMAST M ON M.METALID=A.METALID'  
   SELECT @QRY=@QRY+CHAR(13)+' LEFT JOIN COSTCENTRE C ON C.COSTID=A.COSTID'  
   --SELECT @QRY=@QRY+CHAR(13)+' WHERE A.FROMWEIGHT=''0.001'' AND A.TOWEIGHT =''0.001'' ' 
   SELECT @QRY=@QRY+CHAR(13)+' INNER JOIN (SELECT DISTINCT FROMWEIGHT,TOWEIGHT FROM TEMPTABLEDB..TEMPSELECTRANGE) D ON D.FROMWEIGHT = A.FROMWEIGHT AND D.TOWEIGHT = A.TOWEIGHT'   
   SELECT @QRY=@QRY+CHAR(13)+' GROUP BY A.CAPTION,A.FROMWEIGHT,A.TOWEIGHT,'+@BASENAME+',SUBITEMNAME,A.'+@BASECOL+',A.SUBITEMID,METALNAME,M.METALID,C.COSTNAME,C.COSTID)X'       
   PRINT '#########################'  
   PRINT @QRY  
   EXEC(@QRY)     
   IF @WITHOUTESTK ='Y'  
   BEGIN  
       SELECT @QRY=' DELETE FROM TEMPTABLEDB..TEMPRANGEWISE_RES WHERE RANGE<>''RANGE-IN'' '   
       PRINT @QRY  
       EXEC(@QRY)     
   END  
   SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPRANGEWISE_RES(PARTICULAR,METALNAME,RESULT,COLHEAD)'  
   SELECT @QRY=@QRY+CHAR(13)+' SELECT METALNAME,METALNAME,0,''T'' FROM TEMPTABLEDB..TEMPRANGEWISE_RES WHERE RESULT=3 GROUP BY METALNAME'  
   PRINT '#########################'  
   EXEC(@QRY)    
   IF @COSTFILTER <>''  
   print @COSTID  
   BEGIN    
    SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPRANGEWISE_RES(PARTICULAR,METALNAME,COSTNAME,'+@BASENAME+',RESULT,COLHEAD)'  
    SELECT @QRY=@QRY+CHAR(13)+' SELECT '+@BASENAME+',METALNAME,COSTNAME,'+@BASENAME+',1,''T1'' FROM TEMPTABLEDB..TEMPRANGEWISE_RES WHERE RESULT=3 GROUP BY METALNAME,COSTNAME,'+@BASENAME+''  
    PRINT '#########################'  
    EXEC(@QRY)  
   END  
    SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPRANGEWISE_RES(PARTICULAR,METALNAME,COSTNAME,'+@BASENAME+',SUBITEMNAME,RESULT,COLHEAD)'  
    SELECT @QRY=@QRY+CHAR(13)+' SELECT SUBITEMNAME,METALNAME,COSTNAME,'+@BASENAME+',SUBITEMNAME,2,''T2'' FROM TEMPTABLEDB..TEMPRANGEWISE_RES WHERE RESULT=3 GROUP BY METALNAME,COSTNAME,'+@BASENAME+',SUBITEMNAME'  
    print '#########################'   EXEC(@QRY)         
   IF @COSTFILTER <>''  
   PRINT @COSTFILTER  
   BEGIN   
    SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPRANGEWISE_RES(PARTICULAR,METALNAME,COSTNAME,'+@BASENAME+',SUBITEMNAME,PCS,GRSWT,RESULT,COLHEAD)'  
    SELECT @QRY=@QRY+CHAR(13)+' SELECT COSTNAME+''-SUBTOTAL'',METALNAME,COSTNAME,''ZZZZ'',''ZZZZZ'',SUM(PCS),SUM(GRSWT),6,''S1'' FROM TEMPTABLEDB..TEMPRANGEWISE_RES WHERE RESULT=3 GROUP BY METALNAME,COSTNAME'  
    print @QRY  
    EXEC(@QRY)  
   END  
   SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPRANGEWISE_RES(PARTICULAR,METALNAME,'+@BASENAME+',SUBITEMNAME,COSTNAME,PCS,GRSWT,RESULT,COLHEAD)'  
   SELECT @QRY=@QRY+CHAR(13)+' SELECT '+@BASENAME+'+''-SUBTOTAL'',METALNAME,'+@BASENAME+',''ZZZZZ'',COSTNAME,SUM(PCS),SUM(GRSWT),5,''S1'' FROM TEMPTABLEDB..TEMPRANGEWISE_RES WHERE RESULT=3 GROUP BY METALNAME,'+@BASENAME+',COSTNAME'  
   print '#########################'  
   EXEC(@QRY)  
   SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPRANGEWISE_RES(PARTICULAR,METALNAME,COSTNAME,'+@BASENAME+',SUBITEMNAME,PCS,GRSWT,RESULT,COLHEAD)'  
   SELECT @QRY=@QRY+CHAR(13)+' SELECT METALNAME+''-SUBTOTAL'',METALNAME,''ZZZZZ'',''ZZZZ'',''ZZZZZ'',SUM(PCS),SUM(GRSWT),6,''S'' FROM TEMPTABLEDB..TEMPRANGEWISE_RES WHERE RESULT=3 GROUP BY METALNAME'  
   print '#########################'  
   EXEC(@QRY)  
   SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPRANGEWISE_RES(PARTICULAR,METALNAME,'+@BASENAME+',SUBITEMNAME,PCS,GRSWT,RESULT,COLHEAD)'  
   SELECT @QRY=@QRY+CHAR(13)+' SELECT ''GRANDTOTAL'',''ZZZ'',''ZZZZ'',''ZZZZZ'',SUM(PCS),SUM(GRSWT),7,''G'' FROM TEMPTABLEDB..TEMPRANGEWISE_RES WHERE RESULT=3 '  
   print '#########################'  
   EXEC(@QRY)  
   SELECT @QRY=' UPDATE TEMPTABLEDB..TEMPRANGEWISE_RES SET PARTICULAR=0 WHERE PARTICULAR IS NULL '  
   print '#########################'  
   EXEC(@QRY)  
   SELECT @QRY=' UPDATE TEMPTABLEDB..TEMPRANGEWISE_RES SET PCS=NULL WHERE PCS=0'  
   print '#########################'  
   EXEC(@QRY)  
   SELECT @QRY=' UPDATE TEMPTABLEDB..TEMPRANGEWISE_RES SET RANGE=NULL WHERE RANGE=''0'''  
   print '#########################'  
   EXEC(@QRY)  
   SELECT @QRY=' UPDATE TEMPTABLEDB..TEMPRANGEWISE_RES SET GRSWT=NULL WHERE GRSWT=0.000 '  
   print '#########################'  
   EXEC(@QRY)  
   SELECT @QRY=' SELECT * FROM TEMPTABLEDB..TEMPRANGEWISE_RES    ORDER BY METALNAME,COSTNAME,'+@BASENAME+',SUBITEMNAME,RESULT,FROMWEIGHT,PARTICULAR '  
   print '#########################'  
   PRINT @QRY  
   EXEC(@QRY)  
    END  
    IF @RPTTYPE ='S'  
    BEGIN  
   IF OBJECT_ID('TEMPTABLEDB..TEMPRANGEWISE_RES ') IS NOT NULL DROP TABLE TEMPTABLEDB..TEMPRANGEWISE_RES   
   SELECT @QRY = ' SELECT PARTICULAR,'+@BASENAME+',COSTNAME,COSTID,'+@BASECOL+',METALNAME,METALID,PCS,GRSWT,FROMWEIGHT,TOWEIGHT,RESULT,COLHEAD,RANGE,DISPORDER INTO TEMPTABLEDB..TEMPRANGEWISE_RES FROM ( '  
   SELECT @QRY=@QRY+CHAR(13)+' SELECT CONVERT(VARCHAR,T.CAPTION)+''        '' as PARTICULAR,'+@BASENAME+',C.COSTNAME,C.COSTID,A.'+@BASECOL+',METALNAME,M.METALID'  
   SELECT @QRY=@QRY+CHAR(13)+' ,SUM(CASE WHEN A.GRSWT BETWEEN T.FROMWEIGHT AND T.TOWEIGHT THEN A.PCS ELSE 0 END)PCS,SUM(CASE WHEN A.GRSWT BETWEEN T.FROMWEIGHT AND T.TOWEIGHT THEN A.GRSWT ELSE 0 END)GRSWT,T.FROMWEIGHT,T.TOWEIGHT,3 RESULT,''DD''COLHEAD'  
   SELECT @QRY=@QRY + ' ,CONVERT(VARCHAR(12),CASE WHEN (SUM(CASE WHEN A.GRSWT BETWEEN T.FROMWEIGHT AND T.TOWEIGHT THEN A.GRSWT ELSE 0 END))>0 THEN ''RANGE-IN'' ELSE ''0'' END) AS  RANGE '  
   SELECT @QRY=@QRY+CHAR(13)+' ,CONVERT(INT,CASE WHEN T.FROMWEIGHT=0.001 AND T.TOWEIGHT=0.001 THEN 1 ELSE 0 END) DISPORDER'  
   SELECT @QRY=@QRY+CHAR(13)+' FROM TEMPTABLEDB..TEMPRANGEWISE A'       
   IF @BASEDON='I' SELECT @QRY = @QRY+ ' LEFT JOIN ITEMMAST I ON I.'+@BASECOL+'=A.'+@BASECOL+'  '    
   IF @BASEDON='D' SELECT @QRY = @QRY+ ' LEFT JOIN DESIGNER I ON I.DESIGNERID=A.DESIGNERID  '    
   SELECT @QRY=@QRY+CHAR(13)+' LEFT JOIN METALMAST M ON M.METALID=A.METALID'  
   SELECT @QRY=@QRY+CHAR(13)+' LEFT JOIN COSTCENTRE C ON C.COSTID=A.COSTID'  
   IF @BASEDON='I' SELECT @QRY=@QRY+CHAR(13)+' INNER JOIN TEMPTABLEDB..TEMPSELECTRANGE AS T ON T.'+@BASECOL+'=A.'+@BASECOL+'  '  
   IF @BASEDON='I' SELECT @QRY=@QRY+CHAR(13)+' WHERE /*T.SUBITEMID=A.SUBITEMID AND*/ T.COSTID=A.COSTID '  
   IF @BASEDON='D' SELECT @QRY=@QRY+CHAR(13)+' INNER JOIN TEMPTABLEDB..TEMPSELECTRANGE AS T ON T.ITEMID=A.ITEMID '  
   SELECT @QRY=@QRY+CHAR(13)+' GROUP BY T.CAPTION,T.FROMWEIGHT,T.TOWEIGHT,'+@BASENAME+',A.'+@BASECOL+',METALNAME,M.METALID,C.COSTNAME,C.COSTID'  
   SELECT @QRY=@QRY+CHAR(13)+' UNION ALL '  
   SELECT @QRY=@QRY+CHAR(13)+ ' SELECT CONVERT(VARCHAR,A.CAPTION)+''         '' as PARTICULAR,'+@BASENAME+',C.COSTNAME,C.COSTID,A.'+@BASECOL+',METALNAME,M.METALID'  
   SELECT @QRY=@QRY+CHAR(13)+' ,SUM(A.PCS)PCS,SUM(A.GRSWT)GRSWT,A.FROMWEIGHT,A.TOWEIGHT,3 RESULT,''DD''COLHEAD'  
   SELECT @QRY=@QRY + ' ,CONVERT(VARCHAR(12),CASE WHEN (SUM(CASE WHEN A.GRSWT BETWEEN A.FROMWEIGHT AND A.TOWEIGHT THEN A.GRSWT ELSE 0 END))>0 THEN ''RANGE-IN'' ELSE ''0'' END) AS  RANGE '  
   SELECT @QRY=@QRY+CHAR(13)+' ,CONVERT(INT,CASE WHEN A.FROMWEIGHT=0.001 AND A.TOWEIGHT=0.001 THEN 1 ELSE 0 END) DISPORDER'  
   SELECT @QRY=@QRY+CHAR(13)+' FROM TEMPTABLEDB..TEMPRANGEWISE A'  
   IF @BASEDON='I' SELECT @QRY = @QRY+ ' LEFT JOIN ITEMMAST I ON I.'+@BASECOL+'=A.'+@BASECOL+'  '    
   IF @BASEDON='D' SELECT @QRY = @QRY+ ' LEFT JOIN DESIGNER I ON I.DESIGNERID=A.DESIGNERID  '    
   SELECT @QRY=@QRY+CHAR(13)+' LEFT JOIN METALMAST M ON M.METALID=A.METALID'  
   SELECT @QRY=@QRY+CHAR(13)+' LEFT JOIN COSTCENTRE C ON C.COSTID=A.COSTID'  
   --SELECT @QRY=@QRY+CHAR(13)+' WHERE A.FROMWEIGHT=''0.001'' AND A.TOWEIGHT =''0.001'' '  
   SELECT @QRY=@QRY+CHAR(13)+' INNER JOIN (SELECT DISTINCT FROMWEIGHT,TOWEIGHT FROM TEMPTABLEDB..TEMPSELECTRANGE) D ON D.FROMWEIGHT = A.FROMWEIGHT AND D.TOWEIGHT = A.TOWEIGHT'
   SELECT @QRY=@QRY+CHAR(13)+' GROUP BY A.CAPTION,A.FROMWEIGHT,A.TOWEIGHT,'+@BASENAME+',A.'+@BASECOL+',METALNAME,M.METALID,C.COSTNAME,C.COSTID)X'       
   print '#########################'  
   print @QRY  
   EXEC(@QRY)     
   IF @WITHOUTESTK ='Y'  
   BEGIN  
       SELECT @QRY=' DELETE FROM TEMPTABLEDB..TEMPRANGEWISE_RES WHERE RANGE<>''RANGE-IN'' '   
       PRINT @QRY  
       EXEC(@QRY)     
   END  
   SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPRANGEWISE_RES(PARTICULAR,METALNAME,RESULT,COLHEAD)'  
   SELECT @QRY=@QRY+CHAR(13)+' SELECT METALNAME,METALNAME,0,''T'' FROM TEMPTABLEDB..TEMPRANGEWISE_RES WHERE RESULT=3 GROUP BY METALNAME'  
   print '#########################'  
   EXEC(@QRY)    
   IF @COSTFILTER <>''  
   print @COSTID  
   BEGIN    
    SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPRANGEWISE_RES(PARTICULAR,METALNAME,COSTNAME,'+@BASENAME+',RESULT,COLHEAD)'  
    SELECT @QRY=@QRY+CHAR(13)+' SELECT '+@BASENAME+',METALNAME,COSTNAME,'+@BASENAME+',1,''T1'' FROM TEMPTABLEDB..TEMPRANGEWISE_RES WHERE RESULT=3 GROUP BY METALNAME,COSTNAME,'+@BASENAME+''  
    print '#########################'  
    EXEC(@QRY)  
   END  
   IF @COSTFILTER <>''  
   print @COSTFILTER  
   BEGIN   
    SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPRANGEWISE_RES(PARTICULAR,METALNAME,COSTNAME,'+@BASENAME+',PCS,GRSWT,RESULT,COLHEAD)'  
    SELECT @QRY=@QRY+CHAR(13)+' SELECT COSTNAME+''-SUBTOTAL'',METALNAME,COSTNAME,''ZZZZ'',SUM(PCS),SUM(GRSWT),6,''S1'' FROM TEMPTABLEDB..TEMPRANGEWISE_RES WHERE RESULT=3 GROUP BY METALNAME,COSTNAME'  
    print @QRY  
    EXEC(@QRY)  
   END  
   SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPRANGEWISE_RES(PARTICULAR,METALNAME,'+@BASENAME+',COSTNAME,PCS,GRSWT,RESULT,COLHEAD)'  
   SELECT @QRY=@QRY+CHAR(13)+' SELECT '+@BASENAME+'+''-SUBTOTAL'',METALNAME,'+@BASENAME+',COSTNAME,SUM(PCS),SUM(GRSWT),5,''S1'' FROM TEMPTABLEDB..TEMPRANGEWISE_RES WHERE RESULT=3 GROUP BY METALNAME,'+@BASENAME+',COSTNAME'  
   print '#########################'  
   EXEC(@QRY)  
   SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPRANGEWISE_RES(PARTICULAR,METALNAME,COSTNAME,'+@BASENAME+',PCS,GRSWT,RESULT,COLHEAD)'  
   SELECT @QRY=@QRY+CHAR(13)+' SELECT METALNAME+''-SUBTOTAL'',METALNAME,''ZZZZZ'',''ZZZZ'',SUM(PCS),SUM(GRSWT),6,''S'' FROM TEMPTABLEDB..TEMPRANGEWISE_RES WHERE RESULT=3 GROUP BY METALNAME'  
   print '#########################'  
   EXEC(@QRY)  
   SELECT @QRY=' INSERT INTO TEMPTABLEDB..TEMPRANGEWISE_RES(PARTICULAR,METALNAME,'+@BASENAME+',PCS,GRSWT,RESULT,COLHEAD)'  
   SELECT @QRY=@QRY+CHAR(13)+' SELECT ''GRANDTOTAL'',''ZZZ'',''ZZZZ'',SUM(PCS),SUM(GRSWT),7,''G'' FROM TEMPTABLEDB..TEMPRANGEWISE_RES WHERE RESULT=3 '  
   print '#########################'  
   EXEC(@QRY)  
   SELECT @QRY=' UPDATE TEMPTABLEDB..TEMPRANGEWISE_RES SET PARTICULAR=0 WHERE PARTICULAR IS NULL '  
   print '#########################'  
   EXEC(@QRY)  
   SELECT @QRY=' UPDATE TEMPTABLEDB..TEMPRANGEWISE_RES SET PCS=NULL WHERE PCS=0'  
   print '#########################'  
   EXEC(@QRY)  
   SELECT @QRY=' UPDATE TEMPTABLEDB..TEMPRANGEWISE_RES SET RANGE=NULL WHERE RANGE=''0'''  
   print '#########################'  
   EXEC(@QRY)  
   SELECT @QRY=' UPDATE TEMPTABLEDB..TEMPRANGEWISE_RES SET GRSWT=NULL WHERE GRSWT=0.000 '  
   print '#########################'  
   EXEC(@QRY)  
   SELECT @QRY=' SELECT * FROM TEMPTABLEDB..TEMPRANGEWISE_RES    ORDER BY METALNAME,COSTNAME,'+@BASENAME+',RESULT,FROMWEIGHT,COLHEAD,PARTICULAR '  
   print '#########################'  
   PRINT @QRY  
   EXEC(@QRY)  
    END  
  END  
 END  


