ALTER PROCEDURE SP_UPDATE_ISSUE  
(  
@FROMID VARCHAR(5),  
@DBNAME VARCHAR(20),  
@SNO VARCHAR(20),      
@TRANNO VARCHAR(15),      
@TRANDATE VARCHAR(20),    
@TRANTYPE VARCHAR(5),      
@PCS VARCHAR(15),  
@GRSWT VARCHAR(20),  
@NETWT VARCHAR(20),  
@LESSWT VARCHAR(20),  
@PUREWT VARCHAR(20),  
@TAGNO VARCHAR(20),  
@ITEMID VARCHAR(20),  
@SUBITEMID VARCHAR(20),  
@WASTPER VARCHAR(20),  
@WASTAGE VARCHAR(20),  
@MCGRM VARCHAR(20),  
@MCHARGE VARCHAR(20),  
@AMOUNT VARCHAR(20),   
@RATE VARCHAR(20),  
@BOARDRATE VARCHAR(20),  
@SALEMODE VARCHAR(20),   
@GRSNET VARCHAR(20),  
@TRANSTATUS VARCHAR(20),  
@REFNO VARCHAR(20),  
@REFDATE VARCHAR(20),  
@COSTID VARCHAR(20),  
@COMPANYID VARCHAR(20),  
@FLAG VARCHAR(20),  
@EMPID VARCHAR(20),  
@TAGPCS VARCHAR(20),  
@TAGGRSWT VARCHAR(20),  
@TAGNETWT VARCHAR(20),  
@TAGRATEID VARCHAR(20),  
@TAGSVALUE VARCHAR(20),  
@TAGDESIGNER VARCHAR(20),  
@ITEMCTRID VARCHAR(20),  
@ITEMTYPEID VARCHAR(20),  
@PURITY VARCHAR(20),  
@TABLECODE VARCHAR(20),  
@INCENTIVE VARCHAR(20),  
@WEIGHTUNIT VARCHAR(20),  
@CATCODE VARCHAR(20),  
@OCATCODE VARCHAR(20),  
@ACCODE VARCHAR(15),  
@ALLOY VARCHAR(20),  
@BATCHNO VARCHAR(25),  
@REMARK1 VARCHAR(100),  
@REMARK2 VARCHAR(100),  
@USERID VARCHAR(20),  
@UPDATED VARCHAR(20),  
@UPTIME VARCHAR(20),  
@SYSTEMID VARCHAR(20),  
@DISCOUNT VARCHAR(20),  
@RUNNO VARCHAR(20),  
@CASHID VARCHAR(20),  
@VATEXM VARCHAR(20),  
@TAX VARCHAR(20),  
@SC VARCHAR(20),  
@STNAMT VARCHAR(20),  
@MISCAMT VARCHAR(20),  
@METALID VARCHAR(20),  
@STONEUNIT VARCHAR(20),  
@APPVER VARCHAR(20),  
@TOUCH VARCHAR(20),  
@ESTSNO VARCHAR(20),  
@OTHERAMT VARCHAR(20),  
@FIN_DISCOUNT VARCHAR(20),  
@RATEID VARCHAR(20),  
@SETGRPID VARCHAR(20),  
@TRANFLAG VARCHAR(20),  
@EXDUTY VARCHAR(20),  
@EDC1 VARCHAR(20),  
@EDC2 VARCHAR(20),  
@EDC3 VARCHAR(20),  
@EDC1ID VARCHAR(10),  
@EDC2ID VARCHAR(10),  
@EDC3ID VARCHAR(10),  
@EDC1PER VARCHAR(10),  
@EDC2PER VARCHAR(10),  
@EDC3PER VARCHAR(10),  
@ORDSTATE_ID VARCHAR(10),  
@DISC_EMPID VARCHAR(10),  
@STKTYPE VARCHAR(1),  
@CHIT_DISCOUNT VARCHAR(20),  
@SGST VARCHAR(20),  
@CGST VARCHAR(20),  
@IGST VARCHAR(20),  
@SGSTPER VARCHAR(10),  
@CGSTPER VARCHAR(10),  
@IGSTPER VARCHAR(10),  
@EDSNO1 VARCHAR(20),  
@EDSNO2 VARCHAR(20),  
@EDSNO3 VARCHAR(20),  
@SGSTSNO VARCHAR(20),  
@CGSTSNO VARCHAR(20),  
@IGSTSNO VARCHAR(20),  
@ENTORDER VARCHAR(3),  
@CESS VARCHAR(20),  
@CESSPER VARCHAR(10),  
@CESSSNO VARCHAR(20),  
@HSNCODE VARCHAR(15),
@ISSNO VARCHAR(100)
)   
AS  
BEGIN  
DECLARE @PREFIXFORMAT VARCHAR(10)  
SELECT @PREFIXFORMAT=CTLTEXT FROM SFTADMINDB..SOFTCONTROL WHERE CTLID='BILLPREFIX_FORMAT'  
IF ISNULL(@PREFIXFORMAT,'')=''  
SET @PREFIXFORMAT='1'  
DECLARE @PREFIX VARCHAR(100)  
DECLARE @PDBNAME VARCHAR(8)  
SET @PREFIX =''  
SET @PDBNAME =''  
IF ISNULL(@PREFIXFORMAT,'')='' OR @PREFIXFORMAT='1'  
BEGIN  
SELECT @PDBNAME = RIGHT(LTRIM(@DBNAME),4)  
SELECT @PREFIX = @PREFIX + (CASE WHEN ISNULL(@COSTID,'')<>'' THEN @COSTID + '/' ELSE '' END)  
SELECT @PREFIX = @PREFIX + @TRANTYPE + '/' + @PDBNAME  
END  
IF @PREFIXFORMAT='2'  
BEGIN  
SELECT @PDBNAME = RIGHT(LTRIM(@DBNAME),4)  
SELECT @PREFIX = LEFT(@PDBNAME,2) + '-' + RIGHT(@PDBNAME,2)   
END  
DECLARE @TBILLPREFIX VARCHAR(10)   
SELECT @TBILLPREFIX =CTLTEXT FROM SFTADMINDB..SOFTCONTROL WHERE CTLID='BILL_PREFIX'  
IF @PREFIXFORMAT='3'  
BEGIN  
SELECT @PREFIX = @TBILLPREFIX /*+''+ @METALID*/   
END  
DECLARE @QRY NVARCHAR(4000)    
DECLARE @QUERY NVARCHAR(4000)  
--SELECT @QRY = ' INSERT INTO '+ @DBNAME +'..ISSUE (PCS'  
--SELECT @QRY = @QRY + ' ,GRSWT,NETWT,LESSWT,WASTPER,WASTAGE,MCGRM,MCHARGE,AMOUNT,RATE,EMPID,TAGPCS,TAGGRSWT,TAGNETWT,TAGRATEID,TAGSVALUE'  
--SELECT @QRY = @QRY + ' ,USERID,TAX,SC,STNAMT,MISCAMT,STONEUNIT,OTHERAMT,FIN_DISCOUNT,RATEID,CHIT_DISCOUNT) VALUES( '  
--SELECT @QRY = @QRY + ' '+@PCS+','+@GRSWT+','  
--SELECT @QRY = @QRY + ' '+@NETWT+','+@LESSWT+','  
--SELECT @QRY = @QRY + ' '+@WASTPER+','+@WASTAGE+','+@MCGRM+','+@MCHARGE+','+@AMOUNT+','+@RATE+','  
--SELECT @QRY = @QRY + ' '+@EMPID+','+@TAGPCS+','  
--SELECT @QRY = @QRY + ' '+@TAGGRSWT+','+@TAGNETWT+','+@TAGRATEID+','+@TAGSVALUE+','  
--SELECT @QRY = @QRY + ' '''+@USERID+''','  
--SELECT @QRY = @QRY + ' '''+@TAX+''','''+@SC+''','  
--SELECT @QRY = @QRY + ' '''+@STNAMT+''','''+@MISCAMT+''','  
--SELECT @QRY = @QRY + ' '''+@STONEUNIT+''','''+@OTHERAMT+''','''+@FIN_DISCOUNT+''','  
--SELECT @QRY = @QRY + ' '''+@RATEID+''','  
--SELECT @QRY = @QRY + ' '''+@CHIT_DISCOUNT+''')'  
SELECT @QRY = ' UPDATE '+ @DBNAME +'..ISSUE SET '  
SELECT @QRY = @QRY + ' PCS='+@PCS+',GRSWT='+@GRSWT+','  
SELECT @QRY = @QRY + ' NETWT='+@NETWT+',LESSWT='+@LESSWT+','  
SELECT @QRY = @QRY + ' WASTPER='+@WASTPER+',WASTAGE='+@WASTAGE+',MCGRM='+@MCGRM+',MCHARGE='+@MCHARGE+',AMOUNT='+@AMOUNT+',RATE='+@RATE+','  
SELECT @QRY = @QRY + ' EMPID='+@EMPID+',TAGPCS='+@TAGPCS+','  
SELECT @QRY = @QRY + ' TAGGRSWT='+@GRSWT+',TAGNETWT='+@NETWT+',TAGRATEID='+@TAGRATEID+',TAGSVALUE='+@TAGSVALUE+','  
SELECT @QRY = @QRY + ' USERID='+@USERID+','  
SELECT @QRY = @QRY + ' TAX='+@TAX+',SC='+@SC+','  
SELECT @QRY = @QRY + ' STNAMT='+@STNAMT+',MISCAMT='+@MISCAMT+','  
SELECT @QRY = @QRY + ' STONEUNIT='''+@STONEUNIT+''',OTHERAMT='+@OTHERAMT+',FIN_DISCOUNT='+@FIN_DISCOUNT+','  
SELECT @QRY = @QRY + ' RATEID='+@RATEID+','  
SELECT @QRY = @QRY + ' CHIT_DISCOUNT='+@CHIT_DISCOUNT+''
SELECT @QRY = @QRY + ' WHERE BATCHNO = '''+@BATCHNO+''' AND TAGNO = '''+@TAGNO+''''
PRINT @QRY  
EXECUTE SP_EXECUTESQL @QRY      

IF @COSTID <> ''  
BEGIN  
SELECT @QUERY=@QRY   
IF @QUERY <> '''' SET @QUERY = REPLACE(@QUERY,'''','''''')  
SELECT @QRY=' EXEC SP_SYNC_GENERATE @FROMID='''+ @FROMID+''',@QRY='''+ @QUERY +''',@MODE=''T'''  
PRINT @QRY  
EXECUTE SP_EXECUTESQL @QRY  
END  
IF @EXDUTY='TRUE'  
BEGIN  
IF @EDC1<>'0'  
BEGIN      
--SELECT @QRY = ' INSERT INTO '+ @DBNAME +'..TAXTRAN(SNO,ISSSNO,TRANNO,TRANDATE,TRANTYPE,BATCHNO,TAXID'  
--SELECT @QRY = @QRY + ' ,AMOUNT,TAXPER,TAXAMOUNT,TSNO) VALUES ('      
--SELECT @QRY = @QRY + ' '''+@EDSNO1+''','''+@SNO+''','+@TRANNO+','''+@TRANDATE+''','''+@TRANTYPE+''','''+@BATCHNO+''','''+@EDC1ID+''','  
--SELECT @QRY = @QRY + ' '+@AMOUNT+','+@EDC1PER+','+ @EDC1 +',''1'')'    
SELECT @QRY = ' UPDATE '+ @DBNAME +'..TAXTRAN SET'  
SELECT @QRY = @QRY + ' AMOUNT='+@AMOUNT+',TAXPER='+@EDC1PER+',TAXAMOUNT='+ @EDC1 +' '
SELECT @QRY = @QRY + ' WHERE BATCHNO = '''+@BATCHNO+''' AND TAXID='''+@EDC1ID+' AND ISSSNO = '''+ @ISSNO + ''''
SELECT @QRY = @QRY + ' AND STUDDED = ''N'''
PRINT @QRY  
EXECUTE SP_EXECUTESQL @QRY   
IF @COSTID <> ''  
BEGIN  
SELECT @QUERY=@QRY   
IF @QUERY <> '''' SET @QUERY = REPLACE(@QUERY,'''','''''')  
SELECT @QRY=' EXEC SP_SYNC_GENERATE @FROMID='''+ @FROMID+''',@QRY='''+ @QUERY +''',@MODE=''T'''  
PRINT @QRY  
EXECUTE SP_EXECUTESQL @QRY  
END  
END  
IF @EDC2<>'0'  
BEGIN      
--SELECT @QRY = ' INSERT INTO '+ @DBNAME +'..TAXTRAN(SNO,ISSSNO,TRANNO,TRANDATE,TRANTYPE,BATCHNO,TAXID'  
--SELECT @QRY = @QRY + ' ,AMOUNT,TAXPER,TAXAMOUNT,TSNO) VALUES ('      
--SELECT @QRY = @QRY + ' '''+@EDSNO2+''','''+@SNO+''','+@TRANNO+','''+@TRANDATE+''','''+@TRANTYPE+''','''+@BATCHNO+''','''+@EDC2ID+''','  
--SELECT @QRY = @QRY + ' '+@EDC1+','+@EDC2PER+','+ @EDC2 +',''2'')'    
SELECT @QRY = ' UPDATE '+ @DBNAME +'..TAXTRAN SET'  
SELECT @QRY = @QRY + ' AMOUNT='+@EDC1+',TAXPER='+@EDC2PER+',TAXAMOUNT='+ @EDC2 +' '
SELECT @QRY = @QRY + ' WHERE BATCHNO = '''+@BATCHNO+''' AND TAXID='''+@EDC2ID+' AND ISSSNO = '''+ @ISSNO +''''
SELECT @QRY = @QRY + ' AND STUDDED = ''N'''
PRINT @QRY  
EXECUTE SP_EXECUTESQL @QRY   
IF @COSTID <> ''  
BEGIN  
SELECT @QUERY=@QRY   
IF @QUERY <> '''' SET @QUERY = REPLACE(@QUERY,'''','''''')  
SELECT @QRY=' EXEC SP_SYNC_GENERATE @FROMID='''+ @FROMID+''',@QRY='''+ @QUERY +''',@MODE=''T'''  
PRINT @QRY  
EXECUTE SP_EXECUTESQL @QRY  
END  
END  
IF @EDC3<>'0'  
BEGIN      
--SELECT @QRY = ' INSERT INTO '+ @DBNAME +'..TAXTRAN(SNO,ISSSNO,TRANNO,TRANDATE,TRANTYPE,BATCHNO,TAXID'  
--SELECT @QRY = @QRY + ' ,AMOUNT,TAXPER,TAXAMOUNT,TSNO) VALUES ('      
--SELECT @QRY = @QRY + ' '''+@EDSNO3+''','''+@SNO+''','+@TRANNO+','''+@TRANDATE+''','''+@TRANTYPE+''','''+@BATCHNO+''','''+@EDC3ID+''','  
--SELECT @QRY = @QRY + ' '+@EDC1+','+@EDC3PER+','+ @EDC3 +',''3'')'    
SELECT @QRY = ' UPDATE '+ @DBNAME +'..TAXTRAN SET'  
SELECT @QRY = @QRY + ' AMOUNT='+@EDC1+',TAXPER='+@EDC3PER+',TAXAMOUNT='+ @EDC3 +' '
SELECT @QRY = @QRY + ' WHERE BATCHNO = '''+@BATCHNO+''' AND TAXID='''+@EDC3ID+' AND ISSSNO = '''+ @ISSNO +''''
SELECT @QRY = @QRY + ' AND STUDDED = ''N'''
PRINT @QRY  
EXECUTE SP_EXECUTESQL @QRY   
IF @COSTID <> ''  
BEGIN  
SELECT @QUERY=@QRY   
IF @QUERY <> '''' SET @QUERY = REPLACE(@QUERY,'''','''''')  
SELECT @QRY=' EXEC SP_SYNC_GENERATE @FROMID='''+ @FROMID+''',@QRY='''+ @QUERY +''',@MODE=''T'''  
PRINT @QRY  
EXECUTE SP_EXECUTESQL @QRY  
END  
END  
END  
IF @SGST<>'0'  
BEGIN      
--SELECT @QRY = ' INSERT INTO '+ @DBNAME +'..TAXTRAN(SNO,ISSSNO,TRANNO,TRANDATE,TRANTYPE,BATCHNO,TAXID'  
--SELECT @QRY = @QRY + ' ,AMOUNT,TAXPER,TAXAMOUNT,TSNO,STUDDED,COSTID,COMPANYID) VALUES ('      
--SELECT @QRY = @QRY + ' '''+@SGSTSNO+''','''+@SNO+''','+@TRANNO+','''+@TRANDATE+''','''+@TRANTYPE+''','''+@BATCHNO+''',''SG'','  
--SELECT @QRY = @QRY + ' '+@AMOUNT+','+@SGSTPER+','+ @SGST +',''1'',''N'','''+@COSTID+''','''+@COMPANYID+''')'    
SELECT @QRY = ' UPDATE '+ @DBNAME +'..TAXTRAN SET'  
SELECT @QRY = @QRY + ' AMOUNT='+@AMOUNT+',TAXPER='+@SGSTPER+',TAXAMOUNT='+ @SGST +''
SELECT @QRY = @QRY + ' WHERE BATCHNO = '''+@BATCHNO+''' AND TAXID=''SG'' AND ISSSNO = '''+ @ISSNO +''''
SELECT @QRY = @QRY + ' AND STUDDED = ''N'''
PRINT @QRY  
EXECUTE SP_EXECUTESQL @QRY   
IF @COSTID <> ''  
BEGIN  
SELECT @QUERY=@QRY   
IF @QUERY <> '''' SET @QUERY = REPLACE(@QUERY,'''','''''')  
SELECT @QRY=' EXEC SP_SYNC_GENERATE @FROMID='''+ @FROMID+''',@QRY='''+ @QUERY +''',@MODE=''T'''  
PRINT @QRY  
EXECUTE SP_EXECUTESQL @QRY  
END  
END  
IF @CGST<>'0'  
BEGIN      
--SELECT @QRY = ' INSERT INTO '+ @DBNAME +'..TAXTRAN(SNO,ISSSNO,TRANNO,TRANDATE,TRANTYPE,BATCHNO,TAXID'  
--SELECT @QRY = @QRY + ' ,AMOUNT,TAXPER,TAXAMOUNT,TSNO,STUDDED,COSTID,COMPANYID) VALUES ('      
--SELECT @QRY = @QRY + ' '''+@CGSTSNO+''','''+@SNO+''','+@TRANNO+','''+@TRANDATE+''','''+@TRANTYPE+''','''+@BATCHNO+''',''CG'','  
--SELECT @QRY = @QRY + ' '+@AMOUNT+','+@CGSTPER+','+ @CGST +',''2'',''N'','''+@COSTID+''','''+@COMPANYID+''')'    
SELECT @QRY = ' UPDATE '+ @DBNAME +'..TAXTRAN SET'  
SELECT @QRY = @QRY + ' AMOUNT='+@AMOUNT+',TAXPER='+@CGSTPER+',TAXAMOUNT='+ @CGST +''
SELECT @QRY = @QRY + ' WHERE BATCHNO = '''+@BATCHNO+''' AND TAXID=''CG'' AND ISSSNO = '''+ @ISSNO +''''
SELECT @QRY = @QRY + ' AND STUDDED = ''N'''
PRINT @QRY  
EXECUTE SP_EXECUTESQL @QRY   
IF @COSTID <> ''  
BEGIN  
SELECT @QUERY=@QRY   
IF @QUERY <> '''' SET @QUERY = REPLACE(@QUERY,'''','''''')  
SELECT @QRY=' EXEC SP_SYNC_GENERATE @FROMID='''+ @FROMID+''',@QRY='''+ @QUERY +''',@MODE=''T'''  
PRINT @QRY  
EXECUTE SP_EXECUTESQL @QRY  
END  
END  
IF @IGST<>'0'  
BEGIN      
--SELECT @QRY = ' INSERT INTO '+ @DBNAME +'..TAXTRAN(SNO,ISSSNO,TRANNO,TRANDATE,TRANTYPE,BATCHNO,TAXID'  
--SELECT @QRY = @QRY + ' ,AMOUNT,TAXPER,TAXAMOUNT,TSNO,STUDDED,COSTID,COMPANYID) VALUES ('      
--SELECT @QRY = @QRY + ' '''+@IGSTSNO+''','''+@SNO+''','+@TRANNO+','''+@TRANDATE+''','''+@TRANTYPE+''','''+@BATCHNO+''',''IG'','  
--SELECT @QRY = @QRY + ' '+@AMOUNT+','+@IGSTPER+','+ @IGST +',''3'',''N'','''+@COSTID+''','''+@COMPANYID+''')'    
SELECT @QRY = ' UPDATE '+ @DBNAME +'..TAXTRAN SET'  
SELECT @QRY = @QRY + ' AMOUNT='+@AMOUNT+',TAXPER='+@IGSTPER+',TAXAMOUNT='+ @IGST +''
SELECT @QRY = @QRY + ' WHERE BATCHNO = '''+@BATCHNO+''' AND TAXID=''IG'' AND ISSSNO = '''+ @ISSNO +''''
SELECT @QRY = @QRY + ' AND STUDDED = ''N'''
PRINT @QRY  
EXECUTE SP_EXECUTESQL @QRY   
IF @COSTID <> ''  
BEGIN  
SELECT @QUERY=@QRY   
IF @QUERY <> '''' SET @QUERY = REPLACE(@QUERY,'''','''''')  
SELECT @QRY=' EXEC SP_SYNC_GENERATE @FROMID='''+ @FROMID+''',@QRY='''+ @QUERY +''',@MODE=''T'''  
PRINT @QRY  
EXECUTE SP_EXECUTESQL @QRY  
END  
END  
IF @CESS<>'0'  
BEGIN      
--SELECT @QRY = ' INSERT INTO '+ @DBNAME +'..TAXTRAN(SNO,ISSSNO,TRANNO,TRANDATE,TRANTYPE,BATCHNO,TAXID'  
--SELECT @QRY = @QRY + ' ,AMOUNT,TAXPER,TAXAMOUNT,TSNO,STUDDED,COSTID,COMPANYID) VALUES ('      
--SELECT @QRY = @QRY + ' '''+@CESSSNO+''','''+@SNO+''','+@TRANNO+','''+@TRANDATE+''','''+@TRANTYPE+''','''+@BATCHNO+''',''CS'','  
--SELECT @QRY = @QRY + ' '+@AMOUNT+','+@CESSPER+','+ @CESS +',''4'',''N'','''+@COSTID+''','''+@COMPANYID+''')'    
SELECT @QRY = ' UPDATE '+ @DBNAME +'..TAXTRAN SET'  
SELECT @QRY = @QRY + ' AMOUNT='+@AMOUNT+',TAXPER='+@CESSPER+',TAXAMOUNT='+ @CESS +''
SELECT @QRY = @QRY + ' WHERE BATCHNO = '''+@BATCHNO+''' AND TAXID=''CS'' AND ISSSNO = '''+ @ISSNO +''''
SELECT @QRY = @QRY + ' AND STUDDED = ''N'''
PRINT @QRY  
EXECUTE SP_EXECUTESQL @QRY   
IF @COSTID <> ''  
BEGIN  
SELECT @QUERY=@QRY   
IF @QUERY <> '''' SET @QUERY = REPLACE(@QUERY,'''','''''')  
SELECT @QRY=' EXEC SP_SYNC_GENERATE @FROMID='''+ @FROMID+''',@QRY='''+ @QUERY +''',@MODE=''T'''  
PRINT @QRY  
EXECUTE SP_EXECUTESQL @QRY  
END  
END  
END
