

 Create PROCEDURE SP_UPDATE_RECEIPT  
 (  
 @FROMID VARCHAR(5),  
 @DBNAME VARCHAR(20),  
 @SNO VARCHAR(20),      
 @TRANNO VARCHAR(15),      
 @TRANDATE VARCHAR(20),    
 @TRANTYPE VARCHAR(5),      
 @PCS VARCHAR(15),  
 @GRSWT VARCHAR(20),  
 @NETWT VARCHAR(20),  
 @LESSWT VARCHAR(20),  
 @PUREWT VARCHAR(20),  
 @TAGNO VARCHAR(20),  
 @ITEMID VARCHAR(20),  
 @SUBITEMID VARCHAR(20),  
 @WASTPER VARCHAR(20),  
 @WASTAGE VARCHAR(20),  
 @MCGRM VARCHAR(20),  
 @MCHARGE VARCHAR(20),  
 @AMOUNT VARCHAR(20),   
 @RATE VARCHAR(20),  
 @BOARDRATE VARCHAR(20),  
 @SALEMODE VARCHAR(20),   
 @GRSNET VARCHAR(20),  
 @TRANSTATUS VARCHAR(20),  
 @REFNO VARCHAR(20),  
 @REFDATE VARCHAR(20),  
 @COSTID VARCHAR(20),  
 @COMPANYID VARCHAR(20),  
 @FLAG VARCHAR(20),  
 @EMPID VARCHAR(20),  
 @TAGPCS VARCHAR(20),  
 @TAGGRSWT VARCHAR(20),  
 @TAGNETWT VARCHAR(20),  
 @TAGRATEID VARCHAR(20),  
 @TAGSVALUE VARCHAR(20),  
 @TAGDESIGNER VARCHAR(20),  
 @ITEMCTRID VARCHAR(20),  
 @ITEMTYPEID VARCHAR(20),  
 @PURITY VARCHAR(20),  
 @TABLECODE VARCHAR(20),  
 @INCENTIVE VARCHAR(20),  
 @WEIGHTUNIT VARCHAR(20),  
 @CATCODE VARCHAR(20),  
 @OCATCODE VARCHAR(20),  
 @ACCODE VARCHAR(15),  
 @ALLOY VARCHAR(20),  
 @BATCHNO VARCHAR(25),  
 @REMARK1 VARCHAR(100),  
 @REMARK2 VARCHAR(100),  
 @USERID VARCHAR(20),  
 @UPDATED VARCHAR(20),  
 @UPTIME VARCHAR(20),  
 @SYSTEMID VARCHAR(20),  
 @DISCOUNT VARCHAR(20),  
 @RUNNO VARCHAR(20),  
 @CASHID VARCHAR(20),  
 @VATEXM VARCHAR(20),  
 @TAX VARCHAR(20),  
 @SC VARCHAR(20),  
 @DUSTWT VARCHAR(20),  
 @MELTWT VARCHAR(20),  
 @PUREXCH VARCHAR(20),  
 @MAKE VARCHAR(20),  
 @STNAMT VARCHAR(20),  
 @MISCAMT VARCHAR(20),  
 @METALID VARCHAR(20),  
 @STONEUNIT VARCHAR(20),  
 @APPVER VARCHAR(20),  
 @TOUCH VARCHAR(20),  
 @ESTSNO VARCHAR(20),  
 @OTHERAMT VARCHAR(20),  
 @FIN_DISCOUNT VARCHAR(20),  
 @RATEID VARCHAR(20),  
 @SETGRPID VARCHAR(20),  
 @TRANFLAG VARCHAR(20),  
 @EXDUTY VARCHAR(20),  
 @EDC1 VARCHAR(20),  
 @EDC2 VARCHAR(20),  
 @EDC3 VARCHAR(20),  
 @EDC1ID VARCHAR(10),  
 @EDC2ID VARCHAR(10),  
 @EDC3ID VARCHAR(10),  
 @EDC1PER VARCHAR(10),  
 @EDC2PER VARCHAR(10),  
 @EDC3PER VARCHAR(10),  
 @ORDSTATE_ID VARCHAR(10),  
 @DISC_EMPID VARCHAR(10),  
 @STKTYPE VARCHAR(1),  
 @SGST VARCHAR(20),  
 @CGST VARCHAR(20),  
 @IGST VARCHAR(20),  
 @SGSTPER VARCHAR(10),  
 @CGSTPER VARCHAR(10),  
 @IGSTPER VARCHAR(10),  
 @EDSNO1 VARCHAR(20),  
 @EDSNO2 VARCHAR(20),  
 @EDSNO3 VARCHAR(20),  
 @SGSTSNO VARCHAR(20),  
 @CGSTSNO VARCHAR(20),  
 @IGSTSNO VARCHAR(20),  
 @ENTORDER VARCHAR(3),  
 @CESS VARCHAR(20),  
 @CESSPER VARCHAR(10),  
 @CESSSNO VARCHAR(20),  
 @HSNCODE VARCHAR(15),
 @WT_ENTORDER VARCHAR(15)
 )   
 AS  
 BEGIN  
 DECLARE @PREFIXFORMAT VARCHAR(10)  
 SELECT @PREFIXFORMAT=CTLTEXT FROM SFTADMINDB..SOFTCONTROL WHERE CTLID='BILLPREFIX_FORMAT'  
 IF ISNULL(@PREFIXFORMAT,'')=''  
  SET @PREFIXFORMAT='1'  
  DECLARE @PREFIX VARCHAR(100)  
  DECLARE @PDBNAME VARCHAR(8)  
  SET @PREFIX =''  
  SET @PDBNAME =''  
 IF ISNULL(@PREFIXFORMAT,'')='' OR @PREFIXFORMAT='1'  
 BEGIN  
   SELECT @PDBNAME = RIGHT(LTRIM(@DBNAME),4)  
   SELECT @PREFIX = @PREFIX + (CASE WHEN ISNULL(@COSTID,'')<>'' THEN @COSTID + '/' ELSE '' END)  
   SELECT @PREFIX = @PREFIX + @TRANTYPE + '/' + @PDBNAME  
 END  
 IF @PREFIXFORMAT='2'  
 BEGIN  
   SELECT @PDBNAME = RIGHT(LTRIM(@DBNAME),4)  
   SELECT @PREFIX = LEFT(@PDBNAME,2) + '-' + RIGHT(@PDBNAME,2)   
 END  
    DECLARE @TBILLPREFIX VARCHAR(10)   
  SELECT @TBILLPREFIX =CTLTEXT FROM SFTADMINDB..SOFTCONTROL WHERE CTLID='BILL_PREFIX'  
  IF @PREFIXFORMAT='3'  
  BEGIN  
    SELECT @PREFIX = @TBILLPREFIX /*+''+ @METALID*/   
  END  
  DECLARE @QRY NVARCHAR(4000)    
  DECLARE @QUERY NVARCHAR(4000)  
  SELECT @QRY = ' UPDATE '+ @DBNAME +'..RECEIPT SET '    
  SELECT @QRY = @QRY + ' PCS = ' + @PCS + ',GRSWT='+@GRSWT+',NETWT='+@NETWT+',LESSWT='+@LESSWT+',PUREWT='+@PUREWT+',WASTPER='+@WASTPER+',WASTAGE='+@WASTAGE+''
  SELECT @QRY = @QRY + ' ,MCGRM='+@MCGRM+',MCHARGE='+@MCHARGE+',AMOUNT='+@AMOUNT+',PURITY='+@PURITY+',CATCODE='''+@CATCODE+''',REMARK1='''+@REMARK1+''''  
  SELECT @QRY = @QRY + ' ,DUSTWT='+@DUSTWT+',MELTWT='+@MELTWT+''
  SELECT @QRY = @QRY + ' WHERE WT_ENTORDER = '+@WT_ENTORDER+' AND BATCHNO = '''+@BATCHNO+''''
  PRINT @QRY  
  EXECUTE SP_EXECUTESQL @QRY      
  IF @COSTID <> ''  
  SELECT @QUERY=@QRY   
  BEGIN  
   IF @QUERY <> '''' SET @QUERY = REPLACE(@QUERY,'''','''''')  
   SELECT @QRY=' EXEC SP_SYNC_GENERATE @FROMID='''+ @FROMID+''',@QRY='''+ @QUERY +''',@MODE=''T'''  
   PRINT @QRY  
   EXECUTE SP_EXECUTESQL @QRY  
  END     
  IF @SGST<>'0'  
  BEGIN      
   SELECT @QRY = ' INSERT INTO '+ @DBNAME +'..TAXTRAN(SNO,ISSSNO,TRANNO,TRANDATE,TRANTYPE,BATCHNO,TAXID'  
   SELECT @QRY = @QRY + ' ,AMOUNT,TAXPER,TAXAMOUNT,TSNO,STUDDED,COSTID,COMPANYID) VALUES ('      
   SELECT @QRY = @QRY + ' '''+@SGSTSNO+''','''+@SNO+''','+@TRANNO+','''+@TRANDATE+''','''+@TRANTYPE+''','''+@BATCHNO+''',''SG'','  
   SELECT @QRY = @QRY + ' '+@AMOUNT+','+@SGSTPER+','+ @SGST +',''1'',''N'','''+@COSTID+''','''+@COMPANYID+''')'    
   PRINT @QRY  
   EXECUTE SP_EXECUTESQL @QRY   
   IF @COSTID <> ''  
   BEGIN  
    SELECT @QUERY=@QRY   
    IF @QUERY <> '''' SET @QUERY = REPLACE(@QUERY,'''','''''')  
    SELECT @QRY=' EXEC SP_SYNC_GENERATE @FROMID='''+ @FROMID+''',@QRY='''+ @QUERY +''',@MODE=''T'''  
    PRINT @QRY  
    EXECUTE SP_EXECUTESQL @QRY  
   END  
  END  
  IF @CGST<>'0'  
  BEGIN      
   SELECT @QRY = ' INSERT INTO '+ @DBNAME +'..TAXTRAN(SNO,ISSSNO,TRANNO,TRANDATE,TRANTYPE,BATCHNO,TAXID'  
   SELECT @QRY = @QRY + ' ,AMOUNT,TAXPER,TAXAMOUNT,TSNO,STUDDED,COSTID,COMPANYID) VALUES ('      
   SELECT @QRY = @QRY + ' '''+@CGSTSNO+''','''+@SNO+''','+@TRANNO+','''+@TRANDATE+''','''+@TRANTYPE+''','''+@BATCHNO+''',''CG'','  
   SELECT @QRY = @QRY + ' '+@AMOUNT+','+@CGSTPER+','+ @CGST +',''2'',''N'','''+@COSTID+''','''+@COMPANYID+''')'    
   PRINT @QRY  
   EXECUTE SP_EXECUTESQL @QRY   
   IF @COSTID <> ''  
   BEGIN  
    SELECT @QUERY=@QRY   
    IF @QUERY <> '''' SET @QUERY = REPLACE(@QUERY,'''','''''')  
    SELECT @QRY=' EXEC SP_SYNC_GENERATE @FROMID='''+ @FROMID+''',@QRY='''+ @QUERY +''',@MODE=''T'''  
    PRINT @QRY  
    EXECUTE SP_EXECUTESQL @QRY  
   END  
  END  
  IF @IGST<>'0'  
  BEGIN      
   SELECT @QRY = ' INSERT INTO '+ @DBNAME +'..TAXTRAN(SNO,ISSSNO,TRANNO,TRANDATE,TRANTYPE,BATCHNO,TAXID'  
   SELECT @QRY = @QRY + ' ,AMOUNT,TAXPER,TAXAMOUNT,TSNO,STUDDED,COSTID,COMPANYID) VALUES ('      
   SELECT @QRY = @QRY + ' '''+@IGSTSNO+''','''+@SNO+''','+@TRANNO+','''+@TRANDATE+''','''+@TRANTYPE+''','''+@BATCHNO+''',''IG'','  
   SELECT @QRY = @QRY + ' '+@AMOUNT+','+@IGSTPER+','+ @IGST +',''3'',''N'','''+@COSTID+''','''+@COMPANYID+''')'    
   PRINT @QRY  
   EXECUTE SP_EXECUTESQL @QRY   
   IF @COSTID <> ''  
   BEGIN  
    SELECT @QUERY=@QRY   
    IF @QUERY <> '''' SET @QUERY = REPLACE(@QUERY,'''','''''')  
    SELECT @QRY=' EXEC SP_SYNC_GENERATE @FROMID='''+ @FROMID+''',@QRY='''+ @QUERY +''',@MODE=''T'''  
    PRINT @QRY  
    EXECUTE SP_EXECUTESQL @QRY  
   END  
  END  
  IF @CESS<>'0'  
  BEGIN      
   SELECT @QRY = ' INSERT INTO '+ @DBNAME +'..TAXTRAN(SNO,ISSSNO,TRANNO,TRANDATE,TRANTYPE,BATCHNO,TAXID'  
   SELECT @QRY = @QRY + ' ,AMOUNT,TAXPER,TAXAMOUNT,TSNO,STUDDED,COSTID,COMPANYID) VALUES ('      
   SELECT @QRY = @QRY + ' '''+@CESSSNO+''','''+@SNO+''','+@TRANNO+','''+@TRANDATE+''','''+@TRANTYPE+''','''+@BATCHNO+''',''CS'','  
   SELECT @QRY = @QRY + ' '+@AMOUNT+','+@CESSPER+','+ @CESS +',''4'',''N'','''+@COSTID+''','''+@COMPANYID+''')'    
   PRINT @QRY  
   EXECUTE SP_EXECUTESQL @QRY   
   IF @COSTID <> ''  
   BEGIN  
    SELECT @QUERY=@QRY   
    IF @QUERY <> '''' SET @QUERY = REPLACE(@QUERY,'''','''''')  
    SELECT @QRY=' EXEC SP_SYNC_GENERATE @FROMID='''+ @FROMID+''',@QRY='''+ @QUERY +''',@MODE=''T'''  
    PRINT @QRY  
    EXECUTE SP_EXECUTESQL @QRY  
   END  
  END  
 END
