CREATE PROCEDURE SP_UPDATE_ADJTRAN  
(  
@FROMID VARCHAR(2),  
@DBNAME VARCHAR(20),  
@SNO VARCHAR(20),  
@TRANNO VARCHAR(15),  
@TRANDATE VARCHAR(20),  
@RECPAY VARCHAR(1),  
@CASH VARCHAR(20),  
@MOBILE VARCHAR(30),  
@PAN VARCHAR(30),  
@ACCODE VARCHAR(7),  
@COSTID VARCHAR(2),  
@COMPANYID VARCHAR(3),  
@BATCHNO VARCHAR(25)  
)   
AS  
BEGIN  
 DECLARE @QRY NVARCHAR(4000)    
 DECLARE @QUERY NVARCHAR(4000)  
 SELECT @QRY = ' UPDATE '+ @DBNAME +'..ADJTRAN '  
 SELECT @QRY = @QRY + ' SET '  
 SELECT @QRY = @QRY + ' CASH = '+@CASH+' '  
 SELECT @QRY = @QRY + ' WHERE BATCHNO = '''+@BATCHNO+''' '  
 PRINT @QRY  
 EXECUTE SP_EXECUTESQL @QRY      
    IF @COSTID <> ''  
    BEGIN  
        SELECT @QUERY=@QRY   
        BEGIN  
            IF @QUERY <> '''' SET @QUERY = REPLACE(@QUERY,'''','''''')  
            SELECT @QRY=' EXEC SP_SYNC_GENERATE @FROMID='''+ @FROMID+''',@QRY='''+ @QUERY +''',@MODE=''M'''  
            PRINT @QRY  
            EXECUTE SP_EXECUTESQL @QRY  
        END     
    END  
END
