ALTER PROCEDURE SP_UPDATE_ISSUESTONE  
(  
@FROMID VARCHAR(5),  
@DBNAME VARCHAR(20),  
@SNO VARCHAR(20),  
@ISSSNO VARCHAR(20),      
@TRANNO VARCHAR(15),      
@TRANDATE VARCHAR(20),    
@TRANTYPE VARCHAR(5),      
@STNPCS VARCHAR(15),  
@STNWT VARCHAR(20),  
@STNRATE VARCHAR(20),  
@STNAMT VARCHAR(20),  
@STNITEMID VARCHAR(20),  
@STNSUBITEMID VARCHAR(20),  
@CALCMODE VARCHAR(20),  
@STONEUNIT VARCHAR(20),  
@STONEMODE VARCHAR(20),  
@TRANSTATUS VARCHAR(20),  
@COSTID VARCHAR(20),  
@COMPANYID VARCHAR(20),  
@BATCHNO VARCHAR(25),  
@SYSTEMID VARCHAR(20),  
@VATEXM VARCHAR(20),  
@CATCODE VARCHAR(20),  
@TAX VARCHAR(20),  
@APPVER VARCHAR(20),  
@DISCOUNT VARCHAR(20),  
@TAGSTNPCS VARCHAR(20),  
@TAGSTNWT VARCHAR(20),      
@CUTID VARCHAR(5),  
@COLORID VARCHAR(5),  
@CLARITYID VARCHAR(5),  
@SHAPEID VARCHAR(5),  
@SETTYPEID VARCHAR(5),  
@HEIGHT VARCHAR(5),  
@WIDTH VARCHAR(5),  
@SGST VARCHAR(20),  
@CGST VARCHAR(20),  
@IGST VARCHAR(20),  
@CESS VARCHAR(20),  
@SGSTPER VARCHAR(10),  
@CGSTPER VARCHAR(10),  
@IGSTPER VARCHAR(10),  
@CESSPER VARCHAR(10),  
@SGSTSNO VARCHAR(20),  
@CGSTSNO VARCHAR(20),  
@IGSTSNO VARCHAR(20),  
@CESSSNO VARCHAR(20),  
@ISMSNO VARCHAR(20),
@ISSSTNSNO VARCHAR(20)
)   
AS  
BEGIN  
 DECLARE @QRY NVARCHAR(4000)    
 DECLARE @QUERY NVARCHAR(4000)  
 SELECT @QRY = ' UPDATE '+ @DBNAME +'..ISSSTONE SET '  
 SELECT @QRY = @QRY + ' STNPCS = '+@STNPCS+','  
 SELECT @QRY = @QRY + ' STNWT = '+@STNWT+', STNRATE = '+@STNRATE+', STNAMT = '+@STNAMT+', '  
 SELECT @QRY = @QRY + ' TAX = '+@TAX+', '  
 SELECT @QRY = @QRY + ' DISCOUNT = '+@DISCOUNT+', TAGSTNPCS = '+@TAGSTNPCS+', TAGSTNWT = '+@TAGSTNWT+' '  
 SELECT @QRY = @QRY + ' WHERE ISSSNO = '''+@ISSSNO+''''
 SELECT @QRY = @QRY + ' AND STNITEMID = '+@STNITEMID+' AND STNSUBITEMID = '+@STNSUBITEMID+''
 PRINT @QRY  
 EXECUTE SP_EXECUTESQL @QRY     
 IF @COSTID <> ''  
 BEGIN  
  SELECT @QUERY=@QRY   
  IF @QUERY <> '''' SET @QUERY = REPLACE(@QUERY,'''','''''')  
  SELECT @QRY=' EXEC SP_SYNC_GENERATE @FROMID='''+ @FROMID+''',@QRY='''+ @QUERY +''',@MODE=''T'''  
  PRINT @QRY  
  EXECUTE SP_EXECUTESQL @QRY  
 END  
 IF @SGST<>'0'  
 BEGIN      
  --SELECT @QRY = ' INSERT INTO '+ @DBNAME +'..TAXTRAN(SNO,ISSSNO,TRANNO,TRANDATE,TRANTYPE,BATCHNO,TAXID'  
  --SELECT @QRY = @QRY + ' ,AMOUNT,TAXPER,TAXAMOUNT,TSNO,STUDDED,COSTID,COMPANYID) VALUES ('      
  --SELECT @QRY = @QRY + ' '''+@SGSTSNO+''','''+@SNO+''','+@TRANNO+','''+@TRANDATE+''','''+@TRANTYPE+''','''+@BATCHNO+''',''SG'','  
  --SELECT @QRY = @QRY + ' '+@STNAMT+','+@SGSTPER+','+ @SGST +',''1'',''Y'','''+@COSTID+''','''+@COMPANYID+''')'    
  SELECT @QRY = ' UPDATE '+ @DBNAME +'..TAXTRAN SET'    
  SELECT @QRY = @QRY + ' AMOUNT='+@STNAMT+',TAXPER='+@SGSTPER+',TAXAMOUNT='+ @SGST +''  
  SELECT @QRY = @QRY + ' WHERE BATCHNO = '''+@BATCHNO+''' AND TAXID=''SG'' AND ISSSNO = '''+ @ISSSTNSNO +''''  
  SELECT @QRY = @QRY + ' AND STUDDED = ''Y'''
  PRINT @QRY  
  EXECUTE SP_EXECUTESQL @QRY   
  IF @COSTID <> ''  
  BEGIN  
   SELECT @QUERY=@QRY   
   IF @QUERY <> '''' SET @QUERY = REPLACE(@QUERY,'''','''''')  
   SELECT @QRY=' EXEC SP_SYNC_GENERATE @FROMID='''+ @FROMID+''',@QRY='''+ @QUERY +''',@MODE=''T'''  
   PRINT @QRY  
   EXECUTE SP_EXECUTESQL @QRY  
  END  
 END  
 IF @CGST<>'0'  
 BEGIN      
  --SELECT @QRY = ' INSERT INTO '+ @DBNAME +'..TAXTRAN(SNO,ISSSNO,TRANNO,TRANDATE,TRANTYPE,BATCHNO,TAXID'  
  --SELECT @QRY = @QRY + ' ,AMOUNT,TAXPER,TAXAMOUNT,TSNO,STUDDED,COSTID,COMPANYID) VALUES ('      
  --SELECT @QRY = @QRY + ' '''+@CGSTSNO+''','''+@SNO+''','+@TRANNO+','''+@TRANDATE+''','''+@TRANTYPE+''','''+@BATCHNO+''',''CG'','  
  --SELECT @QRY = @QRY + ' '+@STNAMT+','+@CGSTPER+','+ @CGST +',''2'',''Y'','''+@COSTID+''','''+@COMPANYID+''')'    
  SELECT @QRY = ' UPDATE '+ @DBNAME +'..TAXTRAN SET'    
  SELECT @QRY = @QRY + ' AMOUNT='+@STNAMT+',TAXPER='+@CGSTPER+',TAXAMOUNT='+ @CGST +''  
  SELECT @QRY = @QRY + ' WHERE BATCHNO = '''+@BATCHNO+''' AND TAXID=''CG'' AND ISSSNO = '''+ @ISSSTNSNO +''''  
  SELECT @QRY = @QRY + ' AND STUDDED = ''Y'''
  PRINT @QRY  
  EXECUTE SP_EXECUTESQL @QRY   
  IF @COSTID <> ''  
  BEGIN  
   SELECT @QUERY=@QRY   
   IF @QUERY <> '''' SET @QUERY = REPLACE(@QUERY,'''','''''')  
   SELECT @QRY=' EXEC SP_SYNC_GENERATE @FROMID='''+ @FROMID+''',@QRY='''+ @QUERY +''',@MODE=''T'''  
   PRINT @QRY  
   EXECUTE SP_EXECUTESQL @QRY  
  END  
 END  
 IF @IGST<>'0'  
 BEGIN      
  --SELECT @QRY = ' INSERT INTO '+ @DBNAME +'..TAXTRAN(SNO,ISSSNO,TRANNO,TRANDATE,TRANTYPE,BATCHNO,TAXID'  
  --SELECT @QRY = @QRY + ' ,AMOUNT,TAXPER,TAXAMOUNT,TSNO,STUDDED,COSTID,COMPANYID) VALUES ('      
  --SELECT @QRY = @QRY + ' '''+@IGSTSNO+''','''+@SNO+''','+@TRANNO+','''+@TRANDATE+''','''+@TRANTYPE+''','''+@BATCHNO+''',''IG'','  
  --SELECT @QRY = @QRY + ' '+@STNAMT+','+@IGSTPER+','+ @IGST +',''3'',''Y'','''+@COSTID+''','''+@COMPANYID+''')'  
  SELECT @QRY = ' UPDATE '+ @DBNAME +'..TAXTRAN SET'    
  SELECT @QRY = @QRY + ' AMOUNT='+@STNAMT+',TAXPER='+@IGSTPER+',TAXAMOUNT='+ @IGST +''  
  SELECT @QRY = @QRY + ' WHERE BATCHNO = '''+@BATCHNO+''' AND TAXID=''IG'' AND ISSSNO = '''+ @ISSSTNSNO +''''  
  SELECT @QRY = @QRY + ' AND STUDDED = ''Y'''
  PRINT @QRY  
  EXECUTE SP_EXECUTESQL @QRY   
  IF @COSTID <> ''  
  BEGIN  
   SELECT @QUERY=@QRY   
   IF @QUERY <> '''' SET @QUERY = REPLACE(@QUERY,'''','''''')  
   SELECT @QRY=' EXEC SP_SYNC_GENERATE @FROMID='''+ @FROMID+''',@QRY='''+ @QUERY +''',@MODE=''T'''  
   PRINT @QRY  
   EXECUTE SP_EXECUTESQL @QRY  
  END  
 END  
 IF @CESS<>'0'  
 BEGIN      
  --SELECT @QRY = ' INSERT INTO '+ @DBNAME +'..TAXTRAN(SNO,ISSSNO,TRANNO,TRANDATE,TRANTYPE,BATCHNO,TAXID'  
  --SELECT @QRY = @QRY + ' ,AMOUNT,TAXPER,TAXAMOUNT,TSNO,STUDDED,COSTID,COMPANYID) VALUES ('      
  --SELECT @QRY = @QRY + ' '''+@CESSSNO+''','''+@SNO+''','+@TRANNO+','''+@TRANDATE+''','''+@TRANTYPE+''','''+@BATCHNO+''',''CS'','  
  --SELECT @QRY = @QRY + ' '+@STNAMT+','+@CESSPER+','+ @CESS +',''4'',''Y'','''+@COSTID+''','''+@COMPANYID+''')'    
  SELECT @QRY = ' UPDATE '+ @DBNAME +'..TAXTRAN SET'    
  SELECT @QRY = @QRY + ' AMOUNT='+@STNAMT+',TAXPER='+@CESSPER+',TAXAMOUNT='+ @CESS +''  
  SELECT @QRY = @QRY + ' WHERE BATCHNO = '''+@BATCHNO+''' AND TAXID=''CS'' AND ISSSNO = '''+ @ISSSTNSNO +''''  
  SELECT @QRY = @QRY + ' AND STUDDED = ''Y'''
  PRINT @QRY  
  EXECUTE SP_EXECUTESQL @QRY   
  IF @COSTID <> ''  
  BEGIN  
   SELECT @QUERY=@QRY   
   IF @QUERY <> '''' SET @QUERY = REPLACE(@QUERY,'''','''''')  
   SELECT @QRY=' EXEC SP_SYNC_GENERATE @FROMID='''+ @FROMID+''',@QRY='''+ @QUERY +''',@MODE=''T'''  
   PRINT @QRY  
   EXECUTE SP_EXECUTESQL @QRY  
  END  
 END  
END
