'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BrighttechRetailJewellery.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Akashaya() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Akashaya", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property approval_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("approval_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property approval1_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("approval1_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AquaBall_Blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AquaBall_Blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BillApproval() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillApproval", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BillGiftVoucher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillGiftVoucher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BillMiscIssue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillMiscIssue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BillOrderRepair() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillOrderRepair", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BillPurchase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillPurchase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BillReceiptPayment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillReceiptPayment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BillReturn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillReturn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BillSales() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BillSales", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Button_Gray_Stripe_01_050() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button_Gray_Stripe_01_050", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CamIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CamIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO ACCENTRYMASTER ( SNO,CAPTION,TYPE,PAYMODE,ACTIVE,AUTOGENERATOR,DRCAPTION,CRCAPTION,DISPLAYORDER,DISPLAYTEXT,APPROVAL) VALUES (&apos;1&apos;,&apos;Receipt&apos;,&apos;R&apos;,&apos;CR&apos;,&apos;Y&apos;,&apos;A&apos;,&apos;Received To&apos;,&apos;Received From&apos;,1,&apos;RECEIPT ENTRY&apos;,&apos;&apos;)
        '''INSERT INTO ACCENTRYMASTER ( SNO,CAPTION,TYPE,PAYMODE,ACTIVE,AUTOGENERATOR,DRCAPTION,CRCAPTION,DISPLAYORDER,DISPLAYTEXT,APPROVAL) VALUES (&apos;2&apos;,&apos;Payment&apos;,&apos;P&apos;,&apos;CP&apos;,&apos;Y&apos;,&apos;A&apos;,&apos;Paid To&apos;,&apos;Paid From&apos;,2,&apos;PAYMENT ENTRY&apos;,&apos;&apos;)
        '''INSERT INTO ACCENTRYMASTER ( SNO,CAPTION,TYPE,PAYMODE,ACTIVE,AUTOGENERATOR,D [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DEMADMINDB_DATA() As String
            Get
                Return ResourceManager.GetString("DEMADMINDB_DATA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO ACCTRAN ( SNO,TRANNO,TRANDATE,TRANMODE,ACCODE,AMOUNT,PCS,GRSWT,NETWT,PUREWT,REFNO,REFDATE,PAYMODE,CHQCARDNO,CARDID,CHQCARDREF,CHQDATE,BRSFLAG,RELIASEDATE,FROMFLAG,REMARK1,REMARK2,CONTRA,BATCHNO,USERID,UPDATED,UPTIME,SYSTEMID,CANCEL,CASHID,COSTID,VATEXM,APPVER,COMPANYID,TRANSFERED,WT_ENTORDER,RATE,TRANFLAG,PCODE,DISC_EMPID,CASHPOINTID,TDSCATID,TDSPER,TDSAMOUNT,FLAG) VALUES (&apos;00DEM121&apos;,1,&apos;07/01/2011&apos;,&apos;D&apos;,&apos;C000106&apos;,22500000,0,9000,9000,0,&apos;101&apos;,&apos;07/01/2011&apos;,&apos;TR&apos;,&apos;&apos;,0,&apos;&apos;,NULL,&apos;&apos;,NULL,&apos;S&apos;,&apos;GOLD BAR PU [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DEMT1112_DATA() As String
            Get
                Return ResourceManager.GetString("DEMT1112_DATA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property email() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("email", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EmptyImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EmptyImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Excel_icon_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Excel_icon_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exit_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gtk_Dnd_Multiple_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gtk_Dnd_Multiple_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_voucher_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_voucher_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Live_Messenger_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Live_Messenger_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property no_photo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no_photo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property no_user_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("no_user_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noimagenew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noimagenew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notes_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notes_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property payment_icon_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("payment_icon_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pdfImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pdfImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Printer_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Printer_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Printer_256x256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Printer_256x256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property receipt_1_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("receipt_1_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property receipt_22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("receipt_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sales() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sales", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sales1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sales1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property saveBill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveBill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Settings_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Settings_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shortcutarrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shortcutarrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property skin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property skin1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skin1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Software_installation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Software_installation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property T1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("T1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Trial() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trial", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property word1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("word1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
