ALTER PROCEDURE [dbo].[SP_TRANVIEW]
(  
@LINESPERPAGE INT,  
@ISCANCEL VARCHAR(1),  
@SCHEME VARCHAR(300),  
@COSTNAME VARCHAR(200),  
@SYSTEMID VARCHAR(200),  
@GROUPCODE VARCHAR(200),  
@USERID VARCHAR(200),  
@FRMDATE VARCHAR(12),  
@TODATE VARCHAR(12),  
@WITHSCHDENOMI VARCHAR(3),  
@BASEDONMAINCOSTID VARCHAR(3),  
@ORDERBY VARCHAR(50),  
@DETAILEDVIEW VARCHAR(1),  
@PAYMODE VARCHAR(50),@VERSIONTYPE  VARCHAR(50),@INSTALLMENT VARCHAR(5)  
)  
AS  
BEGIN  
DECLARE @SQLTEXT VARCHAR(8000)  
DECLARE @RESULT INT   
DECLARE @INDEX INT  
DECLARE @COLHEAD INT  
DECLARE @NOOFRECORDS INT  
SET @SCHEME=REPLACE(@SCHEME,',',''',''')   
SET @GROUPCODE=REPLACE(@GROUPCODE,',',''',''')   
SET @PAYMODE=REPLACE(@PAYMODE,',',''',''')   
SELECT @INDEX=0  
SELECT @COLHEAD=1  
SELECT @NOOFRECORDS=0  
SET @SYSTEMID = ''''+REPLACE(@SYSTEMID,',',''',''')+''''  
SET @USERID  = ''''+REPLACE(@USERID,',',''',''')+''''  
SET @VERSIONTYPE  = ''''+REPLACE(@VERSIONTYPE,',',''',''')+''''    
IF OBJECT_ID('TEMPTABLEDB..TEMPCOLLECT', 'U') IS NOT NULL DROP TABLE TEMPTABLEDB..TEMPCOLLECT  
IF OBJECT_ID('TEMPTABLEDB..TEMPTRANVIEW', 'U') IS NOT NULL DROP TABLE TEMPTABLEDB..TEMPTRANVIEW  
IF OBJECT_ID('TEMPTABLEDB..TEMPTRAN', 'U') IS NOT NULL DROP TABLE TEMPTABLEDB..TEMPTRAN  
IF OBJECT_ID('TEMPTABLEDB..TEMPMODEWISE', 'U') IS NOT NULL DROP TABLE TEMPTABLEDB..TEMPMODEWISE  
IF OBJECT_ID('TEMPTABLEDB..TEMPTRANVIEWCOSTNAME', 'U') IS NOT NULL DROP TABLE TEMPTABLEDB..TEMPTRANVIEWCOSTNAME  
IF OBJECT_ID('TEMPTABLEDB..TEMPRECISS','U') IS NOT NULL  DROP TABLE TEMPTABLEDB..TEMPRECISS   
SELECT @SQLTEXT='SELECT * INTO TEMPTABLEDB..TEMPCOLLECT FROM RTMsh0708 ..SCHEMECOLLECT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' WHERE RDATE BETWEEN '''+CONVERT(VARCHAR,@FRMDATE)+''' AND '''+CONVERT(VARCHAR,@TODATE)+''''    
EXECUTE(@SQLTEXT)  
SELECT @SQLTEXT='UPDATE TEMPTABLEDB..TEMPCOLLECT SET MODEPAY=''G'' WHERE ACCODE IN(SELECT ACCOUNT FROM CREDITCARD WHERE CARDTYPE=''G'')'  
EXECUTE(@SQLTEXT)  
SELECT @SQLTEXT='SELECT SM.COSTID AS MCOSTID,ST.COSTID AS TCOSTID,SM.SNO,ST.GROUPCODE,ST.REGNO'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+',CAST((CASE  WHEN (SELECT COUNT(RECEIPTNO)FROM RTMsh0708..SCHEMECOLLECT WHERE ST.GROUPCODE = GROUPCODE AND ST.REGNO= REGNO   AND  RECEIPTNO=ST.RECEIPTNO)>1 THEN SC.AMOUNT ELSE  ST.AMOUNT END) AS DECIMAL(12,2)) AMOUNT'
  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+',ST.RECEIPTNO,CAST(ST.INSTALLMENT AS DECIMAL(18,2))INSTALLMENT,CONVERT(VARCHAR,SC.RDATE,5)RDATE,SC.RDATE AS RDATE1, SC.MODEPAY'   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+', CAST((CASE WHEN (ST.WEIGHT)<>0 THEN(CASE  WHEN (SELECT COUNT(RECEIPTNO)FROM RTMsh0708..SCHEMECOLLECT WHERE ST.GROUPCODE = GROUPCODE AND ST.REGNO= REGNO   '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND  RECEIPTNO=ST.RECEIPTNO )>1 THEN SC.AMOUNT/ST.RATE ELSE  ST.WEIGHT END)ELSE ST.WEIGHT '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' END)AS DECIMAL(12,3)) WEIGHT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+',CONVERT(VARCHAR,ST.RATE) RATE '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+',SC.CANCEL,SC.CHQBANK ,SC.CHQBRANCH,SC.CHQ_CARDNO, SC.CHQDATE,ST.USERID,ST.SYSTEMID , ST.UPDATETIME AS UPTIME, ST.UPDATETIME AS UPTIME1,ISNULL(ST.MONTHWISEINS,'''')MONTHWISEINS,SC.CHEQUERETDATE ,S.SCHEMENAME,C.COSTNAME,0 COLHEAD,CONVERT(NUMERIC(15,1),0) RESULT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' INTO TEMPTABLEDB..TEMPTRAN'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM SCHEMEMAST SM'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' INNER JOIN RTMsh0708 ..SCHEMETRAN ST ON ST.GROUPCODE=SM.GROUPCODE AND ST.REGNO =SM.REGNO'   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' INNER JOIN SCHEME S ON S.SCHEMEID=SM.SCHEMEID'   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' LEFT JOIN TEMPTABLEDB..TEMPCOLLECT SC ON ST.GROUPCODE =SC.GROUPCODE AND ST.REGNO=SC.REGNO   AND SC.RECEIPTNO=ST.RECEIPTNO  AND SC.ENTREFNO=ST.ENTREFNO '  
IF @BASEDONMAINCOSTID='Y'  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' LEFT JOIN COSTCENTRE C ON C.COSTID=SM.COSTID'   
END  
ELSE  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' LEFT JOIN COSTCENTRE C ON C.COSTID=ST.COSTID'   
END  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' WHERE ST.RDATE BETWEEN '''+CONVERT(VARCHAR,@FRMDATE)+''' AND '''+CONVERT(VARCHAR,@TODATE)+''''    
IF @ISCANCEL='Y'  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND ISNULL(ST.CANCEL,'''')<>''Y'''  
END  
IF @SCHEME<>'ALL'  
BEGIN   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND SM.SCHEMEID IN(SELECT SCHEMEID FROM SCHEME WHERE SCHEMENAME IN('''+@SCHEME+'''))'  
END  
IF @COSTNAME<>'ALL'  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND ST.COSTID IN (SELECT COSTID FROM COSTCENTRE WHERE COSTNAME IN ( '''+ REPLACE(@COSTNAME, ', ', ''',''') +'''))'  
END  
IF @SYSTEMID<>'''ALL'''  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND CAST(ST.SYSTEMID AS VARCHAR) IN ('+@SYSTEMID+')'  
END  
IF @GROUPCODE<>'ALL'  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND SM.GROUPCODE IN('''+@GROUPCODE+''')'  
END             
IF @PAYMODE<>'ALL'  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND SC.MODEPAY IN('''+@PAYMODE+''')'  
END            
IF @USERID<>'''ALL'''  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND CAST(ST.USERID AS VARCHAR) IN ('+@USERID+')'  
END  
IF @INSTALLMENT<>''  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND CAST(ST.INSTALLMENT AS VARCHAR) IN ('+ @INSTALLMENT +')'  
END  
PRINT @VERSIONTYPE  
IF @VERSIONTYPE NOT LIKE  '%ALL%'   
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND ( ST.APPVER NOT IN ('''')'  
IF @VERSIONTYPE NOT LIKE  '%WEB%'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND ST.APPVER NOT IN(''WEB'') '  
IF @VERSIONTYPE NOT LIKE '%APP%'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND ST.APPVER NOT IN(''APP'') '  
IF @VERSIONTYPE NOT LIKE '%VAP%'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND ST.APPVER NOT IN(''VAP'') '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' )'  
IF @VERSIONTYPE NOT LIKE '%WEB%' AND @VERSIONTYPE NOT LIKE '%APP%' AND @VERSIONTYPE NOT LIKE '%VAP%' AND @VERSIONTYPE NOT LIKE '%HOMECOLLECT%'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND ST.APPVER NOT IN(''APP'',''WEB'',''VAP'') '  
IF @VERSIONTYPE NOT LIKE '%WINDOWS%' AND @VERSIONTYPE NOT LIKE '%HOMECOLLECT%'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND ST.APPVER IN(''APP'',''WEB'',''VAP'') '  
IF @VERSIONTYPE LIKE '%HOMECOLLECT%'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND SM.HOMECOLLECT = ''Y''  '  
/*IF @VERSIONTYPE = 'WEB'   
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND ST.APPVER IN(''WEB'') '  
END  
IF @VERSIONTYPE = 'APP'   
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND CAST(SC.SYSTEMID AS VARCHAR) IN (''APP'')'  
End  
IF @VERSIONTYPE <> 'WEB' AND @VERSIONTYPE <> 'APP'    
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND ST.APPVER NOT IN(''WEB'') '  
END */  
END  
PRINT @SQLTEXT  
EXECUTE(@SQLTEXT)  
SELECT @SQLTEXT='SELECT IDENTITY(INT, 1,1) AS ID,CASE WHEN ISNULL(P.INITIAL,'''')<>'''' THEN P.INITIAL +''.'''   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ELSE ''''END +P.PNAME +''''  AS CUSNAME,P.MOBILE,T.SNO,T.GROUPCODE,T.REGNO,T.AMOUNT,T.RECEIPTNO'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,CONVERT(DECIMAL(10,2),T.INSTALLMENT) AS INSTALLMENT,CONVERT(VARCHAR,T.RDATE,5)RDATE,T.RDATE1,T.MODEPAY,T.WEIGHT,CONVERT(VARCHAR,T.RATE)RATE, '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' T.CANCEL,T.CHQBANK ,T.CHQBRANCH,T.CHQ_CARDNO, T.CHQDATE,T.USERID,T.SYSTEMID ,'            
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' CASE WHEN LEN(LTRIM(RIGHT(CONVERT(VARCHAR, T.UPTIME, 100),8)))=6 THEN  RIGHT(''0''+ LTRIM(RIGHT(CONVERT(VARCHAR, T.UPTIME, 100),8)) ,8) ELSE RIGHT(LTRIM(RIGHT(CONVERT(VARCHAR, T.UPTIME, 100),8)) ,8) END AS UPTIME,T.UPTIME1'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,ISNULL(T.MONTHWISEINS,'''')MONTHWISEINS,T.CHEQUERETDATE ,T.SCHEMENAME,T.COSTNAME,T.COLHEAD,T.RESULT,T.TCOSTID'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' INTO TEMPTABLEDB..TEMPTRANVIEW FROM PERSONALINFO P,TEMPTABLEDB..TEMPTRAN T WHERE P.PERSONALID=T.SNO'  
IF @ORDERBY='GROUP'  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ORDER BY GROUPCODE,REGNO'  
END  
IF @ORDERBY='DATE'  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ORDER BY RDATE1,RECEIPTNO'  
END  
IF @ORDERBY ='RNO'  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ORDER BY RECEIPTNO'  
END  
IF @ORDERBY ='UPTIME'  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ORDER BY T.RDATE1,T.UPTIME1 '  
END  
PRINT @SQLTEXT  
EXECUTE(@SQLTEXT)            
SELECT @SQLTEXT=' SELECT MODEPAY, SUM(AMOUNT) AS CASHAMOUNT'              
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(AMOUNT)ELSE 0 END AS CANCELAMT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUM(WEIGHT) AS WEIGHT, CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(WEIGHT)ELSE 0 END AS CANCELWGT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SCHEMENAME  INTO TEMPTABLEDB..TEMPMODEWISE '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM TEMPTABLEDB..TEMPTRANVIEW GROUP BY SCHEMENAME, MODEPAY , CANCEL'  
PRINT @SQLTEXT  
EXECUTE(@SQLTEXT)  
SELECT @NOOFRECORDS=COUNT(*)FROM TEMPTABLEDB..TEMPTRANVIEW  
IF @NOOFRECORDS=0  
BEGIN  
RETURN  
END  
DECLARE CUR1 CURSOR FOR SELECT  ID FROM TEMPTABLEDB..TEMPTRANVIEW ORDER BY ID  
OPEN CUR1  
FETCH NEXT FROM CUR1 INTO @RESULT  
WHILE @@FETCH_STATUS<>-1  
BEGIN  
UPDATE TEMPTABLEDB..TEMPTRANVIEW SET COLHEAD=@COLHEAD WHERE ID=@RESULT   
SELECT @INDEX=@INDEX+1  
IF @INDEX=@LINESPERPAGE  
BEGIN  
SELECT @COLHEAD=@COLHEAD+1  
SELECT @INDEX=0  
END  
FETCH NEXT FROM CUR1 INTO @RESULT  
END  
CLOSE CUR1  
DEALLOCATE CUR1  
IF OBJECT_ID('TEMPTABLEDB..TEMPRECISS','U') IS NOT NULL  DROP TABLE TEMPTABLEDB..TEMPRECISS   
SELECT @SQLTEXT= ' SELECT * INTO TEMPTABLEDB..TEMPRECISS FROM('  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT R.PAYMODE,ISNULL(SUM(CASE WHEN R.TRANTYPE = ''R'' THEN R.AMOUNT ELSE 0 END),0) AS RECEIPT,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ISNULL(SUM(CASE WHEN R.TRANTYPE = ''P'' THEN R.AMOUNT ELSE 0 END),0) AS PAYMENT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM RECPAY R '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' INNER JOIN RTMsh0708..SCHEMETRAN ST ON ST.ENTREFNO=R.ENTREFNO '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' INNER JOIN SCHEMEMAST  M ON ST.GROUPCODE=M.GROUPCODE AND ST.REGNO=M.REGNO '  
IF @SCHEME<>'ALL'  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND M.SCHEMEID IN(SELECT SCHEMEID FROM SCHEME WHERE SCHEMENAME IN('''+@SCHEME+'''))'  
END  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' WHERE R.TRANDATE BETWEEN '''+CONVERT(VARCHAR,@FRMDATE)+''' AND '''+CONVERT(VARCHAR,@TODATE)+''''   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND ISNULL(R.CANCEL,'''') <> ''Y'' '  
IF @COSTNAME<>'ALL'  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND R.COSTID IN (SELECT COSTID FROM COSTCENTRE WHERE COSTNAME IN ( '''+ REPLACE(@COSTNAME, ', ', ''',''') +'''))'  
END  
IF @SYSTEMID<>'''ALL'''  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND CAST(R.SYSTEMID AS VARCHAR) IN ('+@SYSTEMID+')'  
END  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' GROUP BY R.PAYMODE '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UNION ALL '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT R.PAYMODE,ISNULL(SUM(CASE WHEN R.TRANTYPE = ''R'' THEN R.AMOUNT ELSE 0 END),0) AS RECEIPT,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ISNULL(SUM(CASE WHEN R.TRANTYPE = ''P'' THEN R.AMOUNT ELSE 0 END),0) AS PAYMENT '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM RECPAY R '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' INNER JOIN SCHEMEMAST  M ON R.GROUPCODE=M.GROUPCODE AND R.REGNO=M.REGNO '  
IF @SCHEME<>'ALL'  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND M.SCHEMEID IN(SELECT SCHEMEID FROM SCHEME WHERE SCHEMENAME IN('''+@SCHEME+'''))'  
END  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' WHERE R.TRANDATE BETWEEN '''+CONVERT(VARCHAR,@FRMDATE)+''' AND '''+CONVERT(VARCHAR,@TODATE)+''''   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND ISNULL(R.CANCEL,'''') <> ''Y'' '  
IF @COSTNAME<>'ALL'  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND R.COSTID IN (SELECT COSTID FROM COSTCENTRE WHERE COSTNAME IN ( '''+ REPLACE(@COSTNAME, ', ', ''',''') +'''))'  
END  
IF @SYSTEMID<>'''ALL'''  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND CAST(R.SYSTEMID AS VARCHAR) IN ('+@SYSTEMID+')'  
END  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' GROUP BY R.PAYMODE '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UNION ALL '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT R.PAYMODE,ISNULL(SUM(CASE WHEN R.TRANTYPE = ''R'''   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' THEN R.AMOUNT ELSE 0 END),0) AS RECEIPT, ISNULL(SUM(CASE WHEN R.TRANTYPE = ''P'''  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' THEN R.AMOUNT ELSE 0 END),0) AS PAYMENT FROM RECPAY R  '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' WHERE R.TRANDATE BETWEEN '''+CONVERT(VARCHAR,@FRMDATE)+''' AND '''+CONVERT(VARCHAR,@TODATE)+''''   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND ISNULL(R.PAYMODE,'''')='''''  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' AND ISNULL(R.GROUPCODE,'''')='''' AND ISNULL(R.REGNO,0)=0'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' GROUP BY R.PAYMODE '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' )X ORDER BY X.PAYMODE'  
PRINT @SQLTEXT   
EXEC (@SQLTEXT)  
DECLARE @SQLTEXT_TEMP AS VARCHAR(1000)  
SELECT @SQLTEXT_TEMP=' IF OBJECT_ID(''T1'',''U'') IS NOT NULL  DROP TABLE T1 '  
SELECT @SQLTEXT_TEMP=@SQLTEXT_TEMP+ CHAR(13)+' CREATE TABLE T1(PAYMODE VARCHAR(10),RECEIPT FLOAT, PAYMENT  FLOAT)'      
SELECT @SQLTEXT_TEMP=@SQLTEXT_TEMP+ CHAR(13)+' INSERT INTO T1 EXEC SP_RECPAY @QRY = ''SELECT * FROM TEMPTABLEDB..TEMPRECISS'' '            
PRINT @SQLTEXT_TEMP  
EXEC (@SQLTEXT_TEMP)  
SELECT @SQLTEXT=' ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN GROUPCODE VARCHAR(100)'            
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN MODEPAY VARCHAR(100)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN AMOUNT  NUMERIC '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN RECEIPTNO  NUMERIC '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN WEIGHT  NUMERIC(18,3)'            
PRINT @SQLTEXT  
EXECUTE(@SQLTEXT)  
SELECT @SQLTEXT=' INSERT INTO TEMPTABLEDB..TEMPTRANVIEW(CUSNAME,AMOUNT,RECEIPTNO,INSTALLMENT,RATE,MODEPAY,WEIGHT,MONTHWISEINS,RESULT,COLHEAD)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT ''SUB TOTAL  =>'',SUM(GROSSAMT)GROSSAMT,SUM(CANCELAMT)CANCELAMT,(SUM(GROSSAMT)-SUM(CANCELAMT))NETAMT '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUM(GROSSWGT)GROSSWGT,SUM(CANCELWGT)CANCELWGT,(SUM(GROSSWGT)-SUM(CANCELWGT))NETWGT,'''',2 RESULT,COLHEAD'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM ( SELECT   SUM(AMOUNT)AS GROSSAMT, '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(AMOUNT)ELSE 0 END AS CANCELAMT, '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(WEIGHT)AS GROSSWGT,CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(WEIGHT)ELSE 0 END AS CANCELWGT,COLHEAD '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM TEMPTABLEDB..TEMPTRANVIEW WHERE  RESULT =0 GROUP BY COLHEAD,CANCEL)X GROUP BY COLHEAD '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UNION ALL'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT ''GRAND TOTAL=>'',SUM(GROSSAMT)GROSSAMT,SUM(CANCELAMT)CANCELAMT,(SUM(GROSSAMT)-SUM(CANCELAMT))NETAMT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUM(GROSSWGT),SUM(CANCELWGT),(SUM(GROSSWGT)-SUM(CANCELWGT))NETWGT,'''',4 RESULT, ''9999'''  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM ( SELECT   SUM(AMOUNT)AS GROSSAMT,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(AMOUNT)ELSE 0 END AS CANCELAMT, '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(WEIGHT)AS GROSSWGT,CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(WEIGHT)ELSE 0 END AS CANCELWGT,COLHEAD '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM TEMPTABLEDB..TEMPTRANVIEW WHERE  RESULT=0 GROUP BY COLHEAD,CANCEL)X'  
/*SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UNION ALL'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT TOP 1 ''''GROUPCODE,0,0,0,0,0,0,'''' MONTHWISEINS,5 RESULT,''99999''COLHEAD FROM TEMPTABLEDB..TEMPTRANVIEW   '*/  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UNION ALL'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT TOP 1 ''COLLECTION SUMMARY'',0,0,0,0,0,0,''''MONTHWISEINS,6 RESULT,''9999''COLHEAD FROM TEMPTABLEDB..TEMPTRANVIEW   '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' INSERT INTO TEMPTABLEDB..TEMPTRANVIEW(CUSNAME,AMOUNT,RECEIPTNO,INSTALLMENT,RATE,MODEPAY,WEIGHT,MONTHWISEINS,RESULT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,COLHEAD) SELECT CASE MODEPAY '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' WHEN ''C'' THEN ''CASH AMOUNT'' WHEN ''D'' THEN ''CHEQUE AMOUNT'' WHEN ''R''THEN ''CREDITCARD AMOUNT'' WHEN ''E'' THEN ''E-TRANSFER AMOUNT'' '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' WHEN ''O'' THEN ''OTHER AMOUNT'' WHEN ''A'' THEN ''ADVANCE AMOUNT'' WHEN ''G'' THEN ''GIFT VOUCHER'' WHEN ''P'' THEN ''CREDIT PURCHASE'' ELSE ''''  END AS MODEPAY'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,ISNULL(SUM(GROSSAMT),0)GROSSAMT,ISNULL(SUM(CANCELAMT),0)CANCELAMT,ISNULL(SUM(GROSSAMT),0)-ISNULL(SUM(CANCELAMT),0)NETAMOUNT,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ISNULL(SUM(GROSSWGT),0)GROSSWGT,CONVERT(VARCHAR,ISNULL(SUM(CANCELWGT),0))CANCELWGT '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,ISNULL(SUM(GROSSWGT),0)-ISNULL(SUM(CANCELWGT),0)NETAMOUNT,'''',8,''9999'' '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM (SELECT SUM(AMOUNT)AS GROSSAMT, '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(AMOUNT)ELSE 0 END AS CANCELAMT, '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(WEIGHT)AS GROSSWGT,CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(WEIGHT)ELSE 0 END AS CANCELWGT, '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' MODEPAY FROM TEMPTABLEDB..TEMPTRANVIEW WHERE RESULT =0'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' GROUP BY MODEPAY,CANCEL )X GROUP BY MODEPAY '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UNION ALL'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT ''TOTAL AMOUNT'', SUM(GROSSAMT)GROSSAMT,SUM(CANCELAMT)CANCELAMT,SUM(GROSSAMT)-SUM(CANCELAMT)NETAMOUNT,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(GROSSWGT)GROSSWGT,CONVERT(VARCHAR,SUM(CANCELWGT))CANCELWGT ,SUM(GROSSWGT)-SUM(CANCELWGT)NETAMOUNT,'''',9,''9999'' '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM (SELECT SUM(AMOUNT)AS GROSSAMT, '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(AMOUNT)ELSE 0 END AS CANCELAMT, '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(WEIGHT)AS GROSSWGT,CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(WEIGHT)ELSE 0 END AS CANCELWGT, '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' MODEPAY FROM TEMPTABLEDB..TEMPTRANVIEW WHERE RESULT =0'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' GROUP BY MODEPAY,CANCEL )X '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' INSERT INTO TEMPTABLEDB..TEMPTRANVIEW(CUSNAME,INSTALLMENT,WEIGHT,MONTHWISEINS,RESULT,COLHEAD)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT TOP 1 '''',0,0,'''',12 RESULT,''99999'' FROM TEMPTABLEDB..TEMPTRANVIEW '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UNION ALL '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT TOP 1 ''CREDIT COLLECTION'',0,0,'''',16 RESULT,''99999'' FROM TEMPTABLEDB..TEMPTRANVIEW '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UNION ALL '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT CHQBANK,SUM(AMOUNT)-(CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(AMOUNT)ELSE 0 END) AS AMOUNT,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(WEIGHT)-(CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(WEIGHT)ELSE 0 END )AS WEIGHT,'''',17 RESULT,''99999'' '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM TEMPTABLEDB..TEMPTRANVIEW  WHERE RESULT=0 AND ISNULL(CANCEL,'''')='''' AND CHQBANK<>'''' AND MODEPAY=''R'''  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' GROUP BY CHQBANK ,CANCEL'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UNION ALL'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT ''TOTAL =>'',SUM(AMOUNT)-(CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(AMOUNT)ELSE 0 END) AS AMOUNT,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(WEIGHT)-(CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(WEIGHT)ELSE 0 END )AS WEIGHT,'''',18 RESULT,''99999'''  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM TEMPTABLEDB..TEMPTRANVIEW  WHERE RESULT=0 AND ISNULL(CANCEL,'''')=''''  AND CHQBANK<>'''' AND MODEPAY=''R'' GROUP BY CANCEL'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UNION ALL '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT TOP 1 ''GIFT COLLECTION'',0,0,'''',18.1 RESULT,''99999'' FROM TEMPTABLEDB..TEMPTRANVIEW '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UNION ALL '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT CHQBANK,SUM(AMOUNT)-(CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(AMOUNT)ELSE 0 END) AS AMOUNT,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(WEIGHT)-(CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(WEIGHT)ELSE 0 END )AS WEIGHT,'''',18.2 RESULT,''99999'' '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM TEMPTABLEDB..TEMPTRANVIEW  WHERE RESULT=0 AND ISNULL(CANCEL,'''')='''' AND CHQBANK<>'''' AND MODEPAY=''G'''  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' GROUP BY CHQBANK ,CANCEL'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UNION ALL'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT ''TOTAL =>'',SUM(AMOUNT)-(CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(AMOUNT)ELSE 0 END) AS AMOUNT,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(WEIGHT)-(CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(WEIGHT)ELSE 0 END )AS WEIGHT,'''',18.3 RESULT,''99999'''  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM TEMPTABLEDB..TEMPTRANVIEW  WHERE RESULT=0 AND ISNULL(CANCEL,'''')=''''  AND CHQBANK<>'''' AND MODEPAY=''G'' GROUP BY CANCEL'  
IF @DETAILEDVIEW = 'N'  
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UNION ALL '   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT TOP 1 ''SCHEMEWISE SUMMARY'',0,0,'''',19 RESULT,''99999'' FROM TEMPTABLEDB..TEMPTRANVIEW '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UNION ALL'             
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT SCHEMENAME,SUM(AMOUNT)-(CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(AMOUNT)ELSE 0 END) AS AMOUNT,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(WEIGHT)-(CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(WEIGHT)ELSE 0 END )AS WEIGHT,'''',20 RESULT,''99999'' '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM TEMPTABLEDB..TEMPTRANVIEW  WHERE RESULT=0 AND ISNULL(CANCEL,'''')='''' GROUP BY SCHEMENAME ,CANCEL'  
END  
PRINT @SQLTEXT   
EXECUTE(@SQLTEXT)  
SELECT @SQLTEXT= ''''  
/*REPLACE*/  
SELECT @SQLTEXT_TEMP=' INSERT INTO TEMPTABLEDB..TEMPTRANVIEW(CUSNAME,MOBILE,INSTALLMENT,MONTHWISEINS,RESULT,COLHEAD)'  
SELECT @SQLTEXT_TEMP=@SQLTEXT_TEMP+ CHAR(13)+' SELECT ''RECEIPT'','''',ISNULL(SUM(RECEIPT),0)RECEIPT,'''',10,''99999'' FROM T1 '  
SELECT @SQLTEXT_TEMP=@SQLTEXT_TEMP+ CHAR(13)+' UNION ALL'  
SELECT @SQLTEXT_TEMP=@SQLTEXT_TEMP+ CHAR(13)+' SELECT ''PAYMENT'','''',ISNULL(SUM(PAYMENT),0)RECEIPT,'''',10,''99999'' FROM T1 '  
SELECT @SQLTEXT_TEMP=@SQLTEXT_TEMP+ CHAR(13)+' UNION ALL'  
SELECT @SQLTEXT_TEMP=@SQLTEXT_TEMP+ CHAR(13)+' SELECT ''FINAL AMOUNT'','''', ISNULL(SUM(AMOUNT),0)AMOUNT,'''',10,''99999'' FROM '  
SELECT @SQLTEXT_TEMP=@SQLTEXT_TEMP+ CHAR(13)+' (SELECT SUM(AMOUNT)AMOUNT FROM TEMPTABLEDB..TEMPTRANVIEW WHERE ISNULL(CANCEL,'''')='''' AND RESULT=0 '  
SELECT @SQLTEXT_TEMP=@SQLTEXT_TEMP+ CHAR(13)+' UNION ALL'  
SELECT @SQLTEXT_TEMP=@SQLTEXT_TEMP+ CHAR(13)+' SELECT SUM(RECEIPT)-SUM(PAYMENT)AMOUNT  FROM T1  )X'  
PRINT @SQLTEXT_TEMP  
EXEC (@SQLTEXT_TEMP)  
IF @DETAILEDVIEW = 'Y'  
BEGIN  
SELECT @NOOFRECORDS = COUNT (*) FROM TEMPTABLEDB..TEMPTRANVIEW  
IF @NOOFRECORDS = 0  
BEGIN  
RETURN  
END  
SELECT @SQLTEXT=' DECLARE @SCHEMES AS VARCHAR(1000)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' DECLARE @RESULTS AS VARCHAR(1000)'         
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' DECLARE CURSCHEME CURSOR FOR SELECT DISTINCT SCHEMENAME FROM TEMPTABLEDB..TEMPTRANVIEW WHERE ISNULL(SCHEMENAME,'''')!='''' ORDER BY SCHEMENAME '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' OPEN CURSCHEME'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' DECLARE @ROW INT '      
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT @ROW = ''19'''      
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FETCH NEXT FROM CURSCHEME INTO @RESULTS  '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' PRINT @RESULTS'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' WHILE @@FETCH_STATUS<>-1'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' BEGIN'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT @ROW = @ROW + 1'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' DECLARE @ROW1 AS INT '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SET @ROW1 = @ROW + 1'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' INSERT INTO TEMPTABLEDB..TEMPTRANVIEW( CUSNAME,MOBILE, AMOUNT,RECEIPTNO,INSTALLMENT, MODEPAY, WEIGHT, RATE,CHQBANK, USERID, SYSTEMID,MONTHWISEINS, COLHEAD, RESULT)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT SCHEMENAME,'''', CONVERT(VARCHAR(50)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,ISNULL(SUM( CASHAMOUNT)-SUM(CANCELAMT),0),128) AS TOTAMOUNT '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,ISNULL(SUM( CASE WHEN MODEPAY = ''C'' THEN CASHAMOUNT END),0) - ISNULL(SUM( CASE WHEN MODEPAY = ''C'' THEN CANCELAMT ELSE 0 END),0) AS RECEIPTNO '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,ISNULL(SUM( CASE WHEN MODEPAY = ''D'' THEN CASHAMOUNT END),0) - ISNULL(SUM( CASE WHEN MODEPAY = ''D'' THEN CANCELAMT ELSE 0 END),0) AS INSTALLMENT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,ISNULL(SUM( CASE WHEN MODEPAY = ''E'' THEN CASHAMOUNT END),0) - ISNULL(SUM( CASE WHEN MODEPAY = ''E'' THEN CANCELAMT ELSE 0 END),0) AS MODEPAY '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,ISNULL(SUM( CASE WHEN MODEPAY = ''R'' THEN CASHAMOUNT END),0) - ISNULL(SUM( CASE WHEN MODEPAY = ''R'' THEN CANCELAMT ELSE 0 END),0) AS RATE '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,CONVERT(VARCHAR(50), ISNULL(SUM( WEIGHT)-SUM(CANCELWGT),0),128) AS WEIGHT '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,ISNULL(SUM( CASE WHEN MODEPAY IN (''O'',''A'') THEN CASHAMOUNT END),0) - ISNULL(SUM( CASE WHEN MODEPAY IN (''O'',''A'') THEN CANCELAMT ELSE 0 END),0) AS CHQBANK '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,ISNULL(SUM( CASE WHEN MODEPAY = ''G'' THEN CASHAMOUNT END),0) - ISNULL(SUM( CASE WHEN MODEPAY = ''G'' THEN CANCELAMT ELSE 0 END),0) AS USERID '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,(SELECT COUNT(DISTINCT RECEIPTNO)GROUPCODE FROM TEMPTABLEDB..TEMPTRANVIEW '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' WHERE  SCHEMENAME = @RESULTS AND INSTALLMENT= ''1.00'' AND ISNULL(CANCEL,'''')='''' AND RESULT=0)SYSTEMID'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,'''' , ''9999999'', @ROW1 RESULT   FROM TEMPTABLEDB..TEMPMODEWISE WHERE SCHEMENAME = @RESULTS'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' GROUP BY SCHEMENAME '  
/*SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' INSERT INTO TEMPTABLEDB..TEMPTRANVIEW( CUSNAME, AMOUNT, CHQBANK, RECEIPTNO, INSTALLMENT, MODEPAY, RDATE,  WEIGHT, RATE, USERID, MONTHWISEINS, COLHEAD, RESULT)'    
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT SCHEMENAME, CONVERT(VARCHAR(50),ISNULL(SUM( CASHAMOUNT)-SUM(CANCELAMT),0),128) AS TOTAMOUNT '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,CONVERT(VARCHAR(50), ISNULL(SUM( WEIGHT)-SUM(CANCELWGT),0),128) AS WEIGHT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,ISNULL(SUM( CASE WHEN MODEPAY = ''C'' THEN CASHAMOUNT END),0) - ISNULL(SUM( CASE WHEN MODEPAY = ''C'' THEN CANCELAMT ELSE 0 END),0) AS RECEIPTNO'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,ISNULL(SUM( CASE WHEN MODEPAY = ''D'' THEN CASHAMOUNT END),0) - ISNULL(SUM( CASE WHEN MODEPAY = ''D'' THEN CANCELAMT ELSE 0 END),0) AS INSTALLMENT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,ISNULL(SUM( CASE WHEN MODEPAY = ''R'' THEN CASHAMOUNT END),0) - ISNULL(SUM( CASE WHEN MODEPAY = ''R'' THEN CANCELAMT ELSE 0 END),0) AS RDATE'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,ISNULL(SUM( CASE WHEN MODEPAY = ''E'' THEN CASHAMOUNT END),0) - ISNULL(SUM( CASE WHEN MODEPAY = ''E'' THEN CANCELAMT ELSE 0 END),0) AS PAYMODE'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,ISNULL(SUM( CASE WHEN MODEPAY IN (''O'',''A'') THEN CASHAMOUNT END),0) - ISNULL(SUM( CASE WHEN MODEPAY IN (''O'',''A'') THEN CANCELAMT ELSE 0 END),0) AS WEIGHT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,ISNULL(SUM( CASE WHEN MODEPAY = ''G'' THEN CASHAMOUNT END),0) - ISNULL(SUM( CASE WHEN MODEPAY = ''G'' THEN CANCELAMT ELSE 0 END),0) AS RATE'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,(SELECT COUNT(DISTINCT RECEIPTNO)GROUPCODE FROM TEMPTABLEDB..TEMPTRANVIEW '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' WHERE  SCHEMENAME = @RESULTS AND INSTALLMENT= ''1.00'' AND ISNULL(CANCEL,'''')='''' AND RESULT=0)NEWMEMBERS'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,'''' , ''9999999'', @ROW1 RESULT   FROM TEMPTABLEDB..TEMPMODEWISE WHERE SCHEMENAME = @RESULTS'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' GROUP BY SCHEMENAME '*/  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FETCH NEXT FROM CURSCHEME INTO @RESULTS  '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' END  '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' CLOSE CURSCHEME'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' DEALLOCATE CURSCHEME'    
PRINT @SQLTEXT   
EXECUTE(@SQLTEXT)     
IF @DETAILEDVIEW = 'Y'  
BEGIN  
SELECT @SQLTEXT=' INSERT INTO TEMPTABLEDB..TEMPTRANVIEW(CUSNAME,MOBILE,AMOUNT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' , RECEIPTNO, INSTALLMENT, RDATE, MODEPAY, WEIGHT, RATE, CHQBANK, USERID'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' , MONTHWISEINS,RESULT,COLHEAD,SYSTEMID)'        
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT ''TOTAL =>'','''' '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,(SELECT  SUM(AMOUNT)- SUM(RECEIPTNO)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM TEMPTABLEDB..TEMPTRANVIEW WHERE RESULT <> 19 AND CUSNAME = ''TOTAL AMOUNT'' AND  ISNULL(CANCEL,'''')=''''  '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' GROUP BY CANCEL )AS AMOUNT,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' RECEIPTNO, INSTALLMENT, RDATE, MODEPAY, OTHERS, RATE, CHQBANK, USERID, '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' '''' MONTHWISEINS,99 RESULT, ''9999999'',SYSTEMID '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM (SELECT   '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(RECEIPTNO)-(CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(RECEIPTNO)ELSE 0 END) AS RECEIPTNO,  '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(INSTALLMENT)-(CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(INSTALLMENT)ELSE 0 END) AS INSTALLMENT,  '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(CONVERT(DECIMAL(18,2),RDATE)) - (CASE ISNULL(CANCEL, '''') WHEN ''Y'' THEN SUM(CONVERT(DECIMAL(18,2),RDATE)) ELSE 0 END)AS RDATE,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(CONVERT(DECIMAL(18,2),MODEPAY)) - (CASE ISNULL(CANCEL, '''') WHEN ''Y'' THEN SUM(CONVERT(DECIMAL(18,2),MODEPAY)) ELSE 0 END)AS MODEPAY,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(WEIGHT)-(CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(WEIGHT)ELSE 0 END )AS OTHERS, '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(CONVERT(DECIMAL(18,3),RATE)) - (CASE ISNULL(CANCEL, '''') WHEN ''Y'' THEN SUM(CONVERT(DECIMAL(18,3),RATE)) ELSE 0 END)AS RATE,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' (SELECT  SUM(CONVERT(DECIMAL(18,3),RDATE))- SUM(CONVERT(DECIMAL(18,3),MODEPAY))'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM TEMPTABLEDB..TEMPTRANVIEW WHERE RESULT <> 19 AND CUSNAME = ''TOTAL AMOUNT'' AND  ISNULL(CANCEL,'''')=''''  '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' GROUP BY CANCEL )CHQBANK'                  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,(SELECT  SUM(CONVERT(INT,USERID))'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM TEMPTABLEDB..TEMPTRANVIEW WHERE RESULT >= 19 AND  ISNULL(CANCEL,'''')=''''  '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' GROUP BY CANCEL )USERID'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,(SELECT  SUM(CONVERT(INT,SYSTEMID))'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM TEMPTABLEDB..TEMPTRANVIEW WHERE RESULT >= 19 AND  ISNULL(CANCEL,'''')=''''  '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' GROUP BY CANCEL )SYSTEMID'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM TEMPTABLEDB..TEMPTRANVIEW  WHERE RESULT >=19 AND ISNULL(CANCEL,'''')=''''  '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' GROUP BY CANCEL)X'  
PRINT @SQLTEXT   
EXECUTE(@SQLTEXT)       
END  
ELSE  
BEGIN  
SELECT @SQLTEXT=' INSERT INTO TEMPTABLEDB..TEMPTRANVIEW(CUSNAME,MOBILE,INSTALLMENT,WEIGHT,MONTHWISEINS,RESULT,COLHEAD)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT ''TOTAL =>'','''',SUM(AMOUNT)-(CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(AMOUNT)ELSE 0 END) AS AMOUNT,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(WEIGHT)-(CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(WEIGHT)ELSE 0 END )AS RATE,'''',99 RESULT, ''9999999'' '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM TEMPTABLEDB..TEMPTRANVIEW  WHERE RESULT=0 AND ISNULL(CANCEL,'''')='''' GROUP BY CANCEL'  
PRINT @SQLTEXT   
EXECUTE(@SQLTEXT)   
END  
SELECT @SQLTEXT=' ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN CUSNAME VARCHAR(100)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN MOBILE VARCHAR(100)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN AMOUNT VARCHAR(100)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN RECEIPTNO VARCHAR(100)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN INSTALLMENT VARCHAR(100)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN RDATE VARCHAR(100)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN RESULT VARCHAR(100)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN WEIGHT VARCHAR(100)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN USERID VARCHAR(100)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN SYSTEMID VARCHAR(100)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' INSERT INTO TEMPTABLEDB..TEMPTRANVIEW(CUSNAME,MOBILE,AMOUNT, RECEIPTNO'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' , INSTALLMENT, MODEPAY, WEIGHT,  CHQBANK, RATE, USERID,SYSTEMID'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' , RESULT, COLHEAD, MONTHWISEINS)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT TOP 1 ''SCHEMEWISE SUMMARY'','''', ''AMOUNT'', ''CASH'''  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' , ''CHEQUE'', ''E-TRANS'', ''CARD'', ''OTHERS/ADVANCE'', ''WEIGHT'', ''GIFT'''  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' , ''NEWMEMBERS'', 19 RESULT,''999999'', '''' FROM TEMPTABLEDB..TEMPTRANVIEW '  
PRINT @SQLTEXT  
EXECUTE(@SQLTEXT)  
END  
IF @WITHSCHDENOMI='Y'  
BEGIN  
SELECT @SQLTEXT=' INSERT INTO TEMPTABLEDB..TEMPTRANVIEW(CUSNAME,MOBILE,INSTALLMENT,WEIGHT,MONTHWISEINS,RESULT,COLHEAD)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT TOP 1 '''','''',NULL,0,'''',22 RESULT,''99999'' FROM TEMPTABLEDB..TEMPTRANVIEW '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' INSERT INTO TEMPTABLEDB..TEMPTRANVIEW(CUSNAME,MOBILE,AMOUNT,RECEIPTNO'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,INSTALLMENT,MODEPAY,WEIGHT,RATE,CHQBANK,COSTNAME,MONTHWISEINS,RESULT,COLHEAD) '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT TOP 1 ''SCHEMEWISE DENOMINI'' CUSNAME,'''''  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,NULL AMOUNT,NULL RECEIPTNO,NULL INSTALLMENT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,NULL MODEPAY,NULL WEIGHT,0 RDATE, NULL CHQBANK'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,'''' COSTNAME,'''' MONTHWISEINS,22 RESULT,''999999'' COLHEAD'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM TEMPTABLEDB..TEMPTRANVIEW     '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UNION ALL '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT DISTINCT SCHEMENAME,'''''  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUM(CASE MODEPAY WHEN ''C'' THEN X.AMOUNT ELSE NULL END) AS AMOUNT,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(CASE MODEPAY WHEN ''D'' THEN X.AMOUNT ELSE NULL END) AS RECEIPTNO,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(CASE MODEPAY WHEN ''R'' THEN X.AMOUNT ELSE NULL END )AS INSTALLMENT,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(CASE MODEPAY WHEN ''E'' THEN X.AMOUNT ELSE NULL END )AS MODEPAY,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(CASE WHEN MODEPAY IN (''O'',''A'') THEN X.AMOUNT ELSE NULL END )AS WEIGHT, '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(CANCELAMT) AS RATE,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(X.AMOUNT )AS RATE, COSTNAME,'''',24 RESULT,''999999''    '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM ('  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT SUM(CONVERT(NUMERIC,AMOUNT))AS AMOUNT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SCHEMENAME,CONVERT(VARCHAR,COSTNAME)AS COSTNAME,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(CONVERT(NUMERIC,AMOUNT))ELSE 0 END AS CANCELAMT,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' MODEPAY FROM TEMPTABLEDB..TEMPTRANVIEW WHERE RESULT =''0'' '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' GROUP BY MODEPAY,SCHEMENAME,CANCEL,COSTNAME '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' )X GROUP BY SCHEMENAME,COSTNAME'  
PRINT (@SQLTEXT)  
EXEC (@SQLTEXT)  
END  
SELECT @SQLTEXT='ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN AMOUNT VARCHAR(100)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+'ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN RECEIPTNO VARCHAR(100)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+'ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN MODEPAY VARCHAR(100)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+'ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN INSTALLMENT VARCHAR(100)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+'ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN WEIGHT VARCHAR(100)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+'ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN RDATE VARCHAR(100)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+'ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN RATE VARCHAR(100)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+'ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN SYSTEMID VARCHAR(100)'  
PRINT @SQLTEXT  
EXEC (@SQLTEXT)  
IF @WITHSCHDENOMI='Y'  
BEGIN  
PRINT 'CHECKING'  
SELECT @SQLTEXT='INSERT INTO TEMPTABLEDB..TEMPTRANVIEW(CUSNAME,SNO,AMOUNT,RECEIPTNO,INSTALLMENT,MODEPAY,WEIGHT,RATE,SYSTEMID,MONTHWISEINS,RESULT,COLHEAD,CHQBANK)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+'    SELECT '''','''',''CASH'',''CHEQUE'',''CR.CARD'',''E-T..'',''OTH/ADV'',''CANCEL'',''TOTAL'','''',23,''99999'',''TOTAL'''  
PRINT @SQLTEXT  
EXEC (@SQLTEXT)  
SELECT @SQLTEXT='INSERT INTO TEMPTABLEDB..TEMPTRANVIEW(CUSNAME,MOBILE,SNO,AMOUNT,RECEIPTNO,INSTALLMENT,MODEPAY,WEIGHT,RATE,SYSTEMID,COSTNAME,MONTHWISEINS,RESULT,COLHEAD,CHQBANK)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT ''GRAND TOTAL =>'' CUSTNAME,'''' MOBILE,'''' SNO'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUM(CONVERT(NUMERIC,AMOUNT)) AS AMOUNT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUM(CONVERT(NUMERIC,RECEIPTNO)) AS RECEIPTNO, '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(CONVERT(NUMERIC,INSTALLMENT)) AS INSTALLMENT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUM(CONVERT(NUMERIC,MODEPAY)) AS MODEPAY '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUM(CONVERT(NUMERIC,WEIGHT)) AS WEIGHT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUM(CONVERT(NUMERIC,RATE)) AS RATE'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUM(CONVERT(NUMERIC,SYSTEMID)) AS SYSTEMID'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,''ZZZZZ'' COSTNAME,'''' MONTHWISEINS,26 RESULT,''99999'' COLHEAD'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUM(CONVERT(NUMERIC,CHQBANK)) AS CHQBANK '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM TEMPTABLEDB..TEMPTRANVIEW  WHERE RESULT=''24'' '  
PRINT @SQLTEXT  
EXEC (@SQLTEXT)  
SELECT @SQLTEXT=' SELECT DISTINCT SCHEMENAME,'''' MOBILE,SUM(CASE MODEPAY WHEN ''C'' THEN X.AMOUNT ELSE NULL END) AS AMOUNT,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(CASE MODEPAY WHEN ''D'' THEN X.AMOUNT ELSE NULL END) AS RECEIPTNO,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(CASE MODEPAY WHEN ''R'' THEN X.AMOUNT ELSE NULL END )AS INSTALLMENT,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(CASE MODEPAY WHEN ''E'' THEN X.AMOUNT ELSE NULL END )AS MODEPAY,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(CASE WHEN MODEPAY IN (''O'',''A'') THEN X.AMOUNT ELSE NULL END )AS WEIGHT, '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(CANCELAMT) AS RATE,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(X.AMOUNT)AS CHQBANK, COSTNAME,24 RESULT   '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' INTO TEMPTABLEDB..TEMPTRANVIEWCOSTNAME '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM ('  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT SUM(CONVERT(NUMERIC,AMOUNT))AS AMOUNT,SCHEMENAME,CONVERT(VARCHAR,COSTNAME)AS COSTNAME,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN SUM(CONVERT(NUMERIC,AMOUNT))ELSE 0 END AS CANCELAMT,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' MODEPAY FROM TEMPTABLEDB..TEMPTRANVIEW WHERE RESULT =''0'''  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' GROUP BY MODEPAY,SCHEMENAME,CANCEL,COSTNAME )X GROUP BY SCHEMENAME,COSTNAME  '  
PRINT @SQLTEXT  
EXEC (@SQLTEXT)            
SELECT @SQLTEXT= ' INSERT INTO TEMPTABLEDB..TEMPTRANVIEWCOSTNAME (SCHEMENAME,MOBILE,COSTNAME,RESULT) '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT DISTINCT ISNULL(COSTNAME,''''),ISNULL(MOBILE,''''),ISNULL(COSTNAME,''''),23 FROM TEMPTABLEDB..TEMPTRANVIEWCOSTNAME '  
PRINT @SQLTEXT  
EXEC (@SQLTEXT)  
SELECT @SQLTEXT= ' INSERT INTO TEMPTABLEDB..TEMPTRANVIEWCOSTNAME(SCHEMENAME,MOBILE,AMOUNT,RECEIPTNO,INSTALLMENT,MODEPAY,WEIGHT,RATE,CHQBANK,COSTNAME,RESULT)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT ''TOTAL =>'','''' MOBILE,SUM(CONVERT(NUMERIC,AMOUNT)) AS AMOUNT,SUM(CONVERT(NUMERIC,RECEIPTNO)) AS RECEIPTNO, '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUM(CONVERT(NUMERIC,INSTALLMENT)) AS INSTALLMENT '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUM(CONVERT(NUMERIC,MODEPAY)) AS MODEPAY'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUM(CONVERT(NUMERIC,WEIGHT)) AS WEIGHT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUM(CONVERT(NUMERIC,RATE)) AS RATE'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUM(CONVERT(NUMERIC,CHQBANK)) AS CHQBANK'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,COSTNAME'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,25 RESULT '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' FROM TEMPTABLEDB..TEMPTRANVIEWCOSTNAME '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+'  WHERE RESULT=24 GROUP BY COSTNAME '  
PRINT @SQLTEXT  
EXEC (@SQLTEXT)            
END  
SELECT @SQLTEXT='INSERT INTO TEMPTABLEDB..TEMPTRANVIEW(CUSNAME,MOBILE,AMOUNT,RECEIPTNO,INSTALLMENT,MODEPAY,WEIGHT,RATE,MONTHWISEINS,RESULT,COLHEAD)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+'    SELECT '''','''',''GRSSAMT'',''CAN.AMT'',''NETAMT'',''GRSSWGT'',''CAN.WGT'',''NETWGT'','''',1,COLHEAD FROM TEMPTABLEDB..TEMPTRANVIEW WHERE RESULT=''2'''  
PRINT @SQLTEXT  
EXEC (@SQLTEXT)  
SELECT @SQLTEXT='INSERT INTO TEMPTABLEDB..TEMPTRANVIEW(CUSNAME,MOBILE,AMOUNT,RECEIPTNO,INSTALLMENT,MODEPAY,WEIGHT,RATE,MONTHWISEINS,RESULT,COLHEAD)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+'  SELECT '''','''',''GRSSAMT'',''CAN.AMT'',''NETAMT'',''GRSSWGT'',''CAN.WGT'',''NETWGT'','''',3,COLHEAD FROM TEMPTABLEDB..TEMPTRANVIEW WHERE RESULT=''4'''  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+'  INSERT INTO TEMPTABLEDB..TEMPTRANVIEW(CUSNAME,MONTHWISEINS,RESULT,COLHEAD)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+'  SELECT ''NEW MEMBERS :''+CONVERT(VARCHAR,COUNT(DISTINCT RECEIPTNO))GROUPCODE,'''',11,''99999'' FROM TEMPTABLEDB..TEMPTRANVIEW WHERE INSTALLMENT= ''1.00'' AND ISNULL(CANCEL,'''')=''''' /* AND RESULT=''0'''*/  
PRINT @SQLTEXT  
EXEC (@SQLTEXT)  
IF @WITHSCHDENOMI='Y'  
BEGIN  
SELECT @SQLTEXT='DELETE FROM TEMPTABLEDB..TEMPTRANVIEW WHERE RESULT NOT IN (''22'',''23'',''25'',''26'')'  
PRINT @SQLTEXT  
EXEC (@SQLTEXT)  
SELECT @SQLTEXT='INSERT INTO TEMPTABLEDB..TEMPTRANVIEW(CUSNAME,MOBILE,AMOUNT,RECEIPTNO,INSTALLMENT,CHQBANK,MODEPAY,WEIGHT,RATE,COSTNAME,MONTHWISEINS,RESULT,COLHEAD)'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT SCHEMENAME,'''' MOBILE,AMOUNT,RECEIPTNO,INSTALLMENT,CHQBANK,MODEPAY,WEIGHT,RATE,COSTNAME,'''',RESULT,''99999'' FROM TEMPTABLEDB..TEMPTRANVIEWCOSTNAME '  
PRINT @SQLTEXT  
EXEC (@SQLTEXT)  
END  
/*SELECT @SQLTEXT='ALTER TABLE TEMPTABLEDB..TEMPTRANVIEW ALTER COLUMN USERID VARCHAR(100)'  */  
SELECT @SQLTEXT=' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET AMOUNT = '''' WHERE AMOUNT = ''0'' '    
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET AMOUNT = '''' WHERE AMOUNT = ''0.00'' '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET RECEIPTNO = '''' WHERE RECEIPTNO = ''0'' '   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET RECEIPTNO = '''' WHERE RECEIPTNO = ''0.00'' '   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET INSTALLMENT = '''' WHERE INSTALLMENT = ''0.00'' '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET RDATE = '''' WHERE RDATE = ''0.00'' '   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET MODEPAY = '''' WHERE MODEPAY = ''0.0'' '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET MODEPAY = '''' WHERE MODEPAY = ''0.00'' '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET MODEPAY = '''' WHERE MODEPAY = ''0.000'' '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET WEIGHT = '''' WHERE WEIGHT = ''0.000''  '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET WEIGHT = '''' WHERE WEIGHT = ''0.00'' '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET WEIGHT = '''' WHERE WEIGHT = ''0''  '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET RATE = '''' WHERE RATE = ''0.00'' '   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET CHQBANK = '''' WHERE CHQBANK = ''0.00'' '   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET RDATE = '''' WHERE RDATE = ''0'' '   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET RDATE = '''' WHERE RDATE = ''0.00'' '   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET CHQBANK = '''' WHERE CHQBANK = ''0'' '   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET CHQBANK = '''' WHERE CHQBANK = ''0.00'' '   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET CHQBANK = '''' WHERE CHQBANK = ''0.000'' '   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' UPDATE TEMPTABLEDB..TEMPTRANVIEW  SET USERID = '''' WHERE USERID = ''0'' '   
PRINT @SQLTEXT  
EXEC (@SQLTEXT)  
SELECT @SQLTEXT=' SELECT SUBSTRING(CONVERT(VARCHAR,ID),0,10)SNO,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUBSTRING(GROUPCODE,0,9)GROUPCODE '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUBSTRING(CONVERT(VARCHAR,REGNO),0,7)REGNO,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUBSTRING(CUSNAME,0,50)CUSNAME,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SCHEMENAME,'
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' INSAMOUNT,'
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUBSTRING(MOBILE,0,20)MOBILE,'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUBSTRING(CONVERT(VARCHAR,AMOUNT),0,9)AMOUNT '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUBSTRING(CONVERT(VARCHAR,RECEIPTNO),0,9)RECEIPTNO '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUBSTRING(CONVERT(VARCHAR,(CASE ISNULL(MONTHWISEINS,'''') WHEN '''' THEN  CONVERT(VARCHAR,INSTALLMENT) ELSE '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' CONVERT(VARCHAR,INSTALLMENT) +''(''+MONTHWISEINS+'')'' END)),0,15) AS INSTALLMENT '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUBSTRING(CONVERT(VARCHAR,(CASE ISNULL(CANCEL,'''') WHEN ''Y'' THEN PAYMODE+''(*)'' ELSE PAYMODE END)),0,15) AS PAYMODE  '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,CASE CONVERT(VARCHAR,CHQDATE,105)WHEN ''01-01-1900'' THEN '''' ELSE CONVERT(VARCHAR,CHQDATE,105) END AS CHQDATE'   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUBSTRING(CONVERT(VARCHAR,WEIGHT),0,9)WEIGHT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUBSTRING(CONVERT(VARCHAR,RATE),0,8)RATE, '  
/*SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUBSTRING((CHQBANK+''-''+ CHQ_CARDNO+''-''),0,200)REMARKS, '*/  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ISNULL((LTRIM(CHQBANK)+''-''+ LTRIM(CHQ_CARDNO)),'''') + CASE ISNULL(CHQDATE,'''') WHEN  '''' THEN '''' ELSE ''  '' + LTRIM(CHQDATE) END REMARKS, '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SUBSTRING(CONVERT(VARCHAR,USERID),0,15)USERID'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUBSTRING(SYSTEMID,0,4)SYSTEMID'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,RIGHT(CONVERT(VARCHAR,UPTIME, 100), 7)UPTIME,UPTIME1'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,SUBSTRING(RDATE,0,9)RDATE,RDATE1 '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,RESULT,CANCEL FROM '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ('  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' SELECT  TV.GROUPCODE,TV.REGNO,CUSNAME,TV.SCHEMENAME,INSAMOUNT.AMOUNT INSAMOUNT,MOBILE,TV.AMOUNT,RECEIPTNO,INSTALLMENT'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,RDATE,RDATE1, CASE MODEPAY WHEN ''C'' THEN ''CASH'' WHEN ''D'' THEN ''CHEQUE'''   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' WHEN ''R'' THEN ''CR-CARD'' WHEN ''E'' THEN ''E-TRAN'' WHEN ''A'' THEN ''ADVANCE'' WHEN ''O'''   
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' THEN ''OTHERS'' WHEN ''G'' THEN ''GIFT'' ELSE MODEPAY END AS PAYMODE  ,WEIGHT,RATE,CHQBANK,CHQBRANCH,  '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' CASE ISNULL(CHQ_CARDNO,''0'') WHEN  ''0'' THEN '''' ELSE CHQ_CARDNO END AS CHQ_CARDNO'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,CASE CONVERT(VARCHAR,CHQDATE,105)WHEN ''01-01-1900'' THEN '''' ELSE CONVERT(VARCHAR,CHQDATE,105) END AS '  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' CHQDATE,TV.USERID,SYSTEMID,UPTIME'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ,UPTIME1,CANCEL,COLHEAD,COSTNAME,RESULT,ID,MONTHWISEINS FROM TEMPTABLEDB..TEMPTRANVIEW TV'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' LEFT JOIN SCHEME on SCHEME.SCHEMENAME = TV.SCHEMENAME'  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' LEFT JOIN INSAMOUNT on INSAMOUNT.SCHEMEID = SCHEME.SCHEMEID AND TV.GROUPCODE = INSAMOUNT.GROUPCODE'
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' )X '  
IF @WITHSCHDENOMI='Y'  
BEGIN  
IF  (SELECT COUNT(COSTNAME)COSTNAME FROM COSTCENTRE)=0  SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ORDER BY RESULT '  
IF  (SELECT COUNT(COSTNAME)COSTNAME FROM COSTCENTRE)<>0  SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ORDER BY COSTNAME,RESULT '  
END   
ELSE IF @WITHSCHDENOMI='Y'   
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ORDER BY RESULT '  
END   
ELSE    
BEGIN  
SELECT @SQLTEXT=@SQLTEXT+ CHAR(13)+' ORDER BY  COLHEAD,RESULT '  
END  
PRINT @SQLTEXT  
EXEC (@SQLTEXT)  
END   