Imports System.Data.OleDb
Public Class AGR_Initializer
    Dim StrSql As String
    Dim Cmd As OleDbCommand

    Public Sub Generate(ByVal Cn As OleDbConnection, ByVal Tran As OleDbTransaction)
        AGR_SP_VATFORM_ANNEXURE_1(Cn, Tran)
        AGR_SP_VATFORM_ANNEXURE_2(Cn, Tran)
        AGR_SP_VATFORM_ANNEXURE_3(Cn, Tran)
        AGR_SP_VATFORM_ANNEXURE_4_0(Cn, Tran)
        AGR_SP_VATFORM_ANNEXURE_4_E(Cn, Tran)
        AGR_SP_VATFORM_PAYMENTS(Cn, Tran)
        AGR_SP_VATFORMI(Cn, Tran)
        AGR_SP_TDSDETAILS(Cn, Tran)
        AGR_SP_TDSCOLLECTION(Cn, Tran)
    End Sub

    Private Sub AGR_SP_VATFORM_ANNEXURE_1(ByVal Cn As OleDbConnection, ByVal Tran As OleDbTransaction)
        StrSql = " IF(SELECT 1 FROM SYSOBJECTS WHERE NAME='AGR_SP_VATFORM_ANNEXURE_1')>0"
        StrSql += vbCrLf + "  	DROP PROCEDURE [AGR_SP_VATFORM_ANNEXURE_1]"
        Cmd = New OleDbCommand(StrSql, cn, tran)
        Cmd.ExecuteNonQuery()
        StrSql = vbCrLf + " CREATE PROCEDURE [AGR_SP_VATFORM_ANNEXURE_1]  "
        StrSql += vbCrLf + " (  "
        StrSql += vbCrLf + " @DBNAME VARCHAR(20),  "
        StrSql += vbCrLf + " @FROMDATE VARCHAR(20),  "
        StrSql += vbCrLf + " @TODATE VARCHAR(20),  "
        StrSql += vbCrLf + " @COMPANYIDS VARCHAR(50)  "
        StrSql += vbCrLf + " )AS  "
        StrSql += vbCrLf + " DECLARE @query NVARCHAR(3500)  "
        StrSql += vbCrLf + " BEGIN              "
        StrSql += vbCrLf + " select @query = 'SELECT AC.ACNAME  AS [Seller Name],ISNULL(AC.LOCALTAXNO,'''') AS [Seller Tin No.],ISNULL(CT.Commodity,'''') AS [Commodity Code],ISNULL(CT.Taxcategory,'''') AS [Category Code],'  "
        StrSql += vbCrLf + " select @query = @query +' REFNO AS Invno,Refdate as Invdate,CT.SALESTAX,SUM(ISNULL(T.Amount,0)) AS INVVALUE,SUM(ISNULL(T.TAX,0)) AS TAX'  "
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME+ '..RECEIPT as T LEFT JOIN ACHEAD AS AC ON AC.ACCODE = T.ACCODE LEFT JOIN CATEGORY AS CT ON CT.CATCODE = T.CATCODE'  "
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.CANCEL <> ''Y'' AND  T.COMPANYID IN (' + @COMPANYIDS + ') and isnull(t.accode,'''') <> '''''  "
        StrSql += vbCrLf + " select @query = @query + ' AND T.TRANDATE BETWEEN '''+@FROMDATE+''' AND  '''+@TODATE+''''     "
        StrSql += vbCrLf + " select @query = @query + ' GROUP BY AC.ACNAME  ,AC.LOCALTAXNO ,CT.Commodity ,CT.Taxcategory , REFNO ,Refdate ,CT.SALESTAX'  "
        StrSql += vbCrLf + " PRINT @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + " END  "
        Cmd = New OleDbCommand(StrSql, cn, tran)
        Cmd.ExecuteNonQuery()
    End Sub

    Private Sub AGR_SP_VATFORM_ANNEXURE_2(ByVal Cn As OleDbConnection, ByVal Tran As OleDbTransaction)
        StrSql = " IF(SELECT 1 FROM SYSOBJECTS WHERE NAME='AGR_SP_VATFORM_ANNEXURE_2')>0"
        StrSql += vbCrLf + "  	DROP PROCEDURE [AGR_SP_VATFORM_ANNEXURE_2]"
        Cmd = New OleDbCommand(StrSql, cn, tran)
        Cmd.ExecuteNonQuery()
        StrSql = vbCrLf + " CREATE PROCEDURE [AGR_SP_VATFORM_ANNEXURE_2]  "
        StrSql += vbCrLf + " (  "
        StrSql += vbCrLf + " @DBNAME VARCHAR(20),  "
        StrSql += vbCrLf + " @FROMDATE VARCHAR(20),  "
        StrSql += vbCrLf + " @TODATE VARCHAR(20),  "
        StrSql += vbCrLf + " @COMPANYIDS VARCHAR(50)  "
        StrSql += vbCrLf + " )AS  "
        StrSql += vbCrLf + " DECLARE @query NVARCHAR(3500)  "
        StrSql += vbCrLf + " BEGIN              "
        StrSql += vbCrLf + " select @query = 'SELECT ''CUSTOMER ''  AS [Seller Name],'''' AS [Seller Tin No.],ISNULL(CT.Commodity,'''') AS [Commodity Code],ISNULL(CT.Taxcategory,'''') AS [Category Code],'  "
        StrSql += vbCrLf + " select @query = @query +' CONVERT(VARCHAR(10),Tranno) AS Invno,Trandate as Invdate,CT.SALESTAX,SUM(ISNULL(T.Amount,0))*(-1) AS INVVALUE,SUM(ISNULL(T.TAX,0))*(-1) AS TAX'  "
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME+ '..RECEIPT as T  LEFT JOIN CATEGORY AS CT ON CT.CATCODE = T.CATCODE'  "
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.COMPANYID IN (' + @COMPANYIDS + ') and T.TRANTYPE =''SR'''  "
        StrSql += vbCrLf + " select @query = @query + ' AND T.CANCEL <> ''Y'' AND T.TRANDATE BETWEEN '''+@FROMDATE+''' AND  '''+@TODATE+''''     "
        StrSql += vbCrLf + " select @query = @query + ' GROUP BY CT.Commodity ,CT.Taxcategory , Tranno ,Trandate ,CT.SALESTAX'  "
        StrSql += vbCrLf + " select @query = @query + ' UNION ALL SELECT ''CUSTOMER ''  AS [Seller Name],'''' AS [Seller Tin No.],ISNULL(CT.Commodity,'''') AS [Commodity Code],ISNULL(CT.Taxcategory,'''') AS [Category Code],'  "
        StrSql += vbCrLf + " select @query = @query +' CONVERT(VARCHAR(10),Tranno) AS Invno,Trandate as Invdate,CT.SALESTAX,SUM(ISNULL(T.Amount,0)) AS INVVALUE,SUM(ISNULL(T.TAX,0)) AS TAX'  "
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME+ '..ISSUE as T  LEFT JOIN CATEGORY AS CT ON CT.CATCODE = T.CATCODE'  "
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.COMPANYID IN (' + @COMPANYIDS + ') and T.TRANTYPE =''SA'''  "
        StrSql += vbCrLf + " select @query = @query + ' AND T.CANCEL <> ''Y'' AND T.TRANDATE BETWEEN '''+@FROMDATE+''' AND  '''+@TODATE+''''     "
        StrSql += vbCrLf + " select @query = @query + ' GROUP BY CT.Commodity ,CT.Taxcategory , Tranno ,Trandate ,CT.SALESTAX'  "
        StrSql += vbCrLf + " select @query = @query + ' ORDER BY Trandate '  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " PRINT @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + " END  "
        Cmd = New OleDbCommand(StrSql, cn, tran)
        Cmd.ExecuteNonQuery()
    End Sub

    Private Sub AGR_SP_VATFORM_ANNEXURE_3(ByVal Cn As OleDbConnection, ByVal Tran As OleDbTransaction)
        StrSql = " IF(SELECT 1 FROM SYSOBJECTS WHERE NAME='AGR_SP_VATFORM_ANNEXURE_3')>0"
        StrSql += vbCrLf + "  	DROP PROCEDURE [AGR_SP_VATFORM_ANNEXURE_3]"
        Cmd = New OleDbCommand(StrSql, cn, tran)
        Cmd.ExecuteNonQuery()
        StrSql = vbCrLf + " CREATE PROCEDURE [AGR_SP_VATFORM_ANNEXURE_3]  "
        StrSql += vbCrLf + " (  "
        StrSql += vbCrLf + " @TEMPTABLE VARCHAR(30),  "
        StrSql += vbCrLf + " @DBNAME VARCHAR(20),  "
        StrSql += vbCrLf + " @FROMDATE VARCHAR(20),  "
        StrSql += vbCrLf + " @TODATE VARCHAR(20),  "
        StrSql += vbCrLf + " @COMPANYIDS VARCHAR(50),  "
        StrSql += vbCrLf + " @OPERATION CHAR(1)  "
        StrSql += vbCrLf + " )AS  "
        StrSql += vbCrLf + " DECLARE @query NVARCHAR(3500)  "
        StrSql += vbCrLf + " BEGIN              "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " IF @OPERATION = 'E'   "
        StrSql += vbCrLf + " BEGIN  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'SELECT T.LINNO,DESCRIPTION,USECTION,INOUT,COMDTYCODE,TINNO,'  "
        StrSql += vbCrLf + " select @query = @query + ' T.TAXPERCENT AS TAXPER,T.TAXABLEAMOUNT AS AMOUNT,T.TAXAMOUNT AS TAX'  "
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME+ '..VATFORM_ANNEX as T WHERE T.COMPANYID IN (' + @COMPANYIDS + ') AND INOUT = ''I'' AND TAXMONTH = '+ CONVERT(VARCHAR(2),MONTH(@TODATE))+' AND TAXYEAR = '+CONVERT(VARCHAR(4),YEAR(@TODATE))+''  "
        StrSql += vbCrLf + " select @query = @query + ' ORDER BY LINNO'  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + " RETURN  "
        StrSql += vbCrLf + " END  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " SET @query = ' IF  EXISTS (SELECT * FROM sysobjects WHERE xtype = ''U'' AND NAME = '  +''''+@TEMPTABLE+''''+' )'     +  'DROP TABLE ' + @TEMPTABLE    EXECUTE sp_executesql @query SET @query = 'CREATE TABLE ' + @TEMPTABLE+  '(  [LINNO] INT, [DESCRIPTION] [VARCHAR](100),[USECTION] [VARCHAR](20),COMDTYCODE VARCHAR(10),TINNO VARCHAR(20),[INOUT] [VARCHAR](1),TAXPER DECIMAL(8,2) default 0,AMOUNT DECIMAL(12,2) DEFAULT 0,TAX DECIMAL(12,2) DEFAULT 0' select @query = @query + ') ON [PRIMARY]'  EXECUTE sp_executesql @query"
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,USECTION,COMDTYCODE,TINNO,INOUT,TAXPER,AMOUNT,TAX'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 1,''Goods used for civil structures'',''Sec 2(11)'','''','''',''I'',0,'  "
        StrSql += vbCrLf + " select @query = @query + ' 0 ,0 '  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,USECTION,COMDTYCODE,TINNO,INOUT,TAXPER,AMOUNT,TAX'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 2,''Goods utilised for self use'',''Sec 19(7)(a)'','''','''',''I'',0,'  "
        StrSql += vbCrLf + " select @query = @query + ' 0 ,0 '  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,USECTION,COMDTYCODE,TINNO,INOUT,TAXPER,AMOUNT,TAX'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 3,''Purchase of automobiles ,spare parts and accessories other than dealer in Automobiles'',''Sec 19(7)(b)'','''','''',''I'',0,'  "
        StrSql += vbCrLf + " select @query = @query + ' 0 ,0 '  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,USECTION,COMDTYCODE,TINNO,INOUT,TAXPER,AMOUNT,TAX'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 4,''Purchase of Airconditioners other than dealers in Airconditioners'',''Sec 19(7)(c)'','''','''',''I'',0,'  "
        StrSql += vbCrLf + " select @query = @query + ' 0 ,0 '  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,USECTION,COMDTYCODE,TINNO,INOUT,TAXPER,AMOUNT,TAX'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 5,''Goods given as gift,free sample'',''Sec 19(8)'','''','''',''I'',0,'  "
        StrSql += vbCrLf + " select @query = @query + ' 0 ,0 '  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,USECTION,COMDTYCODE,TINNO,INOUT,TAXPER,AMOUNT,TAX'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 6,''Goods lost on theft,loss,etc.'',''Sec 19(8)(i)'','''','''',''I'',0,'  "
        StrSql += vbCrLf + " select @query = @query + ' 0 ,0 '  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,USECTION,COMDTYCODE,TINNO,INOUT,TAXPER,AMOUNT,TAX'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 7,''Inputs detroyed in fire or lost'',''Sec 19(8)(ii)'','''','''',''I'',0,'  "
        StrSql += vbCrLf + " select @query = @query + ' 0 ,0 '  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,USECTION,COMDTYCODE,TINNO,INOUT,TAXPER,AMOUNT,TAX'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 8,''Inputs damaged in transit or destroyed before manufacture'',''Sec 19(8)(iii)'','''','''',''I'',0,'  "
        StrSql += vbCrLf + " select @query = @query + ' 0 ,0 '  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,USECTION,COMDTYCODE,TINNO,INOUT,TAXPER,AMOUNT,TAX'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 9,''Unavailed credit on Capital goods (time barred)'',''Sec 19(3)(b)'','''','''',''I'',0,'  "
        StrSql += vbCrLf + " select @query = @query + ' 0 ,0 '  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,USECTION,COMDTYCODE,TINNO,INOUT,TAXPER,AMOUNT,TAX'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 10,''Consignment Sales Without F form '',''Sec 19(4)(i)&(ii)'','''','''',''I'',0,'  "
        StrSql += vbCrLf + " select @query = @query + ' 0 ,0 '  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,USECTION,COMDTYCODE,TINNO,INOUT,TAXPER,AMOUNT,TAX'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 11,''Stock transfer without F form'',''Sec.19(4)(i)&(ii)'','''','''',''I'',0,'  "
        StrSql += vbCrLf + " select @query = @query + ' 0 ,0 '  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,USECTION,COMDTYCODE,TINNO,INOUT,TAXPER,AMOUNT,TAX'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 11,''Stock transfer without F form'',''Sec.19(4)(i)&(ii)'','''','''',''I'',0,'  "
        StrSql += vbCrLf + " select @query = @query + ' 0 ,0 '  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,USECTION,COMDTYCODE,TINNO,INOUT,TAXPER,AMOUNT,TAX'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 12,''Purchases for production of Exempted goods(Finished)'',''Sec.19(5)(a)'','''','''',''I'',0,'  "
        StrSql += vbCrLf + " select @query = @query + ' 0 ,0 '  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,USECTION,COMDTYCODE,TINNO,INOUT,TAXPER,AMOUNT,TAX'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 13,''Interstate sale without C form'',''Sec.19(5)(c)'','''','''',''I'',0,'  "
        StrSql += vbCrLf + " select @query = @query + ' 0 ,0 '  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,USECTION,COMDTYCODE,TINNO,INOUT,TAXPER,AMOUNT,TAX'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 14,''Purchase return'',''Sec 4(i)'','''','''',''I'',0,'  "
        StrSql += vbCrLf + " select @query = @query + ' 0 ,0 '  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,USECTION,COMDTYCODE,TINNO,INOUT,TAXPER,AMOUNT,TAX'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 15,''ITC availed for Finished goods subsequently exempt'',''Sec 19(12)'','''','''',''I'',0,'  "
        StrSql += vbCrLf + " select @query = @query + ' 0 ,0 '  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,USECTION,COMDTYCODE,TINNO,INOUT,TAXPER,AMOUNT,TAX'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 16,''Others(specify)'','''','''','''',''I'',0,'  "
        StrSql += vbCrLf + " select @query = @query + ' 0 ,0 '  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'SELECT T.* '  "
        StrSql += vbCrLf + " select @query = @query + ' from ' + @TEMPTABLE+ ' as T ORDER BY INOUT,LINNO'  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + " END  "
        Cmd = New OleDbCommand(StrSql, cn, tran)
        Cmd.ExecuteNonQuery()
    End Sub

    Private Sub AGR_SP_VATFORM_ANNEXURE_4_0(ByVal Cn As OleDbConnection, ByVal Tran As OleDbTransaction)
        StrSql = " IF(SELECT 1 FROM SYSOBJECTS WHERE NAME='AGR_SP_VATFORM_ANNEXURE_4_0')>0"
        StrSql += vbCrLf + "  	DROP PROCEDURE [AGR_SP_VATFORM_ANNEXURE_4_0]"
        Cmd = New OleDbCommand(StrSql, cn, tran)
        Cmd.ExecuteNonQuery()
        StrSql = vbCrLf + " CREATE PROCEDURE [AGR_SP_VATFORM_ANNEXURE_4_0]  "
        StrSql += vbCrLf + " (  "
        StrSql += vbCrLf + " @TEMPTABLE VARCHAR(30),  "
        StrSql += vbCrLf + " @DBNAME VARCHAR(20),  "
        StrSql += vbCrLf + " @FROMDATE VARCHAR(20),  "
        StrSql += vbCrLf + " @TODATE VARCHAR(20),  "
        StrSql += vbCrLf + " @COMPANYIDS VARCHAR(50),  "
        StrSql += vbCrLf + " @OPERATION CHAR(1)  "
        StrSql += vbCrLf + " )AS  "
        StrSql += vbCrLf + " DECLARE @query NVARCHAR(3500)  "
        StrSql += vbCrLf + " BEGIN              "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " IF @OPERATION = 'E'   "
        StrSql += vbCrLf + " BEGIN  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'SELECT T.LINNO,DESCRIPTION,INOUT,COMDTYCODE,TINNO,'  "
        StrSql += vbCrLf + " select @query = @query + ' T.TAXPERCENT AS TAXPER,T.TAXABLEAMOUNT AS AMOUNT,T.TAXAMOUNT AS TAX,T.TAXCREDIT'  "
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME+ '..VATFORM_ANNEX as T WHERE T.COMPANYID IN (' + @COMPANYIDS + ') AND INOUT = ''Z'' AND TAXMONTH = '+ CONVERT(VARCHAR(2),MONTH(@TODATE))+' AND TAXYEAR = '+CONVERT(VARCHAR(4),YEAR(@TODATE))+''  "
        StrSql += vbCrLf + " select @query = @query + ' ORDER BY LINNO'  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + " RETURN  "
        StrSql += vbCrLf + " END  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " SET @query = ' IF  EXISTS (SELECT * FROM sysobjects WHERE xtype = ''U'' AND NAME = '  +''''+@TEMPTABLE+''''+' )'     +  'DROP TABLE ' + @TEMPTABLE    EXECUTE sp_executesql @query SET @query = 'CREATE TABLE ' + @TEMPTABLE+  '(  [LINNO] INT, [DESCRIPTION] [VARCHAR](100),COMDTYCODE VARCHAR(10),TINNO VARCHAR(20),[INOUT] [VARCHAR](1),TAXPER DECIMAL(8,2) default 0,AMOUNT DECIMAL(12,2) DEFAULT 0,TAX DECIMAL(12,2) DEFAULT 0,TAXCREDIT DECIMAL(12,2) DEFAULT 0' select @query = @query + ') ON [PRIMARY]'"
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " EXECUTE sp_executesql @query"
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,COMDTYCODE,TINNO,INOUT,TAXPER,AMOUNT,TAX,TAXCREDIT'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 1,'' '','''','''',''Z'',0,0,0 ,0 '  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'SELECT T.*  from ' + @TEMPTABLE+ ' as T ORDER BY INOUT,LINNO'  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + " END  "
        Cmd = New OleDbCommand(StrSql, cn, tran)
        Cmd.ExecuteNonQuery()
    End Sub

    Private Sub AGR_SP_VATFORM_ANNEXURE_4_E(ByVal Cn As OleDbConnection, ByVal Tran As OleDbTransaction)
        StrSql = " IF(SELECT 1 FROM SYSOBJECTS WHERE NAME='AGR_SP_VATFORM_ANNEXURE_4_E')>0"
        StrSql += vbCrLf + "  	DROP PROCEDURE [AGR_SP_VATFORM_ANNEXURE_4_E]"
        Cmd = New OleDbCommand(StrSql, cn, tran)
        Cmd.ExecuteNonQuery()
        StrSql = vbCrLf + " CREATE PROCEDURE [AGR_SP_VATFORM_ANNEXURE_4_E]  "
        StrSql += vbCrLf + " (  "
        StrSql += vbCrLf + " @TEMPTABLE VARCHAR(30),  "
        StrSql += vbCrLf + " @DBNAME VARCHAR(20),  "
        StrSql += vbCrLf + " @FROMDATE VARCHAR(20),  "
        StrSql += vbCrLf + " @TODATE VARCHAR(20),  "
        StrSql += vbCrLf + " @COMPANYIDS VARCHAR(50),  "
        StrSql += vbCrLf + " @OPERATION CHAR(1)  "
        StrSql += vbCrLf + " )AS  "
        StrSql += vbCrLf + " DECLARE @query NVARCHAR(3500)  "
        StrSql += vbCrLf + " BEGIN              "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " IF @OPERATION = 'E'   "
        StrSql += vbCrLf + " BEGIN  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'SELECT T.LINNO,DESCRIPTION,INOUT,COMDTYCODE,TINNO,'  "
        StrSql += vbCrLf + " select @query = @query + ' T.TAXPERCENT AS TAXPER,T.TAXABLEAMOUNT AS AMOUNT,T.TAXAMOUNT AS TAX,T.TAXCREDIT'  "
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME+ '..VATFORM_ANNEX as T WHERE T.COMPANYID IN (' + @COMPANYIDS + ') AND INOUT = ''E'' AND TAXMONTH = '+ CONVERT(VARCHAR(2),MONTH(@TODATE))+' AND TAXYEAR = '+CONVERT(VARCHAR(4),YEAR(@TODATE))+''  "
        StrSql += vbCrLf + " select @query = @query + ' ORDER BY LINNO'  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + " RETURN  "
        StrSql += vbCrLf + " END  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " SET @query = ' IF  EXISTS (SELECT * FROM sysobjects WHERE xtype = ''U'' AND NAME = '  +''''+@TEMPTABLE+''''+' )'     +  'DROP TABLE ' + @TEMPTABLE    EXECUTE sp_executesql @query SET @query = 'CREATE TABLE ' + @TEMPTABLE+  '(  [LINNO] INT, [DESCRIPTION] [VARCHAR](100),COMDTYCODE VARCHAR(10),TINNO VARCHAR(20),[INOUT] [VARCHAR](1),TAXPER DECIMAL(8,2) default 0,AMOUNT DECIMAL(12,2) DEFAULT 0,TAX DECIMAL(12,2) DEFAULT 0,TAXCREDIT DECIMAL(12,2) DEFAULT 0' select @query = @query + ') ON [PRIMARY]'"
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " EXECUTE sp_executesql @query   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,COMDTYCODE,TINNO,INOUT,TAXPER,AMOUNT,TAX,TAXCREDIT'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 1,'' '','''','''',''E'',0,0,0 ,0 '  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'SELECT T.*  from ' + @TEMPTABLE+ ' as T ORDER BY INOUT,LINNO'  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + " END  "
        Cmd = New OleDbCommand(StrSql, cn, tran)
        Cmd.ExecuteNonQuery()
    End Sub

    Private Sub AGR_SP_VATFORM_PAYMENTS(ByVal Cn As OleDbConnection, ByVal Tran As OleDbTransaction)
        StrSql = " IF(SELECT 1 FROM SYSOBJECTS WHERE NAME='AGR_SP_VATFORM_PAYMENTS')>0"
        StrSql += vbCrLf + "  	DROP PROCEDURE [AGR_SP_VATFORM_PAYMENTS]"
        Cmd = New OleDbCommand(StrSql, cn, tran)
        Cmd.ExecuteNonQuery()
        StrSql = vbCrLf + " CREATE PROCEDURE [AGR_SP_VATFORM_PAYMENTS]  "
        StrSql += vbCrLf + " (  "
        StrSql += vbCrLf + " @TEMPTABLE VARCHAR(30),  "
        StrSql += vbCrLf + " @DBNAME VARCHAR(20),  "
        StrSql += vbCrLf + " @FROMDATE VARCHAR(20),  "
        StrSql += vbCrLf + " @TODATE VARCHAR(20),  "
        StrSql += vbCrLf + " @COMPANYIDS VARCHAR(50),  "
        StrSql += vbCrLf + " @OPERATION CHAR(1)  "
        StrSql += vbCrLf + " )AS  "
        StrSql += vbCrLf + " DECLARE @query NVARCHAR(3500)  "
        StrSql += vbCrLf + " BEGIN              "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " IF @OPERATION = 'E'   "
        StrSql += vbCrLf + " BEGIN  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'SELECT '''' AS PAYMENT,T.LINNO,DESCRIPTION,T.TAXABLEAMOUNT,TAXCREDIT,TAXDEBIT,PAYMENTTYPE,TAXTYPE,VALUETYPE,BANKNAME,BANKCODE,BANKBRANCH,CHQ_DDNO,CHQ_DDDATE'  "
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME+ '..VAT_TDS_DETAILS as T WHERE T.COMPANYID IN ('+ @COMPANYIDS + ') AND TAXTYPE = ''VAT'' AND TAXMONTH = '+ CONVERT(VARCHAR(2),MONTH(@TODATE))+' AND TAXYEAR = '+CONVERT(VARCHAR(4),YEAR(@TODATE))+''  "
        StrSql += vbCrLf + " select @query = @query + ' ORDER BY LINNO'  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + " RETURN  "
        StrSql += vbCrLf + " END  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " SET @query = ' IF  EXISTS (SELECT * FROM sysobjects WHERE xtype = ''U'' AND NAME = '  +''''+@TEMPTABLE+''''+' )'     +  'DROP TABLE ' + @TEMPTABLE    EXECUTE sp_executesql @query SET @query = 'CREATE TABLE ' + @TEMPTABLE+  '(  [LINNO] INT, [DESCRIPTION] [VARCHAR](40),TAXABLEAMOUNT DECIMAL(12,2),TAXCREDIT DECIMAL(12,2),TAXDEBIT DECIMAL(12,2),PAYMENTTYPE VARCHAR(10),TAXTYPE VARCHAR(3),VALUETYPE VARCHAR(3),BANKNAME VARCHAR(20),BANKCODE VARCHAR(20),BANKBRANCH VARCHAR(20),CHQ_DDNO VARCHAR(20),CHQ_DDDATE DATETIME' select @query = @query + ') ON [PRIMARY]' print @query EXECUTE sp_executesql @query   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,TAXABLEAMOUNT,TAXCREDIT,TAXDEBIT,PAYMENTTYPE,TAXTYPE,VALUETYPE,BANKNAME,BANKCODE,BANKBRANCH,CHQ_DDNO,CHQ_DDDATE'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 1,''VAT PAYABLE'',0,T.TAXAMOUNT,0,'''',''VAT'',''NTP'','''','''','''','''',GETDATE()'  "
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME+ '..VATFORMI as T WHERE T.COMPANYID IN (' + @COMPANYIDS + ') AND TAXMOVEMENT = ''T4'' AND TAXMONTH = '+ CONVERT(VARCHAR(2),MONTH(@TODATE))+' AND TAXYEAR = '+CONVERT(VARCHAR(4),YEAR(@TODATE))+''  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,TAXABLEAMOUNT,TAXCREDIT,TAXDEBIT,PAYMENTTYPE,TAXTYPE,VALUETYPE,BANKNAME,BANKCODE,BANKBRANCH,CHQ_DDNO,CHQ_DDDATE'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 2,''Input Tax Credit '',0,SUM(ISNULL(T.TAXAMOUNT,0)),0,'''',''VAT'',''ITC'','''','''','''','''',GETDATE()'  "
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME+ '..VATFORM_ANNEX as T WHERE T.COMPANYID IN (' + @COMPANYIDS + ') AND INOUT = ''Z'' AND TAXMONTH = '+ CONVERT(VARCHAR(2),MONTH(@TODATE))+' AND TAXYEAR = '+CONVERT(VARCHAR(4),YEAR(@TODATE))+''  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,TAXABLEAMOUNT,TAXDEBIT,TAXCREDIT,PAYMENTTYPE,TAXTYPE,VALUETYPE,BANKNAME,BANKCODE,BANKBRANCH,CHQ_DDNO,CHQ_DDDATE'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 3,''Less Zero Rate Sales'',0,SUM(ISNULL(T.TAXAMOUNT,0)),0,'''',''VAT'',''ZRS'','''','''','''','''',GETDATE()'  "
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME+ '..VATFORM_ANNEX as T WHERE T.COMPANYID IN (' + @COMPANYIDS + ') AND INOUT = ''Z'' AND TAXMONTH = '+ CONVERT(VARCHAR(2),MONTH(@TODATE))+' AND TAXYEAR = '+CONVERT(VARCHAR(4),YEAR(@TODATE))+''  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE   "
        StrSql += vbCrLf + " select @query =@query + '(LINNO,DESCRIPTION,TAXABLEAMOUNT,TAXDEBIT,TAXCREDIT,PAYMENTTYPE,TAXTYPE,VALUETYPE,BANKNAME,BANKCODE,BANKBRANCH,CHQ_DDNO,CHQ_DDDATE'  "
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 4,''Less CST  Sales'',0,SUM(ISNULL(T.TAXAMOUNT,0)),0,'''',''VAT'',''CST'','''','''','''','''',GETDATE()'  "
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME+ '..VATFORM_ANNEX as T WHERE T.COMPANYID IN (' + @COMPANYIDS + ') AND INOUT = ''Z'' AND TAXMONTH = '+ CONVERT(VARCHAR(2),MONTH(@TODATE))+' AND TAXYEAR = '+CONVERT(VARCHAR(4),YEAR(@TODATE))+''  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = 'SELECT '''' AS PAYMENT,T.*  from ' + @TEMPTABLE+ ' as T ORDER BY LINNO'  "
        StrSql += vbCrLf + " print @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + " END  "
        Cmd = New OleDbCommand(StrSql, cn, tran)
        Cmd.ExecuteNonQuery()
    End Sub

    Private Sub AGR_SP_VATFORMI(ByVal Cn As OleDbConnection, ByVal Tran As OleDbTransaction)
        StrSql = " IF(SELECT 1 FROM SYSOBJECTS WHERE NAME='AGR_SP_VATFORMI')>0"
        StrSql += vbCrLf + "  	DROP PROCEDURE [AGR_SP_VATFORMI]"
        Cmd = New OleDbCommand(StrSql, cn, tran)
        Cmd.ExecuteNonQuery()
        StrSql = vbCrLf + " CREATE PROCEDURE [AGR_SP_VATFORMI]"
        StrSql += vbCrLf + " ("
        StrSql += vbCrLf + " @TEMPTABLE VARCHAR(30),"
        StrSql += vbCrLf + " @DBNAME VARCHAR(20),"
        StrSql += vbCrLf + " @FROMDATE VARCHAR(20),"
        StrSql += vbCrLf + " @TODATE VARCHAR(20),"
        StrSql += vbCrLf + " @COMPANYIDS VARCHAR(50),"
        StrSql += vbCrLf + " @OPERATION CHAR(1)"
        StrSql += vbCrLf + " )AS"
        StrSql += vbCrLf + " DECLARE @query NVARCHAR(3500)"
        StrSql += vbCrLf + " BEGIN            "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " IF @OPERATION = 'E' "
        StrSql += vbCrLf + " BEGIN"
        StrSql += vbCrLf + " select @query = 'SELECT CASE WHEN INOUT = ''I'' THEN ''INPUT TAX CREDIT'' ELSE ''TAX PAYABLE'' END AS HEAD,'"
        StrSql += vbCrLf + " select @query = @query +' SCHNO,DESCRIPTION,INOUT,'"
        StrSql += vbCrLf + " select @query = @query + ' T.TAXPERCENT AS TAXPER,T.TAXABLEAMOUNT AS AMOUNT,T.TAXAMOUNT AS TAX,TAXMOVEMENT AS MOVEMENT,T.LINNO '"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME+ '..VATFORMI as T WHERE T.COMPANYID IN (' + @COMPANYIDS + ') AND TAXMONTH = '+ CONVERT(VARCHAR(2),MONTH(@TODATE))+' AND TAXYEAR = '+CONVERT(VARCHAR(4),YEAR(@TODATE))+''"
        StrSql += vbCrLf + " select @query = @query + ' ORDER BY INOUT,SCHNO'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " RETURN"
        StrSql += vbCrLf + " END"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " SET @query = ' IF  EXISTS (SELECT * FROM sysobjects WHERE xtype = ''U'' AND NAME = '"
        StrSql += vbCrLf + " 	+''''+@TEMPTABLE+''''+' )'"
        StrSql += vbCrLf + "     +"
        StrSql += vbCrLf + " 	'DROP TABLE ' + @TEMPTABLE "
        StrSql += vbCrLf + " 		EXECUTE sp_executesql @query"
        StrSql += vbCrLf + " SET @query = 'CREATE TABLE ' + @TEMPTABLE+  '("
        StrSql += vbCrLf + "  [SCHNO] INT, [DESCRIPTION] [VARCHAR](40),[MOVEMENT] [VARCHAR](3),[INOUT] [VARCHAR](1),TAXPER DECIMAL(8,2) default 0,AMOUNT DECIMAL(12,2) DEFAULT 0,TAX DECIMAL(12,2) DEFAULT 0'"
        StrSql += vbCrLf + " select @query = @query + ') ON [PRIMARY]'"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " EXECUTE sp_executesql @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 1,''Input Tax Credit carry forward '',''PA'',''I'',1,'"
        StrSql += vbCrLf + " select @query = @query + ' 0,SUM(isnull(T.TAXCREDIT,0)-isnull(T.TAXDEBIT,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME+ '..VAT_TDS_DETAILS as T WHERE T.COMPANYID IN (' + @COMPANYIDS + ') AND TAXMONTH = '+ CONVERT(VARCHAR(2),MONTH(@TODATE))+' AND TAXYEAR = '+CONVERT(VARCHAR(4),YEAR(@TODATE))+''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 1,''a.Goods taxable at 1%'',''PU'',''I'',1,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..RECEIPT AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN ACHEAD AS AC ON T.ACCODE = AC.ACCODE '"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND AC.LOCALOUTST = ''L'' AND T.CANCEL <> ''Y'''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.TRANTYPE = ''RPU'' AND A.SALESTAX = 1 AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 1,''b.Goods taxable at 2%'',''PU'',''I'',2,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..RECEIPT AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN ACHEAD AS AC ON T.ACCODE = AC.ACCODE '"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND AC.LOCALOUTST = ''L'' AND T.CANCEL <> ''Y'''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.TRANTYPE = ''RPU'' AND A.SALESTAX = 2 AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 1,''c.Goods taxable at 4%'',''PU'',''I'',4,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..RECEIPT AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN ACHEAD AS AC ON T.ACCODE = AC.ACCODE '"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND AC.LOCALOUTST = ''L'' AND T.CANCEL <> ''Y'''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.TRANTYPE = ''RPU'' AND A.SALESTAX = 4 AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 1,''d.Goods taxable at 12.5%'',''PU'',''I'',12.5,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..RECEIPT AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN ACHEAD AS AC ON T.ACCODE = AC.ACCODE '"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND AC.LOCALOUTST = ''L'' AND T.CANCEL <> ''Y'''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.TRANTYPE = ''RPU'' AND A.SALESTAX = 12.5 AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 1,''f.Purchase under sec 12'',''PU'',''I'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(T.AMOUNT*(A.SALESTAX/100)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..RECEIPT AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.CANCEL <> ''Y'''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.TRANTYPE = ''PU'' AND A.SALESTAX <> 0 AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 1,''f1.Tax paid under sec 12'',''PU'',''I'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' 0 AS AMOUNT,SUM(T.AMOUNT*(A.SALESTAX/100))*(-1) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..RECEIPT AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.CANCEL <> ''Y'''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.TRANTYPE = ''PU'' AND A.SALESTAX <> 0 AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 1,''Total'',''PT1'',''I'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @TEMPTABLE + ' AS T '"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.MOVEMENT =''PU'''"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 2,''Less: Reverse credit'',''PR'',''I'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0))*(-1) AS AMOUNT,SUM(isnull(TAX,0))*(-1) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..ISSUE AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.TRANTYPE = ''PR'' AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 2,''TOTAL NET'',''IB1'',''I'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(T.TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @TEMPTABLE+ ' as T where MOVEMENT IN(''PU'',''PR'') AND T.INOUT =''I''' "
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 2,''Goods exempted '',''PU'',''I'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..RECEIPT AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.TRANTYPE IN (''RPU'',''PU'') AND A.SALESTAX =0 AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 3,''a.Upto previous month'',''PUC'',''I'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..RECEIPT AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.TRANTYPE = ''PC'' AND A.SALESTAX IN(1,2,4,12.5) AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 3,''b.during the month'',''PUC'',''I'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..RECEIPT AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.TRANTYPE = ''PC'' AND A.SALESTAX IN(1,2,4,12.5) AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 3,''Total '',''PUT'',''I'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(T.TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @TEMPTABLE+ ' as T where MOVEMENT IN(''PUC'') AND T.INOUT =''I''' "
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 3,''Less: Reverse credit'',''PRC'',''I'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0))*(-1) AS AMOUNT,SUM(isnull(TAX,0))*(-1) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..ISSUE AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.TRANTYPE = ''PC'' AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 3,''Less: Claimed upto previous month'',''PRC'',''I'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0))*(-1) AS AMOUNT,SUM(isnull(TAX,0))*(-1) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..ISSUE AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.TRANTYPE = ''PC'' AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 3,''TOTAL NET'',''IC1'',''I'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(T.TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @TEMPTABLE+ ' as T where MOVEMENT IN(''PRC'',''PUT'') AND T.INOUT =''I''' "
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 4,''Total Input Tax credit'',''IE'',''I'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(T.TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @TEMPTABLE+ ' as T where MOVEMENT IN(''IA'',''IB1'',''IC1'') AND T.INOUT =''I''' "
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " --- tax payable"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 1,''Purchase turnover under sec 12'',''PA'',''O'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(T.AMOUNT*(A.SALESTAX/100)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..RECEIPT AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.CANCEL <> ''Y'''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.TRANTYPE = ''PU'' AND A.SALESTAX <> 0 AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 1,''a.Local sales at 1%'',''SA'',''O'',1,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..ISSUE AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.CANCEL <> ''Y'' AND T.TRANTYPE = ''SA'' AND A.SALESTAX = 1 AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 1,''b.Local sales at 2%'',''SA'',''O'',2,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..ISSUE AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.CANCEL <> ''Y'' AND T.TRANTYPE = ''SA'' AND A.SALESTAX = 2 AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 1,''c.Local sales at 4%'',''SA'',''O'',4,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..ISSUE AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.CANCEL <> ''Y'' AND T.TRANTYPE = ''SA'' AND A.SALESTAX = 4 AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 1,''d.Local sales at 12.5%'',''SA'',''O'',12.5,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..ISSUE AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.CANCEL <> ''Y'' AND T.TRANTYPE = ''SA'' AND A.SALESTAX = 12.5 AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 1,''Total'',''ST'',''O'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(CASE WHEN T.MOVEMENT = ''SA'' THEN TAX END,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @TEMPTABLE + ' AS T '"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.MOVEMENT IN(''SA'',''PA'')  AND T.INOUT=''O'''"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 2,'' Less: Sales return/Unfructified sales'',''SR'',''O'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0))*(-1) AS AMOUNT,SUM(isnull(TAX,0))*(-1) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..RECEIPT AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.CANCEL <> ''Y'' AND T.TRANTYPE = ''SR'' AND A.SALESTAX IN(1,2,4,12.5)   AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 2,''TOTAL NET'',''T1'',''O'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(T.TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @TEMPTABLE+ ' as T where MOVEMENT IN(''ST'',''SR'') AND T.INOUT =''O''' "
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 2,''Zero rate sales'',''SA'',''O'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..ISSUE AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.CANCEL <> ''Y'' AND T.TRANTYPE = ''SA'' AND A.SALESTAX IN(1,2,4,12.5) AND ISNULL(TAX,0) = 0 AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 2,''1.Adjustment of advance tax'',''AT'',''O'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(T.TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @TEMPTABLE+ ' as T where MOVEMENT IN(''AT'') AND T.INOUT =''O''' "
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 2,''2.Entry tax paid if any'',''AT'',''O'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(T.TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @TEMPTABLE+ ' as T where MOVEMENT IN(''AT'') AND T.INOUT =''O''' "
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 2,''Less : Total(1+2)'',''OH1'',''O'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(T.TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @TEMPTABLE+ ' as T where MOVEMENT IN(''AT'') AND T.INOUT =''O''' "
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 2,''  Net tax payable'',''OT1'',''O'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(T.TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @TEMPTABLE+ ' as T where MOVEMENT IN(''T1'',''OH1'') AND T.INOUT =''O''' "
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 2,''Exempted sales'',''SAE'',''O'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..ISSUE AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.CANCEL <> ''Y'' AND T.TRANTYPE = ''SA'' AND A.SALESTAX NOT IN(1,2,4,12.5) AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 2,''Less: Sales return/Unfructified sales'',''SRE'',''O'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0))*(-1) AS AMOUNT,SUM(isnull(TAX,0))*(-1) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..RECEIPT AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.CANCEL <> ''Y'' AND T.TRANTYPE = ''SR'' AND A.SALESTAX = 0 AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 2,''  Total '',''OJ'',''O'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(T.TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @TEMPTABLE+ ' as T where MOVEMENT IN(''SAE'',''SRE'') AND T.INOUT =''O''' "
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 3,''Sales under Sec10(S)'',''OS1'',''O'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0))*(-1) AS AMOUNT,SUM(isnull(TAX,0))*(-1) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME + '..RECEIPT AS T '"
        StrSql += vbCrLf + " select @query = @query + ' LEFT JOIN CATEGORY AS A ON T.CATCODE = A.CATCODE'"
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.TRANDATE BETWEEN  '''+@FROMDATE +''' AND  ''' +@TODATE+''''"
        StrSql += vbCrLf + " select @query = @query + ' AND T.TRANTYPE = ''S10'' AND T.COMPANYID IN (' + @COMPANYIDS + ')'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 3,''1.Adjustment of advance tax'',''SAT'',''O'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(T.TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @TEMPTABLE+ ' as T where MOVEMENT IN(''SAT'') AND T.INOUT =''O''' "
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 3,''2.Entry tax paid,TDS refund if any'',''SAT'',''O'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(T.TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @TEMPTABLE+ ' as T where MOVEMENT IN(''SAT'') AND T.INOUT =''O''' "
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 3,''Less Total'',''T3'',''O'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(T.TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @TEMPTABLE+ ' as T where MOVEMENT IN(''SAT'') AND T.INOUT =''O''' "
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'INSERT INTO '+@TEMPTABLE "
        StrSql += vbCrLf + " select @query =@query + '(SCHNO,DESCRIPTION,MOVEMENT,INOUT,TAXPER,AMOUNT,TAX'"
        StrSql += vbCrLf + " select @query = @query + ')  SELECT 4,'' Net tax payable '',''T4'',''O'',0,'"
        StrSql += vbCrLf + " select @query = @query + ' SUM(isnull(T.AMOUNT,0)) AS AMOUNT,SUM(isnull(T.TAX,0)) AS TAX'"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @TEMPTABLE+ ' as T where MOVEMENT IN(''OJ'',''T1'',''T2'',''T3'') AND T.INOUT =''O''' "
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " "
        StrSql += vbCrLf + " select @query = 'SELECT CASE WHEN INOUT = ''I'' THEN ''INPUT TAX CREDIT'' ELSE ''TAX PAYABLE'' END AS HEAD,T.* '"
        StrSql += vbCrLf + " select @query = @query + ' from ' + @TEMPTABLE+ ' as T ORDER BY INOUT,SCHNO'"
        StrSql += vbCrLf + " print @query"
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query"
        StrSql += vbCrLf + " END"
        Cmd = New OleDbCommand(StrSql, cn, tran)
        Cmd.ExecuteNonQuery()
    End Sub

    Private Sub AGR_SP_TDSDETAILS(ByVal Cn As OleDbConnection, ByVal Tran As OleDbTransaction)
        StrSql = " IF(SELECT 1 FROM SYSOBJECTS WHERE NAME='AGR_SP_TDSDETAILS')>0"
        StrSql += vbCrLf + "  	DROP PROCEDURE [AGR_SP_TDSDETAILS]"
        Cmd = New OleDbCommand(StrSql, cn, tran)
        Cmd.ExecuteNonQuery()
        StrSql = vbCrLf + " CREATE PROCEDURE [AGR_SP_TDSDETAILS]  "
        StrSql += vbCrLf + " (  "
        StrSql += vbCrLf + "  @DBNAME VARCHAR(20),  "
        StrSql += vbCrLf + "  @FROMDATE VARCHAR(12),  "
        StrSql += vbCrLf + "  @TODATE VARCHAR(12),  "
        StrSql += vbCrLf + "  @COMPANYIDS VARCHAR(50),  "
        StrSql += vbCrLf + "  @PARTYIDS VARCHAR(50)  "
        StrSql += vbCrLf + " )  "
        StrSql += vbCrLf + " AS   "
        StrSql += vbCrLf + " DECLARE @QUERY NVARCHAR(4000)  "
        StrSql += vbCrLf + " BEGIN  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " SELECT @QUERY ='SELECT CONVERT(VARCHAR(3),DATENAME(MONTH,TI.TAXMONTH)) + ''`''+ convert(varchar(4),year(TI.TAXYEAR))  as PAYMENTDATE,'  "
        StrSql += vbCrLf + " SELECT @QUERY = @QUERY + ' TI.TAXABLEAMOUNT,TI.TAXCREDIT,TI.TDSAMOUNT,TI.SCAMOUNT,TI.EDCESSAMOUNT,TD.TAXDEBIT,TD.BANKCODE,TD.CHQ_DDDATE,TI.CHALLANNO'  "
        StrSql += vbCrLf + " SELECT @QUERY = @QUERY + ' FROM ' + @DBNAME+ '..TDS_INVDETAILS AS TI INNER JOIN ' + @DBNAME+ '..VAT_TDS_DETAILS AS TD ON TI.TAXMONTH=TD.TAXMONTH AND TI.TAXYEAR=TD.TAXYEAR'  "
        StrSql += vbCrLf + " SELECT @QUERY = @QUERY + ' WHERE TI.COMPANYID IN ('+ @COMPANYIDS +') AND TI.PARTYCODE IN ('+ @PARTYIDS +') AND TD.VALUETYPE=''TPY'' AND TD.TAXTYPE=''TDS'''  "
        StrSql += vbCrLf + " SELECT @QUERY = @QUERY + ' AND TI.TAXMONTH BETWEEN MONTH('''+ @FROMDATE +''') AND MONTH('''+ @TODATE +''') AND TI.TAXYEAR  BETWEEN YEAR('''+ @FROMDATE +''') AND YEAR('''+ @TODATE +''')'  "
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " PRINT @QUERY  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @QUERY  "
        StrSql += vbCrLf + " END"
        Cmd = New OleDbCommand(StrSql, cn, tran)
        Cmd.ExecuteNonQuery()
    End Sub

    Private Sub AGR_SP_TDSCOLLECTION(ByVal Cn As OleDbConnection, ByVal Tran As OleDbTransaction)
        StrSql = " IF(SELECT 1 FROM SYSOBJECTS WHERE NAME='AGR_SP_TDSCOLLECTION')>0"
        StrSql += vbCrLf + "  	DROP PROCEDURE [AGR_SP_TDSCOLLECTION]"
        Cmd = New OleDbCommand(StrSql, cn, tran)
        Cmd.ExecuteNonQuery()
        StrSql = vbCrLf + " CREATE PROCEDURE [AGR_SP_TDSCOLLECTION]  "
        StrSql += vbCrLf + " (  "
        StrSql += vbCrLf + " @DBNAME VARCHAR(20),  "
        StrSql += vbCrLf + " @FROMDATE VARCHAR(20),  "
        StrSql += vbCrLf + " @TODATE VARCHAR(20),  "
        StrSql += vbCrLf + " @COMPANYIDS VARCHAR(50),  "
        StrSql += vbCrLf + " @PARTYIDS VARCHAR(50)  "
        StrSql += vbCrLf + " )AS  "
        StrSql += vbCrLf + " DECLARE @query NVARCHAR(3500)  "
        StrSql += vbCrLf + " BEGIN    "
        StrSql += vbCrLf + " select @query = 'SELECT  month(T.TRANDATE) as TaxMonth,Year(T.TRANDATE) as TaxYear,SUM(ISNULL(T.Amount,0)) AS INVVALUE,0 AS TDSAmount,0 as SCAmount,0 AS ECESSAmount,getdate() as PaidDate,'''' as CHQ_DDNo,'''' as PaymentType,'''' as BankName,'''' as BankCode,'''' as BankBranch,'''' as ChallanNO'"
        StrSql += vbCrLf + "   "
        StrSql += vbCrLf + " select @query = @query + ' from ' + @DBNAME+ '..ACCTRAN as T INNER JOIN '+ @DBNAME+ '..ACCTRAN as PC ON T.ACCODE = PC.CONTRA AND T.BATCHNO = PC.BATCHNO AND PC.TRANFLAG = ''TD'''   "
        StrSql += vbCrLf + " select @query = @query + ' WHERE T.COMPANYID IN ('+ @COMPANYIDS +') and isnull(t.accode,'''') IN ('+ @PARTYIDS +')'  "
        StrSql += vbCrLf + " select @query = @query + ' AND T.TRANDATE BETWEEN '''+@FROMDATE+''' AND  '''+@TODATE+''''     "
        StrSql += vbCrLf + " select @query = @query + ' GROUP BY month(T.TRANDATE),year(T.TRANDATE)'  "
        StrSql += vbCrLf + " PRINT @query  "
        StrSql += vbCrLf + " EXECUTE SP_EXECUTESQL @query  "
        StrSql += vbCrLf + " END  "
        Cmd = New OleDbCommand(StrSql, cn, tran)
        Cmd.ExecuteNonQuery()
    End Sub

End Class
